"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let GR=2463534242,I8=()=>{let x=GR;x^=x<<13;x^=x>>>17;x^=x<<5;GR=x;return x;},CF=f=>function(){return f(this);},BJ=f=>function(p1){return f(this,p1);},Jx=f=>function(){let args=Array.prototype.slice.apply(arguments);Fy(function()
{f.apply(this,args);});},G4=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=P(BN(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Be(args[i]);}Fy(()=>{f.call(null,javaArgs);},callback);},Y=target=>target.$clinit=()=>{},J2=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls[K]&&cls[K].item){++arrayDegree;cls=cls[K].item;}let clsName="";if(cls[K].primitiveKind!==0){clsName=cls[K].name;}else {clsName=cls[K]?cls[K].name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},F
=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=BN();}return function(){superclass.call(this);};},K=Symbol("teavm_meta"),BE=cls=>{if(cls[K].classObject===null){cls[K].classObject=HE(cls);}return cls[K].classObject;},BN=()=>E,Hi=()=>{{return Ba();}},Ev=t=>{{return Bu(t);}},R=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},Ec=source=>{return Object.assign({name:null,binaryName:null,parent:null,superinterfaces:[],modifiers:0,primitiveKind
:0,itemType:null,arrayType:null,enclosingClass:null,declaringClass:null,simpleName:null,clinit:()=>{},constructor:null,enumConstants:()=>null,resolvedEnumConstants:null,reflection:null,classObject:null,assignableCache:null,valueToObject:o=>o,objectToValue:o=>o},source||{});},Bw=(name,binaryName,kind,config)=>{let cls=()=>{};let meta=Ec({name:name,binaryName:binaryName,modifiers:1|1<<4,primitiveKind:kind});cls[K]=meta;if(typeof config==='function'){config(meta);}return cls;},Iv=Bw("boolean","Z",1,meta=>{}),G2
=Bw("byte","B",2,meta=>{}),HN=Bw("short","S",3,meta=>{}),FL=Bw("char","C",4,meta=>{}),E2=Bw("int","I",5,meta=>{{meta.valueToObject=o=>BA(o);}{meta.objectToValue=o=>Fx(o);}}),DA=Bw("float","F",7,meta=>{}),IK=Bw("void","V",9),Df=(a,b)=>a===b?0:a<b? -1:1,CY=(a,b)=>a===b?0:a>b?1: -1,S=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},DF=(a,b)=>(a>>>0)/(b>>>0)>>>0,J4=(a,b)=>(a>>>0)%(b>>>0)>>>0,Dg=(a,b)=>{a>>>=0;b>>>=0;return a
<b? -1:a>b?1:0;},B0=BigInt(0),B1=val=>BigInt.asIntN(64,BigInt(val|0)),FN=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),DT=val=>Number(val),G0=(a,b)=>a>b,G6=(a,b)=>a>=b,Hh=(a,b)=>a<b,EM=(a,b)=>BigInt.asIntN(64,a+b),I3=(a,b)=>BigInt.asIntN(64,a -b),JD=(a,b)=>BigInt.asIntN(64,a/b),P=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bc(cls))(data);},Jl=(cls,data)=>new (Bc(cls))(data),Iu=(cls,sz)=>new (Bc(cls))(new Array(sz)),BI=sz=>new Jd(new Uint16Array(sz)),BS=sz=>new I_(new Int8Array(sz)),Ho
=sz=>new JR(new Int16Array(sz)),CU=sz=>new Ga(new Int32Array(sz)),I6=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new Ga(buffer);},GS=sz=>new JI(new Int8Array(sz)),Bq=sz=>new EB(new Float32Array(sz));
let IZ=data=>{let buffer=new Float32Array(data.length);buffer.set(data);return new EB(buffer);},Bc=cls=>{let result=cls[K].arrayType;if(result===null){function JavaArray(data){(BN()).call(this);this.data=data;}JavaArray.prototype=Object.create((BN()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.fh
=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bc(this.type))(dataCopy);};let name="["+cls[K].binaryName;JavaArray[K]=Ec({name:name,binaryName:name,parent:BN(),itemType:cls});result=JavaArray;cls[K].arrayType=JavaArray;}return result;},J3=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if
(first>0){for(let i=0;i<first;i=i+1|0){cls=Bc(cls);}if(first===dimensions.length -1){return P(cls,dimensions[first]);}}let arrays=new Array(FC(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=P(cls,firstDim);}return E$(cls,arrays,dimensions,first,0);},IS=dimensions=>{let arrays=new Array(FC(dimensions,0));if(arrays.length===0){return J3(DA,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=Bq(firstDim);}return E$(DA,arrays,
dimensions,0);},FC=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},E$=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=Bc(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=Iu(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex+1|0;}limit
=packedIndex;}return arrays[0];};
function JB(array){return array.data.length;}
let DP,HI=strings=>{Jt();DP=new Array(strings.length);for(let i=0;i<strings.length;++i){DP[i]=EN(Be(strings[i]));}},D=index=>DP[index],Fv=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Be=str=>str===null?null:FX(str),BT=str=>str===null?null:str.cK,Jt=()=>BW(),EN;
{EN=str=>str;}let Cw=(from,to)=>{if(from===to){return true;}let map=from[K].assignableCache;if(map===null){map=new Map();from[K].assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to[K].itemType!==null){let result=from[K].itemType!==null&&Cw(from[K].itemType,to[K].itemType);map.set(to,result);return result;}let parent=from[K].parent;if(parent!==null&&parent!==from){if(Cw(parent,to)){map.set(to,true);return true;}}let superinterfaces=from[K].superinterfaces;for
(let i=0;i<superinterfaces.length;i=i+1|0){if(Cw(superinterfaces[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},J=ex=>{throw E5(ex);},BH=Symbol("javaException"),E5=ex=>{if(!ex.$jsException){Fn(ex);}return ex.$jsException;},Fn=ex=>{let javaCause=Ka(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Br("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[BH]
=ex;ex.$jsException=err;GE(err,ex);},GE=(err,ex)=>{if(typeof Hj==="function"&&err.stack){let stack=Hj(err.stack);let javaStack=P(HB(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Jb(Be(element.className),Be(element.methodName),Be(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){HQ(ex,javaStack);}}},Br;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Br=function Br(message,cause){let self=Reflect.construct(Error,[void 0,cause],Br);Object.setPrototypeOf(self,Br.prototype);self[defaultMessage]=message;return self;}
;Br.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Br},message:{get(){try {let javaException=this[BH];if(typeof javaException==='object'){let javaMessage=IE(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Br=Error;}let IL=e=>e instanceof Error&&typeof e[BH]==='object'?e[BH]:null,U=err=>
{let ex=err[BH];if(!ex){ex=IX(Be("(JavaScript) "+err.toString()));err[BH]=ex;ex.$jsException=err;GE(err,ex);}return ex;},IX=message=>JU(message),IE=t=>J9(t),Ka=t=>Kc(t),HB=()=>BN(),Jb=(className,methodName,fileName,lineNumber)=>{{return null;}},HQ=(e,stack)=>{},F9=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},Ix=typeof $rt_putStdoutCustom
==="function"?$rt_putStdoutCustom:typeof console==="object"?F9(msg=>console.info(msg)):()=>{},HV=typeof $rt_putStderrCustom==="function"?$rt_putStderrCustom:typeof console==="object"?F9(msg=>console.error(msg)):()=>{},EC=null,HX=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}EC=packages;},HL=[],C9=data=>{let packages=EC;let i=0;while(i<data.length){let cls=data[i++];HL.push(cls);let m
=Ec();cls[K]=m;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.parent=superclass!==0?superclass:null;m.superinterfaces=data[i++];if(m.parent){cls.prototype=Object.create(m.parent.prototype);}else {cls.prototype={};}cls.prototype.constructor=cls;m.modifiers=data[i++];m.primitiveKind=0;let innerClassInfo=data[i++];if(innerClassInfo!==0){let enclosingClass
=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];m.clinit=clinit!==0?()=>{m.clinit=()=>{};clinit();}:()=>{};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for
(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}}};
function X(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
X.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};X.prototype.s=X.prototype.push;X.prototype.pop=function(){return this.stack.pop();};X.prototype.l=X.prototype.pop;X.prototype.isResuming=function(){return this.status===2;};X.prototype.isSuspending=function(){return this.status===1;};X.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};X.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(Cf!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};X.prototype.resume=function(){if(Cf!==null){throw new Error("Another thread is running");}this.status=2;this.run();};X.prototype.run=function(){Cf=this;let result;try {result=this.runner();}catch(e){result=e;}finally {Cf=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let HZ=()=>{let thread=B5();return thread!=null&&thread.isSuspending();},Ir=()=>{let thread=B5();return thread!=null&&thread.isResuming();},IG=()=>{let nativeThread=B5();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},Fy=(runner,callback)=>
(new X(runner)).start(callback),Cf=null,B5=()=>Cf,HC=()=>{throw new Error("Invalid recorded state");};
function E(){this.cJ=null;this.$id$=0;}
let Em=b=>{let c,d;if(Ba()===null)return;if(b.cJ===null)C3(b);c=b.cJ;d=c.cM;if(d===null)c.cM=Ba();else if(d!==Ba()){c=new Ff;DG(c,D(0));J(c);}b=b.cJ;b.cO=b.cO+1|0;},BR=b=>{let c,d;if(Ba()===null)return;if(!Cr(b)&&b.cJ.cM===Ba()){c=b.cJ;d=c.cO-1|0;c.cO=d;if(!d)c.cM=null;Cr(b);return;}b=new CI;L(b);J(b);},Kk=b=>{let c,d,$p,$z;$p=0;if(Ir()){let $T=B5();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;if(b.cJ===null)C3(b);d=b.cJ;if(d.cM===null)d.cM=Ba();if(b.cJ.cM===Ba()){b=b.cJ;b.cO=b.cO
+c|0;return;}$p=1;case 1:H0(b,c);if(HZ()){break _;}return;default:HC();}}B5().s(b,c,d,$p);},C3=b=>{let c;c=new GD;c.cM=Ba();b.cJ=c;},JW=(b,c,d)=>{let e,f,g,h,i,j,k,l,m;e=Ba();f=b.cJ;if(f===null){C3(b);Bu(e);b=b.cJ;b.cO=b.cO+c|0;b=null;CT(d,b);return;}if(f.cM===null){f.cM=e;Bu(e);b=b.cJ;b.cO=b.cO+c|0;b=null;CT(d,b);return;}if(f.c6===null){g=new F6;g.c4=P(E,9);f.c6=g;}f=f.c6;g=new EX;g.eq=e;g.er=b;g.en=c;g.eo=d;b=f;c=b.c$;h=b.dj;c=(c>=h?c-h|0:(b.c4.data.length-h|0)+c|0)+1|0;h=b.c4.data.length;if(c>=h){c=Cj(h*
2|0,((c*3|0)/2|0)+1|0);if(c<1)c=2147483647;i=P(E,c);c=0;h=b.dj;j=b.c$;if(h<=j){k=i.data;while(h<j){l=c+1|0;k[c]=b.c4.data[h];h=h+1|0;c=l;}}else{k=i.data;while(true){m=b.c4.data;if(h>=m.length)break;l=c+1|0;k[c]=m[h];h=h+1|0;c=l;}h=0;while(h<j){l=c+1|0;k[c]=m[h];h=h+1|0;c=l;}}b.dj=0;b.c$=c;b.c4=i;}i=b.c4.data;c=b.c$;i[c]=g;b.c$=Gf(c,i.length);b.dK=b.dK+1|0;},Kl=b=>{let c,d;if(!Cr(b)&&b.cJ.cM===Ba()){c=b.cJ;d=c.cO-1|0;c.cO=d;if(d<=0){c.cM=null;c=c.c6;if(c!==null&&!DB(c)){c=new Gn;c.em=b;EE(c);}else Cr(b);}return;}b
=new CI;L(b);J(b);},Cr=a=>{let b,c;b=a.cJ;if(b===null)return 1;a:{if(b.cM===null){c=b.c6;if(!(c!==null&&!DB(c))){b=b.eb;if(b===null)break a;if(b.k())break a;}}return 0;}a.cJ=null;return 1;},Hz=a=>{return;},J_=()=>{let a=new E();Hz(a);return a;},BM=a=>{return BE(Ic(a));},Ic=a=>{return a.constructor;},Jj=a=>{let b,c,d,e,f,g,h,i,j,k;b=a;if(!b.$id$)b.$id$=I8();c=a.$id$;B2();if(!c)d=D(1);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;h=g>>>4|0;if(!h)h=g;else f=f|4;e=h>>>2|0;if
(!e)e=h;else f=f|2;if(e>>>1|0)f=f|1;e=(32-f|0)-1|0;}i=(((32-e|0)+4|0)-1|0)/4|0;j=BI(i);k=j.data;i=(i-1|0)*4|0;e=0;while(i>=0){h=e+1|0;k[e]=Ed((c>>>i|0)&15,16);i=i-4|0;e=h;}d=Ez(j);}b=Bz();Bl(Bl(b,D(2)),d);return BO(b);},DX=a=>{let b,c;b=a.cJ;if(!(b!==null&&b.cM===Ba()?1:0)){b=new CI;L(b);J(b);}b=a.cJ.eb;if(b===null)return;while(!b.k()){c=b.r();if(!c.s())EE(c);}a.cJ.eb=null;},H0=(b,c)=>{let thread=IG();let javaThread=Hi();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error)
{throw result;}return result;}let callback=function(){};callback.h=val=>{thread.attribute=val;Ev(javaThread);thread.resume();};callback.bH=e=>{thread.attribute=E5(e);Ev(javaThread);thread.resume();};callback=J6(callback);thread.suspend(()=>{try {JW(b,c,callback);;}catch($e){callback.bH($e);}});return null;},By=F(0),Cl=F(0),DL=F(0);
function Z(){E.call(this);this.dG=0;}
let II=null,ET=null,Hx=null,BW=()=>{BW=Y(Z);Ik();},H1=(a,b)=>{BW();a.cK=Fv(b.data,0,b.data.length);},Ez=a=>{let b=new Z();H1(b,a);return b;},If=(a,b)=>{a.cK=b;},FX=a=>{let b=new Z();If(b,a);return b;},CL=(a,b)=>{let c;if(b>=0&&b<a.cK.length)return a.cK.charCodeAt(b);c=new CQ;L(c);J(c);},Bt=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof Z))return 0;c=b;return a.cK!==c.cK?0:1;},Ip=a=>{let b;a:{if(!a.dG){b=0;while(true){if(b>=a.cK.length)break a;a.dG=(31*a.dG|0)+a.cK.charCodeAt(b)|0;b=b+1|0;}}}return a.dG;},Ik
=()=>{let b;II=BI(0);b=new Z;BW();b.cK="";ET=b;Hx=new FE;},D_=F();
function B6(){D_.call(this);this.dl=0;}
let HK=null,C0=null,B2=()=>{B2=Y(B6);Hu();},G1=(a,b)=>{B2();a.dl=b;},Fk=a=>{let b=new B6();G1(b,a);return b;},BA=b=>{let c,d;B2();if(b>=(-128)&&b<=127){a:{if(C0===null){C0=P(B6,256);c=0;while(true){d=C0.data;if(c>=d.length)break a;d[c]=Fk(c-128|0);c=c+1|0;}}}return C0.data[b+128|0];}return Fk(b);},Fx=a=>{return a.dl;},Hl=a=>{let b;b=a.dl;B2();return b;},Jw=(a,b)=>{if(a===b)return 1;return b instanceof B6&&b.dl==a.dl?1:0;},Hu=()=>{HK=BE(E2);};
function Dr(){let a=this;E.call(a);a.cN=null;a.cV=0;}
let CG=(a,b,c)=>{let d,e,f,g;d=a.cV;e=d-b|0;d=(d+c|0)-b|0;GH(a,d);f=e-1|0;while(f>=0){g=a.cN.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.cV=a.cV+(c-b|0)|0;},DD=F(0),EI=F(Dr),Ji=a=>{a.cN=BI(16);},Bz=()=>{let a=new EI();Ji(a);return a;},Bl=(a,b)=>{let c,d,e,f,g,h;c=a.cV;d=a;b=b===null?D(3):b;e=d;if(c>=0&&c<=e.cV){a:{if(b===null)b=D(3);else if(b.cK.length?0:1)break a;f=e.cV+b.cK.length|0;GH(e,f);f=e.cV-1|0;while(f>=c){e.cN.data[f+b.cK.length|0]=e.cN.data[f];f=f+(-1)|0;}e.cV=e.cV+b.cK.length|0;f=0;while(f<b.cK.length)
{g=e.cN.data;h=c+1|0;g[c]=CL(b,f);f=f+1|0;c=h;}}return a;}b=new CQ;Gg(b);J(b);},Dj=(a,b)=>{let c,d,e,f,g,h,i,j;c=a.cV;d=1;if(b<0){d=0;b= -b|0;}a:{if(Dg(b,10)<0){if(d)CG(a,c,c+1|0);else{CG(a,c,c+2|0);e=a.cN.data;f=c+1|0;e[c]=45;c=f;}a.cN.data[c]=Ed(b,10);}else{g=1;h=1;f=DF((-1),10);b:{while(true){i=g*10|0;if(Dg(i,b)>0){i=g;break b;}h=h+1|0;if(Dg(i,f)>0)break;g=i;}}if(!d)h=h+1|0;CG(a,c,c+h|0);if(d)f=c;else{e=a.cN.data;f=c+1|0;e[c]=45;}while(true){if(!i)break a;e=a.cN.data;j=f+1|0;e[f]=Ed(DF(b,i),10);b=J4(b,i);i
=DF(i,10);f=j;}}}return a;},EK=(a,b)=>{let c,d;c=a.cV;d=a;CG(d,c,c+1|0);d.cN.data[c]=b;return a;},BO=a=>{let b,c,d,e,f;b=new Z;c=a.cN;d=c.data;e=a.cV;BW();f=d.length;if(e>=0&&e<=(f-0|0)){b.cK=Fv(c.data,0,e);return b;}b=new Bd;L(b);J(b);},GH=(a,b)=>{let c,d,e,f;c=a.cN.data.length;if(c<b){b=c>=1073741823?2147483647:Cj(b,Cj(c*2|0,5));d=a.cN.data;e=BI(b);f=e.data;b=Dk(b,d.length);c=0;while(c<b){f[c]=d[c];c=c+1|0;}a.cN=e;}};
function Bg(){let a=this;E.call(a);a.d4=null;a.d3=null;a.ed=0;a.ek=0;a.fe=null;}
let HP=a=>{return a;},Do=a=>{Fn(a);},J9=a=>{return a.d4;},Kg=a=>{return a.d4;},Kc=a=>{let b;b=a.d3;if(b===a)b=null;return b;},CM=a=>{let b;if(C2===null){b=new EU;Go(b);C2=b;}GA(a,C2);},GA=(a,b)=>{let c,d,e,f,g,h,i;c=GC(BM(a));d=b;BL(d,c);e=a.d4;if(e!==null){c=Bz();Bl(Bl(c,D(4)),e);BL(d,BO(c));}a:{c=b;BL(c,D(5));f=a.fe;if(f!==null){f=f.data;g=f.length;h=0;while(true){if(h>=g)break a;e=f[h];BL(d,D(6));i=D(3);if(e!==null)i=e.q();Fd(c,i);h=h+1|0;}}}c=a.d3;if(c!==null&&c!==a){BL(d,D(7));GA(a.d3,b);}},Bv=F(Bg),O=
F(Bv),L=a=>{Do(a);a.ed=1;a.ek=1;},Kf=()=>{let a=new O();L(a);return a;},DG=(a,b)=>{Do(a);a.ed=1;a.ek=1;a.d4=b;},JU=a=>{let b=new O();DG(b,a);return b;},B3=F(),H7=F(B3),Hr=(a,b)=>{switch(a.primitiveKind){default:return P(a,b);}},HW=F(B3),E8=F(0),GK=F(0),Ey=F(0);
function Fl(){let a=this;E.call(a);a.e3=0;a.c2=null;a.ep=null;}
let HE=b=>{let c;c=new Fl;c.c2=b;return c;},GC=a=>{let b,c,d,e,f;b=a.e3;if(!(b&1)){a.e3=b|1;c=a.c2[K].name;d=c===null?null:Be(c);if(d===null){e=a.c2[K].itemType;if(e!==null){f=GC(BE(e));if(f!==null){if(e[K].itemType!==null){c=Bz();Bl(EK(c,91),f);d=BO(c);}else{c=Bz();EK(Bl(Bl(c,D(8)),f),59);d=BO(c);}}}}a.ep=d;}return a.ep;},CJ=a=>{return !a.c2[K].primitiveKind?0:1;},C$=a=>{let b;b=a.c2[K].itemType;return b===null?null:BE(b);},Dx=F(0);
function En(){let a=this;E.call(a);a.eA=0;a.ez=0;a.eY=null;a.d8=null;a.dp=null;a.dD=null;a.c7=null;a.dP=B0;a.dq=0;}
let BK=null,G=null,W=null,Ci=0,Ct=0,Ca=0,Eq=null,GN=null,BG=null,Cq=null,EO=null,Dm=null,Cz=null,CA=null,Cv=null,Bx=null,DQ=null,M=()=>{M=Y(En);Ha();},Je=a=>{let b,c,d,e,f,g,h,i,j,k,l;a.eY=IZ([0.054901961237192154,0.04313725605607033,0.03921568766236305,1.0]);b=Fh(window.document.getElementById("canvas"));c=Fh(b.getContext("webgl"));M();G=c;E4(a,window.innerWidth,window.innerHeight);d=window;c=Hk(a);d.addEventListener("resize",Q(I(c),"handleEvent"));JS();IT();c=Hb(b);b.addEventListener("click",Q(I(c),"handleEvent"));d
=G.createShader(35633);G.shaderSource(d,"attribute vec3 aPosition; attribute vec2 aTexCoord; attribute vec3 aColor; uniform mat4 uProj; uniform mat4 uModl; varying vec2 vTexCoord; varying vec3 vColor; varying float vFogDist; void main() { vec4 pos = uModl * vec4(aPosition, 1.0); gl_Position = uProj * pos; vTexCoord = aTexCoord; vColor = aColor; vFogDist = length(pos.xyz); }");G.compileShader(d);e=G.createShader(35632);G.shaderSource(e,"precision mediump float; varying vec2 vTexCoord; varying vec3 vColor; varying float vFogDist; uniform sampler2D uTex; uniform bool uHasTexture; uniform bool uHasColor; uniform vec4 uFogColor; uniform float uAlpha; uniform bool uUseFog; void main() { vec4 col = vec4(1.0); if(uHasColor) col *= vec4(vColor, 1.0); if(uHasTexture) col *= texture2D(uTex, vTexCoord); col.a *= uAlpha; if(uUseFog) { float fogFactor = exp(-0.02 * vFogDist); fogFactor = clamp(fogFactor, 0.0, 1.0); gl_FragColor = mix(uFogColor, col, fogFactor); } else { gl_FragColor = col; } }");G.compileShader(e);f
=G.createProgram();W=f;G.attachShader(f,d);c=G;f=W;c.attachShader(f,e);c=G;f=W;c.linkProgram(f);c=G;f=W;c.useProgram(f);Ci=G.getAttribLocation(W,"aPosition");Ct=G.getAttribLocation(W,"aTexCoord");Ca=G.getAttribLocation(W,"aColor");Eq=G.getUniformLocation(W,"uProj");GN=G.getUniformLocation(W,"uModl");BG=G.getUniformLocation(W,"uHasTexture");Cq=G.getUniformLocation(W,"uHasColor");EO=G.getUniformLocation(W,"uFogColor");Dm=G.getUniformLocation(W,"uAlpha");Cz=G.getUniformLocation(W,"uUseFog");f=G.createBuffer();DQ
=f;G.bindBuffer(34963,f);g=Ho(450000).data;h=0;i=0;while(h<300000){j=h<<16>>16;g[i]=j;g[i+1|0]=(h+1|0)<<16>>16;k=i+2|0;l=(h+2|0)<<16>>16;g[k]=l;g[i+3|0]=j;g[i+4|0]=l;g[i+5|0]=(h+3|0)<<16>>16;h=h+4|0;i=i+6|0;}h=g.length;f=new Int16Array(h);j=0;while(j<h){i=g[j];f[j]=i;j=j+1|0;}G.bufferData(34963,f,35044);G.clearColor(0.5,0.800000011920929,1.0,1.0);G.clearDepth(1.0);G.enable(2929);G.depthFunc(515);CV(5889);C1();CV(5888);c=IN(256,256,64);a.dp=c;a.dD=In(c);a.c7=Jk(a.dp);Fp(1);},CV=b=>{M();Bx=b!=5889?Cv:CA;},C1=
()=>{let b,c,d;M();b=0;while(b<16){c=Bx;d=b%5|0?0.0:1.0;c.data[b]=d;b=b+1|0;}},FU=(b,c,d)=>{let e;M();e=Bx.data;e[12]=e[12]+e[0]*b+e[4]*c+e[8]*d;e[13]=e[13]+e[1]*b+e[5]*c+e[9]*d;e[14]=e[14]+e[2]*b+e[6]*c+e[10]*d;e[15]=e[15]+e[3]*b+e[7]*c+e[11]*d;},E1=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x;M();f=Cp(b);g=CH(f);h=B$(f);i=1.0-g;j=c*c*i+g;k=d*c*i;l=e*h;m=k+l;b=c*e*i;n=d*h;o=b-n;p=k-l;q=d*d*i+g;d=d*e*i;c=c*h;r=d+c;k=b+n;l=d-c;s=e*e*i+g;t=Bq(16);u=t.data;Fq(Bx,0,t,0,16);v=0;while(v<4){t=Bx.data;b=u[v]
*j;w=v+4|0;b=b+u[w]*m;x=v+8|0;t[v]=b+u[x]*o;t[w]=u[v]*p+u[w]*q+u[x]*r;t[x]=u[v]*k+u[w]*l+u[x]*s;v=v+1|0;}},IQ=(b,c,d,e)=>{let f,g;M();f=1.0/Hs(b*3.141592653589793/360.0);C1();g=Bx.data;g[0]=f/c;g[5]=f;b=e+d;c=d-e;g[10]=b/c;g[11]=(-1.0);g[14]=2.0*e*d/c;g[15]=0.0;},HF=()=>{let b,c,d;M();b=G;c=Eq;d=CA;b.uniformMatrix4fv(c,!!0,d.data);b=G;c=GN;d=Cv;b.uniformMatrix4fv(c,!!0,d.data);},Fu=a=>{let b,c,d,e,f,g,h;if(Bb(1)){E3(a.dp);return;}b=a.d8;c=Gk();d=I3(c,b.d7);b.d7=c;if(Hh(d,B0))d=B0;if(G0(d,B1(1000000000)))d=B1(1000000000);b.es
=DT(JD(B1(1000000000),d));e=b.dQ+DT(d)*b.ey*b.eV/1.0E9;b.dQ=e;f=e|0;b.d6=f;if(f>100)b.d6=100;e=e-b.d6;b.dQ=e;b.eu=e;f=0;while(true){b=a.d8;if(f>=b.d6)break;J5(a.c7);f=f+1|0;}JP(a,b.eu);a.dq=a.dq+1|0;while(G6(Cx(),EM(a.dP,B1(1000)))){if(Du===null){b=new EZ;Go(b);Du=b;}g=Du;f=a.dq;BB();h=Ce;b=Bz();Dj(Bl(Dj(b,f),D(9)),h);b=BO(b);Fd(g,b);Ce=0;a.dP=EM(a.dP,B1(1000));a.dq=0;}window;b=new Da;b.eN=a;requestAnimationFrame(Q(I(b),"onAnimationFrame"));},HU=(a,b)=>{let c,d,e,f;FU(0.0,0.0,(-0.30000001192092896));E1(a.c7.c8,
1.0,0.0,0.0);E1(a.c7.c_,0.0,1.0,0.0);c=a.c7;d=c.ew;d=d+(c.dy-d)*b;e=c.ev;e=e+(c.dz-e)*b;f=c.eG;f=f+(c.dA-f)*b;FU( -d, -e, -f);},JP=(a,b)=>{let c,d,e,f,g,h,i,j;V();c=BQ|0;BQ=0.0;d=c;c=BP|0;BP=0.0;e=c;f=a.c7;f.c_=f.c_+d*0.15;d=f.c8-e*0.15;f.c8=d;if(d<(-90.0))f.c8=(-90.0);if(f.c8>90.0)f.c8=90.0;JK(a.dD,f);while(true){a:{Cc=null;if(!EG(Bs)){f=I(EY(Bs,0));Cc=f;if(f!==null){c=1;break a;}}c=0;}if(!c)break;if(GF()==1&&Fr()){M();f=BK;if(f!==null)E6(a.dp,f.dW,f.dX,f.dY,0);}if(GF())continue;if(!Fr())continue;M();f=BK;if
(f===null)continue;c=f.dW;g=f.dX;h=f.dY;i=f.ea;if(!i)g=g+(-1)|0;if(i==1)g=g+1|0;if(i==2)h=h+(-1)|0;if(i==3)h=h+1|0;if(i==4)c=c+(-1)|0;if(i==5)c=c+1|0;E6(a.dp,c,g,h,1);}while(true){b:{Bh();Co=null;if(!EG(BD)){f=I(EY(BD,0));Co=f;if(f!==null){c=1;break b;}}c=0;}if(!c)break;f=Co;if((f===null?(-1):DH(f.which))!=28)continue;if(!JF())continue;E3(a.dp);}M();G.clear(16640);CV(5889);C1();IQ(70.0,a.eA/a.ez,0.05000000074505806,1000.0);CV(5888);C1();HU(a,b);HF();G.uniform1i(Cq,1);G.uniform1i(BG,1);G.enable(2884);G.uniform1i(Cz,
0);Gq(a.dD,a.c7,0);G.uniform1i(Cz,1);G.uniform4f(EO,0.0,0.0,0.0,1.0);Gq(a.dD,a.c7,1);G.uniform1i(BG,0);f=BK;if(f!==null)Hf(a.dD,f);f=G;j=Cz;f.uniform1i(j,0);},E4=(a,b,c)=>{let d,e;a.eA=b;a.ez=c;d=window.document.getElementById("canvas");e=b;d.width=e;e=c;d.height=e;M();G.viewport(0,0,b,c);},IP=b=>{let c,d,e;M();c=new B9;d=new En;d.eY=Bq(4);e=new EW;e.ey=1.0;e.es=0.0;e.dQ=0.0;e.eV=60.0;e.d7=Gk();d.d8=e;Bo();Ei(c,d,null);d=new GY;d.eD=c;Ju(d);},Ha=()=>{let b;BK=null;CA=Bq(16);b=Bq(16);Cv=b;Bx=b;},Jf=F(),Ju=b=>
{setTimeout(()=>{Jx(FD)(b);},0);},FD=b=>{b.bt();},EE=b=>{Hn(b,0);},Hn=(b,c)=>{setTimeout(()=>{FD(b);},c);},JM=F(),Q=(b,c)=>{if(b===null||b===undefined){return null;}let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},J8=F();
function B9(){let a=this;E.call(a);a.fc=null;a.fb=B0;a.e8=B0;a.dU=null;a.d2=null;a.e9=null;a.dM=0;a.e2=null;}
let CW=null,Cb=null,DR=0,Bk=0,F7=null,Bo=()=>{Bo=Y(B9);IF();},Ei=(a,b,c)=>{let d;Bo();a.dU=new E;a.dM=1;a.e9=c;a.e2=b;d=DR;DR=d+1|0;a.fb=B1(d);},Kj=(a,b)=>{let c=new B9();Ei(c,a,b);return c;},Bu=b=>{Bo();if(Cb!==b)Cb=b;Cb.e8=Cx();},IA=a=>{let b,$$je;b=a.e2;if(b!==null){b=b;a:{b:{try{Je(b);break b;}catch($$e){$$je=U($$e);if($$je instanceof Bv){b=$$je;}else{throw $$e;}}CM(b);break a;}b.dP=Cx();b.dq=0;Fu(b);}}},Ba=()=>{Bo();return Cb;},ID=a=>{let b;b=a.fc;if(b!==null)return b;Bo();return F7;},IF=()=>{let b;b=new B9;Bo();Ei(b,
null,D(10));CW=b;Cb=b;DR=1;Bk=1;F7=new GG;},F$=F(0),FE=F(),DU=F(),HJ=null,Jm=null,Db=()=>{Db=Y(DU);H_();},Ed=(b,c)=>{Db();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},H_=()=>{HJ=BE(FL);Jm=P(DU,128);};
function EW(){let a=this;E.call(a);a.eV=0.0;a.d7=B0;a.d6=0;a.eu=0.0;a.ey=0.0;a.es=0.0;a.dQ=0.0;}
let HY=F();
function Ek(){E.call(this);this.eX=null;}
let HG=(a,b)=>{a.eX=b;},B7=a=>{let b=new Ek();HG(b,a);return b;},Bf=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Be(typeof b);d=!Bt(c,D(11))&&!Bt(c,D(12))?0:1;Ch();e=Eu;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);e.set(b,new WeakRef(h));return h;}if(Bt(c,D(13))){i=CX;j=Et;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);k=h;i.set(b,new WeakRef(k));j.register(k,
b);return h;}if(Bt(c,D(14))){l=CO;m=ED;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(Bt(c,D(15))){f=E_;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);E_=new WeakRef(h);return h;}}return B7(b);},I=b=>{if(b===null)return null;return !(b instanceof Ek)?b:b.eX;},I0=F(),Du=null,C2=null,Ke=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n;if(b!==null&&d!==null){if(c>=0&&e>=0&&f>=0&&(c
+f|0)<=CR(b)&&(e+f|0)<=CR(d)){a:{b:{if(b!==d){g=C$(BM(b));h=C$(BM(d));if(g!==null&&h!==null){if(g===h)break b;if(!CJ(g)&&!CJ(h)){i=b;j=0;k=c;while(j<f){c:{l=i.data;m=k+1|0;n=l[k];if(n!==null){n=BM(n);if(Cw(n.c2,h.c2)){k=1;break c;}}k=0;}if(!k){CS(b,c,d,e,j);b=new CK;L(b);J(b);}j=j+1|0;k=m;}CS(b,c,d,e,f);return;}if(!CJ(g))break a;if(CJ(h))break b;else break a;}b=new CK;L(b);J(b);}}CS(b,c,d,e,f);return;}b=new CK;L(b);J(b);}b=new Bd;L(b);J(b);}d=new C_;DG(d,D(16));J(d);},Fq=(b,c,d,e,f)=>{if(c>=0&&e>=0&&f>=0&&(c
+f|0)<=CR(b)&&(e+f|0)<=CR(d)){CS(b,c,d,e,f);return;}b=new Bd;L(b);J(b);},CS=(b,c,d,e,f)=>{if(f!==0){if(typeof b.data.buffer!=='undefined'){d.data.set(b.data.subarray(c,c+f),e);}else if(b!==d||e<c){for(let i=0;i<f;i=i+1|0){d.data[e++]=b.data[c++];}}else {c=c+f|0;e=e+f|0;for(let i=0;i<f;i=i+1|0){d.data[ --e]=b.data[ --c];}}}},Cx=()=>{return FN((new Date()).getTime());},Gk=()=>{return FN(performance.now()*1000000.0);},Fg=F(0),GG=F(),Ig=(a,b,c)=>{CM(c);},Bd=F(O),Gg=a=>{L(a);},Ki=()=>{let a=new Bd();Gg(a);return a;},Cm
=F(0);
function GY(){E.call(this);this.eD=null;}
let Iq=a=>{let b,c,d,$$je;b=a.eD;a:{b:{c:{d:{try{Bo();Bk=Bk+1|0;Bu(b);b.d2=J_();IA(b);}catch($$e){$$je=U($$e);if($$je instanceof Bg){c=$$je;break d;}else{c=$$je;break c;}}c=b.dU;Em(c);e:{try{DX(c);BR(c);break e;}catch($$e){$$je=U($$e);b=$$je;}BR(c);J(b);}b.dM=0;Bk=Bk-1|0;b.d2=null;Bu(CW);break a;}try{Ig(ID(b),b,c);break b;}catch($$e){$$je=U($$e);c=$$je;break c;}}d=b.dU;Em(d);f:{try{DX(d);BR(d);break f;}catch($$e){$$je=U($$e);b=$$je;}BR(d);J(b);}b.dM=0;Bk=Bk-1|0;b.d2=null;Bu(CW);J(c);}c=b.dU;Em(c);g:{try{DX(c);BR(c);break g;}
catch($$e){$$je=U($$e);b=$$je;}BR(c);J(b);}b.dM=0;Bk=Bk-1|0;b.d2=null;Bu(CW);}};
function GD(){let a=this;E.call(a);a.c6=null;a.eb=null;a.cM=null;a.cO=0;}
let CI=F(O),EV=F(0),Jr=F(0),Jq=F(O),Ff=F(O);
function Gn(){E.call(this);this.em=null;}
let I1=a=>{let b,c,d,e,f;b=a.em;if(!Cr(b)){c=b.cJ;if(c.cM===null){b=c.c6;if(b!==null&&!DB(b)){b=c.c6;d=b.dj;if(d==b.c$)e=null;else{f=b.c4.data;e=f[d];f[d]=null;b.dj=Gf(d,f.length);b.dK=b.dK+1|0;}if(e===null){b=new El;L(b);J(b);}e=e;c.c6=null;b=e;c=b.eq;e=b.er;d=b.en;b=b.eo;Bu(c);e=e.cJ;e.cM=c;e.cO=e.cO+d|0;c=null;CT(b,c);}}}},F4=F(0);
function FP(){E.call(this);this.ej=null;}
let J6=b=>{let c;c=new FP;c.ej=b;return c;},CT=(a,b)=>{a.ej.h(b);},Jv=(a,b)=>{a.ej.bH(b);};
function EX(){let a=this;E.call(a);a.eq=null;a.er=null;a.en=0;a.eo=null;}
let E9=F(0),CN=F(0),B4=F(),EG=a=>{return a.c5?0:1;},EA=F(0),Eh=F(0),D9=F(0),BX=F(0);
function F6(){let a=this;B4.call(a);a.dK=0;a.c4=null;a.dj=0;a.c$=0;}
let DB=a=>{return a.dj!=a.c$?0:1;},Gf=(b,c)=>{b=b+1|0;if(b==c)b=0;return b;},IY=F(),B$=b=>{return Math.sin(b);},CH=b=>{return Math.cos(b);},Hs=b=>{return Math.tan(b);},Cp=b=>{return b*3.141592653589793/180.0;},GB=b=>{return Math.sqrt(b);},Dy=b=>{return Math.floor(b);},Fi=()=>{return JL();},JL=()=>{return Math.random();},Dk=(b,c)=>{if(b<c)c=b;return c;},Cj=(b,c)=>{if(b>c)c=b;return c;},Iy=b=>{return Math.abs(b);},DE=b=>{return Iy(b);},CQ=F(Bd),GJ=F(),F3=null,Gu=null,E7=null,FR=0,Ep=0,GO=0,DC=0,BD=null,CP=null,EF
=0,FO=null,F2=null,Fw=null,Co=null,C5=null,Bh=()=>{Bh=Y(GJ);Jp();},Ii=()=>{Bh();if(DC)return;DC=1;},JS=()=>{let b,c,d,$$je;Bh();a:{b:{try{if(!Ep)break b;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}return;}c:{try{if(DC)break c;Ii();break c;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}d:{try{c=window;d=HS();FO=I(d);c.addEventListener("keydown",Q(I(d),"handleEvent"));c=window;d=HO();F2=I(d);c.addEventListener("keyup",Q(I(d),"handleEvent"));c
=window;d=Jc();Fw=I(d);c.addEventListener("keypress",Q(I(d),"handleEvent"));Ep=1;b=BD;if(b===null)break d;Gj(b);break d;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}return;}J(GZ(b));},Bb=b=>{Bh();return CP.data[b];},JF=()=>{let b;Bh();b=Co;return b===null?0:Bt(Be(b.type),D(17))?0:1;},DH=b=>{let c;Bh();c=C5.data;return b<=c.length&&b>=0?c[b]:(-1);},Jp=()=>{let b,c,d,e,f,g,h;F3=Jl(Z,[D(18),D(19),D(20),D(21),D(22),D(23),D(24),D(25),D(26),D(27),D(28),D(1),D(29),D(30),D(31),D(32),
D(33),D(34),D(35),D(36),D(37),D(38),D(39),D(40),D(41),D(42),D(43),D(44),D(45),D(46),D(47),D(48),D(49),D(50),D(51),D(52),D(53),D(54),D(55),D(56),D(57),D(58),D(59),D(60),D(61),D(62),D(63),D(64),D(65),D(66),D(67),D(68),D(69),D(70),D(71),D(72),D(73),D(74),D(75),D(76),D(77),D(78),D(79),D(80),D(81),D(82),D(83),D(84),D(85),D(86),D(87),D(88),D(89),D(90),D(91),D(92),D(93),D(94),D(95),D(96),D(97),D(98),D(99),D(100),D(101),D(101),D(101),D(102),D(103),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),
D(101),D(104),D(105),D(106),D(107),D(108),D(109),D(101),D(101),D(101),D(101),D(101),D(101),D(110),D(111),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(112),D(101),D(113),D(101),D(114),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(115),D(101),D(101),D(116),D(117),D(118),D(119),D(120),D(121),D(122),D(123),D(101),D(101),D(101),D(101),D(124),D(125),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(126),D(101),D(101),D(101),D(101),D(101),
D(101),D(101),D(101),D(101),D(101),D(101),D(127),D(101),D(128),D(101),D(129),D(130),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(131),D(132),D(101),D(133),D(134),D(135),D(101),D(136),D(101),D(137),D(101),D(138),D(139),D(140),D(141),D(142),D(101),D(101),D(101),D(101),D(101),D(101),D(143),D(144),D(145),D(146),D(147),D(148)]);Gu=P(Z,256);E7=F0(253);Ep=0;GO=0;BD=He();CP=GS(256);EF=0;FO=null;F2=null;Fw=null;Co=null;C5=I6([(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),14,15,(-1),(-1),(-1),
28,(-1),(-1),42,29,56,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),1,(-1),(-1),(-1),(-1),57,210,201,207,199,203,200,205,208,205,208,(-1),(-1),210,211,211,11,2,3,4,5,6,7,8,9,10,(-1),(-1),(-1),(-1),(-1),(-1),(-1),30,48,46,32,18,33,34,35,23,36,37,38,50,49,24,25,16,19,31,20,22,47,17,45,21,44,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),12,52,53,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),
(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),39,13,51,12,52,53,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),26,43,27,40]);b=0;c=F3.data;d=c.length;e=0;while(e<d){f=c[e];Gu.data[b]=f;g=E7;h=BA(b);CD(g,f,h);b=b+1|0;FR=FR+1|0;e
=e+1|0;}d=0;c=C5.data;b=c.length;e=0;while(e<b){if(Fx(BA(c[e]))!=(-1))d=d+1|0;e=e+1|0;}EF=d;},Bp=F(0),Fh=b=>{return b;},FY=F(0);
function Da(){E.call(this);this.eN=null;}
let JN=(b,c)=>{c;Fu(b.eN);};
function CB(){let a=this;E.call(a);a.eH=null;a.eh=null;a.eI=0;a.eC=0;a.eE=0;a.eJ=0;a.eB=0;a.eF=0;a.dZ=0;a.dr=null;a.dI=null;a.dH=null;a.dV=null;}
let Gi=0,B8=null,CE=0,Ce=0,BB=()=>{BB=Y(CB);H9();},E0=(a,b)=>{let c,d,e,f,g,h,i,j,k;BB();c=CE;if(c!=2){a.dZ=0;Ce=Ce+1|0;CE=c+1|0;if(I(a.dr.data[b])===null){d=a.dr.data;M();d[b]=Bf(G.createBuffer());a.dI.data[b]=Bf(G.createBuffer());a.dH.data[b]=Bf(G.createBuffer());}Gx(B8);c=a.eI;while(c<a.eJ){e=a.eC;while(e<a.eB){f=a.eE;while(f<a.eF){if(Bj(a.eh,c,e,f)){g=a.eh;if(e!=((g.cX*2|0)/3|0)?1:0){BF();Fc(Gr,B8,g,b,c,e,f);}else{BF();Fc(Er,B8,g,b,c,e,f);}}f=f+1|0;}e=e+1|0;}c=c+1|0;}d=a.dV.data;g=B8;h=I(a.dr.data[b]);i
=I(a.dI.data[b]);j=I(a.dH.data[b]);M();k=G;k.bindBuffer(34962,h);k.bufferData(34962,g.dk.subarray(0,g.cL*3|0),35044);k.bindBuffer(34962,i);k.bufferData(34962,g.dt.subarray(0,g.cL*2|0),35044);k.bindBuffer(34962,j);k.bufferData(34962,g.di.subarray(0,g.cL*3|0),35044);c=g.cL;Dh(g);d[b]=c;}},JT=(a,b)=>{let c;if(a.dZ){E0(a,0);E0(a,1);}if(a.dV.data[b]>0){M();c=G;BB();DV(Gi);c.uniform1i(BG,1);c.uniform1i(Cq,1);c.bindBuffer(34962,I(a.dr.data[b]));c.vertexAttribPointer(Ci,3,5126,!!0,0,0);c.enableVertexAttribArray(Ci);c.bindBuffer(34962,
I(a.dI.data[b]));c.vertexAttribPointer(Ct,2,5126,!!0,0,0);c.enableVertexAttribArray(Ct);c.bindBuffer(34962,I(a.dH.data[b]));c.vertexAttribPointer(Ca,3,5126,!!0,0,0);c.enableVertexAttribArray(Ca);c.bindBuffer(34963,DQ);c.drawElements(4,(a.dV.data[b]*6|0)/4|0,5123,0);}},H9=()=>{let b,c,d,e,f,g,h,i,j;b=D(149);Ck();if(Gv(CZ,b)===null?0:1)c=(Fz(CZ,b)).dl;else{c=Dw;Dw=c+1|0;M();d=G;e=d.createTexture();CD(DI,BA(c),Bf(e));CD(CZ,b,BA(c));DV(c);d.texParameteri(3553,10241,9728);d.texParameteri(3553,10240,9728);e=window.document.createElement("img");if
(b===D(150))f=1;else a:{f=0;if((f+D(150).cK.length|0)>b.cK.length)f=0;else{g=0;while(g<D(150).cK.length){h=CL(D(150),g);i=f+1|0;if(h!=CL(b,f)){f=0;break a;}g=g+1|0;f=i;}f=1;}}if(f){g=b.cK.length;f=b.cK.length;i=Df(1,g);if(!i)b=ET;else if(i<=0&&g<=f)b=FX(b.cK.substring(1,g));else{b=new CQ;L(b);J(b);}}e.src=BT(b);j=new C7;j.eM=c;j.eK=d;j.eL=e;e.addEventListener("load",Q(I(j),"handleEvent"));}Gi=c;B8=FI();CE=0;Ce=0;},C_=F(O),Gw=F(0),Fj=F(0),Gh=F(0),DJ=F();
function Dp(){DJ.call(this);this.ff=null;}
function Dl(){let a=this;Dp.call(a);a.fa=0;a.e$=null;a.fg=null;a.fd=null;}
let Cd=F(Dl),Go=a=>{let b,c;b=null;c=null;a.ff=b;a.e$=Bz();a.fg=BI(32);a.fa=0;a.fd=c;},Fd=(a,b)=>{a.B(b);a.B(D(5));},EZ=F(Cd),Js=(a,b)=>{if(b===null)b=D(3);Ix(BT(b));},EQ=F(0),D$=F();
function D7(){let a=this;D$.call(a);a.dB=0;a.c1=null;a.d1=0;a.e4=0.0;a.ee=0;}
let Hc=a=>{Ew(a,16);},GU=()=>{let a=new D7();Hc(a);return a;},Ew=(a,b)=>{let c;if(b<0){c=new B_;L(c);J(c);}b=FV(b);a.dB=0;a.c1=P(CC,b);a.e4=0.75;Gl(a);},F0=a=>{let b=new D7();Ew(b,a);return b;},FV=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},Gl=a=>{a.ee=a.c1.data.length*a.e4|0;},Fz=(a,b)=>{let c;c=Gv(a,b);if(c===null)return null;return c.dO;},Gv=(a,b)=>{let c,d;if(b===null)c=GM(a);else{d=b.b1();c=Fb(a,b,d&(a.c1.data.length-1|
0),d);}return c;},Fb=(a,b,c,d)=>{let e,f;e=a.c1.data[c];while(e!==null){if(e.d_==d){f=e.el;if(b!==f&&!b.by(f)?0:1)break;}e=e.dE;}return e;},GM=a=>{let b;b=a.c1.data[0];while(b!==null&&b.el!==null){b=b.dE;}return b;},CD=(a,b,c)=>{let d,e,f;if(b===null){d=GM(a);if(d===null){a.d1=a.d1+1|0;d=Ge(a,null,0,0);e=a.dB+1|0;a.dB=e;if(e>a.ee)Gz(a);}}else{e=b.b1();f=e&(a.c1.data.length-1|0);d=Fb(a,b,f,e);if(d===null){a.d1=a.d1+1|0;d=Ge(a,b,f,e);e=a.dB+1|0;a.dB=e;if(e>a.ee)Gz(a);}}b=d.dO;d.dO=c;return b;},Ge=(a,b,c,d)=>{let e,
f,g;e=new CC;f=null;e.el=b;e.dO=f;e.d_=d;g=a.c1.data;e.dE=g[c];g[c]=e;return e;},Gz=a=>{let b,c,d,e,f,g,h,i;b=a.c1.data.length;b=FV(!b?1:b<<1);c=P(CC,b);d=c.data;e=0;f=b-1|0;while(true){g=a.c1.data;if(e>=g.length)break;h=g[e];g[e]=null;while(h!==null){b=h.d_&f;i=h.dE;h.dE=d[b];d[b]=h;h=i;}e=e+1|0;}a.c1=c;Gl(a);},EP=F(0);
function Cg(){B4.call(this);this.cY=0;}
let BC=(a,b)=>{let c,d,e,f;c=a.c5;d=a;if(c<0){b=new Bd;L(b);J(b);}d=Gp(d,c);FA(d);e=new F1;e.eZ=b;b=d.dw;e.df=b;f=d.dx;e.de=f;if(b!==null)b.de=e;else d.dn.dT=e;if(f!==null)f.df=e;else d.dn.dF=e;d.dw=e;b=d.dn;b.c5=b.c5+1|0;c=b.cY+1|0;b.cY=c;d.dJ=c;d.ef=null;return 1;},Dz=F(Cg),EY=(a,b)=>{let c,d,e,f,g,h,i,j,k;if(b<0){c=new Bd;L(c);J(c);}c=Gp(a,b);FA(c);d=c.dx;if(d===null){c=new El;L(c);J(c);}e=d.eZ;c.ef=d;c.dw=d;f=d.de;c.dx=f;g=c.d5+1|0;c.d5=g;h=c.dn;i=d.df;if(i===null)h.dT=f;else i.de=f;j=d.de;if(j===null)h.dF
=i;else j.df=i;h.c5=h.c5-1|0;k=h.cY+1|0;h.cY=k;if(d===d){c.dw=!(f===null?0:1)?null:f.df;c.d5=g-1|0;}else if(d===f){if(!(d===null?0:1))j=null;c.dx=j;}c.dJ=k;c.ef=null;return e;};
function D6(){let a=this;Dz.call(a);a.dT=null;a.dF=null;a.c5=0;}
let Kd=a=>{return;},He=()=>{let a=new D6();Kd(a);return a;},Gj=a=>{a.dT=null;a.dF=null;a.c5=0;a.cY=a.cY+1|0;},Gp=(a,b)=>{let c,d,e,f;if(b<0){c=new Bd;L(c);J(c);}d=a.c5;if(b<=(d/2|0)){e=a.dT;f=0;while(f<b){e=e.de;f=f+1|0;}return F8(a,e,e===null?null:e.df,b);}if(b>d){c=new Bd;L(c);J(c);}c=a.dF;f=b;while(f<d){c=c.df;f=f+1|0;}return F8(a,c===null?null:c.de,c,b);},FS=F(),CZ=null,DI=null,Dw=0,C4=0,Ck=()=>{Ck=Y(FS);HH();},DV=b=>{Ck();if(b!=C4){M();G.bindTexture(3553,I(Fz(DI,BA(b))));C4=b;}},HH=()=>{CZ=GU();DI=GU();Dw
=1;C4=(-9999999);};
function FQ(){let a=this;E.call(a);a.dk=null;a.dt=null;a.di=null;a.cL=0;a.eT=0.0;a.eS=0.0;a.eU=0.0;a.eR=0.0;a.eQ=0.0;a.ds=0;a.dC=0;a.ec=null;a.e5=null;a.e6=null;}
let J$=a=>{a.dk=new Float32Array(300000);a.dt=new Float32Array(200000);a.di=new Float32Array(300000);a.cL=0;a.ds=0;a.dC=0;},FI=()=>{let a=new FQ();J$(a);return a;},Gm=a=>{let b;if(a.cL>0){M();b=G;if(a.ec===null){a.ec=b.createBuffer();a.e5=b.createBuffer();a.e6=b.createBuffer();}b.bindBuffer(34962,a.ec);b.bufferData(34962,a.dk.subarray(0,a.cL*3|0),35048);b.vertexAttribPointer(Ci,3,5126,!!0,0,0);b.enableVertexAttribArray(Ci);if(!a.dC)b.uniform1i(BG,0);else{b.bindBuffer(34962,a.e5);b.bufferData(34962,a.dt.subarray(0,
a.cL*2|0),35048);b.vertexAttribPointer(Ct,2,5126,!!0,0,0);b.enableVertexAttribArray(Ct);b.uniform1i(BG,1);}if(!a.ds)b.uniform1i(Cq,0);else{b.bindBuffer(34962,a.e6);b.bufferData(34962,a.di.subarray(0,a.cL*3|0),35048);b.vertexAttribPointer(Ca,3,5126,!!0,0,0);b.enableVertexAttribArray(Ca);b.uniform1i(Cq,1);}b.bindBuffer(34963,DQ);b.drawElements(4,(a.cL*6|0)/4|0,5123,0);}Dh(a);},Dh=a=>{a.cL=0;},Gx=a=>{Dh(a);a.ds=0;a.dC=0;},N=(a,b,c)=>{a.dC=1;a.eT=b;a.eS=c;},BU=(a,b,c,d)=>{a.ds=1;a.eU=b;a.eR=c;a.eQ=d;},H=(a,b,c,
d)=>{let e;a.dk[(a.cL*3|0)+0|0]=b;a.dk[(a.cL*3|0)+1|0]=c;a.dk[(a.cL*3|0)+2|0]=d;if(a.dC){a.dt[(a.cL*2|0)+0|0]=a.eT;a.dt[(a.cL*2|0)+1|0]=a.eS;}if(a.ds){a.di[(a.cL*3|0)+0|0]=a.eU;a.di[(a.cL*3|0)+1|0]=a.eR;a.di[(a.cL*3|0)+2|0]=a.eQ;}e=a.cL+1|0;a.cL=e;if(e==100000)Gm(a);},H2=F(),T=F(0);
function C7(){let a=this;E.call(a);a.eM=0;a.eK=null;a.eL=null;}
let JC=(b,c)=>{let d;b=b;d=b.eM;c=b.eK;b=b.eL;Ck();DV(d);c.texImage2D(3553,0,6408,6408,5121,b);c.generateMipmap(3553);},Dt=F(),Cs=F(Dt),G$=F(Cs),B_=F(O),Kb=F(),FF=F(),HA=null,Eu=null,CX=null,CO=null,E_=null,Et=null,ED=null,Ch=()=>{Ch=Y(FF);IU();},IU=()=>{let b;HA=new WeakMap();Eu=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();CX=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();CO=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(CX===null)b=null;else{b=new Dd;b=new FinalizationRegistry(Q(I(b),
"accept"));}Et=b;if(CO===null)b=null;else{b=new Dc;b=new FinalizationRegistry(Q(I(b),"accept"));}ED=b;},I9=F(),H8=F(),Ej=F(0),Dd=F(),It=(b,c)=>{b;Ch();CX.delete(c);},Dc=F(),HT=(b,c)=>{b;Ch();CO.delete(c);},Es=F(0);
function D8(){let a=this;E.call(a);a.el=null;a.dO=null;}
function DO(){E.call(this);this.ex=null;}
let G5=(a,b)=>{a.ex=b;},Hk=a=>{let b=new DO();G5(b,a);return b;},Io=(b,c)=>{E4(b.ex,window.innerWidth,window.innerHeight);},Gb=F(),DK=0,ER=0,ES=0,BQ=0.0,BP=0.0,Dv=0,DW=null,Gt=null,GX=0,Id=0,Ie=0,Cn=0,Bs=null,Ea=null,Ds=0,EJ=null,Gs=null,Fe=null,EH=null,FZ=null,Gc=null,FG=null,FB=null,Cc=null,V=()=>{V=Y(Gb);G9();},JG=()=>{let b,c,d,e,f;V();DW=P(Z,16);b=0;while(b<16){c=DW.data;d=Bz();Dj(Bl(d,D(151)),b);c[b]=BO(d);d=Gt;e=DW.data[b];f=BA(b);CD(d,e,f);b=b+1|0;}GX=1;},IT=()=>{let b,c,d,$$je;V();a:{b:{try{if(!DK)break b;}
catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}return;}c:{try{if(GX)break c;JG();break c;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}d:{try{c=window;d=I$();EJ=I(d);c.addEventListener("contextmenu",Q(I(d),"handleEvent"));c=window;d=Hw();Gs=I(d);c.addEventListener("mousedown",Q(I(d),"handleEvent"));c=window;d=Ht();Fe=I(d);c.addEventListener("mouseup",Q(I(d),"handleEvent"));c=window;d=Ij();EH=I(d);c.addEventListener("mousemove",Q(I(d),"handleEvent"));c
=window;d=Il();FZ=I(d);c.addEventListener("wheel",Q(I(d),"handleEvent"));c=window.document;d=IC();Gc=I(d);c.addEventListener("pointerlockchange",Q(I(d),"handleEvent"));c=window;d=Is();FG=I(d);c.addEventListener("mouseleave",Q(I(d),"handleEvent"));c=window;d=IJ();FB=I(d);c.addEventListener("mouseenter",Q(I(d),"handleEvent"));DK=1;b=Bs;if(b===null)break d;Gj(b);break d;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}try{Fp(Cn);}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}
else{throw $$e;}}return;}J(GZ(b));},GF=()=>{let b,c;V();b=Cc;if(b===null)return (-1);c=b.button;if(c==1)c=2;else if(c==2)c=1;return c;},Fr=()=>{let b;V();b=Cc;return b===null?0:Bt(Be(b.type),D(152));},Fp=b=>{let c;V();c=Cn;Cn=b;if(DK){if(b&&!c){if(!(document.pointerLockElement!=null?1:0)){Id=ER;Ie=ES;BQ=0.0;BP=0.0;document.body.requestPointerLock();}}else if(!b&&c&&(document.pointerLockElement!=null?1:0))document.exitPointerLock();Dv=0;BP=0.0;BQ=0.0;}},G9=()=>{Gt=F0(16);Bs=new D6;Ea=GS(8);Ds=1;EJ=null;Gs=null;Fe
=null;EH=null;FZ=null;Gc=null;FG=null;FB=null;Cc=null;};
function DN(){E.call(this);this.eW=null;}
let Hy=(a,b)=>{a.eW=b;},Hb=a=>{let b=new DN();Hy(b,a);return b;},Jo=(b,c)=>{b=b.eW;M();b.requestPointerLock();},JA=F(Cs);
function GV(){let a=this;E.call(a);a.cU=0;a.cZ=0;a.cX=0;a.dv=null;a.dL=null;a.dg=null;}
let Hq=(a,b,c,d)=>{let e,f,g,h,i,j,k,l;a.dg=FK();a.cU=b;a.cZ=c;a.cX=d;e=S(b,c);f=BS(S(e,d));g=f.data;a.dv=f;a.dL=CU(e);h=0;i=d*2|0;while(h<b){j=0;while(j<d){k=0;while(k<c){g[S(S(j,c)+k|0,b)+h|0]=(j>(i/3|0)?0:1)<<24>>24;k=k+1|0;}j=j+1|0;}h=h+1|0;}Eo(a,0,0,b,c);l=new Di;l.eP=a;Hp(Q(I(l),"onResult"));},IN=(a,b,c)=>{let d=new GV();Hq(d,a,b,c);return d;},E3=a=>{let b,$$je;a:{try{HM(BT(Ib(G7(),a.dv)));break a;}catch($$e){$$je=U($$e);if($$je instanceof Bv){b=$$je;CM(b);break a;}else{throw $$e;}}}},Eo=(a,b,c,d,e)=>
{let f,g,h,i,j,k,l;f=b+d|0;d=c+e|0;while(b<f){g=c;while(g<d){h=a.dL.data[b+S(g,a.cU)|0];i=a.cX-1|0;while(i>0&&!Bj(a,b,i,g)){i=i+(-1)|0;}a:{a.dL.data[b+S(g,a.cU)|0]=i;e=Df(h,i);if(e){j=e>=0?i:h;if(e>0)i=h;k=0;while(true){l=a.dg;if(k>=l.c0)break a;DS(BV(l,k),b-1|0,j-1|0,g-1|0,b+1|0,i+1|0,g+1|0);k=k+1|0;}}}g=g+1|0;}b=b+1|0;}},Bj=(a,b,c,d)=>{let e,f;if(b>=0&&c>=0&&d>=0){e=a.cU;if(b<e&&c<a.cX){f=a.cZ;if(d<f)return a.dv.data[S(S(c,f)+d|0,e)+b|0]!=1?0:1;}}return 0;},IM=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m;c=FK();d=b.cP
|0;e=b.cQ+1.0|0;f=b.cR|0;g=b.cW+1.0|0;h=b.cT|0;i=b.cS+1.0|0;if(d<0)d=0;if(f<0)f=0;if(h<0)h=0;j=a.cU;if(e<=j)j=e;k=a.cX;if(g<=k)k=g;g=a.cZ;if(i<=g)g=i;while(d<j){l=f;while(l<k){m=h;while(m<g){if(Bj(a,d,l,m))FJ(c,Cy(d,l,m,d+1|0,l+1|0,m+1|0));m=m+1|0;}l=l+1|0;}d=d+1|0;}return c;},BY=(a,b,c,d)=>{let e,f;e=1.0;if(b>=0&&c>=0&&d>=0){f=a.cU;if(b<f&&c<a.cX&&d<a.cZ){if(c<a.dL.data[b+S(d,f)|0])e=0.4000000059604645;return e;}}return e;},E6=(a,b,c,d,e)=>{let f,g,h,i,j;a:{if(b>=0&&c>=0&&d>=0){f=a.cU;if(b<f&&c<a.cX){g=a.cZ;if
(d<g){a.dv.data[S(S(c,g)+d|0,f)+b|0]=e<<24>>24;Eo(a,b,d,1,1);f=0;e=b-1|0;g=c-1|0;h=d-1|0;b=b+1|0;i=c+1|0;d=d+1|0;while(true){j=a.dg;if(f>=j.c0)break a;DS(BV(j,f),e,g,h,b,i,d);f=f+1|0;}}}}}},Hp=b=>{var req=indexedDB.open('rubydung',1);req.onupgradeneeded=function(e){e.target.result.createObjectStore('levels');};req.onsuccess=function(e){var db=e.target.result;if(!db.objectStoreNames.contains('levels'))return;var tx=db.transaction('levels','readonly');var getReq=(tx.objectStore('levels')).get('level.dat');getReq.onsuccess
=function(e){if(e.target.result)b(e.target.result);};};},HM=b=>{var req=indexedDB.open('rubydung',1);req.onupgradeneeded=function(e){e.target.result.createObjectStore('levels');};req.onsuccess=function(e){var db=e.target.result;var tx=db.transaction('levels','readwrite');(tx.objectStore('levels')).put(b,'level.dat');};},Fa=F(0);
function FH(){let a=this;E.call(a);a.d$=null;a.du=null;a.dS=0;a.eg=0;a.d9=0;a.dR=null;}
let Ia=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p;a.dR=FI();a.d$=b;FJ(b.dg,a);c=b.cU/16|0;a.dS=c;d=b.cX/16|0;a.eg=d;e=b.cZ/16|0;a.d9=e;a.du=P(CB,S(S(c,d),e));c=0;while(c<a.dS){f=0;while(f<a.eg){d=0;while(true){e=a.d9;if(d>=e)break;g=c*16|0;h=f*16|0;i=d*16|0;j=(c+1|0)*16|0;k=(f+1|0)*16|0;l=d+1|0;m=l*16|0;n=b.cU;if(j<=n)n=j;j=b.cX;if(k<=j)j=k;k=b.cZ;if(m<=k)k=m;o=a.du.data;e=S(c+S(f,a.dS)|0,e)+d|0;p=new CB;BB();p.dZ=1;p.dr=P(E,2);p.dI=P(E,2);p.dH=P(E,2);p.dV=CU(2);p.eh=b;p.eI=g;p.eC=h;p.eE=i;p.eJ=n;p.eB=j;p.eF=k;p.eH
=Cy(g,h,i,n,j,k);o[e]=p;d=l;}f=f+1|0;}c=c+1|0;}},In=a=>{let b=new FH();Ia(b,a);return b;},Gq=(a,b,c)=>{let d,e,f;BB();CE=0;Cu();HR(C8);d=C8;e=0;while(true){f=a.du.data;if(e>=f.length)break;b=f[e].eH;if(Jz(d,b.cP,b.cR,b.cT,b.cQ,b.cW,b.cS))JT(a.du.data[e],c);e=e+1|0;}},JK=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z;c=b.dy;d=b.dz;e=b.dA;f=CH(Cp( -b.c8));g=B$(Cp( -b.c8));h=CH(Cp(b.c_));i=B$(Cp(b.c_))*f;j= -h*f;k=Dy(c)|0;l=Dy(d)|0;m=Dy(e)|0;n=CY(i,0.0);o=n<=0?(-1):1;p=CY(g,0.0);q=p<=0?(-1):1;r=CY(j,
0.0);s=r<=0?(-1):1;t=!n?3.4028234663852886E38:DE(1.0/i);u=!p?3.4028234663852886E38:DE(1.0/g);v=!r?3.4028234663852886E38:DE(1.0/j);w=n<=0?(c-k)*t:((k+1|0)-c)*t;x=p<=0?(d-l)*u:((l+1|0)-d)*u;y=r<=0?(e-m)*v:((m+1|0)-e)*v;n=(-1);z=0.0;while(z<5.0){if(Bj(a.d$,k,l,m)){b=new GP;b.dW=k;b.dX=l;b.dY=m;b.e_=0;b.ea=n;M();BK=b;return;}if(!(w<x)){if(!(x<y)){c=y+v;m=m+s|0;n=s<=0?3:2;z=y;y=c;continue;}c=x+u;l=l+q|0;n=q<=0?1:0;z=x;x=c;continue;}if(!(w<y)){c=y+v;m=m+s|0;n=s<=0?3:2;z=y;y=c;continue;}c=w+t;k=k+o|0;n=o<=0?5:4;z=
w;w=c;}b=null;M();BK=b;},Hf=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o;M();c=G;c.enable(3042);c.blendFunc(770,1);c.uniform1f(Dm,B$(DT(Cx())/100.0)*0.20000000298023224+0.4000000059604645);Gx(a.dR);BF();d=a.dR;e=b.dW;f=b.dX;g=b.dY;h=b.ea;i=e;j=i+0.0;k=i+1.0;l=f;m=l+0.0;n=l+1.0;o=g;l=o+0.0;i=o+1.0;if(!h){H(d,j,m,i);H(d,j,m,l);H(d,k,m,l);H(d,k,m,i);}if(h==1){H(d,k,n,i);H(d,k,n,l);H(d,j,n,l);H(d,j,n,i);}if(h==2){H(d,j,n,l);H(d,k,n,l);H(d,k,m,l);H(d,j,m,l);}if(h==3){H(d,j,n,i);H(d,j,m,i);H(d,k,m,i);H(d,k,n,i);}if(h==4)
{H(d,j,n,i);H(d,j,n,l);H(d,j,m,l);H(d,j,m,i);}if(h==5){H(d,k,m,i);H(d,k,m,l);H(d,k,n,l);H(d,k,n,i);}Gm(a.dR);c.disable(3042);b=Dm;c.uniform1f(b,1.0);},DS=(a,b,c,d,e,f,g)=>{let h,i,j,k,l;h=b/16|0;e=e/16|0;b=c/16|0;c=f/16|0;f=d/16|0;g=g/16|0;if(h<0)h=0;if(b<0)b=0;if(f<0)f=0;i=a.dS;if(e>=i)e=i-1|0;d=a.eg;if(c>=d)c=d-1|0;j=a.d9;if(g>=j)g=j-1|0;while(h<=e){k=b;while(k<=c){l=f;while(l<=g){a.du.data[S(h+S(k,i)|0,j)+l|0].dZ=1;l=l+1|0;}k=k+1|0;}h=h+1|0;}},Im=a=>{let b;b=a.d$;DS(a,0,0,0,b.cU,b.cX,b.cZ);};
function EL(){let a=this;E.call(a);a.dN=null;a.ew=0.0;a.ev=0.0;a.eG=0.0;a.dy=0.0;a.dz=0.0;a.dA=0.0;a.da=0.0;a.dh=0.0;a.dc=0.0;a.c_=0.0;a.c8=0.0;a.c3=null;a.d0=0;}
let Iz=(a,b)=>{a.d0=0;a.dN=b;Fs(a);},Jk=a=>{let b=new EL();Iz(b,a);return b;},Fs=a=>{let b,c,d,e;b=Fi();c=a.dN;b=b*c.cU;d=c.cX+10|0;e=Fi()*a.dN.cZ;a.dy=b;a.dz=d;a.dA=e;a.c3=Cy(b-0.30000001192092896,d-0.8999999761581421,e-0.30000001192092896,b+0.30000001192092896,d+0.8999999761581421,e+0.30000001192092896);},J5=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q;a.ew=a.dy;a.ev=a.dz;a.eG=a.dA;b=0.0;c=0.0;if(Bb(19))Fs(a);if(!(!Bb(200)&&!Bb(17)))c=(-1.0);if(!(!Bb(208)&&!Bb(31)))c=c+1.0;if(!(!Bb(203)&&!Bb(30)))b=(-1.0);if(!(!Bb(205)
&&!Bb(32)))b=b+1.0;if(!(!Bb(57)&&!Bb(219))&&a.d0)a.dh=0.11999999731779099;d=!a.d0?0.004999999888241291:0.019999999552965164;e=b*b+c*c;if(!(e<0.009999999776482582)){d=d/GB(e);b=b*d;c=c*d;d=B$(a.c_*3.141592653589793/180.0);e=CH(a.c_*3.141592653589793/180.0);a.da=a.da+b*e-c*d;a.dc=a.dc+c*e+b*d;}b=a.dh-0.005;a.dh=b;c=a.da;d=a.dc;f=a.dN;g=a.c3;h=g.cP;i=g.cR;j=g.cT;k=g.cQ;l=g.cW;m=g.cS;if(c<0.0)h=h+c;if(c>0.0)k=k+c;n=Df(b,0.0);if(n<0)i=i+b;if(b>0.0)l=l+b;if(d<0.0)j=j+d;if(d>0.0)m=m+d;g=IM(f,Cy(h,i,j,k,l,m));o=0;p
=g;k=b;while(o<p.c0){k=H6(BV(p,o),a.c3,k);o=o+1|0;}De(a.c3,0.0,k,0.0);q=0;e=c;while(q<p.c0){e=J0(BV(p,q),a.c3,e);q=q+1|0;}De(a.c3,e,0.0,0.0);q=0;h=d;while(q<p.c0){h=Hd(BV(p,q),a.c3,h);q=q+1|0;}De(a.c3,0.0,0.0,h);q=CY(b,k);o=q&&n<0?1:0;a.d0=o;if(c!==e)a.da=0.0;if(q)a.dh=0.0;if(d!==h)a.dc=0.0;g=a.c3;a.dy=(g.cP+g.cQ)/2.0;a.dz=g.cR+1.6200000047683716;a.dA=(g.cT+g.cS)/2.0;b=a.da*0.9100000262260437;a.da=b;a.dh=a.dh*0.9800000190734863;c=a.dc*0.9100000262260437;a.dc=c;if(o){a.da=b*0.800000011920929;a.dc=c*0.800000011920929;}},El
=F(O);
function GP(){let a=this;E.call(a);a.dW=0;a.dX=0;a.dY=0;a.e_=0;a.ea=0;}
function CC(){let a=this;D8.call(a);a.d_=0;a.dE=null;}
let Ee=F(),J7=a=>{return;},HS=()=>{let a=new Ee();J7(a);return a;},I7=(b,c)=>{let d;b;Bh();CP.data[DH(c.which)]=1;b=BD;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();},Eg=F(),JX=a=>{return;},HO=()=>{let a=new Eg();JX(a);return a;},IR=(b,c)=>{let d;b;Bh();CP.data[DH(c.which)]=0;b=BD;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();},Ef=F(),I2=a=>{return;},Jc=()=>{let a=new Ef();I2(a);return a;},I4=(b,c)=>{let d;b;Bh();if(GO&&(c.repeat?1:0)){b=BD;d=Bf(c);BC(b,d);}c.preventDefault();c.stopPropagation();},Gd
=F(Bv),H$=(a,b)=>{Do(a);a.ed=1;a.ek=1;HP(a);a.d3=b;},GZ=a=>{let b=new Gd();H$(b,a);return b;},DY=F(),IW=a=>{return;},I$=()=>{let a=new DY();IW(a);return a;},Hm=(b,c)=>{b;c.preventDefault();c.stopPropagation();},D1=F(),JH=a=>{return;},Hw=()=>{let a=new D1();JH(a);return a;},H4=(b,c)=>{let d,e,f;b;d=c.button;V();e=Ea;if(d==1)d=2;else if(d==2)d=1;e.data[d]=1;b=Bs;f=Bf(c);BC(b,f);c.preventDefault();c.stopPropagation();},D2=F(),JZ=a=>{return;},Ht=()=>{let a=new D2();JZ(a);return a;},Jg=(b,c)=>{let d,e,f;b;d=c.button;V();e
=Ea;if(d==1)d=2;else if(d==2)d=1;e.data[d]=0;b=Bs;f=Bf(c);BC(b,f);c.preventDefault();c.stopPropagation();},DZ=F(),JQ=a=>{return;},Ij=()=>{let a=new DZ();JQ(a);return a;},J1=(b,c)=>{let d,e;b;c.preventDefault();c.stopPropagation();d=window.devicePixelRatio;e=c.clientX*d|0;V();ER=e;ES=(window.innerHeight-c.clientY|0)*d|0;BQ=BQ+c.movementX;BP=BP+ -c.movementY;b=Bs;c=Bf(c);BC(b,c);},D0=F(),JV=a=>{return;},Il=()=>{let a=new D0();JV(a);return a;},I5=(b,c)=>{let d,e;b;V();b=Bs;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();e
=!(c.deltaY>0.0)?(-1):1;Dv=Dv+e|0;},D4=F(),JY=a=>{return;},IC=()=>{let a=new D4();JY(a);return a;},Ja=(b,c)=>{b;if(!(document.pointerLockElement!=null?1:0))Cn=0;else Cn=1;},D5=F(),JO=a=>{return;},Is=()=>{let a=new D5();JO(a);return a;},Iw=(b,c)=>{b;c.preventDefault();c.stopPropagation();V();Ds=0;},D3=F(),IV=a=>{return;},IJ=()=>{let a=new D3();IV(a);return a;},HD=(b,c)=>{b;c.preventDefault();c.stopPropagation();V();Ds=1;},FW=F(0);
function FM(){let a=this;Cg.call(a);a.dm=null;a.c0=0;}
let H3=a=>{a.dm=P(E,10);},FK=()=>{let a=new FM();H3(a);return a;},BV=(a,b)=>{let c;if(b>=0&&b<a.c0)return a.dm.data[b];c=new Bd;L(c);J(c);},IH=a=>{return a.c0;},FJ=(a,b)=>{let c,d,e,f,g,h;c=a.c0+1|0;d=a.dm.data.length;if(d<c){c=d>=1073741823?2147483647:Cj(c,Cj(d*2|0,5));e=a.dm;f=C$(BM(e));if(f===null){b=new C_;L(b);J(b);}if(f===BE(IK)){b=new B_;L(b);J(b);}if(c<0){b=new GW;L(b);J(b);}g=e.data;e=Hr(f.c2,c);h=Dk(c,g.length);d=0;while(d<h){e.data[d]=g[d];d=d+1|0;}a.dm=e;}e=a.dm.data;h=a.c0;a.c0=h+1|0;e[h]=b;a.cY
=a.cY+1|0;return 1;},EU=F(Cd),BL=(a,b)=>{if(b===null)b=D(3);HV(BT(b));},IB=F(),FT=(b,c)=>{let d,e,f,g;b=b.data;d=0;e=b.length;if(d>e){f=new B_;L(f);J(f);}while(d<e){g=d+1|0;b[d]=c;d=g;}};
function Gy(){let a=this;E.call(a);a.db=0.0;a.cP=0.0;a.cR=0.0;a.cT=0.0;a.cQ=0.0;a.cW=0.0;a.cS=0.0;}
let G_=(a,b,c,d,e,f,g)=>{a.db=0.0;a.cP=b;a.cR=c;a.cT=d;a.cQ=e;a.cW=f;a.cS=g;},Cy=(a,b,c,d,e,f)=>{let g=new Gy();G_(g,a,b,c,d,e,f);return g;},J0=(a,b,c)=>{let d,e;if(!(b.cW<=a.cR)&&!(b.cR>=a.cW)){if(!(b.cS<=a.cT)&&!(b.cT>=a.cS)){if(!(c>0.0))d=c;else{d=b.cQ;e=a.cP;if(!(d<=e))d=c;else{d=e-d-a.db;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cP;e=a.cQ;if(!(c>=e))e=d;else{e=e-c+a.db;if(!(e>d))e=d;}}return e;}return c;}return c;},H6=(a,b,c)=>{let d,e;if(!(b.cQ<=a.cP)&&!(b.cP>=a.cQ)){if(!(b.cS<=a.cT)&&!(b.cT>=a.cS)){if
(!(c>0.0))d=c;else{d=b.cW;e=a.cR;if(!(d<=e))d=c;else{d=e-d-a.db;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cR;e=a.cW;if(!(c>=e))e=d;else{e=e-c+a.db;if(!(e>d))e=d;}}return e;}return c;}return c;},Hd=(a,b,c)=>{let d,e;if(!(b.cQ<=a.cP)&&!(b.cP>=a.cQ)){if(!(b.cW<=a.cR)&&!(b.cR>=a.cW)){if(!(c>0.0))d=c;else{d=b.cS;e=a.cT;if(!(d<=e))d=c;else{d=e-d-a.db;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cT;e=a.cS;if(!(c>=e))e=d;else{e=e-c+a.db;if(!(e>d))e=d;}}return e;}return c;}return c;},De=(a,b,c,d)=>{a.cP=a.cP+b;a.cR=a.cR+
c;a.cT=a.cT+d;a.cQ=a.cQ+b;a.cW=a.cW+c;a.cS=a.cS+d;},H5=F(),CR=b=>{let c;c=(BM(b)).c2;if(c[K].itemType!==null)return JB(b);b=new B_;L(b);J(b);},CK=F(O),JJ=F(),G7=()=>{let b;b=new F_;Bi();b.e7=Dq;b.e0=1;return b;},Jy=()=>{let b;b=new Ft;Bi();b.et=Eb;return b;};
function DM(){let a=this;E.call(a);a.c9=null;a.e1=null;a.eO=null;a.dd=null;}
let C8=null,Cu=()=>{Cu=Y(DM);Hg();},BZ=(a,b,c)=>{let d,e;b=b.data;d=GB(b[c].data[0]*b[c].data[0]+b[c].data[1]*b[c].data[1]+b[c].data[2]*b[c].data[2]);e=b[c].data;e[0]=e[0]/d;e=b[c].data;e[1]=e[1]/d;e=b[c].data;e[2]=e[2]/d;b=b[c].data;b[3]=b[3]/d;},HR=a=>{let b,c,d,e;M();b=CA;c=b.data;a.e1=b;b=Cv;d=b.data;a.eO=b;b=a.dd.data;b[0]=d[0]*c[0]+d[1]*c[4]+d[2]*c[8]+d[3]*c[12];b[1]=d[0]*c[1]+d[1]*c[5]+d[2]*c[9]+d[3]*c[13];b[2]=d[0]*c[2]+d[1]*c[6]+d[2]*c[10]+d[3]*c[14];b[3]=d[0]*c[3]+d[1]*c[7]+d[2]*c[11]+d[3]*c[15];b[4]
=d[4]*c[0]+d[5]*c[4]+d[6]*c[8]+d[7]*c[12];b[5]=d[4]*c[1]+d[5]*c[5]+d[6]*c[9]+d[7]*c[13];b[6]=d[4]*c[2]+d[5]*c[6]+d[6]*c[10]+d[7]*c[14];b[7]=d[4]*c[3]+d[5]*c[7]+d[6]*c[11]+d[7]*c[15];b[8]=d[8]*c[0]+d[9]*c[4]+d[10]*c[8]+d[11]*c[12];b[9]=d[8]*c[1]+d[9]*c[5]+d[10]*c[9]+d[11]*c[13];b[10]=d[8]*c[2]+d[9]*c[6]+d[10]*c[10]+d[11]*c[14];b[11]=d[8]*c[3]+d[9]*c[7]+d[10]*c[11]+d[11]*c[15];b[12]=d[12]*c[0]+d[13]*c[4]+d[14]*c[8]+d[15]*c[12];b[13]=d[12]*c[1]+d[13]*c[5]+d[14]*c[9]+d[15]*c[13];b[14]=d[12]*c[2]+d[13]*c[6]+d[14]
*c[10]+d[15]*c[14];b[15]=d[12]*c[3]+d[13]*c[7]+d[14]*c[11]+d[15]*c[15];d=a.c9;c=d.data;c[0].data[0]=b[3]-b[0];c[0].data[1]=b[7]-b[4];c[0].data[2]=b[11]-b[8];c[0].data[3]=b[15]-b[12];BZ(a,d,0);b=a.c9;d=b.data;e=d[1].data;c=a.dd.data;e[0]=c[3]+c[0];d[1].data[1]=c[7]+c[4];d[1].data[2]=c[11]+c[8];d[1].data[3]=c[15]+c[12];BZ(a,b,1);b=a.c9;d=b.data;e=d[2].data;c=a.dd.data;e[0]=c[3]+c[1];d[2].data[1]=c[7]+c[5];d[2].data[2]=c[11]+c[9];d[2].data[3]=c[15]+c[13];BZ(a,b,2);b=a.c9;d=b.data;e=d[3].data;c=a.dd.data;e[0]=c[3]
-c[1];d[3].data[1]=c[7]-c[5];d[3].data[2]=c[11]-c[9];d[3].data[3]=c[15]-c[13];BZ(a,b,3);b=a.c9;d=b.data;e=d[4].data;c=a.dd.data;e[0]=c[3]-c[2];d[4].data[1]=c[7]-c[6];d[4].data[2]=c[11]-c[10];d[4].data[3]=c[15]-c[14];BZ(a,b,4);b=a.c9;d=b.data;e=d[5].data;c=a.dd.data;e[0]=c[3]+c[2];d[5].data[1]=c[7]+c[6];d[5].data[2]=c[11]+c[10];d[5].data[3]=c[15]+c[14];BZ(a,b,5);},Jz=(a,b,c,d,e,f,g)=>{let h,i;h=0;while(h<6){i=a.c9.data;if(!(i[h].data[0]*b+i[h].data[1]*c+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]
*c+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*f+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*f+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*c+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*c+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*f+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*f+i[h].data[2]*g+i[h].data[3]>0.0))return 0;h=h+1|0;}return 1;},Hg=()=>{let b;b=new DM;Cu();b.c9=IS([4,6]);b.e1=Bq(16);b.eO
=Bq(16);b.dd=Bq(16);C8=b;};
function Dn(){E.call(this);this.ei=0;}
let Er=null,Gr=null,BF=()=>{BF=Y(Dn);JE();},G8=(a,b)=>{BF();a.ei=0;a.ei=b;},Fo=a=>{let b=new Dn();G8(b,a);return b;},Fc=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r;h=a.ei/16.0;i=h+0.062437500804662704;j=e;k=j+0.0;l=j+1.0;m=f;n=m+0.0;j=m+1.0;m=g;o=m+0.0;p=m+1.0;q=f-1|0;if(!Bj(c,e,q,g)){m=BY(c,e,q,g)*1.0;if((m!==1.0?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,h,0.062437500804662704);H(b,k,n,p);N(b,h,0.0);H(b,k,n,o);N(b,i,0.0);H(b,l,n,o);N(b,i,0.062437500804662704);H(b,l,n,p);}}if(!Bj(c,e,f+1|0,g)){m=BY(c,e,f,g)*1.0;if((m
!==1.0?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.062437500804662704);H(b,l,j,p);N(b,i,0.0);H(b,l,j,o);N(b,h,0.0);H(b,k,j,o);N(b,h,0.062437500804662704);H(b,k,j,p);}}r=g-1|0;if(!Bj(c,e,f,r)){m=BY(c,e,f,r)*0.800000011920929;if((m!==0.800000011920929?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.0);H(b,k,j,o);N(b,h,0.0);H(b,l,j,o);N(b,h,0.062437500804662704);H(b,l,n,o);N(b,i,0.062437500804662704);H(b,k,n,o);}}r=g+1|0;if(!Bj(c,e,f,r)){m=BY(c,e,f,r)*0.800000011920929;if((m!==0.800000011920929?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,
h,0.0);H(b,k,j,p);N(b,h,0.062437500804662704);H(b,k,n,p);N(b,i,0.062437500804662704);H(b,l,n,p);N(b,i,0.0);H(b,l,j,p);}}r=e-1|0;if(!Bj(c,r,f,g)){m=BY(c,r,f,g)*0.6000000238418579;if((m!==0.6000000238418579?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.0);H(b,k,j,p);N(b,h,0.0);H(b,k,j,o);N(b,h,0.062437500804662704);H(b,k,n,o);N(b,i,0.062437500804662704);H(b,k,n,p);}}e=e+1|0;if(!Bj(c,e,f,g)){m=BY(c,e,f,g)*0.6000000238418579;if((m!==0.6000000238418579?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,h,0.062437500804662704);H(b,l,n,p);N(b,
i,0.062437500804662704);H(b,l,n,o);N(b,i,0.0);H(b,l,j,o);N(b,h,0.0);H(b,l,j,p);}}},JE=()=>{Er=Fo(0);Gr=Fo(1);},GQ=F(0);
function Di(){E.call(this);this.eP=null;}
let G3=(b,c)=>{let d,e,f,g,$$je;c=Be(c);b=b.eP;a:{try{d=Hv(Jy(),c);e=d.data;f=b.dv;Fq(d,0,f,0,Dk(e.length,f.data.length));Eo(b,0,0,b.cU,b.cZ);g=0;while(g<IH(b.dg)){Im(BV(b.dg,g));g=g+1|0;}break a;}catch($$e){$$je=U($$e);if($$je instanceof Bv){b=$$je;CM(b);break a;}else{throw $$e;}}}};
function F_(){let a=this;E.call(a);a.e7=null;a.e0=0;}
let Ib=(a,b)=>{let c,d,e,f,g,h;c=b.data;d=a.e7;e=a.e0;Bi();f=c.length;g=((f+2|0)/3|0)*4|0;if(!e){f=f%3|0;if(f)g=g-(3-f|0)|0;}h=BS(g);c=h.data;IO(b,h,d,e);e=c.length;d=BI(e);b=d.data;g=0;while(g<e){b[g]=c[g]&255&65535;g=g+1|0;}return Ez(d);},F5=F(),Dq=null,GI=null,Eb=null,C6=null,Bi=()=>{Bi=Y(F5);Jn();},Ih=(b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p;Bi();b=b.data;e=b.length;f=e-1|0;while(f>=0&&b[f]==61){e=e+(-1)|0;f=f+(-1)|0;}g=(e/4|0)*4|0;h=0;i=0;while(h<g){j=c.data;f=h+1|0;k=Bn(d,b[h]);h=f+1|0;l=Bn(d,b[f]);f=h+1
|0;m=Bn(d,b[h]);h=f+1|0;n=Bn(d,b[f]);o=k<<18|l<<12|m<<6|n;f=i+1|0;j[i]=(o>>>16|0)<<24>>24;k=f+1|0;j[f]=(o>>>8|0)<<24>>24;i=k+1|0;j[k]=o<<24>>24;}p=e-h|0;if(p==2)c.data[i]=(Bn(d,b[h])<<2|(Bn(d,b[h+1|0])>>>4|0))<<24>>24;else if(p==3){c=c.data;k=Bn(d,b[h]);l=Bn(d,b[h+1|0]);h=Bn(d,b[h+2|0]);c[i]=(k<<2|(l>>>4|0))<<24>>24;c[i+1|0]=(l<<4|(h>>>2|0))<<24>>24;}},Bn=(b,c)=>{Bi();return b.data[c];},IO=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n;Bi();f=b.data;g=f.length;h=(g/3|0)*3|0;i=0;j=0;while(j<h){b=c.data;k=i+1|0;b[i]=Bm(d,
(f[j]>>>2|0)<<24>>24);l=k+1|0;m=f[j]<<4;i=j+1|0;b[k]=Bm(d,(m|((f[i]&255)>>>4|0))<<24>>24);m=l+1|0;j=f[i]<<2;n=i+1|0;b[l]=Bm(d,(j|((f[n]&255)>>>6|0))<<24>>24);i=m+1|0;b[m]=Bm(d,f[n]);j=n+1|0;}l=g-j|0;if(l==1){b=c.data;l=i+1|0;b[i]=Bm(d,(f[j]>>>2|0)<<24>>24);i=l+1|0;b[l]=Bm(d,f[j]<<4<<24>>24);if(e){e=i+1|0;b[i]=61;i=e+1|0;b[e]=61;}}else if(l==2){b=c.data;m=i+1|0;b[i]=Bm(d,(f[j]>>>2|0)<<24>>24);i=m+1|0;n=f[j]<<4;l=j+1|0;b[m]=Bm(d,(n|((f[l]&255)>>>4|0))<<24>>24);m=i+1|0;b[i]=Bm(d,f[l]<<2<<24>>24);if(!e)i=m;else
{i=m+1|0;b[m]=61;}}return i;},Bm=(b,c)=>{Bi();return b.data[c&63];},Jn=()=>{let b,c,d,e,f,g;b=BS(64);c=b.data;Dq=b;b=BS(64);d=b.data;GI=b;b=CU(256);Eb=b;C6=CU(256);e=0;f=65;while(f<=90){g=f<<24>>24;c[e]=g;d[e]=g;e=e+1|0;f=(f+1|0)&65535;}f=97;while(f<=122){g=f<<24>>24;c[e]=g;d[e]=g;e=e+1|0;f=(f+1|0)&65535;}g=48;while(g<=57){f=g<<24>>24;c[e]=f;d[e]=f;e=e+1|0;g=(g+1|0)&65535;}c[e]=43;d[e]=45;e=e+1|0;c[e]=47;d[e]=95;FT(b,(-1));FT(C6,(-1));g=0;while(true){b=Dq.data;if(g>=b.length)break;Eb.data[b[g]]=g;C6.data[GI.data[g]]
=g;g=g+1|0;}},GL=F(0),GT=F(0);
function Ex(){let a=this;E.call(a);a.dx=null;a.dw=null;a.ef=null;a.d5=0;a.dJ=0;a.dn=null;}
let Jh=(a,b,c,d,e)=>{a.dn=b;a.dJ=b.cY;a.dx=c;a.dw=d;a.d5=e;},F8=(a,b,c,d)=>{let e=new Ex();Jh(e,a,b,c,d);return e;},FA=a=>{let b;if(a.dJ>=a.dn.cY)return;b=new Fm;L(b);J(b);};
function F1(){let a=this;E.call(a);a.eZ=null;a.de=null;a.df=null;}
function Ft(){E.call(this);this.et=null;}
let Hv=(a,b)=>{let c,d,e,f,g,h,i;c=BS(b.cK.length);d=c.data;e=0;f=d.length;while(e<f){d[e]=CL(b,e)<<24>>24;e=e+1|0;}g=a.et;Bi();h=(f/4|0)*3|0;i=f%4|0;if(!(i!=2&&i!=3))h=h+(i-1|0)|0;e=f-1|0;while(e>=0&&d[e]==61){h=h+(-1)|0;e=e+(-1)|0;}d=BS(h);Ih(c,d,g);return d;},Fm=F(O),GW=F(O);
HX([-1,"java",0,"util",0,"lang",-1,"org",3,"lwjgl"]);
C9([E,0,0,[],1,0,0,0,By,0,E,[],1537,0,0,0,Cl,0,E,[],1537,0,0,0,DL,0,E,[],1537,0,0,0,Z,0,E,[By,Cl,DL],17,0,()=>BW(),["by",BJ(Bt),"b1",CF(Ip)],D_,0,E,[By],1025,0,0,0,B6,0,D_,[Cl],1,0,()=>B2(),["b1",CF(Hl),"by",BJ(Jw)],Dr,0,E,[By,DL],0,0,0,0,DD,0,E,[],1537,0,0,0,EI,0,Dr,[DD],1,0,0,0,Bg,0,E,[],1,0,0,0,Bv,0,Bg,[],1,0,0,0,O,0,Bv,[],1,0,0,0,B3,0,E,[],1025,0,0,0,H7,0,B3,[],17,0,0,0,HW,0,B3,[],17,0,0,0,E8,0,E,[],1537,0,0,0,GK,0,E,[E8],1537,0,0,0,Ey,0,E,[],1537,0,0,0,Fl,0,E,[GK,Ey],17,0,0,0,Dx,0,E,[],1537,0,0,0,En,0,
E,[Dx],1,0,()=>M(),0,Jf,0,E,[],17,0,0,0,JM,0,E,[],17,0,0,0,J8,0,E,[],17,0,0,0,B9,0,E,[Dx],1,0,()=>Bo(),0,F$,0,E,[],1537,0,0,0,FE,0,E,[F$],1,0,0,0,DU,0,E,[Cl],1,0,()=>Db(),0,EW,0,E,[],1,0,0,0,HY,0,E,[],17,0,0,0,Ek,0,E,[],17,0,0,0,I0,0,E,[],17,0,0,0,Fg,0,E,[],1537,0,0,0,GG,0,E,[Fg],1,0,0,0,Bd,"IndexOutOfBoundsException",2,O,[],1,0,0,0,Cm,0,E,[],1537,0,0,0,GY,0,E,[Cm],1,0,0,["bt",CF(Iq)],GD,0,E,[],0,0,0,0,CI,"IllegalMonitorStateException",2,O,[],1,0,0,0,EV,0,E,[],1537,0,0,0,Jr,0,E,[Cm,EV],1536,0,0,0,Jq,"ClassCastException",
2,O,[],1,0,0,0,Ff,"IllegalStateException",2,O,[],1,0,0,0,Gn,0,E,[Cm],1,0,0,["bt",CF(I1)],F4,0,E,[],1537,0,0,0,FP,0,E,[F4],0,0,0,["h",BJ(CT),"bH",BJ(Jv)],EX,0,E,[Cm],1,0,0,0,E9,0,E,[],1537,0,0,0,CN,0,E,[E9],1537,0,0,0]);
C9([B4,0,E,[CN],1025,0,0,0,EA,0,E,[CN],1537,0,0,0,Eh,0,E,[CN],1537,0,0,0,D9,0,E,[EA,Eh],1537,0,0,0,BX,0,E,[],1537,0,0,0,F6,0,B4,[D9,BX,By],1,0,0,0,IY,0,E,[],17,0,0,0,CQ,"StringIndexOutOfBoundsException",2,Bd,[],1,0,0,0,GJ,0,E,[],1,0,()=>Bh(),0,Bp,0,E,[],1537,0,0,0,FY,0,E,[Bp],1537,0,0,0,Da,0,E,[FY],1,0,0,0,CB,0,E,[],1,0,()=>BB(),0,C_,"NullPointerException",2,O,[],1,0,0,0,Gw,0,E,[],1537,0,0,0,Fj,0,E,[Gw],1537,0,0,0,Gh,0,E,[],1537,0,0,0,DJ,0,E,[Fj,Gh],1025,0,0,0,Dp,0,DJ,[],1,0,0,0,Dl,0,Dp,[DD],1,0,0,0,Cd,0,Dl,
[],1025,0,0,0,EZ,0,Cd,[],1,0,0,["B",BJ(Js)],EQ,0,E,[],1537,0,0,0,D$,0,E,[EQ],1025,0,0,0,D7,0,D$,[BX,By],1,0,0,0,EP,0,E,[Eh],1537,0,0,0,Cg,0,B4,[EP],1025,0,0,0,Dz,0,Cg,[],1025,0,0,0,D6,0,Dz,[D9,BX],1,0,0,0,FS,0,E,[],1,0,()=>Ck(),0,FQ,0,E,[],1,0,0,0,H2,0,E,[Cl],1025,0,0,0,T,0,E,[Bp],1537,0,0,0,C7,0,E,[T],1,0,0,0,Dt,0,E,[Bp],1025,0,0,0,Cs,0,Dt,[],1025,0,0,0,G$,0,Cs,[],1,0,0,0,B_,"IllegalArgumentException",2,O,[],1,0,0,0,Kb,0,E,[],17,0,0,0,FF,0,E,[],0,0,()=>Ch(),0,I9,0,E,[Bp],1,0,0,0,H8,0,E,[Bp],1025,0,0,0,Ej,0,
E,[Bp],1536,0,0,0,Dd,0,E,[Ej],1,0,0,0,Dc,0,E,[Ej],1,0,0,0,Es,0,E,[],1537,0,0,0,D8,0,E,[Es,BX],0,0,0,0,DO,0,E,[T],1,0,0,0,Gb,0,E,[],1,0,()=>V(),0,DN,0,E,[T],1,0,0,0]);
C9([JA,0,Cs,[],1,0,0,0,GV,0,E,[],1,0,0,0,Fa,0,E,[],1537,0,0,0,FH,0,E,[Fa],1,0,0,0,EL,0,E,[],1,0,0,0,El,"NoSuchElementException",1,O,[],1,0,0,0,GP,0,E,[],1,0,0,0,CC,0,D8,[],0,0,0,0,Ee,0,E,[T],0,0,0,0,Eg,0,E,[T],0,0,0,0,Ef,0,E,[T],0,0,0,0,Gd,"LWJGLException",4,Bv,[],1,0,0,0,DY,0,E,[T],0,0,0,0,D1,0,E,[T],0,0,0,0,D2,0,E,[T],0,0,0,0,DZ,0,E,[T],0,0,0,0,D0,0,E,[T],0,0,0,0,D4,0,E,[T],0,0,0,0,D5,0,E,[T],0,0,0,0,D3,0,E,[T],0,0,0,0,FW,0,E,[],1537,0,0,0,FM,0,Cg,[BX,By,FW],1,0,0,0,EU,0,Cd,[],1,0,0,["B",BJ(BL)],IB,0,E,[],
1,0,0,0,Gy,0,E,[],1,0,0,0,H5,0,E,[],17,0,0,0,CK,"ArrayStoreException",2,O,[],1,0,0,0,JJ,0,E,[],17,0,0,0,DM,0,E,[],1,0,()=>Cu(),0,Dn,0,E,[],1,0,()=>BF(),0,GQ,0,E,[Bp],1537,0,0,0,Di,0,E,[GQ],1,0,0,0,F_,0,E,[],1,0,0,0,F5,0,E,[],17,0,()=>Bi(),0,GL,0,E,[],1537,0,0,0,GT,0,E,[GL],1537,0,0,0,Ex,0,E,[GT],0,0,0,0,F1,0,E,[],0,0,0,0,Ft,0,E,[],1,0,0,0,Fm,"ConcurrentModificationException",1,O,[],1,0,0,0,GW,"NegativeArraySizeException",2,O,[],1,0,0,0]);
let JI=Bc(Iv),Jd=Bc(FL),I_=Bc(G2),JR=Bc(HN),Ga=Bc(E2),EB=Bc(DA);
HI(["Can\'t enter monitor from another thread synchronously","0","<java_object>@","null",": ","\n","\tat ","Caused by: ","[L"," fps, ","main","object","function","string","number","undefined","Either src or dest is null","keyup","NONE","ESCAPE","1","2","3","4","5","6","7","8","9","MINUS","EQUALS","BACK","TAB","Q","W","E","R","T","Y","U","I","O","P","LBRACKET","RBRACKET","RETURN","LCONTROL","A","S","D","F","G","H","J","K","L","SEMICOLON","APOSTROPHE","GRAVE","LSHIFT","BACKSLASH","Z","X","C","V","B","N","M","COMMA",
"PERIOD","SLASH","RSHIFT","MULTIPLY","LMENU","SPACE","CAPITAL","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","NUMLOCK","SCROLL","NUMPAD7","NUMPAD8","NUMPAD9","SUBTRACT","NUMPAD4","NUMPAD5","NUMPAD6","ADD","NUMPAD1","NUMPAD2","NUMPAD3","NUMPAD0","DECIMAL","","F11","F12","F13","F14","F15","F16","F17","F18","KANA","F19","CONVERT","NOCONVERT","YEN","NUMPADEQUALS","CIRCUMFLEX","AT","COLON","UNDERLINE","KANJI","STOP","AX","UNLABELED","NUMPADENTER","RCONTROL","SECTION","NUMPADCOMMA","DIVIDE","SYSRQ","RMENU","FUNCTION",
"PAUSE","HOME","UP","PRIOR","LEFT","RIGHT","END","DOWN","NEXT","INSERT","DELETE","CLEAR","LMETA","RMETA","APPS","POWER","SLEEP","/terrain.png","/","BUTTON","mousedown"]);
Z.prototype.toString=function(){return BT(this);};
Z.prototype.valueOf=Z.prototype.toString;E.prototype.toString=function(){return BT(Jj(this));};
E.prototype.__teavm_class__=function(){return J2(this);};
let C=G4(IP);
C.javaException=IL;
let Kh=Symbol('jsoClass');
(()=>{let c;c=Da.prototype;c.onAnimationFrame=R(JN);c=C7.prototype;c.handleEvent=R(JC);c=Dd.prototype;c.accept=R(It);c=Dc.prototype;c.accept=R(HT);c=DO.prototype;c.handleEvent=R(Io);c=DN.prototype;c.handleEvent=R(Jo);c=Ee.prototype;c.handleEvent=R(I7);c=Eg.prototype;c.handleEvent=R(IR);c=Ef.prototype;c.handleEvent=R(I4);c=DY.prototype;c.handleEvent=R(Hm);c=D1.prototype;c.handleEvent=R(H4);c=D2.prototype;c.handleEvent=R(Jg);c=DZ.prototype;c.handleEvent=R(J1);c=D0.prototype;c.handleEvent=R(I5);c=D4.prototype;c.handleEvent
=R(Ja);c=D5.prototype;c.handleEvent=R(Iw);c=D3.prototype;c.handleEvent=R(HD);c=Di.prototype;c.onResult=R(G3);})();
B.main=C;}));
