"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let GP=2463534242,I3=()=>{let x=GP;x^=x<<13;x^=x>>>17;x^=x<<5;GP=x;return x;},CF=f=>function(){return f(this);},BJ=f=>function(p1){return f(this,p1);},Js=f=>function(){let args=Array.prototype.slice.apply(arguments);Fx(function()
{f.apply(this,args);});},G1=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=P(BN(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Be(args[i]);}Fx(()=>{f.call(null,javaArgs);},callback);},Y=target=>target.$clinit=()=>{},JX=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls[K]&&cls[K].item){++arrayDegree;cls=cls[K].item;}let clsName="";if(cls[K].primitiveKind!==0){clsName=cls[K].name;}else {clsName=cls[K]?cls[K].name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},F
=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=BN();}return function(){superclass.call(this);};},K=Symbol("teavm_meta"),BE=cls=>{if(cls[K].classObject===null){cls[K].classObject=HA(cls);}return cls[K].classObject;},BN=()=>E,Hf=()=>{{return Ba();}},Eu=t=>{{return Bt(t);}},S=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},Eb=source=>{return Object.assign({name:null,binaryName:null,parent:null,superinterfaces:[],modifiers:0,primitiveKind
:0,itemType:null,arrayType:null,enclosingClass:null,declaringClass:null,simpleName:null,clinit:()=>{},constructor:null,enumConstants:()=>null,resolvedEnumConstants:null,reflection:null,classObject:null,assignableCache:null,valueToObject:o=>o,objectToValue:o=>o},source||{});},Bw=(name,binaryName,kind,config)=>{let cls=()=>{};let meta=Eb({name:name,binaryName:binaryName,modifiers:1|1<<4,primitiveKind:kind});cls[K]=meta;if(typeof config==='function'){config(meta);}return cls;},Iq=Bw("boolean","Z",1,meta=>{}),G0
=Bw("byte","B",2,meta=>{}),HI=Bw("short","S",3,meta=>{}),FK=Bw("char","C",4,meta=>{}),E1=Bw("int","I",5,meta=>{{meta.valueToObject=o=>BA(o);}{meta.objectToValue=o=>Fw(o);}}),Dz=Bw("float","F",7,meta=>{}),IF=Bw("void","V",9),Df=(a,b)=>a===b?0:a<b? -1:1,CY=(a,b)=>a===b?0:a>b?1: -1,R=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},DE=(a,b)=>(a>>>0)/(b>>>0)>>>0,JZ=(a,b)=>(a>>>0)%(b>>>0)>>>0,Dg=(a,b)=>{a>>>=0;b>>>=0;return a
<b? -1:a>b?1:0;},B0=BigInt(0),B1=val=>BigInt.asIntN(64,BigInt(val|0)),FM=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),DS=val=>Number(val),GY=(a,b)=>a>b,G3=(a,b)=>a>=b,He=(a,b)=>a<b,EL=(a,b)=>BigInt.asIntN(64,a+b),IY=(a,b)=>BigInt.asIntN(64,a -b),Jy=(a,b)=>BigInt.asIntN(64,a/b),P=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bc(cls))(data);},Jg=(cls,data)=>new (Bc(cls))(data),Ip=(cls,sz)=>new (Bc(cls))(new Array(sz)),BI=sz=>new I$(new Uint16Array(sz)),BS=sz=>new I6(new Int8Array(sz)),Hl
=sz=>new JM(new Int16Array(sz)),CU=sz=>new F_(new Int32Array(sz)),I1=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new F_(buffer);},GQ=sz=>new JD(new Int8Array(sz)),Bp=sz=>new EA(new Float32Array(sz));
let IU=data=>{let buffer=new Float32Array(data.length);buffer.set(data);return new EA(buffer);},Bc=cls=>{let result=cls[K].arrayType;if(result===null){function JavaArray(data){(BN()).call(this);this.data=data;}JavaArray.prototype=Object.create((BN()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.fe
=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bc(this.type))(dataCopy);};let name="["+cls[K].binaryName;JavaArray[K]=Eb({name:name,binaryName:name,parent:BN(),itemType:cls});result=JavaArray;cls[K].arrayType=JavaArray;}return result;},JY=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if
(first>0){for(let i=0;i<first;i=i+1|0){cls=Bc(cls);}if(first===dimensions.length -1){return P(cls,dimensions[first]);}}let arrays=new Array(FB(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=P(cls,firstDim);}return E9(cls,arrays,dimensions,first,0);},IN=dimensions=>{let arrays=new Array(FB(dimensions,0));if(arrays.length===0){return JY(Dz,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=Bp(firstDim);}return E9(Dz,arrays,
dimensions,0);},FB=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},E9=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=Bc(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=Ip(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex+1|0;}limit
=packedIndex;}return arrays[0];};
function Jw(array){return array.data.length;}
let DO,HE=strings=>{Jo();DO=new Array(strings.length);for(let i=0;i<strings.length;++i){DO[i]=EM(Be(strings[i]));}},D=index=>DO[index],Fu=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Be=str=>str===null?null:FW(str),BT=str=>str===null?null:str.cI,Jo=()=>BW(),EM;
{EM=str=>str;}let Cw=(from,to)=>{if(from===to){return true;}let map=from[K].assignableCache;if(map===null){map=new Map();from[K].assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to[K].itemType!==null){let result=from[K].itemType!==null&&Cw(from[K].itemType,to[K].itemType);map.set(to,result);return result;}let parent=from[K].parent;if(parent!==null&&parent!==from){if(Cw(parent,to)){map.set(to,true);return true;}}let superinterfaces=from[K].superinterfaces;for
(let i=0;i<superinterfaces.length;i=i+1|0){if(Cw(superinterfaces[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},J=ex=>{throw E4(ex);},BH=Symbol("javaException"),E4=ex=>{if(!ex.$jsException){Fm(ex);}return ex.$jsException;},Fm=ex=>{let javaCause=J7(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Bq("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[BH]
=ex;ex.$jsException=err;GD(err,ex);},GD=(err,ex)=>{if(typeof Hg==="function"&&err.stack){let stack=Hg(err.stack);let javaStack=P(Hx(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=I8(Be(element.className),Be(element.methodName),Be(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){HL(ex,javaStack);}}},Bq;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bq=function Bq(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bq);Object.setPrototypeOf(self,Bq.prototype);self[defaultMessage]=message;return self;}
;Bq.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bq},message:{get(){try {let javaException=this[BH];if(typeof javaException==='object'){let javaMessage=Iz(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bq=Error;}let IG=e=>e instanceof Error&&typeof e[BH]==='object'?e[BH]:null,U=err=>
{let ex=err[BH];if(!ex){ex=IS(Be("(JavaScript) "+err.toString()));err[BH]=ex;ex.$jsException=err;GD(err,ex);}return ex;},IS=message=>JP(message),Iz=t=>J4(t),J7=t=>J9(t),Hx=()=>BN(),I8=(className,methodName,fileName,lineNumber)=>{{return null;}},HL=(e,stack)=>{},F8=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},Is=typeof $rt_putStdoutCustom
==="function"?$rt_putStdoutCustom:typeof console==="object"?F8(msg=>console.info(msg)):()=>{},HQ=typeof $rt_putStderrCustom==="function"?$rt_putStderrCustom:typeof console==="object"?F8(msg=>console.error(msg)):()=>{},EB=null,HS=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}EB=packages;},HH=[],C9=data=>{let packages=EB;let i=0;while(i<data.length){let cls=data[i++];HH.push(cls);let m
=Eb();cls[K]=m;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.parent=superclass!==0?superclass:null;m.superinterfaces=data[i++];if(m.parent){cls.prototype=Object.create(m.parent.prototype);}else {cls.prototype={};}cls.prototype.constructor=cls;m.modifiers=data[i++];m.primitiveKind=0;let innerClassInfo=data[i++];if(innerClassInfo!==0){let enclosingClass
=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];m.clinit=clinit!==0?()=>{m.clinit=()=>{};clinit();}:()=>{};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for
(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}}};
function X(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
X.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};X.prototype.s=X.prototype.push;X.prototype.pop=function(){return this.stack.pop();};X.prototype.l=X.prototype.pop;X.prototype.isResuming=function(){return this.status===2;};X.prototype.isSuspending=function(){return this.status===1;};X.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};X.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(Cf!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};X.prototype.resume=function(){if(Cf!==null){throw new Error("Another thread is running");}this.status=2;this.run();};X.prototype.run=function(){Cf=this;let result;try {result=this.runner();}catch(e){result=e;}finally {Cf=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let HU=()=>{let thread=B5();return thread!=null&&thread.isSuspending();},Im=()=>{let thread=B5();return thread!=null&&thread.isResuming();},IB=()=>{let nativeThread=B5();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},Fx=(runner,callback)=>
(new X(runner)).start(callback),Cf=null,B5=()=>Cf,Hy=()=>{throw new Error("Invalid recorded state");};
function E(){this.cH=null;this.$id$=0;}
let El=b=>{let c,d;if(Ba()===null)return;if(b.cH===null)C3(b);c=b.cH;d=c.cK;if(d===null)c.cK=Ba();else if(d!==Ba()){c=new Fe;DF(c,D(0));J(c);}b=b.cH;b.cM=b.cM+1|0;},BR=b=>{let c,d;if(Ba()===null)return;if(!Cr(b)&&b.cH.cK===Ba()){c=b.cH;d=c.cM-1|0;c.cM=d;if(!d)c.cK=null;Cr(b);return;}b=new CI;L(b);J(b);},Kf=b=>{let c,d,$p,$z;$p=0;if(Im()){let $T=B5();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;if(b.cH===null)C3(b);d=b.cH;if(d.cK===null)d.cK=Ba();if(b.cH.cK===Ba()){b=b.cH;b.cM=b.cM
+c|0;return;}$p=1;case 1:HV(b,c);if(HU()){break _;}return;default:Hy();}}B5().s(b,c,d,$p);},C3=b=>{let c;c=new GC;c.cK=Ba();b.cH=c;},JR=(b,c,d)=>{let e,f,g,h,i,j,k,l,m;e=Ba();f=b.cH;if(f===null){C3(b);Bt(e);b=b.cH;b.cM=b.cM+c|0;b=null;CT(d,b);return;}if(f.cK===null){f.cK=e;Bt(e);b=b.cH;b.cM=b.cM+c|0;b=null;CT(d,b);return;}if(f.c4===null){g=new F5;g.c2=P(E,9);f.c4=g;}f=f.c4;g=new EW;g.eo=e;g.ep=b;g.el=c;g.em=d;b=f;c=b.c8;h=b.dh;c=(c>=h?c-h|0:(b.c2.data.length-h|0)+c|0)+1|0;h=b.c2.data.length;if(c>=h){c=Cj(h*
2|0,((c*3|0)/2|0)+1|0);if(c<1)c=2147483647;i=P(E,c);c=0;h=b.dh;j=b.c8;if(h<=j){k=i.data;while(h<j){l=c+1|0;k[c]=b.c2.data[h];h=h+1|0;c=l;}}else{k=i.data;while(true){m=b.c2.data;if(h>=m.length)break;l=c+1|0;k[c]=m[h];h=h+1|0;c=l;}h=0;while(h<j){l=c+1|0;k[c]=m[h];h=h+1|0;c=l;}}b.dh=0;b.c8=c;b.c2=i;}i=b.c2.data;c=b.c8;i[c]=g;b.c8=Ge(c,i.length);b.dI=b.dI+1|0;},Kg=b=>{let c,d;if(!Cr(b)&&b.cH.cK===Ba()){c=b.cH;d=c.cM-1|0;c.cM=d;if(d<=0){c.cK=null;c=c.c4;if(c!==null&&!DA(c)){c=new Gm;c.ek=b;ED(c);}else Cr(b);}return;}b
=new CI;L(b);J(b);},Cr=a=>{let b,c;b=a.cH;if(b===null)return 1;a:{if(b.cK===null){c=b.c4;if(!(c!==null&&!DA(c))){b=b.d_;if(b===null)break a;if(b.k())break a;}}return 0;}a.cH=null;return 1;},Hv=a=>{return;},J6=()=>{let a=new E();Hv(a);return a;},BM=a=>{return BE(H9(a));},H9=a=>{return a.constructor;},Je=a=>{let b,c,d,e,f,g,h,i,j,k;b=a;if(!b.$id$)b.$id$=I3();c=a.$id$;B2();if(!c)d=D(1);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;h=g>>>4|0;if(!h)h=g;else f=f|4;e=h>>>2|0;if
(!e)e=h;else f=f|2;if(e>>>1|0)f=f|1;e=(32-f|0)-1|0;}i=(((32-e|0)+4|0)-1|0)/4|0;j=BI(i);k=j.data;i=(i-1|0)*4|0;e=0;while(i>=0){h=e+1|0;k[e]=Ec((c>>>i|0)&15,16);i=i-4|0;e=h;}d=Ey(j);}b=Bz();Bl(Bl(b,D(2)),d);return BO(b);},DW=a=>{let b,c;b=a.cH;if(!(b!==null&&b.cK===Ba()?1:0)){b=new CI;L(b);J(b);}b=a.cH.d_;if(b===null)return;while(!b.k()){c=b.r();if(!c.s())ED(c);}a.cH.d_=null;},HV=(b,c)=>{let thread=IB();let javaThread=Hf();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error)
{throw result;}return result;}let callback=function(){};callback.h=val=>{thread.attribute=val;Eu(javaThread);thread.resume();};callback.bH=e=>{thread.attribute=E4(e);Eu(javaThread);thread.resume();};callback=J1(callback);thread.suspend(()=>{try {JR(b,c,callback);;}catch($e){callback.bH($e);}});return null;},By=F(0),Cl=F(0),DK=F(0);
function Z(){E.call(this);this.dE=0;}
let ID=null,ES=null,Ht=null,BW=()=>{BW=Y(Z);If();},HW=(a,b)=>{BW();a.cI=Fu(b.data,0,b.data.length);},Ey=a=>{let b=new Z();HW(b,a);return b;},Ia=(a,b)=>{a.cI=b;},FW=a=>{let b=new Z();Ia(b,a);return b;},CL=(a,b)=>{let c;if(b>=0&&b<a.cI.length)return a.cI.charCodeAt(b);c=new CQ;L(c);J(c);},Bs=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof Z))return 0;c=b;return a.cI!==c.cI?0:1;},Ik=a=>{let b;a:{if(!a.dE){b=0;while(true){if(b>=a.cI.length)break a;a.dE=(31*a.dE|0)+a.cI.charCodeAt(b)|0;b=b+1|0;}}}return a.dE;},If
=()=>{let b;ID=BI(0);b=new Z;BW();b.cI="";ES=b;Ht=new FD;},D$=F();
function B6(){D$.call(this);this.dj=0;}
let HG=null,C0=null,B2=()=>{B2=Y(B6);Hq();},GZ=(a,b)=>{B2();a.dj=b;},Fj=a=>{let b=new B6();GZ(b,a);return b;},BA=b=>{let c,d;B2();if(b>=(-128)&&b<=127){a:{if(C0===null){C0=P(B6,256);c=0;while(true){d=C0.data;if(c>=d.length)break a;d[c]=Fj(c-128|0);c=c+1|0;}}}return C0.data[b+128|0];}return Fj(b);},Fw=a=>{return a.dj;},Hi=a=>{let b;b=a.dj;B2();return b;},Jr=(a,b)=>{if(a===b)return 1;return b instanceof B6&&b.dj==a.dj?1:0;},Hq=()=>{HG=BE(E1);};
function Dq(){let a=this;E.call(a);a.cL=null;a.cT=0;}
let CG=(a,b,c)=>{let d,e,f,g;d=a.cT;e=d-b|0;d=(d+c|0)-b|0;GG(a,d);f=e-1|0;while(f>=0){g=a.cL.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.cT=a.cT+(c-b|0)|0;},DC=F(0),EH=F(Dq),Jd=a=>{a.cL=BI(16);},Bz=()=>{let a=new EH();Jd(a);return a;},Bl=(a,b)=>{let c,d,e,f,g,h;c=a.cT;d=a;b=b===null?D(3):b;e=d;if(c>=0&&c<=e.cT){a:{if(b===null)b=D(3);else if(b.cI.length?0:1)break a;f=e.cT+b.cI.length|0;GG(e,f);f=e.cT-1|0;while(f>=c){e.cL.data[f+b.cI.length|0]=e.cL.data[f];f=f+(-1)|0;}e.cT=e.cT+b.cI.length|0;f=0;while(f<b.cI.length)
{g=e.cL.data;h=c+1|0;g[c]=CL(b,f);f=f+1|0;c=h;}}return a;}b=new CQ;Gf(b);J(b);},Di=(a,b)=>{let c,d,e,f,g,h,i,j;c=a.cT;d=1;if(b<0){d=0;b= -b|0;}a:{if(Dg(b,10)<0){if(d)CG(a,c,c+1|0);else{CG(a,c,c+2|0);e=a.cL.data;f=c+1|0;e[c]=45;c=f;}a.cL.data[c]=Ec(b,10);}else{g=1;h=1;f=DE((-1),10);b:{while(true){i=g*10|0;if(Dg(i,b)>0){i=g;break b;}h=h+1|0;if(Dg(i,f)>0)break;g=i;}}if(!d)h=h+1|0;CG(a,c,c+h|0);if(d)f=c;else{e=a.cL.data;f=c+1|0;e[c]=45;}while(true){if(!i)break a;e=a.cL.data;j=f+1|0;e[f]=Ec(DE(b,i),10);b=JZ(b,i);i
=DE(i,10);f=j;}}}return a;},EJ=(a,b)=>{let c,d;c=a.cT;d=a;CG(d,c,c+1|0);d.cL.data[c]=b;return a;},BO=a=>{let b,c,d,e,f;b=new Z;c=a.cL;d=c.data;e=a.cT;BW();f=d.length;if(e>=0&&e<=(f-0|0)){b.cI=Fu(c.data,0,e);return b;}b=new Bd;L(b);J(b);},GG=(a,b)=>{let c,d,e,f;c=a.cL.data.length;if(c<b){b=c>=1073741823?2147483647:Cj(b,Cj(c*2|0,5));d=a.cL.data;e=BI(b);f=e.data;b=Dj(b,d.length);c=0;while(c<b){f[c]=d[c];c=c+1|0;}a.cL=e;}};
function Bg(){let a=this;E.call(a);a.d2=null;a.d1=null;a.eb=0;a.ei=0;a.fb=null;}
let HK=a=>{return a;},Dn=a=>{Fm(a);},J4=a=>{return a.d2;},Kb=a=>{return a.d2;},J9=a=>{let b;b=a.d1;if(b===a)b=null;return b;},CM=a=>{let b;if(C2===null){b=new ET;Gn(b);C2=b;}Gz(a,C2);},Gz=(a,b)=>{let c,d,e,f,g,h,i;c=GB(BM(a));d=b;BL(d,c);e=a.d2;if(e!==null){c=Bz();Bl(Bl(c,D(4)),e);BL(d,BO(c));}a:{c=b;BL(c,D(5));f=a.fb;if(f!==null){f=f.data;g=f.length;h=0;while(true){if(h>=g)break a;e=f[h];BL(d,D(6));i=D(3);if(e!==null)i=e.q();Fc(c,i);h=h+1|0;}}}c=a.d1;if(c!==null&&c!==a){BL(d,D(7));Gz(a.d1,b);}},Bu=F(Bg),O=
F(Bu),L=a=>{Dn(a);a.eb=1;a.ei=1;},Ka=()=>{let a=new O();L(a);return a;},DF=(a,b)=>{Dn(a);a.eb=1;a.ei=1;a.d2=b;},JP=a=>{let b=new O();DF(b,a);return b;},B3=F(),H2=F(B3),Hn=(a,b)=>{switch(a.primitiveKind){default:return P(a,b);}},HR=F(B3),E7=F(0),GJ=F(0),Ex=F(0);
function Fk(){let a=this;E.call(a);a.e0=0;a.c0=null;a.en=null;}
let HA=b=>{let c;c=new Fk;c.c0=b;return c;},GB=a=>{let b,c,d,e,f;b=a.e0;if(!(b&1)){a.e0=b|1;c=a.c0[K].name;d=c===null?null:Be(c);if(d===null){e=a.c0[K].itemType;if(e!==null){f=GB(BE(e));if(f!==null){if(e[K].itemType!==null){c=Bz();Bl(EJ(c,91),f);d=BO(c);}else{c=Bz();EJ(Bl(Bl(c,D(8)),f),59);d=BO(c);}}}}a.en=d;}return a.en;},CJ=a=>{return !a.c0[K].primitiveKind?0:1;},C$=a=>{let b;b=a.c0[K].itemType;return b===null?null:BE(b);},Dw=F(0);
function Em(){let a=this;E.call(a);a.ey=0;a.ex=0;a.eV=null;a.d6=null;a.dm=null;a.dB=null;a.c5=null;a.dN=B0;a.dn=0;}
let BK=null,G=null,W=null,Ci=0,Ct=0,Ca=0,Ep=null,GM=null,BG=null,Cq=null,EN=null,Dl=null,Cz=null,CA=null,Cv=null,Bx=null,DP=null,M=()=>{M=Y(Em);G9();},I_=a=>{let b,c,d,e,f,g,h,i,j,k,l;a.eV=IU([0.054901961237192154,0.04313725605607033,0.03921568766236305,1.0]);b=Fg(window.document.getElementById("canvas"));c=Fg(b.getContext("webgl"));M();G=c;E3(a,window.innerWidth,window.innerHeight);d=window;c=Hh(a);d.addEventListener("resize",Q(I(c),"handleEvent"));JN();IO();c=G$(b);b.addEventListener("click",Q(I(c),"handleEvent"));d
=G.createShader(35633);G.shaderSource(d,"attribute vec3 aPosition; attribute vec2 aTexCoord; attribute vec3 aColor; uniform mat4 uProj; uniform mat4 uModl; varying vec2 vTexCoord; varying vec3 vColor; varying float vFogDist; void main() { vec4 pos = uModl * vec4(aPosition, 1.0); gl_Position = uProj * pos; vTexCoord = aTexCoord; vColor = aColor; vFogDist = length(pos.xyz); }");G.compileShader(d);e=G.createShader(35632);G.shaderSource(e,"precision mediump float; varying vec2 vTexCoord; varying vec3 vColor; varying float vFogDist; uniform sampler2D uTex; uniform bool uHasTexture; uniform bool uHasColor; uniform vec4 uFogColor; uniform float uAlpha; uniform bool uUseFog; void main() { vec4 col = vec4(1.0); if(uHasColor) col *= vec4(vColor, 1.0); if(uHasTexture) col *= texture2D(uTex, vTexCoord); col.a *= uAlpha; if(uUseFog) { float fogFactor = exp(-0.02 * vFogDist); fogFactor = clamp(fogFactor, 0.0, 1.0); gl_FragColor = mix(uFogColor, col, fogFactor); } else { gl_FragColor = col; } }");G.compileShader(e);f
=G.createProgram();W=f;G.attachShader(f,d);c=G;f=W;c.attachShader(f,e);c=G;f=W;c.linkProgram(f);c=G;f=W;c.useProgram(f);Ci=G.getAttribLocation(W,"aPosition");Ct=G.getAttribLocation(W,"aTexCoord");Ca=G.getAttribLocation(W,"aColor");Ep=G.getUniformLocation(W,"uProj");GM=G.getUniformLocation(W,"uModl");BG=G.getUniformLocation(W,"uHasTexture");Cq=G.getUniformLocation(W,"uHasColor");EN=G.getUniformLocation(W,"uFogColor");Dl=G.getUniformLocation(W,"uAlpha");Cz=G.getUniformLocation(W,"uUseFog");f=G.createBuffer();DP
=f;G.bindBuffer(34963,f);g=Hl(450000).data;h=0;i=0;while(h<300000){j=h<<16>>16;g[i]=j;g[i+1|0]=(h+1|0)<<16>>16;k=i+2|0;l=(h+2|0)<<16>>16;g[k]=l;g[i+3|0]=j;g[i+4|0]=l;g[i+5|0]=(h+3|0)<<16>>16;h=h+4|0;i=i+6|0;}h=g.length;f=new Int16Array(h);j=0;while(j<h){i=g[j];f[j]=i;j=j+1|0;}G.bufferData(34963,f,35044);G.clearColor(0.5,0.800000011920929,1.0,1.0);G.clearDepth(1.0);G.enable(2929);G.depthFunc(515);CV(5889);C1();CV(5888);c=II(256,256,64);a.dm=c;a.dB=Ii(c);a.c5=Jf(a.dm);Fo(1);},CV=b=>{M();Bx=b!=5889?Cv:CA;},C1=
()=>{let b,c,d;M();b=0;while(b<16){c=Bx;d=b%5|0?0.0:1.0;c.data[b]=d;b=b+1|0;}},FT=(b,c,d)=>{let e;M();e=Bx.data;e[12]=e[12]+e[0]*b+e[4]*c+e[8]*d;e[13]=e[13]+e[1]*b+e[5]*c+e[9]*d;e[14]=e[14]+e[2]*b+e[6]*c+e[10]*d;e[15]=e[15]+e[3]*b+e[7]*c+e[11]*d;},E0=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x;M();f=Cp(b);g=CH(f);h=B$(f);i=1.0-g;j=c*c*i+g;k=d*c*i;l=e*h;m=k+l;b=c*e*i;n=d*h;o=b-n;p=k-l;q=d*d*i+g;d=d*e*i;c=c*h;r=d+c;k=b+n;l=d-c;s=e*e*i+g;t=Bp(16);u=t.data;Fp(Bx,0,t,0,16);v=0;while(v<4){t=Bx.data;b=u[v]
*j;w=v+4|0;b=b+u[w]*m;x=v+8|0;t[v]=b+u[x]*o;t[w]=u[v]*p+u[w]*q+u[x]*r;t[x]=u[v]*k+u[w]*l+u[x]*s;v=v+1|0;}},IL=(b,c,d,e)=>{let f,g;M();f=1.0/Ho(b*3.141592653589793/360.0);C1();g=Bx.data;g[0]=f/c;g[5]=f;b=e+d;c=d-e;g[10]=b/c;g[11]=(-1.0);g[14]=2.0*e*d/c;g[15]=0.0;},HB=()=>{let b,c,d;M();b=G;c=Ep;d=CA;b.uniformMatrix4fv(c,!!0,d.data);b=G;c=GM;d=Cv;b.uniformMatrix4fv(c,!!0,d.data);},Ft=a=>{let b,c,d,e,f,g,h;if(Bb(1)){E2(a.dm);return;}b=a.d6;c=Gj();d=IY(c,b.d5);b.d5=c;if(He(d,B0))d=B0;if(GY(d,B1(1000000000)))d=B1(1000000000);b.eq
=DS(Jy(B1(1000000000),d));e=b.dO+DS(d)*b.ew*b.eS/1.0E9;b.dO=e;f=e|0;b.d4=f;if(f>100)b.d4=100;e=e-b.d4;b.dO=e;b.es=e;f=0;while(true){b=a.d6;if(f>=b.d4)break;J0(a.c5);f=f+1|0;}JK(a,b.es);a.dn=a.dn+1|0;while(G3(Cx(),EL(a.dN,B1(1000)))){if(Dt===null){b=new EY;Gn(b);Dt=b;}g=Dt;f=a.dn;BB();h=Ce;b=Bz();Di(Bl(Di(b,f),D(9)),h);b=BO(b);Fc(g,b);Ce=0;a.dN=EL(a.dN,B1(1000));a.dn=0;}window;b=new Da;b.eL=a;requestAnimationFrame(Q(I(b),"onAnimationFrame"));},HP=(a,b)=>{let c,d,e,f;FT(0.0,0.0,(-0.30000001192092896));E0(a.c5.c6,
1.0,0.0,0.0);E0(a.c5.c9,0.0,1.0,0.0);c=a.c5;d=c.eu;d=d+(c.dw-d)*b;e=c.et;e=e+(c.dx-e)*b;f=c.eE;f=f+(c.dy-f)*b;FT( -d, -e, -f);},JK=(a,b)=>{let c,d,e,f,g,h,i,j;V();c=BQ|0;BQ=0.0;d=c;c=BP|0;BP=0.0;e=c;f=a.c5;f.c9=f.c9+d*0.15;d=f.c6-e*0.15;f.c6=d;if(d<(-90.0))f.c6=(-90.0);if(f.c6>90.0)f.c6=90.0;JF(a.dB,f);while(true){a:{Cc=null;if(!EF(Br)){f=I(EX(Br,0));Cc=f;if(f!==null){c=1;break a;}}c=0;}if(!c)break;if(GE()==1&&Fq()){M();f=BK;if(f!==null)E5(a.dm,f.dU,f.dV,f.dW,0);}if(GE())continue;if(!Fq())continue;M();f=BK;if
(f===null)continue;c=f.dU;g=f.dV;h=f.dW;i=f.d$;if(!i)g=g+(-1)|0;if(i==1)g=g+1|0;if(i==2)h=h+(-1)|0;if(i==3)h=h+1|0;if(i==4)c=c+(-1)|0;if(i==5)c=c+1|0;E5(a.dm,c,g,h,1);}while(true){b:{Bh();Co=null;if(!EF(BD)){f=I(EX(BD,0));Co=f;if(f!==null){c=1;break b;}}c=0;}if(!c)break;f=Co;if((f===null?(-1):DG(f.which))!=28)continue;if(!JA())continue;E2(a.dm);}M();G.clear(16640);CV(5889);C1();IL(70.0,a.ey/a.ex,0.05000000074505806,1000.0);CV(5888);C1();HP(a,b);HB();G.uniform1i(Cq,1);G.uniform1i(BG,1);G.enable(2884);G.uniform1i(Cz,
0);Gp(a.dB,a.c5,0);G.uniform1i(Cz,1);G.uniform4f(EN,0.0,0.0,0.0,1.0);Gp(a.dB,a.c5,1);G.uniform1i(BG,0);f=BK;if(f!==null)Hc(a.dB,f);f=G;j=Cz;f.uniform1i(j,0);},E3=(a,b,c)=>{let d,e;a.ey=b;a.ex=c;d=window.document.getElementById("canvas");e=b;d.width=e;e=c;d.height=e;M();G.viewport(0,0,b,c);},IK=b=>{let c,d,e;M();c=new B9;d=new Em;d.eV=Bp(4);e=new EV;e.ew=1.0;e.eq=0.0;e.dO=0.0;e.eS=60.0;e.d5=Gj();d.d6=e;Bo();Eh(c,d,null);d=new GW;d.eB=c;Jp(d);},G9=()=>{let b;BK=null;CA=Bp(16);b=Bp(16);Cv=b;Bx=b;},Ja=F(),Jp=b=>
{setTimeout(()=>{Js(FC)(b);},0);},FC=b=>{b.bt();},ED=b=>{Hk(b,0);},Hk=(b,c)=>{setTimeout(()=>{FC(b);},c);},JH=F(),Q=(b,c)=>{if(b===null||b===undefined){return null;}let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},J3=F();
function B9(){let a=this;E.call(a);a.e_=null;a.e$=B0;a.e5=B0;a.dS=null;a.d0=null;a.e6=null;a.dK=0;a.eZ=null;}
let CW=null,Cb=null,DQ=0,Bk=0,F6=null,Bo=()=>{Bo=Y(B9);IA();},Eh=(a,b,c)=>{let d;Bo();a.dS=new E;a.dK=1;a.e6=c;a.eZ=b;d=DQ;DQ=d+1|0;a.e$=B1(d);},Ke=(a,b)=>{let c=new B9();Eh(c,a,b);return c;},Bt=b=>{Bo();if(Cb!==b)Cb=b;Cb.e5=Cx();},Iv=a=>{let b,$$je;b=a.eZ;if(b!==null){b=b;a:{b:{try{I_(b);break b;}catch($$e){$$je=U($$e);if($$je instanceof Bu){b=$$je;}else{throw $$e;}}CM(b);break a;}b.dN=Cx();b.dn=0;Ft(b);}}},Ba=()=>{Bo();return Cb;},Iy=a=>{let b;b=a.e_;if(b!==null)return b;Bo();return F6;},IA=()=>{let b;b=new B9;Bo();Eh(b,
null,D(10));CW=b;Cb=b;DQ=1;Bk=1;F6=new GF;},F9=F(0),FD=F(),DT=F(),HF=null,Jh=null,Db=()=>{Db=Y(DT);H6();},Ec=(b,c)=>{Db();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},H6=()=>{HF=BE(FK);Jh=P(DT,128);};
function EV(){let a=this;E.call(a);a.eS=0.0;a.d5=B0;a.d4=0;a.es=0.0;a.ew=0.0;a.eq=0.0;a.dO=0.0;}
let HT=F();
function Ej(){E.call(this);this.eU=null;}
let HC=(a,b)=>{a.eU=b;},B7=a=>{let b=new Ej();HC(b,a);return b;},Bf=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Be(typeof b);d=!Bs(c,D(11))&&!Bs(c,D(12))?0:1;Ch();e=Et;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);e.set(b,new WeakRef(h));return h;}if(Bs(c,D(13))){i=CX;j=Es;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);k=h;i.set(b,new WeakRef(k));j.register(k,
b);return h;}if(Bs(c,D(14))){l=CO;m=EC;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(Bs(c,D(15))){f=E$;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);E$=new WeakRef(h);return h;}}return B7(b);},I=b=>{if(b===null)return null;return !(b instanceof Ej)?b:b.eU;},IV=F(),Dt=null,C2=null,J_=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n;if(b!==null&&d!==null){if(c>=0&&e>=0&&f>=0&&(c
+f|0)<=CR(b)&&(e+f|0)<=CR(d)){a:{b:{if(b!==d){g=C$(BM(b));h=C$(BM(d));if(g!==null&&h!==null){if(g===h)break b;if(!CJ(g)&&!CJ(h)){i=b;j=0;k=c;while(j<f){c:{l=i.data;m=k+1|0;n=l[k];if(n!==null){n=BM(n);if(Cw(n.c0,h.c0)){k=1;break c;}}k=0;}if(!k){CS(b,c,d,e,j);b=new CK;L(b);J(b);}j=j+1|0;k=m;}CS(b,c,d,e,f);return;}if(!CJ(g))break a;if(CJ(h))break b;else break a;}b=new CK;L(b);J(b);}}CS(b,c,d,e,f);return;}b=new CK;L(b);J(b);}b=new Bd;L(b);J(b);}d=new C_;DF(d,D(16));J(d);},Fp=(b,c,d,e,f)=>{if(c>=0&&e>=0&&f>=0&&(c
+f|0)<=CR(b)&&(e+f|0)<=CR(d)){CS(b,c,d,e,f);return;}b=new Bd;L(b);J(b);},CS=(b,c,d,e,f)=>{if(f!==0){if(typeof b.data.buffer!=='undefined'){d.data.set(b.data.subarray(c,c+f),e);}else if(b!==d||e<c){for(let i=0;i<f;i=i+1|0){d.data[e++]=b.data[c++];}}else {c=c+f|0;e=e+f|0;for(let i=0;i<f;i=i+1|0){d.data[ --e]=b.data[ --c];}}}},Cx=()=>{return FM((new Date()).getTime());},Gj=()=>{return FM(performance.now()*1000000.0);},Ff=F(0),GF=F(),Ib=(a,b,c)=>{CM(c);},Bd=F(O),Gf=a=>{L(a);},Kd=()=>{let a=new Bd();Gf(a);return a;},Cm
=F(0);
function GW(){E.call(this);this.eB=null;}
let Il=a=>{let b,c,d,$$je;b=a.eB;a:{b:{c:{d:{try{Bo();Bk=Bk+1|0;Bt(b);b.d0=J6();Iv(b);}catch($$e){$$je=U($$e);if($$je instanceof Bg){c=$$je;break d;}else{c=$$je;break c;}}c=b.dS;El(c);e:{try{DW(c);BR(c);break e;}catch($$e){$$je=U($$e);b=$$je;}BR(c);J(b);}b.dK=0;Bk=Bk-1|0;b.d0=null;Bt(CW);break a;}try{Ib(Iy(b),b,c);break b;}catch($$e){$$je=U($$e);c=$$je;break c;}}d=b.dS;El(d);f:{try{DW(d);BR(d);break f;}catch($$e){$$je=U($$e);b=$$je;}BR(d);J(b);}b.dK=0;Bk=Bk-1|0;b.d0=null;Bt(CW);J(c);}c=b.dS;El(c);g:{try{DW(c);BR(c);break g;}
catch($$e){$$je=U($$e);b=$$je;}BR(c);J(b);}b.dK=0;Bk=Bk-1|0;b.d0=null;Bt(CW);}};
function GC(){let a=this;E.call(a);a.c4=null;a.d_=null;a.cK=null;a.cM=0;}
let CI=F(O),EU=F(0),Jm=F(0),Jl=F(O),Fe=F(O);
function Gm(){E.call(this);this.ek=null;}
let IW=a=>{let b,c,d,e,f;b=a.ek;if(!Cr(b)){c=b.cH;if(c.cK===null){b=c.c4;if(b!==null&&!DA(b)){b=c.c4;d=b.dh;if(d==b.c8)e=null;else{f=b.c2.data;e=f[d];f[d]=null;b.dh=Ge(d,f.length);b.dI=b.dI+1|0;}if(e===null){b=new Ek;L(b);J(b);}e=e;c.c4=null;b=e;c=b.eo;e=b.ep;d=b.el;b=b.em;Bt(c);e=e.cH;e.cK=c;e.cM=e.cM+d|0;c=null;CT(b,c);}}}},F3=F(0);
function FO(){E.call(this);this.eh=null;}
let J1=b=>{let c;c=new FO;c.eh=b;return c;},CT=(a,b)=>{a.eh.h(b);},Jq=(a,b)=>{a.eh.bH(b);};
function EW(){let a=this;E.call(a);a.eo=null;a.ep=null;a.el=0;a.em=null;}
let E8=F(0),CN=F(0),B4=F(),EF=a=>{return a.c3?0:1;},Ez=F(0),Eg=F(0),D8=F(0),BX=F(0);
function F5(){let a=this;B4.call(a);a.dI=0;a.c2=null;a.dh=0;a.c8=0;}
let DA=a=>{return a.dh!=a.c8?0:1;},Ge=(b,c)=>{b=b+1|0;if(b==c)b=0;return b;},IT=F(),B$=b=>{return Math.sin(b);},CH=b=>{return Math.cos(b);},Ho=b=>{return Math.tan(b);},Cp=b=>{return b*3.141592653589793/180.0;},GA=b=>{return Math.sqrt(b);},Dx=b=>{return Math.floor(b);},Fh=()=>{return JG();},JG=()=>{return Math.random();},Dj=(b,c)=>{if(b<c)c=b;return c;},Cj=(b,c)=>{if(b>c)c=b;return c;},It=b=>{return Math.abs(b);},DD=b=>{return It(b);},CQ=F(Bd),GI=F(),F2=null,Gt=null,E6=null,FQ=0,Eo=0,GN=0,DB=0,BD=null,CP=null,EE
=0,FN=null,F1=null,Fv=null,Co=null,C5=null,Bh=()=>{Bh=Y(GI);Jk();},Id=()=>{Bh();if(DB)return;DB=1;},JN=()=>{let b,c,d,$$je;Bh();a:{b:{try{if(!Eo)break b;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}return;}c:{try{if(DB)break c;Id();break c;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}d:{try{c=window;d=HN();FN=I(d);c.addEventListener("keydown",Q(I(d),"handleEvent"));c=window;d=HJ();F1=I(d);c.addEventListener("keyup",Q(I(d),"handleEvent"));c
=window;d=I9();Fv=I(d);c.addEventListener("keypress",Q(I(d),"handleEvent"));Eo=1;b=BD;if(b===null)break d;Gi(b);break d;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}return;}J(GX(b));},Bb=b=>{Bh();return CP.data[b];},JA=()=>{let b;Bh();b=Co;return b===null?0:Bs(Be(b.type),D(17))?0:1;},DG=b=>{let c;Bh();c=C5.data;return b<=c.length&&b>=0?c[b]:(-1);},Jk=()=>{let b,c,d,e,f,g,h;F2=Jg(Z,[D(18),D(19),D(20),D(21),D(22),D(23),D(24),D(25),D(26),D(27),D(28),D(1),D(29),D(30),D(31),D(32),
D(33),D(34),D(35),D(36),D(37),D(38),D(39),D(40),D(41),D(42),D(43),D(44),D(45),D(46),D(47),D(48),D(49),D(50),D(51),D(52),D(53),D(54),D(55),D(56),D(57),D(58),D(59),D(60),D(61),D(62),D(63),D(64),D(65),D(66),D(67),D(68),D(69),D(70),D(71),D(72),D(73),D(74),D(75),D(76),D(77),D(78),D(79),D(80),D(81),D(82),D(83),D(84),D(85),D(86),D(87),D(88),D(89),D(90),D(91),D(92),D(93),D(94),D(95),D(96),D(97),D(98),D(99),D(100),D(101),D(101),D(101),D(102),D(103),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),
D(101),D(104),D(105),D(106),D(107),D(108),D(109),D(101),D(101),D(101),D(101),D(101),D(101),D(110),D(111),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(112),D(101),D(113),D(101),D(114),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(115),D(101),D(101),D(116),D(117),D(118),D(119),D(120),D(121),D(122),D(123),D(101),D(101),D(101),D(101),D(124),D(125),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(126),D(101),D(101),D(101),D(101),D(101),
D(101),D(101),D(101),D(101),D(101),D(101),D(127),D(101),D(128),D(101),D(129),D(130),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(131),D(132),D(101),D(133),D(134),D(135),D(101),D(136),D(101),D(137),D(101),D(138),D(139),D(140),D(141),D(142),D(101),D(101),D(101),D(101),D(101),D(101),D(143),D(144),D(145),D(146),D(147),D(148)]);Gt=P(Z,256);E6=FZ(253);Eo=0;GN=0;BD=Hb();CP=GQ(256);EE=0;FN=null;F1=null;Fv=null;Co=null;C5=I1([(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),14,15,(-1),(-1),(-1),
28,(-1),(-1),42,29,56,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),1,(-1),(-1),(-1),(-1),57,210,201,207,199,203,200,205,208,205,208,(-1),(-1),210,211,211,11,2,3,4,5,6,7,8,9,10,(-1),(-1),(-1),(-1),(-1),(-1),(-1),30,48,46,32,18,33,34,35,23,36,37,38,50,49,24,25,16,19,31,20,22,47,17,45,21,44,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),12,52,53,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),
(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),39,13,51,12,52,53,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),26,43,27,40]);b=0;c=F2.data;d=c.length;e=0;while(e<d){f=c[e];Gt.data[b]=f;g=E6;h=BA(b);CD(g,f,h);b=b+1|0;FQ=FQ+1|0;e
=e+1|0;}d=0;c=C5.data;b=c.length;e=0;while(e<b){if(Fw(BA(c[e]))!=(-1))d=d+1|0;e=e+1|0;}EE=d;},Bv=F(0),Fg=b=>{return b;},FX=F(0);
function Da(){E.call(this);this.eL=null;}
let JI=(b,c)=>{c;Ft(b.eL);};
function CB(){let a=this;E.call(a);a.eF=null;a.ef=null;a.eG=0;a.eA=0;a.eC=0;a.eH=0;a.ez=0;a.eD=0;a.dX=0;a.dp=null;a.dG=null;a.dF=null;a.dT=null;}
let Gh=0,B8=null,CE=0,Ce=0,BB=()=>{BB=Y(CB);H4();},EZ=(a,b)=>{let c,d,e,f,g,h,i,j,k;BB();c=CE;if(c!=2){a.dX=0;Ce=Ce+1|0;CE=c+1|0;if(I(a.dp.data[b])===null){d=a.dp.data;M();d[b]=Bf(G.createBuffer());a.dG.data[b]=Bf(G.createBuffer());a.dF.data[b]=Bf(G.createBuffer());}Gw(B8);c=a.eG;while(c<a.eH){e=a.eA;while(e<a.ez){f=a.eC;while(f<a.eD){if(Bj(a.ef,c,e,f)){g=a.ef;if(e!=((g.cV*2|0)/3|0)?1:0){BF();Fb(Gq,B8,g,b,c,e,f);}else{BF();Fb(Eq,B8,g,b,c,e,f);}}f=f+1|0;}e=e+1|0;}c=c+1|0;}d=a.dT.data;g=B8;h=I(a.dp.data[b]);i
=I(a.dG.data[b]);j=I(a.dF.data[b]);M();k=G;k.bindBuffer(34962,h);k.bufferData(34962,g.di.subarray(0,g.cJ*3|0),35044);k.bindBuffer(34962,i);k.bufferData(34962,g.dr.subarray(0,g.cJ*2|0),35044);k.bindBuffer(34962,j);k.bufferData(34962,g.dg.subarray(0,g.cJ*3|0),35044);c=g.cJ;Dh(g);d[b]=c;}},JO=(a,b)=>{let c;if(a.dX){EZ(a,0);EZ(a,1);}if(a.dT.data[b]>0){M();c=G;BB();DU(Gh);c.uniform1i(BG,1);c.uniform1i(Cq,1);c.bindBuffer(34962,I(a.dp.data[b]));c.vertexAttribPointer(Ci,3,5126,!!0,0,0);c.enableVertexAttribArray(Ci);c.bindBuffer(34962,
I(a.dG.data[b]));c.vertexAttribPointer(Ct,2,5126,!!0,0,0);c.enableVertexAttribArray(Ct);c.bindBuffer(34962,I(a.dF.data[b]));c.vertexAttribPointer(Ca,3,5126,!!0,0,0);c.enableVertexAttribArray(Ca);c.bindBuffer(34963,DP);c.drawElements(4,(a.dT.data[b]*6|0)/4|0,5123,0);}},H4=()=>{let b,c,d,e,f,g,h,i,j;b=D(149);Ck();if(Gu(CZ,b)===null?0:1)c=(Fy(CZ,b)).dj;else{c=Dv;Dv=c+1|0;M();d=G;e=d.createTexture();CD(DH,BA(c),Bf(e));CD(CZ,b,BA(c));DU(c);d.texParameteri(3553,10241,9728);d.texParameteri(3553,10240,9728);e=window.document.createElement("img");if
(b===D(150))f=1;else a:{f=0;if((f+D(150).cI.length|0)>b.cI.length)f=0;else{g=0;while(g<D(150).cI.length){h=CL(D(150),g);i=f+1|0;if(h!=CL(b,f)){f=0;break a;}g=g+1|0;f=i;}f=1;}}if(f){g=b.cI.length;f=b.cI.length;i=Df(1,g);if(!i)b=ES;else if(i<=0&&g<=f)b=FW(b.cI.substring(1,g));else{b=new CQ;L(b);J(b);}}e.src=BT(b);j=new C7;j.eK=c;j.eI=d;j.eJ=e;e.addEventListener("load",Q(I(j),"handleEvent"));}Gh=c;B8=FH();CE=0;Ce=0;},C_=F(O),Gv=F(0),Fi=F(0),Gg=F(0),DI=F();
function Do(){DI.call(this);this.fc=null;}
function Dk(){let a=this;Do.call(a);a.e9=0;a.e7=null;a.fd=null;a.fa=null;}
let Cd=F(Dk),Gn=a=>{let b,c;b=null;c=null;a.fc=b;a.e7=Bz();a.fd=BI(32);a.e9=0;a.fa=c;},Fc=(a,b)=>{a.B(b);a.B(D(5));},EY=F(Cd),Jn=(a,b)=>{if(b===null)b=D(3);Is(BT(b));},EP=F(0),D9=F();
function D6(){let a=this;D9.call(a);a.dz=0;a.cZ=null;a.dZ=0;a.e1=0.0;a.ec=0;}
let G_=a=>{Ev(a,16);},GS=()=>{let a=new D6();G_(a);return a;},Ev=(a,b)=>{let c;if(b<0){c=new B_;L(c);J(c);}b=FU(b);a.dz=0;a.cZ=P(CC,b);a.e1=0.75;Gk(a);},FZ=a=>{let b=new D6();Ev(b,a);return b;},FU=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},Gk=a=>{a.ec=a.cZ.data.length*a.e1|0;},Fy=(a,b)=>{let c;c=Gu(a,b);if(c===null)return null;return c.dM;},Gu=(a,b)=>{let c,d;if(b===null)c=GL(a);else{d=b.b1();c=Fa(a,b,d&(a.cZ.data.length-1|
0),d);}return c;},Fa=(a,b,c,d)=>{let e,f;e=a.cZ.data[c];while(e!==null){if(e.d9==d){f=e.ej;if(b!==f&&!b.by(f)?0:1)break;}e=e.dC;}return e;},GL=a=>{let b;b=a.cZ.data[0];while(b!==null&&b.ej!==null){b=b.dC;}return b;},CD=(a,b,c)=>{let d,e,f;if(b===null){d=GL(a);if(d===null){a.dZ=a.dZ+1|0;d=Gd(a,null,0,0);e=a.dz+1|0;a.dz=e;if(e>a.ec)Gy(a);}}else{e=b.b1();f=e&(a.cZ.data.length-1|0);d=Fa(a,b,f,e);if(d===null){a.dZ=a.dZ+1|0;d=Gd(a,b,f,e);e=a.dz+1|0;a.dz=e;if(e>a.ec)Gy(a);}}b=d.dM;d.dM=c;return b;},Gd=(a,b,c,d)=>{let e,
f,g;e=new CC;f=null;e.ej=b;e.dM=f;e.d9=d;g=a.cZ.data;e.dC=g[c];g[c]=e;return e;},Gy=a=>{let b,c,d,e,f,g,h,i;b=a.cZ.data.length;b=FU(!b?1:b<<1);c=P(CC,b);d=c.data;e=0;f=b-1|0;while(true){g=a.cZ.data;if(e>=g.length)break;h=g[e];g[e]=null;while(h!==null){b=h.d9&f;i=h.dC;h.dC=d[b];d[b]=h;h=i;}e=e+1|0;}a.cZ=c;Gk(a);},EO=F(0);
function Cg(){B4.call(this);this.cW=0;}
let BC=(a,b)=>{let c,d,e,f;c=a.c3;d=a;if(c<0){b=new Bd;L(b);J(b);}d=Go(d,c);Fz(d);e=new F0;e.eW=b;b=d.du;e.dd=b;f=d.dv;e.dc=f;if(b!==null)b.dc=e;else d.dl.dR=e;if(f!==null)f.dd=e;else d.dl.dD=e;d.du=e;b=d.dl;b.c3=b.c3+1|0;c=b.cW+1|0;b.cW=c;d.dH=c;d.ed=null;return 1;},Dy=F(Cg),EX=(a,b)=>{let c,d,e,f,g,h,i,j,k;if(b<0){c=new Bd;L(c);J(c);}c=Go(a,b);Fz(c);d=c.dv;if(d===null){c=new Ek;L(c);J(c);}e=d.eW;c.ed=d;c.du=d;f=d.dc;c.dv=f;g=c.d3+1|0;c.d3=g;h=c.dl;i=d.dd;if(i===null)h.dR=f;else i.dc=f;j=d.dc;if(j===null)h.dD
=i;else j.dd=i;h.c3=h.c3-1|0;k=h.cW+1|0;h.cW=k;if(d===d){c.du=!(f===null?0:1)?null:f.dd;c.d3=g-1|0;}else if(d===f){if(!(d===null?0:1))j=null;c.dv=j;}c.dH=k;c.ed=null;return e;};
function D5(){let a=this;Dy.call(a);a.dR=null;a.dD=null;a.c3=0;}
let J$=a=>{return;},Hb=()=>{let a=new D5();J$(a);return a;},Gi=a=>{a.dR=null;a.dD=null;a.c3=0;a.cW=a.cW+1|0;},Go=(a,b)=>{let c,d,e,f;if(b<0){c=new Bd;L(c);J(c);}d=a.c3;if(b<=(d/2|0)){e=a.dR;f=0;while(f<b){e=e.dc;f=f+1|0;}return F7(a,e,e===null?null:e.dd,b);}if(b>d){c=new Bd;L(c);J(c);}c=a.dD;f=b;while(f<d){c=c.dd;f=f+1|0;}return F7(a,c===null?null:c.dc,c,b);},FR=F(),CZ=null,DH=null,Dv=0,C4=0,Ck=()=>{Ck=Y(FR);HD();},DU=b=>{Ck();if(b!=C4){M();G.bindTexture(3553,I(Fy(DH,BA(b))));C4=b;}},HD=()=>{CZ=GS();DH=GS();Dv
=1;C4=(-9999999);};
function FP(){let a=this;E.call(a);a.di=null;a.dr=null;a.dg=null;a.cJ=0;a.eQ=0.0;a.eP=0.0;a.eR=0.0;a.eO=0.0;a.eN=0.0;a.dq=0;a.dA=0;a.ea=null;a.e2=null;a.e3=null;}
let J5=a=>{a.di=new Float32Array(300000);a.dr=new Float32Array(200000);a.dg=new Float32Array(300000);a.cJ=0;a.dq=0;a.dA=0;},FH=()=>{let a=new FP();J5(a);return a;},Gl=a=>{let b;if(a.cJ>0){M();b=G;if(a.ea===null){a.ea=b.createBuffer();a.e2=b.createBuffer();a.e3=b.createBuffer();}b.bindBuffer(34962,a.ea);b.bufferData(34962,a.di.subarray(0,a.cJ*3|0),35048);b.vertexAttribPointer(Ci,3,5126,!!0,0,0);b.enableVertexAttribArray(Ci);if(!a.dA)b.uniform1i(BG,0);else{b.bindBuffer(34962,a.e2);b.bufferData(34962,a.dr.subarray(0,
a.cJ*2|0),35048);b.vertexAttribPointer(Ct,2,5126,!!0,0,0);b.enableVertexAttribArray(Ct);b.uniform1i(BG,1);}if(!a.dq)b.uniform1i(Cq,0);else{b.bindBuffer(34962,a.e3);b.bufferData(34962,a.dg.subarray(0,a.cJ*3|0),35048);b.vertexAttribPointer(Ca,3,5126,!!0,0,0);b.enableVertexAttribArray(Ca);b.uniform1i(Cq,1);}b.bindBuffer(34963,DP);b.drawElements(4,(a.cJ*6|0)/4|0,5123,0);}Dh(a);},Dh=a=>{a.cJ=0;},Gw=a=>{Dh(a);a.dq=0;a.dA=0;},N=(a,b,c)=>{a.dA=1;a.eQ=b;a.eP=c;},BU=(a,b,c,d)=>{a.dq=1;a.eR=b;a.eO=c;a.eN=d;},H=(a,b,c,
d)=>{let e;a.di[(a.cJ*3|0)+0|0]=b;a.di[(a.cJ*3|0)+1|0]=c;a.di[(a.cJ*3|0)+2|0]=d;if(a.dA){a.dr[(a.cJ*2|0)+0|0]=a.eQ;a.dr[(a.cJ*2|0)+1|0]=a.eP;}if(a.dq){a.dg[(a.cJ*3|0)+0|0]=a.eR;a.dg[(a.cJ*3|0)+1|0]=a.eO;a.dg[(a.cJ*3|0)+2|0]=a.eN;}e=a.cJ+1|0;a.cJ=e;if(e==100000)Gl(a);},HX=F(),T=F(0);
function C7(){let a=this;E.call(a);a.eK=0;a.eI=null;a.eJ=null;}
let Jx=(b,c)=>{let d;b=b;d=b.eK;c=b.eI;b=b.eJ;Ck();DU(d);c.texImage2D(3553,0,6408,6408,5121,b);c.generateMipmap(3553);},Ds=F(),Cs=F(Ds),G7=F(Cs),B_=F(O),J8=F(),FE=F(),Hw=null,Et=null,CX=null,CO=null,E$=null,Es=null,EC=null,Ch=()=>{Ch=Y(FE);IP();},IP=()=>{let b;Hw=new WeakMap();Et=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();CX=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();CO=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(CX===null)b=null;else{b=new Dd;b=new FinalizationRegistry(Q(I(b),
"accept"));}Es=b;if(CO===null)b=null;else{b=new Dc;b=new FinalizationRegistry(Q(I(b),"accept"));}EC=b;},I4=F(),H3=F(),Ei=F(0),Dd=F(),Io=(b,c)=>{b;Ch();CX.delete(c);},Dc=F(),HO=(b,c)=>{b;Ch();CO.delete(c);},Er=F(0);
function D7(){let a=this;E.call(a);a.ej=null;a.dM=null;}
function DN(){E.call(this);this.ev=null;}
let G2=(a,b)=>{a.ev=b;},Hh=a=>{let b=new DN();G2(b,a);return b;},Ij=(b,c)=>{E3(b.ev,window.innerWidth,window.innerHeight);},Ga=F(),DJ=0,EQ=0,ER=0,BQ=0.0,BP=0.0,Du=0,DV=null,Gs=null,GV=0,H$=0,H_=0,Cn=0,Br=null,D_=null,Dr=0,EI=null,Gr=null,Fd=null,EG=null,FY=null,Gb=null,FF=null,FA=null,Cc=null,V=()=>{V=Y(Ga);G6();},JB=()=>{let b,c,d,e,f;V();DV=P(Z,16);b=0;while(b<16){c=DV.data;d=Bz();Di(Bl(d,D(151)),b);c[b]=BO(d);d=Gs;e=DV.data[b];f=BA(b);CD(d,e,f);b=b+1|0;}GV=1;},IO=()=>{let b,c,d,$$je;V();a:{b:{try{if(!DJ)break b;}
catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}return;}c:{try{if(GV)break c;JB();break c;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}d:{try{c=window;d=I5();EI=I(d);c.addEventListener("contextmenu",Q(I(d),"handleEvent"));c=window;d=Hs();Gr=I(d);c.addEventListener("mousedown",Q(I(d),"handleEvent"));c=window;d=Hp();Fd=I(d);c.addEventListener("mouseup",Q(I(d),"handleEvent"));c=window;d=Ie();EG=I(d);c.addEventListener("mousemove",Q(I(d),"handleEvent"));c
=window;d=Ig();FY=I(d);c.addEventListener("wheel",Q(I(d),"handleEvent"));c=window.document;d=Ix();Gb=I(d);c.addEventListener("pointerlockchange",Q(I(d),"handleEvent"));c=window;d=In();FF=I(d);c.addEventListener("mouseleave",Q(I(d),"handleEvent"));c=window;d=IE();FA=I(d);c.addEventListener("mouseenter",Q(I(d),"handleEvent"));DJ=1;b=Br;if(b===null)break d;Gi(b);break d;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}try{Fo(Cn);}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}
else{throw $$e;}}return;}J(GX(b));},GE=()=>{let b,c;V();b=Cc;if(b===null)return (-1);c=b.button;if(c==1)c=2;else if(c==2)c=1;return c;},Fq=()=>{let b;V();b=Cc;return b===null?0:Bs(Be(b.type),D(152));},Fo=b=>{let c;V();c=Cn;Cn=b;if(DJ){if(b&&!c){if(!(document.pointerLockElement!=null?1:0)){H$=EQ;H_=ER;BQ=0.0;BP=0.0;document.body.requestPointerLock();}}else if(!b&&c&&(document.pointerLockElement!=null?1:0))document.exitPointerLock();Du=0;BP=0.0;BQ=0.0;}},G6=()=>{Gs=FZ(16);Br=new D5;D_=GQ(8);Dr=1;EI=null;Gr=null;Fd
=null;EG=null;FY=null;Gb=null;FF=null;FA=null;Cc=null;};
function DM(){E.call(this);this.eT=null;}
let Hu=(a,b)=>{a.eT=b;},G$=a=>{let b=new DM();Hu(b,a);return b;},Jj=(b,c)=>{b=b.eT;M();b.requestPointerLock();},Jv=F(Cs);
function GT(){let a=this;E.call(a);a.cS=0;a.cX=0;a.cV=0;a.dt=null;a.dJ=null;a.de=null;}
let Hm=(a,b,c,d)=>{let e,f,g,h,i,j,k,l,m,$$je;a.de=FJ();a.cS=b;a.cX=c;a.cV=d;e=R(b,c);f=BS(R(e,d));g=f.data;a.dt=f;a.dJ=CU(e);h=0;e=d*2|0;while(h<b){i=0;while(i<d){j=0;while(j<c){g[R(R(i,c)+j|0,b)+h|0]=(i>(e/3|0)?0:1)<<24>>24;j=j+1|0;}i=i+1|0;}h=h+1|0;}En(a,0,0,b,c);a:{try{b:{k=Be(window.localStorage.getItem("level.dat"));if(k!==null){g=Hr(Jt(),k);l=g.data;f=a.dt;Fp(g,0,f,0,Dj(l.length,f.data.length));En(a,0,0,a.cS,a.cX);b=0;while(true){if(b>=IC(a.de))break b;Ih(BV(a.de,b));b=b+1|0;}}}break a;}catch($$e){$$je
=U($$e);if($$je instanceof Bu){m=$$je;CM(m);break a;}else{throw $$e;}}}},II=(a,b,c)=>{let d=new GT();Hm(d,a,b,c);return d;},E2=a=>{let b,c,$$je;a:{try{b=H8(G4(),a.dt);window.localStorage.setItem("level.dat",BT(b));break a;}catch($$e){$$je=U($$e);if($$je instanceof Bu){c=$$je;CM(c);break a;}else{throw $$e;}}}},En=(a,b,c,d,e)=>{let f,g,h,i,j,k,l;f=b+d|0;d=c+e|0;while(b<f){g=c;while(g<d){h=a.dJ.data[b+R(g,a.cS)|0];i=a.cV-1|0;while(i>0&&!Bj(a,b,i,g)){i=i+(-1)|0;}a:{a.dJ.data[b+R(g,a.cS)|0]=i;e=Df(h,i);if(e){j=e
>=0?i:h;if(e>0)i=h;k=0;while(true){l=a.de;if(k>=l.cY)break a;DR(BV(l,k),b-1|0,j-1|0,g-1|0,b+1|0,i+1|0,g+1|0);k=k+1|0;}}}g=g+1|0;}b=b+1|0;}},Bj=(a,b,c,d)=>{let e,f;if(b>=0&&c>=0&&d>=0){e=a.cS;if(b<e&&c<a.cV){f=a.cX;if(d<f)return a.dt.data[R(R(c,f)+d|0,e)+b|0]!=1?0:1;}}return 0;},IH=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m;c=FJ();d=b.cN|0;e=b.cO+1.0|0;f=b.cP|0;g=b.cU+1.0|0;h=b.cR|0;i=b.cQ+1.0|0;if(d<0)d=0;if(f<0)f=0;if(h<0)h=0;j=a.cS;if(e<=j)j=e;k=a.cV;if(g<=k)k=g;g=a.cX;if(i<=g)g=i;while(d<j){l=f;while(l<k){m=h;while
(m<g){if(Bj(a,d,l,m))FI(c,Cy(d,l,m,d+1|0,l+1|0,m+1|0));m=m+1|0;}l=l+1|0;}d=d+1|0;}return c;},BY=(a,b,c,d)=>{let e,f;e=1.0;if(b>=0&&c>=0&&d>=0){f=a.cS;if(b<f&&c<a.cV&&d<a.cX){if(c<a.dJ.data[b+R(d,f)|0])e=0.6000000238418579;return e;}}return e;},E5=(a,b,c,d,e)=>{let f,g,h,i,j;a:{if(b>=0&&c>=0&&d>=0){f=a.cS;if(b<f&&c<a.cV){g=a.cX;if(d<g){a.dt.data[R(R(c,g)+d|0,f)+b|0]=e<<24>>24;En(a,b,d,1,1);f=0;e=b-1|0;g=c-1|0;h=d-1|0;b=b+1|0;i=c+1|0;d=d+1|0;while(true){j=a.de;if(f>=j.cY)break a;DR(BV(j,f),e,g,h,b,i,d);f=f+1|
0;}}}}}},E_=F(0);
function FG(){let a=this;E.call(a);a.d8=null;a.ds=null;a.dQ=0;a.ee=0;a.d7=0;a.dP=null;}
let H7=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p;a.dP=FH();a.d8=b;FI(b.de,a);c=b.cS/16|0;a.dQ=c;d=b.cV/16|0;a.ee=d;e=b.cX/16|0;a.d7=e;a.ds=P(CB,R(R(c,d),e));c=0;while(c<a.dQ){f=0;while(f<a.ee){d=0;while(true){e=a.d7;if(d>=e)break;g=c*16|0;h=f*16|0;i=d*16|0;j=(c+1|0)*16|0;k=(f+1|0)*16|0;l=d+1|0;m=l*16|0;n=b.cS;if(j<=n)n=j;j=b.cV;if(k<=j)j=k;k=b.cX;if(m<=k)k=m;o=a.ds.data;e=R(c+R(f,a.dQ)|0,e)+d|0;p=new CB;BB();p.dX=1;p.dp=P(E,2);p.dG=P(E,2);p.dF=P(E,2);p.dT=CU(2);p.ef=b;p.eG=g;p.eA=h;p.eC=i;p.eH=n;p.ez=j;p.eD=k;p.eF
=Cy(g,h,i,n,j,k);o[e]=p;d=l;}f=f+1|0;}c=c+1|0;}},Ii=a=>{let b=new FG();H7(b,a);return b;},Gp=(a,b,c)=>{let d,e,f;BB();CE=0;Cu();HM(C8);d=C8;e=0;while(true){f=a.ds.data;if(e>=f.length)break;b=f[e].eF;if(Ju(d,b.cN,b.cP,b.cR,b.cO,b.cU,b.cQ))JO(a.ds.data[e],c);e=e+1|0;}},JF=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z;c=b.dw;d=b.dx;e=b.dy;f=CH(Cp( -b.c6));g=B$(Cp( -b.c6));h=CH(Cp(b.c9));i=B$(Cp(b.c9))*f;j= -h*f;k=Dx(c)|0;l=Dx(d)|0;m=Dx(e)|0;n=CY(i,0.0);o=n<=0?(-1):1;p=CY(g,0.0);q=p<=0?(-1):1;r=CY(j,
0.0);s=r<=0?(-1):1;t=!n?3.4028234663852886E38:DD(1.0/i);u=!p?3.4028234663852886E38:DD(1.0/g);v=!r?3.4028234663852886E38:DD(1.0/j);w=n<=0?(c-k)*t:((k+1|0)-c)*t;x=p<=0?(d-l)*u:((l+1|0)-d)*u;y=r<=0?(e-m)*v:((m+1|0)-e)*v;n=(-1);z=0.0;while(z<5.0){if(Bj(a.d8,k,l,m)){b=new GO;b.dU=k;b.dV=l;b.dW=m;b.e8=0;b.d$=n;M();BK=b;return;}if(!(w<x)){if(!(x<y)){c=y+v;m=m+s|0;n=s<=0?3:2;z=y;y=c;continue;}c=x+u;l=l+q|0;n=q<=0?1:0;z=x;x=c;continue;}if(!(w<y)){c=y+v;m=m+s|0;n=s<=0?3:2;z=y;y=c;continue;}c=w+t;k=k+o|0;n=o<=0?5:4;z=
w;w=c;}b=null;M();BK=b;},Hc=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o;M();c=G;c.enable(3042);c.blendFunc(770,1);c.uniform1f(Dl,B$(DS(Cx())/100.0)*0.20000000298023224+0.4000000059604645);Gw(a.dP);BF();d=a.dP;e=b.dU;f=b.dV;g=b.dW;h=b.d$;i=e;j=i+0.0;k=i+1.0;l=f;m=l+0.0;n=l+1.0;o=g;l=o+0.0;i=o+1.0;if(!h){H(d,j,m,i);H(d,j,m,l);H(d,k,m,l);H(d,k,m,i);}if(h==1){H(d,k,n,i);H(d,k,n,l);H(d,j,n,l);H(d,j,n,i);}if(h==2){H(d,j,n,l);H(d,k,n,l);H(d,k,m,l);H(d,j,m,l);}if(h==3){H(d,j,n,i);H(d,j,m,i);H(d,k,m,i);H(d,k,n,i);}if(h==4)
{H(d,j,n,i);H(d,j,n,l);H(d,j,m,l);H(d,j,m,i);}if(h==5){H(d,k,m,i);H(d,k,m,l);H(d,k,n,l);H(d,k,n,i);}Gl(a.dP);c.disable(3042);b=Dl;c.uniform1f(b,1.0);},DR=(a,b,c,d,e,f,g)=>{let h,i,j,k,l;h=b/16|0;e=e/16|0;b=c/16|0;c=f/16|0;f=d/16|0;g=g/16|0;if(h<0)h=0;if(b<0)b=0;if(f<0)f=0;i=a.dQ;if(e>=i)e=i-1|0;d=a.ee;if(c>=d)c=d-1|0;j=a.d7;if(g>=j)g=j-1|0;while(h<=e){k=b;while(k<=c){l=f;while(l<=g){a.ds.data[R(h+R(k,i)|0,j)+l|0].dX=1;l=l+1|0;}k=k+1|0;}h=h+1|0;}},Ih=a=>{let b;b=a.d8;DR(a,0,0,0,b.cS,b.cV,b.cX);};
function EK(){let a=this;E.call(a);a.dL=null;a.eu=0.0;a.et=0.0;a.eE=0.0;a.dw=0.0;a.dx=0.0;a.dy=0.0;a.c$=0.0;a.df=0.0;a.da=0.0;a.c9=0.0;a.c6=0.0;a.c1=null;a.dY=0;}
let Iu=(a,b)=>{a.dY=0;a.dL=b;Fr(a);},Jf=a=>{let b=new EK();Iu(b,a);return b;},Fr=a=>{let b,c,d,e;b=Fh();c=a.dL;b=b*c.cS;d=c.cV+10|0;e=Fh()*a.dL.cX;a.dw=b;a.dx=d;a.dy=e;a.c1=Cy(b-0.30000001192092896,d-0.8999999761581421,e-0.30000001192092896,b+0.30000001192092896,d+0.8999999761581421,e+0.30000001192092896);},J0=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q;a.eu=a.dw;a.et=a.dx;a.eE=a.dy;b=0.0;c=0.0;if(Bb(19))Fr(a);if(!(!Bb(200)&&!Bb(17)))c=(-1.0);if(!(!Bb(208)&&!Bb(31)))c=c+1.0;if(!(!Bb(203)&&!Bb(30)))b=(-1.0);if(!(!Bb(205)
&&!Bb(32)))b=b+1.0;if(!(!Bb(57)&&!Bb(219))&&a.dY)a.df=0.11999999731779099;d=!a.dY?0.004999999888241291:0.019999999552965164;e=b*b+c*c;if(!(e<0.009999999776482582)){d=d/GA(e);b=b*d;c=c*d;d=B$(a.c9*3.141592653589793/180.0);e=CH(a.c9*3.141592653589793/180.0);a.c$=a.c$+b*e-c*d;a.da=a.da+c*e+b*d;}b=a.df-0.005;a.df=b;c=a.c$;d=a.da;f=a.dL;g=a.c1;h=g.cN;i=g.cP;j=g.cR;k=g.cO;l=g.cU;m=g.cQ;if(c<0.0)h=h+c;if(c>0.0)k=k+c;n=Df(b,0.0);if(n<0)i=i+b;if(b>0.0)l=l+b;if(d<0.0)j=j+d;if(d>0.0)m=m+d;g=IH(f,Cy(h,i,j,k,l,m));o=0;p
=g;k=b;while(o<p.cY){k=H1(BV(p,o),a.c1,k);o=o+1|0;}De(a.c1,0.0,k,0.0);q=0;e=c;while(q<p.cY){e=JV(BV(p,q),a.c1,e);q=q+1|0;}De(a.c1,e,0.0,0.0);q=0;h=d;while(q<p.cY){h=Ha(BV(p,q),a.c1,h);q=q+1|0;}De(a.c1,0.0,0.0,h);q=CY(b,k);o=q&&n<0?1:0;a.dY=o;if(c!==e)a.c$=0.0;if(q)a.df=0.0;if(d!==h)a.da=0.0;g=a.c1;a.dw=(g.cN+g.cO)/2.0;a.dx=g.cP+1.6200000047683716;a.dy=(g.cR+g.cQ)/2.0;b=a.c$*0.9100000262260437;a.c$=b;a.df=a.df*0.9800000190734863;c=a.da*0.9100000262260437;a.da=c;if(o){a.c$=b*0.800000011920929;a.da=c*0.800000011920929;}},Ek
=F(O);
function GO(){let a=this;E.call(a);a.dU=0;a.dV=0;a.dW=0;a.e8=0;a.d$=0;}
function CC(){let a=this;D7.call(a);a.d9=0;a.dC=null;}
let Ed=F(),J2=a=>{return;},HN=()=>{let a=new Ed();J2(a);return a;},I2=(b,c)=>{let d;b;Bh();CP.data[DG(c.which)]=1;b=BD;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();},Ef=F(),JS=a=>{return;},HJ=()=>{let a=new Ef();JS(a);return a;},IM=(b,c)=>{let d;b;Bh();CP.data[DG(c.which)]=0;b=BD;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();},Ee=F(),IX=a=>{return;},I9=()=>{let a=new Ee();IX(a);return a;},IZ=(b,c)=>{let d;b;Bh();if(GN&&(c.repeat?1:0)){b=BD;d=Bf(c);BC(b,d);}c.preventDefault();c.stopPropagation();},Gc
=F(Bu),H5=(a,b)=>{Dn(a);a.eb=1;a.ei=1;HK(a);a.d1=b;},GX=a=>{let b=new Gc();H5(b,a);return b;},DX=F(),IR=a=>{return;},I5=()=>{let a=new DX();IR(a);return a;},Hj=(b,c)=>{b;c.preventDefault();c.stopPropagation();},D0=F(),JC=a=>{return;},Hs=()=>{let a=new D0();JC(a);return a;},HZ=(b,c)=>{let d,e,f;b;d=c.button;V();e=D_;if(d==1)d=2;else if(d==2)d=1;e.data[d]=1;b=Br;f=Bf(c);BC(b,f);c.preventDefault();c.stopPropagation();},D1=F(),JU=a=>{return;},Hp=()=>{let a=new D1();JU(a);return a;},Jb=(b,c)=>{let d,e,f;b;d=c.button;V();e
=D_;if(d==1)d=2;else if(d==2)d=1;e.data[d]=0;b=Br;f=Bf(c);BC(b,f);c.preventDefault();c.stopPropagation();},DY=F(),JL=a=>{return;},Ie=()=>{let a=new DY();JL(a);return a;},JW=(b,c)=>{let d,e;b;c.preventDefault();c.stopPropagation();d=window.devicePixelRatio;e=c.clientX*d|0;V();EQ=e;ER=(window.innerHeight-c.clientY|0)*d|0;BQ=BQ+c.movementX;BP=BP+ -c.movementY;b=Br;c=Bf(c);BC(b,c);},DZ=F(),JQ=a=>{return;},Ig=()=>{let a=new DZ();JQ(a);return a;},I0=(b,c)=>{let d,e;b;V();b=Br;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();e
=!(c.deltaY>0.0)?(-1):1;Du=Du+e|0;},D3=F(),JT=a=>{return;},Ix=()=>{let a=new D3();JT(a);return a;},I7=(b,c)=>{b;if(!(document.pointerLockElement!=null?1:0))Cn=0;else Cn=1;},D4=F(),JJ=a=>{return;},In=()=>{let a=new D4();JJ(a);return a;},Ir=(b,c)=>{b;c.preventDefault();c.stopPropagation();V();Dr=0;},D2=F(),IQ=a=>{return;},IE=()=>{let a=new D2();IQ(a);return a;},Hz=(b,c)=>{b;c.preventDefault();c.stopPropagation();V();Dr=1;},FV=F(0);
function FL(){let a=this;Cg.call(a);a.dk=null;a.cY=0;}
let HY=a=>{a.dk=P(E,10);},FJ=()=>{let a=new FL();HY(a);return a;},BV=(a,b)=>{let c;if(b>=0&&b<a.cY)return a.dk.data[b];c=new Bd;L(c);J(c);},IC=a=>{return a.cY;},FI=(a,b)=>{let c,d,e,f,g,h;c=a.cY+1|0;d=a.dk.data.length;if(d<c){c=d>=1073741823?2147483647:Cj(c,Cj(d*2|0,5));e=a.dk;f=C$(BM(e));if(f===null){b=new C_;L(b);J(b);}if(f===BE(IF)){b=new B_;L(b);J(b);}if(c<0){b=new GU;L(b);J(b);}g=e.data;e=Hn(f.c0,c);h=Dj(c,g.length);d=0;while(d<h){e.data[d]=g[d];d=d+1|0;}a.dk=e;}e=a.dk.data;h=a.cY;a.cY=h+1|0;e[h]=b;a.cW
=a.cW+1|0;return 1;},ET=F(Cd),BL=(a,b)=>{if(b===null)b=D(3);HQ(BT(b));},Iw=F(),FS=(b,c)=>{let d,e,f,g;b=b.data;d=0;e=b.length;if(d>e){f=new B_;L(f);J(f);}while(d<e){g=d+1|0;b[d]=c;d=g;}};
function Gx(){let a=this;E.call(a);a.c_=0.0;a.cN=0.0;a.cP=0.0;a.cR=0.0;a.cO=0.0;a.cU=0.0;a.cQ=0.0;}
let G8=(a,b,c,d,e,f,g)=>{a.c_=0.0;a.cN=b;a.cP=c;a.cR=d;a.cO=e;a.cU=f;a.cQ=g;},Cy=(a,b,c,d,e,f)=>{let g=new Gx();G8(g,a,b,c,d,e,f);return g;},JV=(a,b,c)=>{let d,e;if(!(b.cU<=a.cP)&&!(b.cP>=a.cU)){if(!(b.cQ<=a.cR)&&!(b.cR>=a.cQ)){if(!(c>0.0))d=c;else{d=b.cO;e=a.cN;if(!(d<=e))d=c;else{d=e-d-a.c_;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cN;e=a.cO;if(!(c>=e))e=d;else{e=e-c+a.c_;if(!(e>d))e=d;}}return e;}return c;}return c;},H1=(a,b,c)=>{let d,e;if(!(b.cO<=a.cN)&&!(b.cN>=a.cO)){if(!(b.cQ<=a.cR)&&!(b.cR>=a.cQ)){if
(!(c>0.0))d=c;else{d=b.cU;e=a.cP;if(!(d<=e))d=c;else{d=e-d-a.c_;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cP;e=a.cU;if(!(c>=e))e=d;else{e=e-c+a.c_;if(!(e>d))e=d;}}return e;}return c;}return c;},Ha=(a,b,c)=>{let d,e;if(!(b.cO<=a.cN)&&!(b.cN>=a.cO)){if(!(b.cU<=a.cP)&&!(b.cP>=a.cU)){if(!(c>0.0))d=c;else{d=b.cQ;e=a.cR;if(!(d<=e))d=c;else{d=e-d-a.c_;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cR;e=a.cQ;if(!(c>=e))e=d;else{e=e-c+a.c_;if(!(e>d))e=d;}}return e;}return c;}return c;},De=(a,b,c,d)=>{a.cN=a.cN+b;a.cP=a.cP+
c;a.cR=a.cR+d;a.cO=a.cO+b;a.cU=a.cU+c;a.cQ=a.cQ+d;},H0=F(),CR=b=>{let c;c=(BM(b)).c0;if(c[K].itemType!==null)return Jw(b);b=new B_;L(b);J(b);},CK=F(O),JE=F(),G4=()=>{let b;b=new F$;Bi();b.e4=Dp;b.eX=1;return b;},Jt=()=>{let b;b=new Fs;Bi();b.er=Ea;return b;};
function DL(){let a=this;E.call(a);a.c7=null;a.eY=null;a.eM=null;a.db=null;}
let C8=null,Cu=()=>{Cu=Y(DL);Hd();},BZ=(a,b,c)=>{let d,e;b=b.data;d=GA(b[c].data[0]*b[c].data[0]+b[c].data[1]*b[c].data[1]+b[c].data[2]*b[c].data[2]);e=b[c].data;e[0]=e[0]/d;e=b[c].data;e[1]=e[1]/d;e=b[c].data;e[2]=e[2]/d;b=b[c].data;b[3]=b[3]/d;},HM=a=>{let b,c,d,e;M();b=CA;c=b.data;a.eY=b;b=Cv;d=b.data;a.eM=b;b=a.db.data;b[0]=d[0]*c[0]+d[1]*c[4]+d[2]*c[8]+d[3]*c[12];b[1]=d[0]*c[1]+d[1]*c[5]+d[2]*c[9]+d[3]*c[13];b[2]=d[0]*c[2]+d[1]*c[6]+d[2]*c[10]+d[3]*c[14];b[3]=d[0]*c[3]+d[1]*c[7]+d[2]*c[11]+d[3]*c[15];b[4]
=d[4]*c[0]+d[5]*c[4]+d[6]*c[8]+d[7]*c[12];b[5]=d[4]*c[1]+d[5]*c[5]+d[6]*c[9]+d[7]*c[13];b[6]=d[4]*c[2]+d[5]*c[6]+d[6]*c[10]+d[7]*c[14];b[7]=d[4]*c[3]+d[5]*c[7]+d[6]*c[11]+d[7]*c[15];b[8]=d[8]*c[0]+d[9]*c[4]+d[10]*c[8]+d[11]*c[12];b[9]=d[8]*c[1]+d[9]*c[5]+d[10]*c[9]+d[11]*c[13];b[10]=d[8]*c[2]+d[9]*c[6]+d[10]*c[10]+d[11]*c[14];b[11]=d[8]*c[3]+d[9]*c[7]+d[10]*c[11]+d[11]*c[15];b[12]=d[12]*c[0]+d[13]*c[4]+d[14]*c[8]+d[15]*c[12];b[13]=d[12]*c[1]+d[13]*c[5]+d[14]*c[9]+d[15]*c[13];b[14]=d[12]*c[2]+d[13]*c[6]+d[14]
*c[10]+d[15]*c[14];b[15]=d[12]*c[3]+d[13]*c[7]+d[14]*c[11]+d[15]*c[15];d=a.c7;c=d.data;c[0].data[0]=b[3]-b[0];c[0].data[1]=b[7]-b[4];c[0].data[2]=b[11]-b[8];c[0].data[3]=b[15]-b[12];BZ(a,d,0);b=a.c7;d=b.data;e=d[1].data;c=a.db.data;e[0]=c[3]+c[0];d[1].data[1]=c[7]+c[4];d[1].data[2]=c[11]+c[8];d[1].data[3]=c[15]+c[12];BZ(a,b,1);b=a.c7;d=b.data;e=d[2].data;c=a.db.data;e[0]=c[3]+c[1];d[2].data[1]=c[7]+c[5];d[2].data[2]=c[11]+c[9];d[2].data[3]=c[15]+c[13];BZ(a,b,2);b=a.c7;d=b.data;e=d[3].data;c=a.db.data;e[0]=c[3]
-c[1];d[3].data[1]=c[7]-c[5];d[3].data[2]=c[11]-c[9];d[3].data[3]=c[15]-c[13];BZ(a,b,3);b=a.c7;d=b.data;e=d[4].data;c=a.db.data;e[0]=c[3]-c[2];d[4].data[1]=c[7]-c[6];d[4].data[2]=c[11]-c[10];d[4].data[3]=c[15]-c[14];BZ(a,b,4);b=a.c7;d=b.data;e=d[5].data;c=a.db.data;e[0]=c[3]+c[2];d[5].data[1]=c[7]+c[6];d[5].data[2]=c[11]+c[10];d[5].data[3]=c[15]+c[14];BZ(a,b,5);},Ju=(a,b,c,d,e,f,g)=>{let h,i;h=0;while(h<6){i=a.c7.data;if(!(i[h].data[0]*b+i[h].data[1]*c+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]
*c+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*f+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*f+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*c+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*c+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*f+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*f+i[h].data[2]*g+i[h].data[3]>0.0))return 0;h=h+1|0;}return 1;},Hd=()=>{let b;b=new DL;Cu();b.c7=IN([4,6]);b.eY=Bp(16);b.eM
=Bp(16);b.db=Bp(16);C8=b;};
function Dm(){E.call(this);this.eg=0;}
let Eq=null,Gq=null,BF=()=>{BF=Y(Dm);Jz();},G5=(a,b)=>{BF();a.eg=0;a.eg=b;},Fn=a=>{let b=new Dm();G5(b,a);return b;},Fb=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r;h=a.eg/16.0;i=h+0.062437500804662704;j=e;k=j+0.0;l=j+1.0;m=f;n=m+0.0;j=m+1.0;m=g;o=m+0.0;p=m+1.0;q=f-1|0;if(!Bj(c,e,q,g)){m=BY(c,e,q,g)*1.0;if((m!==1.0?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,h,0.062437500804662704);H(b,k,n,p);N(b,h,0.0);H(b,k,n,o);N(b,i,0.0);H(b,l,n,o);N(b,i,0.062437500804662704);H(b,l,n,p);}}if(!Bj(c,e,f+1|0,g)){m=BY(c,e,f,g)*1.0;if((m
!==1.0?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.062437500804662704);H(b,l,j,p);N(b,i,0.0);H(b,l,j,o);N(b,h,0.0);H(b,k,j,o);N(b,h,0.062437500804662704);H(b,k,j,p);}}r=g-1|0;if(!Bj(c,e,f,r)){m=BY(c,e,f,r)*0.800000011920929;if((m!==0.800000011920929?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.0);H(b,k,j,o);N(b,h,0.0);H(b,l,j,o);N(b,h,0.062437500804662704);H(b,l,n,o);N(b,i,0.062437500804662704);H(b,k,n,o);}}r=g+1|0;if(!Bj(c,e,f,r)){m=BY(c,e,f,r)*0.800000011920929;if((m!==0.800000011920929?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,
h,0.0);H(b,k,j,p);N(b,h,0.062437500804662704);H(b,k,n,p);N(b,i,0.062437500804662704);H(b,l,n,p);N(b,i,0.0);H(b,l,j,p);}}r=e-1|0;if(!Bj(c,r,f,g)){m=BY(c,r,f,g)*0.6000000238418579;if((m!==0.6000000238418579?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.0);H(b,k,j,p);N(b,h,0.0);H(b,k,j,o);N(b,h,0.062437500804662704);H(b,k,n,o);N(b,i,0.062437500804662704);H(b,k,n,p);}}e=e+1|0;if(!Bj(c,e,f,g)){m=BY(c,e,f,g)*0.6000000238418579;if((m!==0.6000000238418579?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,h,0.062437500804662704);H(b,l,n,p);N(b,
i,0.062437500804662704);H(b,l,n,o);N(b,i,0.0);H(b,l,j,o);N(b,h,0.0);H(b,l,j,p);}}},Jz=()=>{Eq=Fn(0);Gq=Fn(1);};
function F$(){let a=this;E.call(a);a.e4=null;a.eX=0;}
let H8=(a,b)=>{let c,d,e,f,g,h;c=b.data;d=a.e4;e=a.eX;Bi();f=c.length;g=((f+2|0)/3|0)*4|0;if(!e){f=f%3|0;if(f)g=g-(3-f|0)|0;}h=BS(g);c=h.data;IJ(b,h,d,e);e=c.length;d=BI(e);b=d.data;g=0;while(g<e){b[g]=c[g]&255&65535;g=g+1|0;}return Ey(d);},F4=F(),Dp=null,GH=null,Ea=null,C6=null,Bi=()=>{Bi=Y(F4);Ji();},Ic=(b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p;Bi();b=b.data;e=b.length;f=e-1|0;while(f>=0&&b[f]==61){e=e+(-1)|0;f=f+(-1)|0;}g=(e/4|0)*4|0;h=0;i=0;while(h<g){j=c.data;f=h+1|0;k=Bn(d,b[h]);h=f+1|0;l=Bn(d,b[f]);f=h+1
|0;m=Bn(d,b[h]);h=f+1|0;n=Bn(d,b[f]);o=k<<18|l<<12|m<<6|n;f=i+1|0;j[i]=(o>>>16|0)<<24>>24;k=f+1|0;j[f]=(o>>>8|0)<<24>>24;i=k+1|0;j[k]=o<<24>>24;}p=e-h|0;if(p==2)c.data[i]=(Bn(d,b[h])<<2|(Bn(d,b[h+1|0])>>>4|0))<<24>>24;else if(p==3){c=c.data;k=Bn(d,b[h]);l=Bn(d,b[h+1|0]);h=Bn(d,b[h+2|0]);c[i]=(k<<2|(l>>>4|0))<<24>>24;c[i+1|0]=(l<<4|(h>>>2|0))<<24>>24;}},Bn=(b,c)=>{Bi();return b.data[c];},IJ=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n;Bi();f=b.data;g=f.length;h=(g/3|0)*3|0;i=0;j=0;while(j<h){b=c.data;k=i+1|0;b[i]=Bm(d,
(f[j]>>>2|0)<<24>>24);l=k+1|0;m=f[j]<<4;i=j+1|0;b[k]=Bm(d,(m|((f[i]&255)>>>4|0))<<24>>24);m=l+1|0;j=f[i]<<2;n=i+1|0;b[l]=Bm(d,(j|((f[n]&255)>>>6|0))<<24>>24);i=m+1|0;b[m]=Bm(d,f[n]);j=n+1|0;}l=g-j|0;if(l==1){b=c.data;l=i+1|0;b[i]=Bm(d,(f[j]>>>2|0)<<24>>24);i=l+1|0;b[l]=Bm(d,f[j]<<4<<24>>24);if(e){e=i+1|0;b[i]=61;i=e+1|0;b[e]=61;}}else if(l==2){b=c.data;m=i+1|0;b[i]=Bm(d,(f[j]>>>2|0)<<24>>24);i=m+1|0;n=f[j]<<4;l=j+1|0;b[m]=Bm(d,(n|((f[l]&255)>>>4|0))<<24>>24);m=i+1|0;b[i]=Bm(d,f[l]<<2<<24>>24);if(!e)i=m;else
{i=m+1|0;b[m]=61;}}return i;},Bm=(b,c)=>{Bi();return b.data[c&63];},Ji=()=>{let b,c,d,e,f,g;b=BS(64);c=b.data;Dp=b;b=BS(64);d=b.data;GH=b;b=CU(256);Ea=b;C6=CU(256);e=0;f=65;while(f<=90){g=f<<24>>24;c[e]=g;d[e]=g;e=e+1|0;f=(f+1|0)&65535;}f=97;while(f<=122){g=f<<24>>24;c[e]=g;d[e]=g;e=e+1|0;f=(f+1|0)&65535;}g=48;while(g<=57){f=g<<24>>24;c[e]=f;d[e]=f;e=e+1|0;g=(g+1|0)&65535;}c[e]=43;d[e]=45;e=e+1|0;c[e]=47;d[e]=95;FS(b,(-1));FS(C6,(-1));g=0;while(true){b=Dp.data;if(g>=b.length)break;Ea.data[b[g]]=g;C6.data[GH.data[g]]
=g;g=g+1|0;}};
function Fs(){E.call(this);this.er=null;}
let Hr=(a,b)=>{let c,d,e,f,g,h,i;c=BS(b.cI.length);d=c.data;e=0;f=d.length;while(e<f){d[e]=CL(b,e)<<24>>24;e=e+1|0;}g=a.er;Bi();h=(f/4|0)*3|0;i=f%4|0;if(!(i!=2&&i!=3))h=h+(i-1|0)|0;e=f-1|0;while(e>=0&&d[e]==61){h=h+(-1)|0;e=e+(-1)|0;}d=BS(h);Ic(c,d,g);return d;},GK=F(0),GR=F(0);
function Ew(){let a=this;E.call(a);a.dv=null;a.du=null;a.ed=null;a.d3=0;a.dH=0;a.dl=null;}
let Jc=(a,b,c,d,e)=>{a.dl=b;a.dH=b.cW;a.dv=c;a.du=d;a.d3=e;},F7=(a,b,c,d)=>{let e=new Ew();Jc(e,a,b,c,d);return e;},Fz=a=>{let b;if(a.dH>=a.dl.cW)return;b=new Fl;L(b);J(b);};
function F0(){let a=this;E.call(a);a.eW=null;a.dc=null;a.dd=null;}
let Fl=F(O),GU=F(O);
HS([-1,"java",0,"util",0,"lang",-1,"org",3,"lwjgl"]);
C9([E,0,0,[],1,0,0,0,By,0,E,[],1537,0,0,0,Cl,0,E,[],1537,0,0,0,DK,0,E,[],1537,0,0,0,Z,0,E,[By,Cl,DK],17,0,()=>BW(),["by",BJ(Bs),"b1",CF(Ik)],D$,0,E,[By],1025,0,0,0,B6,0,D$,[Cl],1,0,()=>B2(),["b1",CF(Hi),"by",BJ(Jr)],Dq,0,E,[By,DK],0,0,0,0,DC,0,E,[],1537,0,0,0,EH,0,Dq,[DC],1,0,0,0,Bg,0,E,[],1,0,0,0,Bu,0,Bg,[],1,0,0,0,O,0,Bu,[],1,0,0,0,B3,0,E,[],1025,0,0,0,H2,0,B3,[],17,0,0,0,HR,0,B3,[],17,0,0,0,E7,0,E,[],1537,0,0,0,GJ,0,E,[E7],1537,0,0,0,Ex,0,E,[],1537,0,0,0,Fk,0,E,[GJ,Ex],17,0,0,0,Dw,0,E,[],1537,0,0,0,Em,0,
E,[Dw],1,0,()=>M(),0,Ja,0,E,[],17,0,0,0,JH,0,E,[],17,0,0,0,J3,0,E,[],17,0,0,0,B9,0,E,[Dw],1,0,()=>Bo(),0,F9,0,E,[],1537,0,0,0,FD,0,E,[F9],1,0,0,0,DT,0,E,[Cl],1,0,()=>Db(),0,EV,0,E,[],1,0,0,0,HT,0,E,[],17,0,0,0,Ej,0,E,[],17,0,0,0,IV,0,E,[],17,0,0,0,Ff,0,E,[],1537,0,0,0,GF,0,E,[Ff],1,0,0,0,Bd,"IndexOutOfBoundsException",2,O,[],1,0,0,0,Cm,0,E,[],1537,0,0,0,GW,0,E,[Cm],1,0,0,["bt",CF(Il)],GC,0,E,[],0,0,0,0,CI,"IllegalMonitorStateException",2,O,[],1,0,0,0,EU,0,E,[],1537,0,0,0,Jm,0,E,[Cm,EU],1536,0,0,0,Jl,"ClassCastException",
2,O,[],1,0,0,0,Fe,"IllegalStateException",2,O,[],1,0,0,0,Gm,0,E,[Cm],1,0,0,["bt",CF(IW)],F3,0,E,[],1537,0,0,0,FO,0,E,[F3],0,0,0,["h",BJ(CT),"bH",BJ(Jq)],EW,0,E,[Cm],1,0,0,0,E8,0,E,[],1537,0,0,0,CN,0,E,[E8],1537,0,0,0]);
C9([B4,0,E,[CN],1025,0,0,0,Ez,0,E,[CN],1537,0,0,0,Eg,0,E,[CN],1537,0,0,0,D8,0,E,[Ez,Eg],1537,0,0,0,BX,0,E,[],1537,0,0,0,F5,0,B4,[D8,BX,By],1,0,0,0,IT,0,E,[],17,0,0,0,CQ,"StringIndexOutOfBoundsException",2,Bd,[],1,0,0,0,GI,0,E,[],1,0,()=>Bh(),0,Bv,0,E,[],1537,0,0,0,FX,0,E,[Bv],1537,0,0,0,Da,0,E,[FX],1,0,0,0,CB,0,E,[],1,0,()=>BB(),0,C_,"NullPointerException",2,O,[],1,0,0,0,Gv,0,E,[],1537,0,0,0,Fi,0,E,[Gv],1537,0,0,0,Gg,0,E,[],1537,0,0,0,DI,0,E,[Fi,Gg],1025,0,0,0,Do,0,DI,[],1,0,0,0,Dk,0,Do,[DC],1,0,0,0,Cd,0,Dk,
[],1025,0,0,0,EY,0,Cd,[],1,0,0,["B",BJ(Jn)],EP,0,E,[],1537,0,0,0,D9,0,E,[EP],1025,0,0,0,D6,0,D9,[BX,By],1,0,0,0,EO,0,E,[Eg],1537,0,0,0,Cg,0,B4,[EO],1025,0,0,0,Dy,0,Cg,[],1025,0,0,0,D5,0,Dy,[D8,BX],1,0,0,0,FR,0,E,[],1,0,()=>Ck(),0,FP,0,E,[],1,0,0,0,HX,0,E,[Cl],1025,0,0,0,T,0,E,[Bv],1537,0,0,0,C7,0,E,[T],1,0,0,0,Ds,0,E,[Bv],1025,0,0,0,Cs,0,Ds,[],1025,0,0,0,G7,0,Cs,[],1,0,0,0,B_,"IllegalArgumentException",2,O,[],1,0,0,0,J8,0,E,[],17,0,0,0,FE,0,E,[],0,0,()=>Ch(),0,I4,0,E,[Bv],1,0,0,0,H3,0,E,[Bv],1025,0,0,0,Ei,0,
E,[Bv],1536,0,0,0,Dd,0,E,[Ei],1,0,0,0,Dc,0,E,[Ei],1,0,0,0,Er,0,E,[],1537,0,0,0,D7,0,E,[Er,BX],0,0,0,0,DN,0,E,[T],1,0,0,0,Ga,0,E,[],1,0,()=>V(),0,DM,0,E,[T],1,0,0,0]);
C9([Jv,0,Cs,[],1,0,0,0,GT,0,E,[],1,0,0,0,E_,0,E,[],1537,0,0,0,FG,0,E,[E_],1,0,0,0,EK,0,E,[],1,0,0,0,Ek,"NoSuchElementException",1,O,[],1,0,0,0,GO,0,E,[],1,0,0,0,CC,0,D7,[],0,0,0,0,Ed,0,E,[T],0,0,0,0,Ef,0,E,[T],0,0,0,0,Ee,0,E,[T],0,0,0,0,Gc,"LWJGLException",4,Bu,[],1,0,0,0,DX,0,E,[T],0,0,0,0,D0,0,E,[T],0,0,0,0,D1,0,E,[T],0,0,0,0,DY,0,E,[T],0,0,0,0,DZ,0,E,[T],0,0,0,0,D3,0,E,[T],0,0,0,0,D4,0,E,[T],0,0,0,0,D2,0,E,[T],0,0,0,0,FV,0,E,[],1537,0,0,0,FL,0,Cg,[BX,By,FV],1,0,0,0,ET,0,Cd,[],1,0,0,["B",BJ(BL)],Iw,0,E,[],
1,0,0,0,Gx,0,E,[],1,0,0,0,H0,0,E,[],17,0,0,0,CK,"ArrayStoreException",2,O,[],1,0,0,0,JE,0,E,[],17,0,0,0,DL,0,E,[],1,0,()=>Cu(),0,Dm,0,E,[],1,0,()=>BF(),0,F$,0,E,[],1,0,0,0,F4,0,E,[],17,0,()=>Bi(),0,Fs,0,E,[],1,0,0,0,GK,0,E,[],1537,0,0,0,GR,0,E,[GK],1537,0,0,0,Ew,0,E,[GR],0,0,0,0,F0,0,E,[],0,0,0,0,Fl,"ConcurrentModificationException",1,O,[],1,0,0,0,GU,"NegativeArraySizeException",2,O,[],1,0,0,0]);
let JD=Bc(Iq),I$=Bc(FK),I6=Bc(G0),JM=Bc(HI),F_=Bc(E1),EA=Bc(Dz);
HE(["Can\'t enter monitor from another thread synchronously","0","<java_object>@","null",": ","\n","\tat ","Caused by: ","[L"," fps, ","main","object","function","string","number","undefined","Either src or dest is null","keyup","NONE","ESCAPE","1","2","3","4","5","6","7","8","9","MINUS","EQUALS","BACK","TAB","Q","W","E","R","T","Y","U","I","O","P","LBRACKET","RBRACKET","RETURN","LCONTROL","A","S","D","F","G","H","J","K","L","SEMICOLON","APOSTROPHE","GRAVE","LSHIFT","BACKSLASH","Z","X","C","V","B","N","M","COMMA",
"PERIOD","SLASH","RSHIFT","MULTIPLY","LMENU","SPACE","CAPITAL","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","NUMLOCK","SCROLL","NUMPAD7","NUMPAD8","NUMPAD9","SUBTRACT","NUMPAD4","NUMPAD5","NUMPAD6","ADD","NUMPAD1","NUMPAD2","NUMPAD3","NUMPAD0","DECIMAL","","F11","F12","F13","F14","F15","F16","F17","F18","KANA","F19","CONVERT","NOCONVERT","YEN","NUMPADEQUALS","CIRCUMFLEX","AT","COLON","UNDERLINE","KANJI","STOP","AX","UNLABELED","NUMPADENTER","RCONTROL","SECTION","NUMPADCOMMA","DIVIDE","SYSRQ","RMENU","FUNCTION",
"PAUSE","HOME","UP","PRIOR","LEFT","RIGHT","END","DOWN","NEXT","INSERT","DELETE","CLEAR","LMETA","RMETA","APPS","POWER","SLEEP","/terrain.png","/","BUTTON","mousedown"]);
Z.prototype.toString=function(){return BT(this);};
Z.prototype.valueOf=Z.prototype.toString;E.prototype.toString=function(){return BT(Je(this));};
E.prototype.__teavm_class__=function(){return JX(this);};
let C=G1(IK);
C.javaException=IG;
let Kc=Symbol('jsoClass');
(()=>{let c;c=Da.prototype;c.onAnimationFrame=S(JI);c=C7.prototype;c.handleEvent=S(Jx);c=Dd.prototype;c.accept=S(Io);c=Dc.prototype;c.accept=S(HO);c=DN.prototype;c.handleEvent=S(Ij);c=DM.prototype;c.handleEvent=S(Jj);c=Ed.prototype;c.handleEvent=S(I2);c=Ef.prototype;c.handleEvent=S(IM);c=Ee.prototype;c.handleEvent=S(IZ);c=DX.prototype;c.handleEvent=S(Hj);c=D0.prototype;c.handleEvent=S(HZ);c=D1.prototype;c.handleEvent=S(Jb);c=DY.prototype;c.handleEvent=S(JW);c=DZ.prototype;c.handleEvent=S(I0);c=D3.prototype;c.handleEvent
=S(I7);c=D4.prototype;c.handleEvent=S(Ir);c=D2.prototype;c.handleEvent=S(Hz);})();
B.main=C;}));
