"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let GQ=2463534242,I9=()=>{let x=GQ;x^=x<<13;x^=x>>>17;x^=x<<5;GQ=x;return x;},CF=f=>function(){return f(this);},BJ=f=>function(p1){return f(this,p1);},Jy=f=>function(){let args=Array.prototype.slice.apply(arguments);Fx(function()
{f.apply(this,args);});},G3=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=P(BN(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=Be(args[i]);}Fx(()=>{f.call(null,javaArgs);},callback);},Y=target=>target.$clinit=()=>{},J3=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls[K]&&cls[K].item){++arrayDegree;cls=cls[K].item;}let clsName="";if(cls[K].primitiveKind!==0){clsName=cls[K].name;}else {clsName=cls[K]?cls[K].name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},F
=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=BN();}return function(){superclass.call(this);};},K=Symbol("teavm_meta"),BE=cls=>{if(cls[K].classObject===null){cls[K].classObject=HD(cls);}return cls[K].classObject;},BN=()=>E,Hh=()=>{{return Ba();}},Ev=t=>{{return Bu(t);}},R=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},Ec=source=>{return Object.assign({name:null,binaryName:null,parent:null,superinterfaces:[],modifiers:0,primitiveKind
:0,itemType:null,arrayType:null,enclosingClass:null,declaringClass:null,simpleName:null,clinit:()=>{},constructor:null,enumConstants:()=>null,resolvedEnumConstants:null,reflection:null,classObject:null,assignableCache:null,valueToObject:o=>o,objectToValue:o=>o},source||{});},Bw=(name,binaryName,kind,config)=>{let cls=()=>{};let meta=Ec({name:name,binaryName:binaryName,modifiers:1|1<<4,primitiveKind:kind});cls[K]=meta;if(typeof config==='function'){config(meta);}return cls;},Iw=Bw("boolean","Z",1,meta=>{}),G1
=Bw("byte","B",2,meta=>{}),HM=Bw("short","S",3,meta=>{}),FK=Bw("char","C",4,meta=>{}),E2=Bw("int","I",5,meta=>{{meta.valueToObject=o=>BA(o);}{meta.objectToValue=o=>Fw(o);}}),DA=Bw("float","F",7,meta=>{}),IL=Bw("void","V",9),Df=(a,b)=>a===b?0:a<b? -1:1,CY=(a,b)=>a===b?0:a>b?1: -1,S=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},DF=(a,b)=>(a>>>0)/(b>>>0)>>>0,J5=(a,b)=>(a>>>0)%(b>>>0)>>>0,Dg=(a,b)=>{a>>>=0;b>>>=0;return a
<b? -1:a>b?1:0;},B0=BigInt(0),B1=val=>BigInt.asIntN(64,BigInt(val|0)),FM=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),DT=val=>Number(val),GZ=(a,b)=>a>b,G5=(a,b)=>a>=b,Hg=(a,b)=>a<b,EM=(a,b)=>BigInt.asIntN(64,a+b),I4=(a,b)=>BigInt.asIntN(64,a -b),JE=(a,b)=>BigInt.asIntN(64,a/b),P=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bc(cls))(data);},Jm=(cls,data)=>new (Bc(cls))(data),Iv=(cls,sz)=>new (Bc(cls))(new Array(sz)),BI=sz=>new Je(new Uint16Array(sz)),BS=sz=>new Ja(new Int8Array(sz)),Hn
=sz=>new JS(new Int16Array(sz)),CU=sz=>new F_(new Int32Array(sz)),I7=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new F_(buffer);},GR=sz=>new JJ(new Int8Array(sz)),Bq=sz=>new EB(new Float32Array(sz));
let I0=data=>{let buffer=new Float32Array(data.length);buffer.set(data);return new EB(buffer);},Bc=cls=>{let result=cls[K].arrayType;if(result===null){function JavaArray(data){(BN()).call(this);this.data=data;}JavaArray.prototype=Object.create((BN()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.fi
=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bc(this.type))(dataCopy);};let name="["+cls[K].binaryName;JavaArray[K]=Ec({name:name,binaryName:name,parent:BN(),itemType:cls});result=JavaArray;cls[K].arrayType=JavaArray;}return result;},J4=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if
(first>0){for(let i=0;i<first;i=i+1|0){cls=Bc(cls);}if(first===dimensions.length -1){return P(cls,dimensions[first]);}}let arrays=new Array(FB(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=P(cls,firstDim);}return E$(cls,arrays,dimensions,first,0);},IT=dimensions=>{let arrays=new Array(FB(dimensions,0));if(arrays.length===0){return J4(DA,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=Bq(firstDim);}return E$(DA,arrays,
dimensions,0);},FB=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=start+2;i<dimensions.length;i=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},E$=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=Bc(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=Iv(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex+1|0;}limit
=packedIndex;}return arrays[0];};
function JC(array){return array.data.length;}
let DP,HH=strings=>{Ju();DP=new Array(strings.length);for(let i=0;i<strings.length;++i){DP[i]=EN(Be(strings[i]));}},D=index=>DP[index],Fu=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Be=str=>str===null?null:FW(str),BT=str=>str===null?null:str.cL,Ju=()=>BW(),EN;
{EN=str=>str;}let Cw=(from,to)=>{if(from===to){return true;}let map=from[K].assignableCache;if(map===null){map=new Map();from[K].assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to[K].itemType!==null){let result=from[K].itemType!==null&&Cw(from[K].itemType,to[K].itemType);map.set(to,result);return result;}let parent=from[K].parent;if(parent!==null&&parent!==from){if(Cw(parent,to)){map.set(to,true);return true;}}let superinterfaces=from[K].superinterfaces;for
(let i=0;i<superinterfaces.length;i=i+1|0){if(Cw(superinterfaces[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},J=ex=>{throw E5(ex);},BH=Symbol("javaException"),E5=ex=>{if(!ex.$jsException){Fm(ex);}return ex.$jsException;},Fm=ex=>{let javaCause=Kb(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Br("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[BH]
=ex;ex.$jsException=err;GD(err,ex);},GD=(err,ex)=>{if(typeof Hi==="function"&&err.stack){let stack=Hi(err.stack);let javaStack=P(HA(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Jc(Be(element.className),Be(element.methodName),Be(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){HP(ex,javaStack);}}},Br;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Br=function Br(message,cause){let self=Reflect.construct(Error,[void 0,cause],Br);Object.setPrototypeOf(self,Br.prototype);self[defaultMessage]=message;return self;}
;Br.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Br},message:{get(){try {let javaException=this[BH];if(typeof javaException==='object'){let javaMessage=IF(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Br=Error;}let IM=e=>e instanceof Error&&typeof e[BH]==='object'?e[BH]:null,U=err=>
{let ex=err[BH];if(!ex){ex=IY(Be("(JavaScript) "+err.toString()));err[BH]=ex;ex.$jsException=err;GD(err,ex);}return ex;},IY=message=>JV(message),IF=t=>J$(t),Kb=t=>Kd(t),HA=()=>BN(),Jc=(className,methodName,fileName,lineNumber)=>{{return null;}},HP=(e,stack)=>{},F8=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},Iy=typeof $rt_putStdoutCustom
==="function"?$rt_putStdoutCustom:typeof console==="object"?F8(msg=>console.info(msg)):()=>{},HU=typeof $rt_putStderrCustom==="function"?$rt_putStderrCustom:typeof console==="object"?F8(msg=>console.error(msg)):()=>{},EC=null,HW=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}EC=packages;},HK=[],C9=data=>{let packages=EC;let i=0;while(i<data.length){let cls=data[i++];HK.push(cls);let m
=Ec();cls[K]=m;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.parent=superclass!==0?superclass:null;m.superinterfaces=data[i++];if(m.parent){cls.prototype=Object.create(m.parent.prototype);}else {cls.prototype={};}cls.prototype.constructor=cls;m.modifiers=data[i++];m.primitiveKind=0;let innerClassInfo=data[i++];if(innerClassInfo!==0){let enclosingClass
=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];m.clinit=clinit!==0?()=>{m.clinit=()=>{};clinit();}:()=>{};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for
(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}}};
function X(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
X.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};X.prototype.s=X.prototype.push;X.prototype.pop=function(){return this.stack.pop();};X.prototype.l=X.prototype.pop;X.prototype.isResuming=function(){return this.status===2;};X.prototype.isSuspending=function(){return this.status===1;};X.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};X.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(Cf!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};X.prototype.resume=function(){if(Cf!==null){throw new Error("Another thread is running");}this.status=2;this.run();};X.prototype.run=function(){Cf=this;let result;try {result=this.runner();}catch(e){result=e;}finally {Cf=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let HY=()=>{let thread=B5();return thread!=null&&thread.isSuspending();},Is=()=>{let thread=B5();return thread!=null&&thread.isResuming();},IH=()=>{let nativeThread=B5();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},Fx=(runner,callback)=>
(new X(runner)).start(callback),Cf=null,B5=()=>Cf,HB=()=>{throw new Error("Invalid recorded state");};
function E(){this.cK=null;this.$id$=0;}
let Em=b=>{let c,d;if(Ba()===null)return;if(b.cK===null)C3(b);c=b.cK;d=c.cN;if(d===null)c.cN=Ba();else if(d!==Ba()){c=new Ff;DG(c,D(0));J(c);}b=b.cK;b.cP=b.cP+1|0;},BR=b=>{let c,d;if(Ba()===null)return;if(!Cr(b)&&b.cK.cN===Ba()){c=b.cK;d=c.cP-1|0;c.cP=d;if(!d)c.cN=null;Cr(b);return;}b=new CI;L(b);J(b);},Kl=b=>{let c,d,$p,$z;$p=0;if(Is()){let $T=B5();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;if(b.cK===null)C3(b);d=b.cK;if(d.cN===null)d.cN=Ba();if(b.cK.cN===Ba()){b=b.cK;b.cP=b.cP
+c|0;return;}$p=1;case 1:HZ(b,c);if(HY()){break _;}return;default:HB();}}B5().s(b,c,d,$p);},C3=b=>{let c;c=new GC;c.cN=Ba();b.cK=c;},JX=(b,c,d)=>{let e,f,g,h,i,j,k,l,m;e=Ba();f=b.cK;if(f===null){C3(b);Bu(e);b=b.cK;b.cP=b.cP+c|0;b=null;CT(d,b);return;}if(f.cN===null){f.cN=e;Bu(e);b=b.cK;b.cP=b.cP+c|0;b=null;CT(d,b);return;}if(f.c7===null){g=new F5;g.c5=P(E,9);f.c7=g;}f=f.c7;g=new EX;g.er=e;g.es=b;g.eo=c;g.ep=d;b=f;c=b.c_;h=b.dk;c=(c>=h?c-h|0:(b.c5.data.length-h|0)+c|0)+1|0;h=b.c5.data.length;if(c>=h){c=Cj(h*
2|0,((c*3|0)/2|0)+1|0);if(c<1)c=2147483647;i=P(E,c);c=0;h=b.dk;j=b.c_;if(h<=j){k=i.data;while(h<j){l=c+1|0;k[c]=b.c5.data[h];h=h+1|0;c=l;}}else{k=i.data;while(true){m=b.c5.data;if(h>=m.length)break;l=c+1|0;k[c]=m[h];h=h+1|0;c=l;}h=0;while(h<j){l=c+1|0;k[c]=m[h];h=h+1|0;c=l;}}b.dk=0;b.c_=c;b.c5=i;}i=b.c5.data;c=b.c_;i[c]=g;b.c_=Ge(c,i.length);b.dL=b.dL+1|0;},Km=b=>{let c,d;if(!Cr(b)&&b.cK.cN===Ba()){c=b.cK;d=c.cP-1|0;c.cP=d;if(d<=0){c.cN=null;c=c.c7;if(c!==null&&!DB(c)){c=new Gm;c.en=b;EE(c);}else Cr(b);}return;}b
=new CI;L(b);J(b);},Cr=a=>{let b,c;b=a.cK;if(b===null)return 1;a:{if(b.cN===null){c=b.c7;if(!(c!==null&&!DB(c))){b=b.ec;if(b===null)break a;if(b.k())break a;}}return 0;}a.cK=null;return 1;},Hy=a=>{return;},Ka=()=>{let a=new E();Hy(a);return a;},BM=a=>{return BE(Ic(a));},Ic=a=>{return a.constructor;},Jk=a=>{let b,c,d,e,f,g,h,i,j,k;b=a;if(!b.$id$)b.$id$=I9();c=a.$id$;B2();if(!c)d=D(1);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;h=g>>>4|0;if(!h)h=g;else f=f|4;e=h>>>2|0;if
(!e)e=h;else f=f|2;if(e>>>1|0)f=f|1;e=(32-f|0)-1|0;}i=(((32-e|0)+4|0)-1|0)/4|0;j=BI(i);k=j.data;i=(i-1|0)*4|0;e=0;while(i>=0){h=e+1|0;k[e]=Ed((c>>>i|0)&15,16);i=i-4|0;e=h;}d=Ez(j);}b=Bz();Bl(Bl(b,D(2)),d);return BO(b);},DX=a=>{let b,c;b=a.cK;if(!(b!==null&&b.cN===Ba()?1:0)){b=new CI;L(b);J(b);}b=a.cK.ec;if(b===null)return;while(!b.k()){c=b.r();if(!c.s())EE(c);}a.cK.ec=null;},HZ=(b,c)=>{let thread=IH();let javaThread=Hh();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error)
{throw result;}return result;}let callback=function(){};callback.h=val=>{thread.attribute=val;Ev(javaThread);thread.resume();};callback.bI=e=>{thread.attribute=E5(e);Ev(javaThread);thread.resume();};callback=J7(callback);thread.suspend(()=>{try {JX(b,c,callback);;}catch($e){callback.bI($e);}});return null;},By=F(0),Cl=F(0),DL=F(0);
function Z(){E.call(this);this.dH=0;}
let IJ=null,ET=null,Hw=null,BW=()=>{BW=Y(Z);Il();},H0=(a,b)=>{BW();a.cL=Fu(b.data,0,b.data.length);},Ez=a=>{let b=new Z();H0(b,a);return b;},Ig=(a,b)=>{a.cL=b;},FW=a=>{let b=new Z();Ig(b,a);return b;},CL=(a,b)=>{let c;if(b>=0&&b<a.cL.length)return a.cL.charCodeAt(b);c=new CQ;L(c);J(c);},Bt=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof Z))return 0;c=b;return a.cL!==c.cL?0:1;},Iq=a=>{let b;a:{if(!a.dH){b=0;while(true){if(b>=a.cL.length)break a;a.dH=(31*a.dH|0)+a.cL.charCodeAt(b)|0;b=b+1|0;}}}return a.dH;},Il
=()=>{let b;IJ=BI(0);b=new Z;BW();b.cL="";ET=b;Hw=new FD;},D_=F();
function B6(){D_.call(this);this.dm=0;}
let HJ=null,C0=null,B2=()=>{B2=Y(B6);Ht();},G0=(a,b)=>{B2();a.dm=b;},Fj=a=>{let b=new B6();G0(b,a);return b;},BA=b=>{let c,d;B2();if(b>=(-128)&&b<=127){a:{if(C0===null){C0=P(B6,256);c=0;while(true){d=C0.data;if(c>=d.length)break a;d[c]=Fj(c-128|0);c=c+1|0;}}}return C0.data[b+128|0];}return Fj(b);},Fw=a=>{return a.dm;},Hk=a=>{let b;b=a.dm;B2();return b;},Jx=(a,b)=>{if(a===b)return 1;return b instanceof B6&&b.dm==a.dm?1:0;},Ht=()=>{HJ=BE(E2);};
function Dr(){let a=this;E.call(a);a.cO=null;a.cW=0;}
let CG=(a,b,c)=>{let d,e,f,g;d=a.cW;e=d-b|0;d=(d+c|0)-b|0;GG(a,d);f=e-1|0;while(f>=0){g=a.cO.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.cW=a.cW+(c-b|0)|0;},DD=F(0),EI=F(Dr),Jj=a=>{a.cO=BI(16);},Bz=()=>{let a=new EI();Jj(a);return a;},Bl=(a,b)=>{let c,d,e,f,g,h;c=a.cW;d=a;b=b===null?D(3):b;e=d;if(c>=0&&c<=e.cW){a:{if(b===null)b=D(3);else if(b.cL.length?0:1)break a;f=e.cW+b.cL.length|0;GG(e,f);f=e.cW-1|0;while(f>=c){e.cO.data[f+b.cL.length|0]=e.cO.data[f];f=f+(-1)|0;}e.cW=e.cW+b.cL.length|0;f=0;while(f<b.cL.length)
{g=e.cO.data;h=c+1|0;g[c]=CL(b,f);f=f+1|0;c=h;}}return a;}b=new CQ;Gf(b);J(b);},Dj=(a,b)=>{let c,d,e,f,g,h,i,j;c=a.cW;d=1;if(b<0){d=0;b= -b|0;}a:{if(Dg(b,10)<0){if(d)CG(a,c,c+1|0);else{CG(a,c,c+2|0);e=a.cO.data;f=c+1|0;e[c]=45;c=f;}a.cO.data[c]=Ed(b,10);}else{g=1;h=1;f=DF((-1),10);b:{while(true){i=g*10|0;if(Dg(i,b)>0){i=g;break b;}h=h+1|0;if(Dg(i,f)>0)break;g=i;}}if(!d)h=h+1|0;CG(a,c,c+h|0);if(d)f=c;else{e=a.cO.data;f=c+1|0;e[c]=45;}while(true){if(!i)break a;e=a.cO.data;j=f+1|0;e[f]=Ed(DF(b,i),10);b=J5(b,i);i
=DF(i,10);f=j;}}}return a;},EK=(a,b)=>{let c,d;c=a.cW;d=a;CG(d,c,c+1|0);d.cO.data[c]=b;return a;},BO=a=>{let b,c,d,e,f;b=new Z;c=a.cO;d=c.data;e=a.cW;BW();f=d.length;if(e>=0&&e<=(f-0|0)){b.cL=Fu(c.data,0,e);return b;}b=new Bd;L(b);J(b);},GG=(a,b)=>{let c,d,e,f;c=a.cO.data.length;if(c<b){b=c>=1073741823?2147483647:Cj(b,Cj(c*2|0,5));d=a.cO.data;e=BI(b);f=e.data;b=Dk(b,d.length);c=0;while(c<b){f[c]=d[c];c=c+1|0;}a.cO=e;}};
function Bg(){let a=this;E.call(a);a.d5=null;a.d4=null;a.ee=0;a.el=0;a.ff=null;}
let HO=a=>{return a;},Do=a=>{Fm(a);},J$=a=>{return a.d5;},Kh=a=>{return a.d5;},Kd=a=>{let b;b=a.d4;if(b===a)b=null;return b;},CM=a=>{let b;if(C2===null){b=new EU;Gn(b);C2=b;}Gz(a,C2);},Gz=(a,b)=>{let c,d,e,f,g,h,i;c=GB(BM(a));d=b;BL(d,c);e=a.d5;if(e!==null){c=Bz();Bl(Bl(c,D(4)),e);BL(d,BO(c));}a:{c=b;BL(c,D(5));f=a.ff;if(f!==null){f=f.data;g=f.length;h=0;while(true){if(h>=g)break a;e=f[h];BL(d,D(6));i=D(3);if(e!==null)i=e.q();Fd(c,i);h=h+1|0;}}}c=a.d4;if(c!==null&&c!==a){BL(d,D(7));Gz(a.d4,b);}},Bv=F(Bg),O=
F(Bv),L=a=>{Do(a);a.ee=1;a.el=1;},Kg=()=>{let a=new O();L(a);return a;},DG=(a,b)=>{Do(a);a.ee=1;a.el=1;a.d5=b;},JV=a=>{let b=new O();DG(b,a);return b;},B3=F(),H7=F(B3),Hq=(a,b)=>{switch(a.primitiveKind){default:return P(a,b);}},HV=F(B3),E8=F(0),GJ=F(0),Ey=F(0);
function Fk(){let a=this;E.call(a);a.e4=0;a.c3=null;a.eq=null;}
let HD=b=>{let c;c=new Fk;c.c3=b;return c;},GB=a=>{let b,c,d,e,f;b=a.e4;if(!(b&1)){a.e4=b|1;c=a.c3[K].name;d=c===null?null:Be(c);if(d===null){e=a.c3[K].itemType;if(e!==null){f=GB(BE(e));if(f!==null){if(e[K].itemType!==null){c=Bz();Bl(EK(c,91),f);d=BO(c);}else{c=Bz();EK(Bl(Bl(c,D(8)),f),59);d=BO(c);}}}}a.eq=d;}return a.eq;},CJ=a=>{return !a.c3[K].primitiveKind?0:1;},C$=a=>{let b;b=a.c3[K].itemType;return b===null?null:BE(b);},Dx=F(0);
function En(){let a=this;E.call(a);a.eB=0;a.eA=0;a.eZ=null;a.d9=null;a.dq=null;a.dE=null;a.c8=null;a.dQ=B0;a.dr=0;}
let BK=null,G=null,W=null,Ci=0,Ct=0,Ca=0,Eq=null,GM=null,BG=null,Cq=null,EO=null,Dm=null,Cz=null,CA=null,Cv=null,Bx=null,DQ=null,M=()=>{M=Y(En);G_();},Jf=a=>{let b,c,d,e,f,g,h,i,j,k,l;a.eZ=I0([0.054901961237192154,0.04313725605607033,0.03921568766236305,1.0]);b=H3(window.document.getElementById("canvas"));G=If(b);E4(a,window.innerWidth,window.innerHeight);c=window;d=Hj(a);c.addEventListener("resize",Q(I(d),"handleEvent"));JT();IU();d=Ha(b);b.addEventListener("click",Q(I(d),"handleEvent"));e=G.createShader(35633);G.shaderSource(e,
"attribute vec3 aPosition; attribute vec2 aTexCoord; attribute vec3 aColor; uniform mat4 uProj; uniform mat4 uModl; varying vec2 vTexCoord; varying vec3 vColor; varying float vFogDist; void main() { vec4 pos = uModl * vec4(aPosition, 1.0); gl_Position = uProj * pos; vTexCoord = aTexCoord; vColor = aColor; vFogDist = length(pos.xyz); }");G.compileShader(e);f=G.createShader(35632);G.shaderSource(f,"precision highp float; varying vec2 vTexCoord; varying vec3 vColor; varying float vFogDist; uniform sampler2D uTex; uniform bool uHasTexture; uniform bool uHasColor; uniform vec4 uFogColor; uniform float uAlpha; uniform bool uUseFog; void main() { vec4 col = vec4(1.0); if(uHasColor) col *= vec4(vColor, 1.0); if(uHasTexture) col *= texture2D(uTex, vTexCoord); col.a *= uAlpha; if(uUseFog) { float fogFactor = exp(-0.02 * vFogDist); fogFactor = clamp(fogFactor, 0.0, 1.0); gl_FragColor = mix(uFogColor, col, fogFactor); } else { gl_FragColor = col; } }");G.compileShader(f);c
=G.createProgram();W=c;G.attachShader(c,e);d=G;c=W;d.attachShader(c,f);d=G;c=W;d.linkProgram(c);d=G;c=W;d.useProgram(c);Ci=G.getAttribLocation(W,"aPosition");Ct=G.getAttribLocation(W,"aTexCoord");Ca=G.getAttribLocation(W,"aColor");Eq=G.getUniformLocation(W,"uProj");GM=G.getUniformLocation(W,"uModl");BG=G.getUniformLocation(W,"uHasTexture");Cq=G.getUniformLocation(W,"uHasColor");EO=G.getUniformLocation(W,"uFogColor");Dm=G.getUniformLocation(W,"uAlpha");Cz=G.getUniformLocation(W,"uUseFog");c=G.createBuffer();DQ
=c;G.bindBuffer(34963,c);g=Hn(450000).data;h=0;i=0;while(h<300000){j=h<<16>>16;g[i]=j;g[i+1|0]=(h+1|0)<<16>>16;k=i+2|0;l=(h+2|0)<<16>>16;g[k]=l;g[i+3|0]=j;g[i+4|0]=l;g[i+5|0]=(h+3|0)<<16>>16;h=h+4|0;i=i+6|0;}h=g.length;c=new Int16Array(h);j=0;while(j<h){i=g[j];c[j]=i;j=j+1|0;}G.bufferData(34963,c,35044);G.clearColor(0.5,0.800000011920929,1.0,1.0);G.clearDepth(1.0);G.enable(2929);G.depthFunc(515);CV(5889);C1();CV(5888);d=IO(256,256,64);a.dq=d;a.dE=Io(d);a.c8=Jl(a.dq);Fo(1);},CV=b=>{M();Bx=b!=5889?Cv:CA;},C1=
()=>{let b,c,d;M();b=0;while(b<16){c=Bx;d=b%5|0?0.0:1.0;c.data[b]=d;b=b+1|0;}},FT=(b,c,d)=>{let e;M();e=Bx.data;e[12]=e[12]+e[0]*b+e[4]*c+e[8]*d;e[13]=e[13]+e[1]*b+e[5]*c+e[9]*d;e[14]=e[14]+e[2]*b+e[6]*c+e[10]*d;e[15]=e[15]+e[3]*b+e[7]*c+e[11]*d;},E1=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x;M();f=Cp(b);g=CH(f);h=B$(f);i=1.0-g;j=c*c*i+g;k=d*c*i;l=e*h;m=k+l;b=c*e*i;n=d*h;o=b-n;p=k-l;q=d*d*i+g;d=d*e*i;c=c*h;r=d+c;k=b+n;l=d-c;s=e*e*i+g;t=Bq(16);u=t.data;Fp(Bx,0,t,0,16);v=0;while(v<4){t=Bx.data;b=u[v]
*j;w=v+4|0;b=b+u[w]*m;x=v+8|0;t[v]=b+u[x]*o;t[w]=u[v]*p+u[w]*q+u[x]*r;t[x]=u[v]*k+u[w]*l+u[x]*s;v=v+1|0;}},IR=(b,c,d,e)=>{let f,g;M();f=1.0/Hr(b*3.141592653589793/360.0);C1();g=Bx.data;g[0]=f/c;g[5]=f;b=e+d;c=d-e;g[10]=b/c;g[11]=(-1.0);g[14]=2.0*e*d/c;g[15]=0.0;},HE=()=>{let b,c,d;M();b=G;c=Eq;d=CA;b.uniformMatrix4fv(c,!!0,d.data);b=G;c=GM;d=Cv;b.uniformMatrix4fv(c,!!0,d.data);},Ft=a=>{let b,c,d,e,f,g,h;if(Bb(1)){E3(a.dq);return;}b=a.d9;c=Gj();d=I4(c,b.d8);b.d8=c;if(Hg(d,B0))d=B0;if(GZ(d,B1(1000000000)))d=B1(1000000000);b.et
=DT(JE(B1(1000000000),d));e=b.dR+DT(d)*b.ez*b.eW/1.0E9;b.dR=e;f=e|0;b.d7=f;if(f>100)b.d7=100;e=e-b.d7;b.dR=e;b.ev=e;f=0;while(true){b=a.d9;if(f>=b.d7)break;J6(a.c8);f=f+1|0;}JQ(a,b.ev);a.dr=a.dr+1|0;while(G5(Cx(),EM(a.dQ,B1(1000)))){if(Du===null){b=new EZ;Gn(b);Du=b;}g=Du;f=a.dr;BB();h=Ce;b=Bz();Dj(Bl(Dj(b,f),D(9)),h);b=BO(b);Fd(g,b);Ce=0;a.dQ=EM(a.dQ,B1(1000));a.dr=0;}window;b=new Da;b.eO=a;requestAnimationFrame(Q(I(b),"onAnimationFrame"));},HT=(a,b)=>{let c,d,e,f;FT(0.0,0.0,(-0.30000001192092896));E1(a.c8.c9,
1.0,0.0,0.0);E1(a.c8.da,0.0,1.0,0.0);c=a.c8;d=c.ex;d=d+(c.dz-d)*b;e=c.ew;e=e+(c.dA-e)*b;f=c.eH;f=f+(c.dB-f)*b;FT( -d, -e, -f);},JQ=(a,b)=>{let c,d,e,f,g,h,i,j;V();c=BQ|0;BQ=0.0;d=c;c=BP|0;BP=0.0;e=c;f=a.c8;f.da=f.da+d*0.15;d=f.c9-e*0.15;f.c9=d;if(d<(-90.0))f.c9=(-90.0);if(f.c9>90.0)f.c9=90.0;JL(a.dE,f);while(true){a:{Cc=null;if(!EG(Bs)){f=I(EY(Bs,0));Cc=f;if(f!==null){c=1;break a;}}c=0;}if(!c)break;if(GE()==1&&Fq()){M();f=BK;if(f!==null)E6(a.dq,f.dX,f.dY,f.dZ,0);}if(GE())continue;if(!Fq())continue;M();f=BK;if
(f===null)continue;c=f.dX;g=f.dY;h=f.dZ;i=f.eb;if(!i)g=g+(-1)|0;if(i==1)g=g+1|0;if(i==2)h=h+(-1)|0;if(i==3)h=h+1|0;if(i==4)c=c+(-1)|0;if(i==5)c=c+1|0;E6(a.dq,c,g,h,1);}while(true){b:{Bh();Co=null;if(!EG(BD)){f=I(EY(BD,0));Co=f;if(f!==null){c=1;break b;}}c=0;}if(!c)break;f=Co;if((f===null?(-1):DH(f.which))!=28)continue;if(!JG())continue;E3(a.dq);}M();G.clear(16640);CV(5889);C1();IR(70.0,a.eB/a.eA,0.10000000149011612,1000.0);CV(5888);C1();HT(a,b);HE();G.uniform1i(Cq,1);G.uniform1i(BG,1);G.enable(2884);G.uniform1i(Cz,
0);Gp(a.dE,a.c8,0);G.uniform1i(Cz,1);G.uniform4f(EO,0.0,0.0,0.0,1.0);Gp(a.dE,a.c8,1);G.uniform1i(BG,0);f=BK;if(f!==null)He(a.dE,f);f=G;j=Cz;f.uniform1i(j,0);},E4=(a,b,c)=>{let d,e;a.eB=b;a.eA=c;d=window.document.getElementById("canvas");e=b;d.width=e;e=c;d.height=e;M();G.viewport(0,0,b,c);},IQ=b=>{let c,d,e;M();c=new B9;d=new En;d.eZ=Bq(4);e=new EW;e.ez=1.0;e.et=0.0;e.dR=0.0;e.eW=60.0;e.d8=Gj();d.d9=e;Bo();Ei(c,d,null);d=new GX;d.eE=c;Jv(d);},G_=()=>{let b;BK=null;CA=Bq(16);b=Bq(16);Cv=b;Bx=b;},If=b=>{return b.getContext('webgl',
{antialias:false});},Jg=F(),Jv=b=>{setTimeout(()=>{Jy(FC)(b);},0);},FC=b=>{b.bu();},EE=b=>{Hm(b,0);},Hm=(b,c)=>{setTimeout(()=>{FC(b);},c);},JN=F(),Q=(b,c)=>{if(b===null||b===undefined){return null;}let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},J9=F();
function B9(){let a=this;E.call(a);a.fd=null;a.fc=B0;a.e9=B0;a.dV=null;a.d3=null;a.e$=null;a.dN=0;a.e3=null;}
let CW=null,Cb=null,DR=0,Bk=0,F6=null,Bo=()=>{Bo=Y(B9);IG();},Ei=(a,b,c)=>{let d;Bo();a.dV=new E;a.dN=1;a.e$=c;a.e3=b;d=DR;DR=d+1|0;a.fc=B1(d);},Kk=(a,b)=>{let c=new B9();Ei(c,a,b);return c;},Bu=b=>{Bo();if(Cb!==b)Cb=b;Cb.e9=Cx();},IB=a=>{let b,$$je;b=a.e3;if(b!==null){b=b;a:{b:{try{Jf(b);break b;}catch($$e){$$je=U($$e);if($$je instanceof Bv){b=$$je;}else{throw $$e;}}CM(b);break a;}b.dQ=Cx();b.dr=0;Ft(b);}}},Ba=()=>{Bo();return Cb;},IE=a=>{let b;b=a.fd;if(b!==null)return b;Bo();return F6;},IG=()=>{let b;b=new B9;Bo();Ei(b,
null,D(10));CW=b;Cb=b;DR=1;Bk=1;F6=new GF;},F9=F(0),FD=F(),DU=F(),HI=null,Jn=null,Db=()=>{Db=Y(DU);H_();},Ed=(b,c)=>{Db();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},H_=()=>{HI=BE(FK);Jn=P(DU,128);};
function EW(){let a=this;E.call(a);a.eW=0.0;a.d8=B0;a.d7=0;a.ev=0.0;a.ez=0.0;a.et=0.0;a.dR=0.0;}
let HX=F();
function Ek(){E.call(this);this.eY=null;}
let HF=(a,b)=>{a.eY=b;},B7=a=>{let b=new Ek();HF(b,a);return b;},Bf=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Be(typeof b);d=!Bt(c,D(11))&&!Bt(c,D(12))?0:1;Ch();e=Eu;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);e.set(b,new WeakRef(h));return h;}if(Bt(c,D(13))){i=CX;j=Et;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);k=h;i.set(b,new WeakRef(k));j.register(k,
b);return h;}if(Bt(c,D(14))){l=CO;m=ED;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(Bt(c,D(15))){f=E_;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=B7(b);E_=new WeakRef(h);return h;}}return B7(b);},I=b=>{if(b===null)return null;return !(b instanceof Ek)?b:b.eY;},I1=F(),Du=null,C2=null,Kf=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n;if(b!==null&&d!==null){if(c>=0&&e>=0&&f>=0&&(c
+f|0)<=CR(b)&&(e+f|0)<=CR(d)){a:{b:{if(b!==d){g=C$(BM(b));h=C$(BM(d));if(g!==null&&h!==null){if(g===h)break b;if(!CJ(g)&&!CJ(h)){i=b;j=0;k=c;while(j<f){c:{l=i.data;m=k+1|0;n=l[k];if(n!==null){n=BM(n);if(Cw(n.c3,h.c3)){k=1;break c;}}k=0;}if(!k){CS(b,c,d,e,j);b=new CK;L(b);J(b);}j=j+1|0;k=m;}CS(b,c,d,e,f);return;}if(!CJ(g))break a;if(CJ(h))break b;else break a;}b=new CK;L(b);J(b);}}CS(b,c,d,e,f);return;}b=new CK;L(b);J(b);}b=new Bd;L(b);J(b);}d=new C_;DG(d,D(16));J(d);},Fp=(b,c,d,e,f)=>{if(c>=0&&e>=0&&f>=0&&(c
+f|0)<=CR(b)&&(e+f|0)<=CR(d)){CS(b,c,d,e,f);return;}b=new Bd;L(b);J(b);},CS=(b,c,d,e,f)=>{if(f!==0){if(typeof b.data.buffer!=='undefined'){d.data.set(b.data.subarray(c,c+f),e);}else if(b!==d||e<c){for(let i=0;i<f;i=i+1|0){d.data[e++]=b.data[c++];}}else {c=c+f|0;e=e+f|0;for(let i=0;i<f;i=i+1|0){d.data[ --e]=b.data[ --c];}}}},Cx=()=>{return FM((new Date()).getTime());},Gj=()=>{return FM(performance.now()*1000000.0);},Fg=F(0),GF=F(),Ih=(a,b,c)=>{CM(c);},Bd=F(O),Gf=a=>{L(a);},Kj=()=>{let a=new Bd();Gf(a);return a;},Cm
=F(0);
function GX(){E.call(this);this.eE=null;}
let Ir=a=>{let b,c,d,$$je;b=a.eE;a:{b:{c:{d:{try{Bo();Bk=Bk+1|0;Bu(b);b.d3=Ka();IB(b);}catch($$e){$$je=U($$e);if($$je instanceof Bg){c=$$je;break d;}else{c=$$je;break c;}}c=b.dV;Em(c);e:{try{DX(c);BR(c);break e;}catch($$e){$$je=U($$e);b=$$je;}BR(c);J(b);}b.dN=0;Bk=Bk-1|0;b.d3=null;Bu(CW);break a;}try{Ih(IE(b),b,c);break b;}catch($$e){$$je=U($$e);c=$$je;break c;}}d=b.dV;Em(d);f:{try{DX(d);BR(d);break f;}catch($$e){$$je=U($$e);b=$$je;}BR(d);J(b);}b.dN=0;Bk=Bk-1|0;b.d3=null;Bu(CW);J(c);}c=b.dV;Em(c);g:{try{DX(c);BR(c);break g;}
catch($$e){$$je=U($$e);b=$$je;}BR(c);J(b);}b.dN=0;Bk=Bk-1|0;b.d3=null;Bu(CW);}};
function GC(){let a=this;E.call(a);a.c7=null;a.ec=null;a.cN=null;a.cP=0;}
let CI=F(O),EV=F(0),Js=F(0),Jr=F(O),Ff=F(O);
function Gm(){E.call(this);this.en=null;}
let I2=a=>{let b,c,d,e,f;b=a.en;if(!Cr(b)){c=b.cK;if(c.cN===null){b=c.c7;if(b!==null&&!DB(b)){b=c.c7;d=b.dk;if(d==b.c_)e=null;else{f=b.c5.data;e=f[d];f[d]=null;b.dk=Ge(d,f.length);b.dL=b.dL+1|0;}if(e===null){b=new El;L(b);J(b);}e=e;c.c7=null;b=e;c=b.er;e=b.es;d=b.eo;b=b.ep;Bu(c);e=e.cK;e.cN=c;e.cP=e.cP+d|0;c=null;CT(b,c);}}}},F3=F(0);
function FO(){E.call(this);this.ek=null;}
let J7=b=>{let c;c=new FO;c.ek=b;return c;},CT=(a,b)=>{a.ek.h(b);},Jw=(a,b)=>{a.ek.bI(b);};
function EX(){let a=this;E.call(a);a.er=null;a.es=null;a.eo=0;a.ep=null;}
let E9=F(0),CN=F(0),B4=F(),EG=a=>{return a.c6?0:1;},EA=F(0),Eh=F(0),D9=F(0),BX=F(0);
function F5(){let a=this;B4.call(a);a.dL=0;a.c5=null;a.dk=0;a.c_=0;}
let DB=a=>{return a.dk!=a.c_?0:1;},Ge=(b,c)=>{b=b+1|0;if(b==c)b=0;return b;},IZ=F(),B$=b=>{return Math.sin(b);},CH=b=>{return Math.cos(b);},Hr=b=>{return Math.tan(b);},Cp=b=>{return b*3.141592653589793/180.0;},GA=b=>{return Math.sqrt(b);},Dy=b=>{return Math.floor(b);},Fh=()=>{return JM();},JM=()=>{return Math.random();},Dk=(b,c)=>{if(b<c)c=b;return c;},Cj=(b,c)=>{if(b>c)c=b;return c;},Iz=b=>{return Math.abs(b);},DE=b=>{return Iz(b);},CQ=F(Bd),GI=F(),F2=null,Gt=null,E7=null,FQ=0,Ep=0,GN=0,DC=0,BD=null,CP=null,EF
=0,FN=null,F1=null,Fv=null,Co=null,C5=null,Bh=()=>{Bh=Y(GI);Jq();},Ij=()=>{Bh();if(DC)return;DC=1;},JT=()=>{let b,c,d,$$je;Bh();a:{b:{try{if(!Ep)break b;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}return;}c:{try{if(DC)break c;Ij();break c;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}d:{try{c=window;d=HR();FN=I(d);c.addEventListener("keydown",Q(I(d),"handleEvent"));c=window;d=HN();F1=I(d);c.addEventListener("keyup",Q(I(d),"handleEvent"));c
=window;d=Jd();Fv=I(d);c.addEventListener("keypress",Q(I(d),"handleEvent"));Ep=1;b=BD;if(b===null)break d;Gi(b);break d;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}return;}J(GY(b));},Bb=b=>{Bh();return CP.data[b];},JG=()=>{let b;Bh();b=Co;return b===null?0:Bt(Be(b.type),D(17))?0:1;},DH=b=>{let c;Bh();c=C5.data;return b<=c.length&&b>=0?c[b]:(-1);},Jq=()=>{let b,c,d,e,f,g,h;F2=Jm(Z,[D(18),D(19),D(20),D(21),D(22),D(23),D(24),D(25),D(26),D(27),D(28),D(1),D(29),D(30),D(31),D(32),
D(33),D(34),D(35),D(36),D(37),D(38),D(39),D(40),D(41),D(42),D(43),D(44),D(45),D(46),D(47),D(48),D(49),D(50),D(51),D(52),D(53),D(54),D(55),D(56),D(57),D(58),D(59),D(60),D(61),D(62),D(63),D(64),D(65),D(66),D(67),D(68),D(69),D(70),D(71),D(72),D(73),D(74),D(75),D(76),D(77),D(78),D(79),D(80),D(81),D(82),D(83),D(84),D(85),D(86),D(87),D(88),D(89),D(90),D(91),D(92),D(93),D(94),D(95),D(96),D(97),D(98),D(99),D(100),D(101),D(101),D(101),D(102),D(103),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),
D(101),D(104),D(105),D(106),D(107),D(108),D(109),D(101),D(101),D(101),D(101),D(101),D(101),D(110),D(111),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(112),D(101),D(113),D(101),D(114),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(115),D(101),D(101),D(116),D(117),D(118),D(119),D(120),D(121),D(122),D(123),D(101),D(101),D(101),D(101),D(124),D(125),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(126),D(101),D(101),D(101),D(101),D(101),
D(101),D(101),D(101),D(101),D(101),D(101),D(127),D(101),D(128),D(101),D(129),D(130),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(101),D(131),D(132),D(101),D(133),D(134),D(135),D(101),D(136),D(101),D(137),D(101),D(138),D(139),D(140),D(141),D(142),D(101),D(101),D(101),D(101),D(101),D(101),D(143),D(144),D(145),D(146),D(147),D(148)]);Gt=P(Z,256);E7=FZ(253);Ep=0;GN=0;BD=Hd();CP=GR(256);EF=0;FN=null;F1=null;Fv=null;Co=null;C5=I7([(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),14,15,(-1),(-1),(-1),
28,(-1),(-1),42,29,56,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),1,(-1),(-1),(-1),(-1),57,210,201,207,199,203,200,205,208,205,208,(-1),(-1),210,211,211,11,2,3,4,5,6,7,8,9,10,(-1),(-1),(-1),(-1),(-1),(-1),(-1),30,48,46,32,18,33,34,35,23,36,37,38,50,49,24,25,16,19,31,20,22,47,17,45,21,44,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),12,52,53,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),
(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),39,13,51,12,52,53,(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),(-1),26,43,27,40]);b=0;c=F2.data;d=c.length;e=0;while(e<d){f=c[e];Gt.data[b]=f;g=E7;h=BA(b);CD(g,f,h);b=b+1|0;FQ=FQ+1|0;e
=e+1|0;}d=0;c=C5.data;b=c.length;e=0;while(e<b){if(Fw(BA(c[e]))!=(-1))d=d+1|0;e=e+1|0;}EF=d;},Bp=F(0),H3=b=>{return b;},FX=F(0);
function Da(){E.call(this);this.eO=null;}
let JO=(b,c)=>{c;Ft(b.eO);};
function CB(){let a=this;E.call(a);a.eI=null;a.ei=null;a.eJ=0;a.eD=0;a.eF=0;a.eK=0;a.eC=0;a.eG=0;a.d0=0;a.ds=null;a.dJ=null;a.dI=null;a.dW=null;}
let Gh=0,B8=null,CE=0,Ce=0,BB=()=>{BB=Y(CB);H9();},E0=(a,b)=>{let c,d,e,f,g,h,i,j,k;BB();c=CE;if(c!=2){a.d0=0;Ce=Ce+1|0;CE=c+1|0;if(I(a.ds.data[b])===null){d=a.ds.data;M();d[b]=Bf(G.createBuffer());a.dJ.data[b]=Bf(G.createBuffer());a.dI.data[b]=Bf(G.createBuffer());}Gw(B8);c=a.eJ;while(c<a.eK){e=a.eD;while(e<a.eC){f=a.eF;while(f<a.eG){if(Bj(a.ei,c,e,f)){g=a.ei;if(e!=((g.cY*2|0)/3|0)?1:0){BF();Fc(Gq,B8,g,b,c,e,f);}else{BF();Fc(Er,B8,g,b,c,e,f);}}f=f+1|0;}e=e+1|0;}c=c+1|0;}d=a.dW.data;g=B8;h=I(a.ds.data[b]);i
=I(a.dJ.data[b]);j=I(a.dI.data[b]);M();k=G;k.bindBuffer(34962,h);k.bufferData(34962,g.dl.subarray(0,g.cM*3|0),35044);k.bindBuffer(34962,i);k.bufferData(34962,g.du.subarray(0,g.cM*2|0),35044);k.bindBuffer(34962,j);k.bufferData(34962,g.dj.subarray(0,g.cM*3|0),35044);c=g.cM;Dh(g);d[b]=c;}},JU=(a,b)=>{let c;if(a.d0){E0(a,0);E0(a,1);}if(a.dW.data[b]>0){M();c=G;BB();DV(Gh);c.uniform1i(BG,1);c.uniform1i(Cq,1);c.bindBuffer(34962,I(a.ds.data[b]));c.vertexAttribPointer(Ci,3,5126,!!0,0,0);c.enableVertexAttribArray(Ci);c.bindBuffer(34962,
I(a.dJ.data[b]));c.vertexAttribPointer(Ct,2,5126,!!0,0,0);c.enableVertexAttribArray(Ct);c.bindBuffer(34962,I(a.dI.data[b]));c.vertexAttribPointer(Ca,3,5126,!!0,0,0);c.enableVertexAttribArray(Ca);c.bindBuffer(34963,DQ);c.drawElements(4,(a.dW.data[b]*6|0)/4|0,5123,0);}},H9=()=>{let b,c,d,e,f,g,h,i,j;b=D(149);Ck();if(Gu(CZ,b)===null?0:1)c=(Fy(CZ,b)).dm;else{c=Dw;Dw=c+1|0;M();d=G;e=d.createTexture();CD(DI,BA(c),Bf(e));CD(CZ,b,BA(c));DV(c);d.texParameteri(3553,10241,9728);d.texParameteri(3553,10240,9728);e=window.document.createElement("img");if
(b===D(150))f=1;else a:{f=0;if((f+D(150).cL.length|0)>b.cL.length)f=0;else{g=0;while(g<D(150).cL.length){h=CL(D(150),g);i=f+1|0;if(h!=CL(b,f)){f=0;break a;}g=g+1|0;f=i;}f=1;}}if(f){g=b.cL.length;f=b.cL.length;i=Df(1,g);if(!i)b=ET;else if(i<=0&&g<=f)b=FW(b.cL.substring(1,g));else{b=new CQ;L(b);J(b);}}e.src=BT(b);j=new C7;j.eN=c;j.eL=d;j.eM=e;e.addEventListener("load",Q(I(j),"handleEvent"));}Gh=c;B8=FH();CE=0;Ce=0;},C_=F(O),Gv=F(0),Fi=F(0),Gg=F(0),DJ=F();
function Dp(){DJ.call(this);this.fg=null;}
function Dl(){let a=this;Dp.call(a);a.fb=0;a.e_=null;a.fh=null;a.fe=null;}
let Cd=F(Dl),Gn=a=>{let b,c;b=null;c=null;a.fg=b;a.e_=Bz();a.fh=BI(32);a.fb=0;a.fe=c;},Fd=(a,b)=>{a.B(b);a.B(D(5));},EZ=F(Cd),Jt=(a,b)=>{if(b===null)b=D(3);Iy(BT(b));},EQ=F(0),D$=F();
function D7(){let a=this;D$.call(a);a.dC=0;a.c2=null;a.d2=0;a.e5=0.0;a.ef=0;}
let Hb=a=>{Ew(a,16);},GT=()=>{let a=new D7();Hb(a);return a;},Ew=(a,b)=>{let c;if(b<0){c=new B_;L(c);J(c);}b=FU(b);a.dC=0;a.c2=P(CC,b);a.e5=0.75;Gk(a);},FZ=a=>{let b=new D7();Ew(b,a);return b;},FU=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},Gk=a=>{a.ef=a.c2.data.length*a.e5|0;},Fy=(a,b)=>{let c;c=Gu(a,b);if(c===null)return null;return c.dP;},Gu=(a,b)=>{let c,d;if(b===null)c=GL(a);else{d=b.b2();c=Fb(a,b,d&(a.c2.data.length-1|
0),d);}return c;},Fb=(a,b,c,d)=>{let e,f;e=a.c2.data[c];while(e!==null){if(e.ea==d){f=e.em;if(b!==f&&!b.bz(f)?0:1)break;}e=e.dF;}return e;},GL=a=>{let b;b=a.c2.data[0];while(b!==null&&b.em!==null){b=b.dF;}return b;},CD=(a,b,c)=>{let d,e,f;if(b===null){d=GL(a);if(d===null){a.d2=a.d2+1|0;d=Gd(a,null,0,0);e=a.dC+1|0;a.dC=e;if(e>a.ef)Gy(a);}}else{e=b.b2();f=e&(a.c2.data.length-1|0);d=Fb(a,b,f,e);if(d===null){a.d2=a.d2+1|0;d=Gd(a,b,f,e);e=a.dC+1|0;a.dC=e;if(e>a.ef)Gy(a);}}b=d.dP;d.dP=c;return b;},Gd=(a,b,c,d)=>{let e,
f,g;e=new CC;f=null;e.em=b;e.dP=f;e.ea=d;g=a.c2.data;e.dF=g[c];g[c]=e;return e;},Gy=a=>{let b,c,d,e,f,g,h,i;b=a.c2.data.length;b=FU(!b?1:b<<1);c=P(CC,b);d=c.data;e=0;f=b-1|0;while(true){g=a.c2.data;if(e>=g.length)break;h=g[e];g[e]=null;while(h!==null){b=h.ea&f;i=h.dF;h.dF=d[b];d[b]=h;h=i;}e=e+1|0;}a.c2=c;Gk(a);},EP=F(0);
function Cg(){B4.call(this);this.cZ=0;}
let BC=(a,b)=>{let c,d,e,f;c=a.c6;d=a;if(c<0){b=new Bd;L(b);J(b);}d=Go(d,c);Fz(d);e=new F0;e.e0=b;b=d.dx;e.dg=b;f=d.dy;e.df=f;if(b!==null)b.df=e;else d.dp.dU=e;if(f!==null)f.dg=e;else d.dp.dG=e;d.dx=e;b=d.dp;b.c6=b.c6+1|0;c=b.cZ+1|0;b.cZ=c;d.dK=c;d.eg=null;return 1;},Dz=F(Cg),EY=(a,b)=>{let c,d,e,f,g,h,i,j,k;if(b<0){c=new Bd;L(c);J(c);}c=Go(a,b);Fz(c);d=c.dy;if(d===null){c=new El;L(c);J(c);}e=d.e0;c.eg=d;c.dx=d;f=d.df;c.dy=f;g=c.d6+1|0;c.d6=g;h=c.dp;i=d.dg;if(i===null)h.dU=f;else i.df=f;j=d.df;if(j===null)h.dG
=i;else j.dg=i;h.c6=h.c6-1|0;k=h.cZ+1|0;h.cZ=k;if(d===d){c.dx=!(f===null?0:1)?null:f.dg;c.d6=g-1|0;}else if(d===f){if(!(d===null?0:1))j=null;c.dy=j;}c.dK=k;c.eg=null;return e;};
function D6(){let a=this;Dz.call(a);a.dU=null;a.dG=null;a.c6=0;}
let Ke=a=>{return;},Hd=()=>{let a=new D6();Ke(a);return a;},Gi=a=>{a.dU=null;a.dG=null;a.c6=0;a.cZ=a.cZ+1|0;},Go=(a,b)=>{let c,d,e,f;if(b<0){c=new Bd;L(c);J(c);}d=a.c6;if(b<=(d/2|0)){e=a.dU;f=0;while(f<b){e=e.df;f=f+1|0;}return F7(a,e,e===null?null:e.dg,b);}if(b>d){c=new Bd;L(c);J(c);}c=a.dG;f=b;while(f<d){c=c.dg;f=f+1|0;}return F7(a,c===null?null:c.df,c,b);},FR=F(),CZ=null,DI=null,Dw=0,C4=0,Ck=()=>{Ck=Y(FR);HG();},DV=b=>{Ck();if(b!=C4){M();G.bindTexture(3553,I(Fy(DI,BA(b))));C4=b;}},HG=()=>{CZ=GT();DI=GT();Dw
=1;C4=(-9999999);};
function FP(){let a=this;E.call(a);a.dl=null;a.du=null;a.dj=null;a.cM=0;a.eU=0.0;a.eT=0.0;a.eV=0.0;a.eS=0.0;a.eR=0.0;a.dt=0;a.dD=0;a.ed=null;a.e6=null;a.e7=null;}
let J_=a=>{a.dl=new Float32Array(300000);a.du=new Float32Array(200000);a.dj=new Float32Array(300000);a.cM=0;a.dt=0;a.dD=0;},FH=()=>{let a=new FP();J_(a);return a;},Gl=a=>{let b;if(a.cM>0){M();b=G;if(a.ed===null){a.ed=b.createBuffer();a.e6=b.createBuffer();a.e7=b.createBuffer();}b.bindBuffer(34962,a.ed);b.bufferData(34962,a.dl.subarray(0,a.cM*3|0),35048);b.vertexAttribPointer(Ci,3,5126,!!0,0,0);b.enableVertexAttribArray(Ci);if(!a.dD)b.uniform1i(BG,0);else{b.bindBuffer(34962,a.e6);b.bufferData(34962,a.du.subarray(0,
a.cM*2|0),35048);b.vertexAttribPointer(Ct,2,5126,!!0,0,0);b.enableVertexAttribArray(Ct);b.uniform1i(BG,1);}if(!a.dt)b.uniform1i(Cq,0);else{b.bindBuffer(34962,a.e7);b.bufferData(34962,a.dj.subarray(0,a.cM*3|0),35048);b.vertexAttribPointer(Ca,3,5126,!!0,0,0);b.enableVertexAttribArray(Ca);b.uniform1i(Cq,1);}b.bindBuffer(34963,DQ);b.drawElements(4,(a.cM*6|0)/4|0,5123,0);}Dh(a);},Dh=a=>{a.cM=0;},Gw=a=>{Dh(a);a.dt=0;a.dD=0;},N=(a,b,c)=>{a.dD=1;a.eU=b;a.eT=c;},BU=(a,b,c,d)=>{a.dt=1;a.eV=b;a.eS=c;a.eR=d;},H=(a,b,c,
d)=>{let e;a.dl[(a.cM*3|0)+0|0]=b;a.dl[(a.cM*3|0)+1|0]=c;a.dl[(a.cM*3|0)+2|0]=d;if(a.dD){a.du[(a.cM*2|0)+0|0]=a.eU;a.du[(a.cM*2|0)+1|0]=a.eT;}if(a.dt){a.dj[(a.cM*3|0)+0|0]=a.eV;a.dj[(a.cM*3|0)+1|0]=a.eS;a.dj[(a.cM*3|0)+2|0]=a.eR;}e=a.cM+1|0;a.cM=e;if(e==100000)Gl(a);},H1=F(),T=F(0);
function C7(){let a=this;E.call(a);a.eN=0;a.eL=null;a.eM=null;}
let JD=(b,c)=>{let d;b=b;d=b.eN;c=b.eL;b=b.eM;Ck();DV(d);c.texImage2D(3553,0,6408,6408,5121,b);c.generateMipmap(3553);},Dt=F(),Cs=F(Dt),G9=F(Cs),B_=F(O),Kc=F(),FE=F(),Hz=null,Eu=null,CX=null,CO=null,E_=null,Et=null,ED=null,Ch=()=>{Ch=Y(FE);IV();},IV=()=>{let b;Hz=new WeakMap();Eu=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();CX=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();CO=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(CX===null)b=null;else{b=new Dd;b=new FinalizationRegistry(Q(I(b),
"accept"));}Et=b;if(CO===null)b=null;else{b=new Dc;b=new FinalizationRegistry(Q(I(b),"accept"));}ED=b;},I$=F(),H8=F(),Ej=F(0),Dd=F(),Iu=(b,c)=>{b;Ch();CX.delete(c);},Dc=F(),HS=(b,c)=>{b;Ch();CO.delete(c);},Es=F(0);
function D8(){let a=this;E.call(a);a.em=null;a.dP=null;}
function DO(){E.call(this);this.ey=null;}
let G4=(a,b)=>{a.ey=b;},Hj=a=>{let b=new DO();G4(b,a);return b;},Ip=(b,c)=>{E4(b.ey,window.innerWidth,window.innerHeight);},Ga=F(),DK=0,ER=0,ES=0,BQ=0.0,BP=0.0,Dv=0,DW=null,Gs=null,GW=0,Id=0,Ie=0,Cn=0,Bs=null,Ea=null,Ds=0,EJ=null,Gr=null,Fe=null,EH=null,FY=null,Gb=null,FF=null,FA=null,Cc=null,V=()=>{V=Y(Ga);G8();},JH=()=>{let b,c,d,e,f;V();DW=P(Z,16);b=0;while(b<16){c=DW.data;d=Bz();Dj(Bl(d,D(151)),b);c[b]=BO(d);d=Gs;e=DW.data[b];f=BA(b);CD(d,e,f);b=b+1|0;}GW=1;},IU=()=>{let b,c,d,$$je;V();a:{b:{try{if(!DK)break b;}
catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}return;}c:{try{if(GW)break c;JH();break c;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}d:{try{c=window;d=I_();EJ=I(d);c.addEventListener("contextmenu",Q(I(d),"handleEvent"));c=window;d=Hv();Gr=I(d);c.addEventListener("mousedown",Q(I(d),"handleEvent"));c=window;d=Hs();Fe=I(d);c.addEventListener("mouseup",Q(I(d),"handleEvent"));c=window;d=Ik();EH=I(d);c.addEventListener("mousemove",Q(I(d),"handleEvent"));c
=window;d=Im();FY=I(d);c.addEventListener("wheel",Q(I(d),"handleEvent"));c=window.document;d=ID();Gb=I(d);c.addEventListener("pointerlockchange",Q(I(d),"handleEvent"));c=window;d=It();FF=I(d);c.addEventListener("mouseleave",Q(I(d),"handleEvent"));c=window;d=IK();FA=I(d);c.addEventListener("mouseenter",Q(I(d),"handleEvent"));DK=1;b=Bs;if(b===null)break d;Gi(b);break d;}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}else{throw $$e;}}}try{Fo(Cn);}catch($$e){$$je=U($$e);if($$je instanceof Bg){b=$$je;break a;}
else{throw $$e;}}return;}J(GY(b));},GE=()=>{let b,c;V();b=Cc;if(b===null)return (-1);c=b.button;if(c==1)c=2;else if(c==2)c=1;return c;},Fq=()=>{let b;V();b=Cc;return b===null?0:Bt(Be(b.type),D(152));},Fo=b=>{let c;V();c=Cn;Cn=b;if(DK){if(b&&!c){if(!(document.pointerLockElement!=null?1:0)){Id=ER;Ie=ES;BQ=0.0;BP=0.0;document.body.requestPointerLock();}}else if(!b&&c&&(document.pointerLockElement!=null?1:0))document.exitPointerLock();Dv=0;BP=0.0;BQ=0.0;}},G8=()=>{Gs=FZ(16);Bs=new D6;Ea=GR(8);Ds=1;EJ=null;Gr=null;Fe
=null;EH=null;FY=null;Gb=null;FF=null;FA=null;Cc=null;};
function DN(){E.call(this);this.eX=null;}
let Hx=(a,b)=>{a.eX=b;},Ha=a=>{let b=new DN();Hx(b,a);return b;},Jp=(b,c)=>{b=b.eX;M();b.requestPointerLock();},JB=F(Cs);
function GU(){let a=this;E.call(a);a.cV=0;a.c0=0;a.cY=0;a.dw=null;a.dM=null;a.dh=null;}
let Hp=(a,b,c,d)=>{let e,f,g,h,i,j,k,l;a.dh=FJ();a.cV=b;a.c0=c;a.cY=d;e=S(b,c);f=BS(S(e,d));g=f.data;a.dw=f;a.dM=CU(e);h=0;i=d*2|0;while(h<b){j=0;while(j<d){k=0;while(k<c){g[S(S(j,c)+k|0,b)+h|0]=(j>(i/3|0)?0:1)<<24>>24;k=k+1|0;}j=j+1|0;}h=h+1|0;}Eo(a,0,0,b,c);l=new Di;l.eQ=a;Ho(Q(I(l),"onResult"));},IO=(a,b,c)=>{let d=new GU();Hp(d,a,b,c);return d;},E3=a=>{let b,$$je;a:{try{HL(BT(Ib(G6(),a.dw)));break a;}catch($$e){$$je=U($$e);if($$je instanceof Bv){b=$$je;CM(b);break a;}else{throw $$e;}}}},Eo=(a,b,c,d,e)=>
{let f,g,h,i,j,k,l;f=b+d|0;d=c+e|0;while(b<f){g=c;while(g<d){h=a.dM.data[b+S(g,a.cV)|0];i=a.cY-1|0;while(i>0&&!Bj(a,b,i,g)){i=i+(-1)|0;}a:{a.dM.data[b+S(g,a.cV)|0]=i;e=Df(h,i);if(e){j=e>=0?i:h;if(e>0)i=h;k=0;while(true){l=a.dh;if(k>=l.c1)break a;DS(BV(l,k),b-1|0,j-1|0,g-1|0,b+1|0,i+1|0,g+1|0);k=k+1|0;}}}g=g+1|0;}b=b+1|0;}},Bj=(a,b,c,d)=>{let e,f;if(b>=0&&c>=0&&d>=0){e=a.cV;if(b<e&&c<a.cY){f=a.c0;if(d<f)return a.dw.data[S(S(c,f)+d|0,e)+b|0]!=1?0:1;}}return 0;},IN=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m;c=FJ();d=b.cQ
|0;e=b.cR+1.0|0;f=b.cS|0;g=b.cX+1.0|0;h=b.cU|0;i=b.cT+1.0|0;if(d<0)d=0;if(f<0)f=0;if(h<0)h=0;j=a.cV;if(e<=j)j=e;k=a.cY;if(g<=k)k=g;g=a.c0;if(i<=g)g=i;while(d<j){l=f;while(l<k){m=h;while(m<g){if(Bj(a,d,l,m))FI(c,Cy(d,l,m,d+1|0,l+1|0,m+1|0));m=m+1|0;}l=l+1|0;}d=d+1|0;}return c;},BY=(a,b,c,d)=>{let e,f;e=1.0;if(b>=0&&c>=0&&d>=0){f=a.cV;if(b<f&&c<a.cY&&d<a.c0){if(c<a.dM.data[b+S(d,f)|0])e=0.4000000059604645;return e;}}return e;},E6=(a,b,c,d,e)=>{let f,g,h,i,j;a:{if(b>=0&&c>=0&&d>=0){f=a.cV;if(b<f&&c<a.cY){g=a.c0;if
(d<g){a.dw.data[S(S(c,g)+d|0,f)+b|0]=e<<24>>24;Eo(a,b,d,1,1);f=0;e=b-1|0;g=c-1|0;h=d-1|0;b=b+1|0;i=c+1|0;d=d+1|0;while(true){j=a.dh;if(f>=j.c1)break a;DS(BV(j,f),e,g,h,b,i,d);f=f+1|0;}}}}}},Ho=b=>{var req=indexedDB.open('rubydung',1);req.onupgradeneeded=function(e){e.target.result.createObjectStore('levels');};req.onsuccess=function(e){var db=e.target.result;if(!db.objectStoreNames.contains('levels'))return;var tx=db.transaction('levels','readonly');var getReq=(tx.objectStore('levels')).get('level.dat');getReq.onsuccess
=function(e){if(e.target.result)b(e.target.result);};};},HL=b=>{var req=indexedDB.open('rubydung',1);req.onupgradeneeded=function(e){e.target.result.createObjectStore('levels');};req.onsuccess=function(e){var db=e.target.result;var tx=db.transaction('levels','readwrite');(tx.objectStore('levels')).put(b,'level.dat');};},Fa=F(0);
function FG(){let a=this;E.call(a);a.d_=null;a.dv=null;a.dT=0;a.eh=0;a.d$=0;a.dS=null;}
let Ia=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p;a.dS=FH();a.d_=b;FI(b.dh,a);c=b.cV/16|0;a.dT=c;d=b.cY/16|0;a.eh=d;e=b.c0/16|0;a.d$=e;a.dv=P(CB,S(S(c,d),e));c=0;while(c<a.dT){f=0;while(f<a.eh){d=0;while(true){e=a.d$;if(d>=e)break;g=c*16|0;h=f*16|0;i=d*16|0;j=(c+1|0)*16|0;k=(f+1|0)*16|0;l=d+1|0;m=l*16|0;n=b.cV;if(j<=n)n=j;j=b.cY;if(k<=j)j=k;k=b.c0;if(m<=k)k=m;o=a.dv.data;e=S(c+S(f,a.dT)|0,e)+d|0;p=new CB;BB();p.d0=1;p.ds=P(E,2);p.dJ=P(E,2);p.dI=P(E,2);p.dW=CU(2);p.ei=b;p.eJ=g;p.eD=h;p.eF=i;p.eK=n;p.eC=j;p.eG=k;p.eI
=Cy(g,h,i,n,j,k);o[e]=p;d=l;}f=f+1|0;}c=c+1|0;}},Io=a=>{let b=new FG();Ia(b,a);return b;},Gp=(a,b,c)=>{let d,e,f;BB();CE=0;Cu();HQ(C8);d=C8;e=0;while(true){f=a.dv.data;if(e>=f.length)break;b=f[e].eI;if(JA(d,b.cQ,b.cS,b.cU,b.cR,b.cX,b.cT))JU(a.dv.data[e],c);e=e+1|0;}},JL=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z;c=b.dz;d=b.dA;e=b.dB;f=CH(Cp( -b.c9));g=B$(Cp( -b.c9));h=CH(Cp(b.da));i=B$(Cp(b.da))*f;j= -h*f;k=Dy(c)|0;l=Dy(d)|0;m=Dy(e)|0;n=CY(i,0.0);o=n<=0?(-1):1;p=CY(g,0.0);q=p<=0?(-1):1;r=CY(j,
0.0);s=r<=0?(-1):1;t=!n?3.4028234663852886E38:DE(1.0/i);u=!p?3.4028234663852886E38:DE(1.0/g);v=!r?3.4028234663852886E38:DE(1.0/j);w=n<=0?(c-k)*t:((k+1|0)-c)*t;x=p<=0?(d-l)*u:((l+1|0)-d)*u;y=r<=0?(e-m)*v:((m+1|0)-e)*v;n=(-1);z=0.0;while(z<5.0){if(Bj(a.d_,k,l,m)){b=new GO;b.dX=k;b.dY=l;b.dZ=m;b.fa=0;b.eb=n;M();BK=b;return;}if(!(w<x)){if(!(x<y)){c=y+v;m=m+s|0;n=s<=0?3:2;z=y;y=c;continue;}c=x+u;l=l+q|0;n=q<=0?1:0;z=x;x=c;continue;}if(!(w<y)){c=y+v;m=m+s|0;n=s<=0?3:2;z=y;y=c;continue;}c=w+t;k=k+o|0;n=o<=0?5:4;z=
w;w=c;}b=null;M();BK=b;},He=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o;M();c=G;c.enable(3042);c.blendFunc(770,1);c.uniform1f(Dm,B$(DT(Cx())/100.0)*0.20000000298023224+0.4000000059604645);Gw(a.dS);BF();d=a.dS;e=b.dX;f=b.dY;g=b.dZ;h=b.eb;i=e;j=i+0.0;k=i+1.0;l=f;m=l+0.0;n=l+1.0;o=g;l=o+0.0;i=o+1.0;if(!h){H(d,j,m,i);H(d,j,m,l);H(d,k,m,l);H(d,k,m,i);}if(h==1){H(d,k,n,i);H(d,k,n,l);H(d,j,n,l);H(d,j,n,i);}if(h==2){H(d,j,n,l);H(d,k,n,l);H(d,k,m,l);H(d,j,m,l);}if(h==3){H(d,j,n,i);H(d,j,m,i);H(d,k,m,i);H(d,k,n,i);}if(h==4)
{H(d,j,n,i);H(d,j,n,l);H(d,j,m,l);H(d,j,m,i);}if(h==5){H(d,k,m,i);H(d,k,m,l);H(d,k,n,l);H(d,k,n,i);}Gl(a.dS);c.disable(3042);b=Dm;c.uniform1f(b,1.0);},DS=(a,b,c,d,e,f,g)=>{let h,i,j,k,l;h=b/16|0;e=e/16|0;b=c/16|0;c=f/16|0;f=d/16|0;g=g/16|0;if(h<0)h=0;if(b<0)b=0;if(f<0)f=0;i=a.dT;if(e>=i)e=i-1|0;d=a.eh;if(c>=d)c=d-1|0;j=a.d$;if(g>=j)g=j-1|0;while(h<=e){k=b;while(k<=c){l=f;while(l<=g){a.dv.data[S(h+S(k,i)|0,j)+l|0].d0=1;l=l+1|0;}k=k+1|0;}h=h+1|0;}},In=a=>{let b;b=a.d_;DS(a,0,0,0,b.cV,b.cY,b.c0);};
function EL(){let a=this;E.call(a);a.dO=null;a.ex=0.0;a.ew=0.0;a.eH=0.0;a.dz=0.0;a.dA=0.0;a.dB=0.0;a.db=0.0;a.di=0.0;a.dd=0.0;a.da=0.0;a.c9=0.0;a.c4=null;a.d1=0;}
let IA=(a,b)=>{a.d1=0;a.dO=b;Fr(a);},Jl=a=>{let b=new EL();IA(b,a);return b;},Fr=a=>{let b,c,d,e;b=Fh();c=a.dO;b=b*c.cV;d=c.cY+10|0;e=Fh()*a.dO.c0;a.dz=b;a.dA=d;a.dB=e;a.c4=Cy(b-0.30000001192092896,d-0.8999999761581421,e-0.30000001192092896,b+0.30000001192092896,d+0.8999999761581421,e+0.30000001192092896);},J6=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q;a.ex=a.dz;a.ew=a.dA;a.eH=a.dB;b=0.0;c=0.0;if(Bb(19))Fr(a);if(!(!Bb(200)&&!Bb(17)))c=(-1.0);if(!(!Bb(208)&&!Bb(31)))c=c+1.0;if(!(!Bb(203)&&!Bb(30)))b=(-1.0);if(!(!Bb(205)
&&!Bb(32)))b=b+1.0;if(!(!Bb(57)&&!Bb(219))&&a.d1)a.di=0.11999999731779099;d=!a.d1?0.004999999888241291:0.019999999552965164;e=b*b+c*c;if(!(e<0.009999999776482582)){d=d/GA(e);b=b*d;c=c*d;d=B$(a.da*3.141592653589793/180.0);e=CH(a.da*3.141592653589793/180.0);a.db=a.db+b*e-c*d;a.dd=a.dd+c*e+b*d;}b=a.di-0.005;a.di=b;c=a.db;d=a.dd;f=a.dO;g=a.c4;h=g.cQ;i=g.cS;j=g.cU;k=g.cR;l=g.cX;m=g.cT;if(c<0.0)h=h+c;if(c>0.0)k=k+c;n=Df(b,0.0);if(n<0)i=i+b;if(b>0.0)l=l+b;if(d<0.0)j=j+d;if(d>0.0)m=m+d;g=IN(f,Cy(h,i,j,k,l,m));o=0;p
=g;k=b;while(o<p.c1){k=H6(BV(p,o),a.c4,k);o=o+1|0;}De(a.c4,0.0,k,0.0);q=0;e=c;while(q<p.c1){e=J1(BV(p,q),a.c4,e);q=q+1|0;}De(a.c4,e,0.0,0.0);q=0;h=d;while(q<p.c1){h=Hc(BV(p,q),a.c4,h);q=q+1|0;}De(a.c4,0.0,0.0,h);q=CY(b,k);o=q&&n<0?1:0;a.d1=o;if(c!==e)a.db=0.0;if(q)a.di=0.0;if(d!==h)a.dd=0.0;g=a.c4;a.dz=(g.cQ+g.cR)/2.0;a.dA=g.cS+1.6200000047683716;a.dB=(g.cU+g.cT)/2.0;b=a.db*0.9100000262260437;a.db=b;a.di=a.di*0.9800000190734863;c=a.dd*0.9100000262260437;a.dd=c;if(o){a.db=b*0.800000011920929;a.dd=c*0.800000011920929;}},El
=F(O);
function GO(){let a=this;E.call(a);a.dX=0;a.dY=0;a.dZ=0;a.fa=0;a.eb=0;}
function CC(){let a=this;D8.call(a);a.ea=0;a.dF=null;}
let Ee=F(),J8=a=>{return;},HR=()=>{let a=new Ee();J8(a);return a;},I8=(b,c)=>{let d;b;Bh();CP.data[DH(c.which)]=1;b=BD;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();},Eg=F(),JY=a=>{return;},HN=()=>{let a=new Eg();JY(a);return a;},IS=(b,c)=>{let d;b;Bh();CP.data[DH(c.which)]=0;b=BD;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();},Ef=F(),I3=a=>{return;},Jd=()=>{let a=new Ef();I3(a);return a;},I5=(b,c)=>{let d;b;Bh();if(GN&&(c.repeat?1:0)){b=BD;d=Bf(c);BC(b,d);}c.preventDefault();c.stopPropagation();},Gc
=F(Bv),H$=(a,b)=>{Do(a);a.ee=1;a.el=1;HO(a);a.d4=b;},GY=a=>{let b=new Gc();H$(b,a);return b;},DY=F(),IX=a=>{return;},I_=()=>{let a=new DY();IX(a);return a;},Hl=(b,c)=>{b;c.preventDefault();c.stopPropagation();},D1=F(),JI=a=>{return;},Hv=()=>{let a=new D1();JI(a);return a;},H4=(b,c)=>{let d,e,f;b;d=c.button;V();e=Ea;if(d==1)d=2;else if(d==2)d=1;e.data[d]=1;b=Bs;f=Bf(c);BC(b,f);c.preventDefault();c.stopPropagation();},D2=F(),J0=a=>{return;},Hs=()=>{let a=new D2();J0(a);return a;},Jh=(b,c)=>{let d,e,f;b;d=c.button;V();e
=Ea;if(d==1)d=2;else if(d==2)d=1;e.data[d]=0;b=Bs;f=Bf(c);BC(b,f);c.preventDefault();c.stopPropagation();},DZ=F(),JR=a=>{return;},Ik=()=>{let a=new DZ();JR(a);return a;},J2=(b,c)=>{let d,e;b;c.preventDefault();c.stopPropagation();d=window.devicePixelRatio;e=c.clientX*d|0;V();ER=e;ES=(window.innerHeight-c.clientY|0)*d|0;BQ=BQ+c.movementX;BP=BP+ -c.movementY;b=Bs;c=Bf(c);BC(b,c);},D0=F(),JW=a=>{return;},Im=()=>{let a=new D0();JW(a);return a;},I6=(b,c)=>{let d,e;b;V();b=Bs;d=Bf(c);BC(b,d);c.preventDefault();c.stopPropagation();e
=!(c.deltaY>0.0)?(-1):1;Dv=Dv+e|0;},D4=F(),JZ=a=>{return;},ID=()=>{let a=new D4();JZ(a);return a;},Jb=(b,c)=>{b;if(!(document.pointerLockElement!=null?1:0))Cn=0;else Cn=1;},D5=F(),JP=a=>{return;},It=()=>{let a=new D5();JP(a);return a;},Ix=(b,c)=>{b;c.preventDefault();c.stopPropagation();V();Ds=0;},D3=F(),IW=a=>{return;},IK=()=>{let a=new D3();IW(a);return a;},HC=(b,c)=>{b;c.preventDefault();c.stopPropagation();V();Ds=1;},FV=F(0);
function FL(){let a=this;Cg.call(a);a.dn=null;a.c1=0;}
let H2=a=>{a.dn=P(E,10);},FJ=()=>{let a=new FL();H2(a);return a;},BV=(a,b)=>{let c;if(b>=0&&b<a.c1)return a.dn.data[b];c=new Bd;L(c);J(c);},II=a=>{return a.c1;},FI=(a,b)=>{let c,d,e,f,g,h;c=a.c1+1|0;d=a.dn.data.length;if(d<c){c=d>=1073741823?2147483647:Cj(c,Cj(d*2|0,5));e=a.dn;f=C$(BM(e));if(f===null){b=new C_;L(b);J(b);}if(f===BE(IL)){b=new B_;L(b);J(b);}if(c<0){b=new GV;L(b);J(b);}g=e.data;e=Hq(f.c3,c);h=Dk(c,g.length);d=0;while(d<h){e.data[d]=g[d];d=d+1|0;}a.dn=e;}e=a.dn.data;h=a.c1;a.c1=h+1|0;e[h]=b;a.cZ
=a.cZ+1|0;return 1;},EU=F(Cd),BL=(a,b)=>{if(b===null)b=D(3);HU(BT(b));},IC=F(),FS=(b,c)=>{let d,e,f,g;b=b.data;d=0;e=b.length;if(d>e){f=new B_;L(f);J(f);}while(d<e){g=d+1|0;b[d]=c;d=g;}};
function Gx(){let a=this;E.call(a);a.dc=0.0;a.cQ=0.0;a.cS=0.0;a.cU=0.0;a.cR=0.0;a.cX=0.0;a.cT=0.0;}
let G$=(a,b,c,d,e,f,g)=>{a.dc=0.0;a.cQ=b;a.cS=c;a.cU=d;a.cR=e;a.cX=f;a.cT=g;},Cy=(a,b,c,d,e,f)=>{let g=new Gx();G$(g,a,b,c,d,e,f);return g;},J1=(a,b,c)=>{let d,e;if(!(b.cX<=a.cS)&&!(b.cS>=a.cX)){if(!(b.cT<=a.cU)&&!(b.cU>=a.cT)){if(!(c>0.0))d=c;else{d=b.cR;e=a.cQ;if(!(d<=e))d=c;else{d=e-d-a.dc;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cQ;e=a.cR;if(!(c>=e))e=d;else{e=e-c+a.dc;if(!(e>d))e=d;}}return e;}return c;}return c;},H6=(a,b,c)=>{let d,e;if(!(b.cR<=a.cQ)&&!(b.cQ>=a.cR)){if(!(b.cT<=a.cU)&&!(b.cU>=a.cT)){if
(!(c>0.0))d=c;else{d=b.cX;e=a.cS;if(!(d<=e))d=c;else{d=e-d-a.dc;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cS;e=a.cX;if(!(c>=e))e=d;else{e=e-c+a.dc;if(!(e>d))e=d;}}return e;}return c;}return c;},Hc=(a,b,c)=>{let d,e;if(!(b.cR<=a.cQ)&&!(b.cQ>=a.cR)){if(!(b.cX<=a.cS)&&!(b.cS>=a.cX)){if(!(c>0.0))d=c;else{d=b.cT;e=a.cU;if(!(d<=e))d=c;else{d=e-d-a.dc;if(!(d<c))d=c;}}if(!(d<0.0))e=d;else{c=b.cU;e=a.cT;if(!(c>=e))e=d;else{e=e-c+a.dc;if(!(e>d))e=d;}}return e;}return c;}return c;},De=(a,b,c,d)=>{a.cQ=a.cQ+b;a.cS=a.cS+
c;a.cU=a.cU+d;a.cR=a.cR+b;a.cX=a.cX+c;a.cT=a.cT+d;},H5=F(),CR=b=>{let c;c=(BM(b)).c3;if(c[K].itemType!==null)return JC(b);b=new B_;L(b);J(b);},CK=F(O),JK=F(),G6=()=>{let b;b=new F$;Bi();b.e8=Dq;b.e1=1;return b;},Jz=()=>{let b;b=new Fs;Bi();b.eu=Eb;return b;};
function DM(){let a=this;E.call(a);a.c$=null;a.e2=null;a.eP=null;a.de=null;}
let C8=null,Cu=()=>{Cu=Y(DM);Hf();},BZ=(a,b,c)=>{let d,e;b=b.data;d=GA(b[c].data[0]*b[c].data[0]+b[c].data[1]*b[c].data[1]+b[c].data[2]*b[c].data[2]);e=b[c].data;e[0]=e[0]/d;e=b[c].data;e[1]=e[1]/d;e=b[c].data;e[2]=e[2]/d;b=b[c].data;b[3]=b[3]/d;},HQ=a=>{let b,c,d,e;M();b=CA;c=b.data;a.e2=b;b=Cv;d=b.data;a.eP=b;b=a.de.data;b[0]=d[0]*c[0]+d[1]*c[4]+d[2]*c[8]+d[3]*c[12];b[1]=d[0]*c[1]+d[1]*c[5]+d[2]*c[9]+d[3]*c[13];b[2]=d[0]*c[2]+d[1]*c[6]+d[2]*c[10]+d[3]*c[14];b[3]=d[0]*c[3]+d[1]*c[7]+d[2]*c[11]+d[3]*c[15];b[4]
=d[4]*c[0]+d[5]*c[4]+d[6]*c[8]+d[7]*c[12];b[5]=d[4]*c[1]+d[5]*c[5]+d[6]*c[9]+d[7]*c[13];b[6]=d[4]*c[2]+d[5]*c[6]+d[6]*c[10]+d[7]*c[14];b[7]=d[4]*c[3]+d[5]*c[7]+d[6]*c[11]+d[7]*c[15];b[8]=d[8]*c[0]+d[9]*c[4]+d[10]*c[8]+d[11]*c[12];b[9]=d[8]*c[1]+d[9]*c[5]+d[10]*c[9]+d[11]*c[13];b[10]=d[8]*c[2]+d[9]*c[6]+d[10]*c[10]+d[11]*c[14];b[11]=d[8]*c[3]+d[9]*c[7]+d[10]*c[11]+d[11]*c[15];b[12]=d[12]*c[0]+d[13]*c[4]+d[14]*c[8]+d[15]*c[12];b[13]=d[12]*c[1]+d[13]*c[5]+d[14]*c[9]+d[15]*c[13];b[14]=d[12]*c[2]+d[13]*c[6]+d[14]
*c[10]+d[15]*c[14];b[15]=d[12]*c[3]+d[13]*c[7]+d[14]*c[11]+d[15]*c[15];d=a.c$;c=d.data;c[0].data[0]=b[3]-b[0];c[0].data[1]=b[7]-b[4];c[0].data[2]=b[11]-b[8];c[0].data[3]=b[15]-b[12];BZ(a,d,0);b=a.c$;d=b.data;e=d[1].data;c=a.de.data;e[0]=c[3]+c[0];d[1].data[1]=c[7]+c[4];d[1].data[2]=c[11]+c[8];d[1].data[3]=c[15]+c[12];BZ(a,b,1);b=a.c$;d=b.data;e=d[2].data;c=a.de.data;e[0]=c[3]+c[1];d[2].data[1]=c[7]+c[5];d[2].data[2]=c[11]+c[9];d[2].data[3]=c[15]+c[13];BZ(a,b,2);b=a.c$;d=b.data;e=d[3].data;c=a.de.data;e[0]=c[3]
-c[1];d[3].data[1]=c[7]-c[5];d[3].data[2]=c[11]-c[9];d[3].data[3]=c[15]-c[13];BZ(a,b,3);b=a.c$;d=b.data;e=d[4].data;c=a.de.data;e[0]=c[3]-c[2];d[4].data[1]=c[7]-c[6];d[4].data[2]=c[11]-c[10];d[4].data[3]=c[15]-c[14];BZ(a,b,4);b=a.c$;d=b.data;e=d[5].data;c=a.de.data;e[0]=c[3]+c[2];d[5].data[1]=c[7]+c[6];d[5].data[2]=c[11]+c[10];d[5].data[3]=c[15]+c[14];BZ(a,b,5);},JA=(a,b,c,d,e,f,g)=>{let h,i;h=0;while(h<6){i=a.c$.data;if(!(i[h].data[0]*b+i[h].data[1]*c+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]
*c+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*f+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*f+i[h].data[2]*d+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*c+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*c+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*b+i[h].data[1]*f+i[h].data[2]*g+i[h].data[3]>0.0)&&!(i[h].data[0]*e+i[h].data[1]*f+i[h].data[2]*g+i[h].data[3]>0.0))return 0;h=h+1|0;}return 1;},Hf=()=>{let b;b=new DM;Cu();b.c$=IT([4,6]);b.e2=Bq(16);b.eP
=Bq(16);b.de=Bq(16);C8=b;};
function Dn(){E.call(this);this.ej=0;}
let Er=null,Gq=null,BF=()=>{BF=Y(Dn);JF();},G7=(a,b)=>{BF();a.ej=0;a.ej=b;},Fn=a=>{let b=new Dn();G7(b,a);return b;},Fc=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r;h=a.ej/16.0;i=h+0.062437500804662704;j=e;k=j+0.0;l=j+1.0;m=f;n=m+0.0;j=m+1.0;m=g;o=m+0.0;p=m+1.0;q=f-1|0;if(!Bj(c,e,q,g)){m=BY(c,e,q,g)*1.0;if((m!==1.0?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,h,0.062437500804662704);H(b,k,n,p);N(b,h,0.0);H(b,k,n,o);N(b,i,0.0);H(b,l,n,o);N(b,i,0.062437500804662704);H(b,l,n,p);}}if(!Bj(c,e,f+1|0,g)){m=BY(c,e,f,g)*1.0;if((m
!==1.0?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.062437500804662704);H(b,l,j,p);N(b,i,0.0);H(b,l,j,o);N(b,h,0.0);H(b,k,j,o);N(b,h,0.062437500804662704);H(b,k,j,p);}}r=g-1|0;if(!Bj(c,e,f,r)){m=BY(c,e,f,r)*0.800000011920929;if((m!==0.800000011920929?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.0);H(b,k,j,o);N(b,h,0.0);H(b,l,j,o);N(b,h,0.062437500804662704);H(b,l,n,o);N(b,i,0.062437500804662704);H(b,k,n,o);}}r=g+1|0;if(!Bj(c,e,f,r)){m=BY(c,e,f,r)*0.800000011920929;if((m!==0.800000011920929?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,
h,0.0);H(b,k,j,p);N(b,h,0.062437500804662704);H(b,k,n,p);N(b,i,0.062437500804662704);H(b,l,n,p);N(b,i,0.0);H(b,l,j,p);}}r=e-1|0;if(!Bj(c,r,f,g)){m=BY(c,r,f,g)*0.6000000238418579;if((m!==0.6000000238418579?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,i,0.0);H(b,k,j,p);N(b,h,0.0);H(b,k,j,o);N(b,h,0.062437500804662704);H(b,k,n,o);N(b,i,0.062437500804662704);H(b,k,n,p);}}e=e+1|0;if(!Bj(c,e,f,g)){m=BY(c,e,f,g)*0.6000000238418579;if((m!==0.6000000238418579?0:1)^(d!=1?0:1)){BU(b,m,m,m);N(b,h,0.062437500804662704);H(b,l,n,p);N(b,
i,0.062437500804662704);H(b,l,n,o);N(b,i,0.0);H(b,l,j,o);N(b,h,0.0);H(b,l,j,p);}}},JF=()=>{Er=Fn(0);Gq=Fn(1);},GP=F(0);
function Di(){E.call(this);this.eQ=null;}
let G2=(b,c)=>{let d,e,f,g,$$je;c=Be(c);b=b.eQ;a:{try{d=Hu(Jz(),c);e=d.data;f=b.dw;Fp(d,0,f,0,Dk(e.length,f.data.length));Eo(b,0,0,b.cV,b.c0);g=0;while(g<II(b.dh)){In(BV(b.dh,g));g=g+1|0;}break a;}catch($$e){$$je=U($$e);if($$je instanceof Bv){b=$$je;CM(b);break a;}else{throw $$e;}}}};
function F$(){let a=this;E.call(a);a.e8=null;a.e1=0;}
let Ib=(a,b)=>{let c,d,e,f,g,h;c=b.data;d=a.e8;e=a.e1;Bi();f=c.length;g=((f+2|0)/3|0)*4|0;if(!e){f=f%3|0;if(f)g=g-(3-f|0)|0;}h=BS(g);c=h.data;IP(b,h,d,e);e=c.length;d=BI(e);b=d.data;g=0;while(g<e){b[g]=c[g]&255&65535;g=g+1|0;}return Ez(d);},F4=F(),Dq=null,GH=null,Eb=null,C6=null,Bi=()=>{Bi=Y(F4);Jo();},Ii=(b,c,d)=>{let e,f,g,h,i,j,k,l,m,n,o,p;Bi();b=b.data;e=b.length;f=e-1|0;while(f>=0&&b[f]==61){e=e+(-1)|0;f=f+(-1)|0;}g=(e/4|0)*4|0;h=0;i=0;while(h<g){j=c.data;f=h+1|0;k=Bn(d,b[h]);h=f+1|0;l=Bn(d,b[f]);f=h+1
|0;m=Bn(d,b[h]);h=f+1|0;n=Bn(d,b[f]);o=k<<18|l<<12|m<<6|n;f=i+1|0;j[i]=(o>>>16|0)<<24>>24;k=f+1|0;j[f]=(o>>>8|0)<<24>>24;i=k+1|0;j[k]=o<<24>>24;}p=e-h|0;if(p==2)c.data[i]=(Bn(d,b[h])<<2|(Bn(d,b[h+1|0])>>>4|0))<<24>>24;else if(p==3){c=c.data;k=Bn(d,b[h]);l=Bn(d,b[h+1|0]);h=Bn(d,b[h+2|0]);c[i]=(k<<2|(l>>>4|0))<<24>>24;c[i+1|0]=(l<<4|(h>>>2|0))<<24>>24;}},Bn=(b,c)=>{Bi();return b.data[c];},IP=(b,c,d,e)=>{let f,g,h,i,j,k,l,m,n;Bi();f=b.data;g=f.length;h=(g/3|0)*3|0;i=0;j=0;while(j<h){b=c.data;k=i+1|0;b[i]=Bm(d,
(f[j]>>>2|0)<<24>>24);l=k+1|0;m=f[j]<<4;i=j+1|0;b[k]=Bm(d,(m|((f[i]&255)>>>4|0))<<24>>24);m=l+1|0;j=f[i]<<2;n=i+1|0;b[l]=Bm(d,(j|((f[n]&255)>>>6|0))<<24>>24);i=m+1|0;b[m]=Bm(d,f[n]);j=n+1|0;}l=g-j|0;if(l==1){b=c.data;l=i+1|0;b[i]=Bm(d,(f[j]>>>2|0)<<24>>24);i=l+1|0;b[l]=Bm(d,f[j]<<4<<24>>24);if(e){e=i+1|0;b[i]=61;i=e+1|0;b[e]=61;}}else if(l==2){b=c.data;m=i+1|0;b[i]=Bm(d,(f[j]>>>2|0)<<24>>24);i=m+1|0;n=f[j]<<4;l=j+1|0;b[m]=Bm(d,(n|((f[l]&255)>>>4|0))<<24>>24);m=i+1|0;b[i]=Bm(d,f[l]<<2<<24>>24);if(!e)i=m;else
{i=m+1|0;b[m]=61;}}return i;},Bm=(b,c)=>{Bi();return b.data[c&63];},Jo=()=>{let b,c,d,e,f,g;b=BS(64);c=b.data;Dq=b;b=BS(64);d=b.data;GH=b;b=CU(256);Eb=b;C6=CU(256);e=0;f=65;while(f<=90){g=f<<24>>24;c[e]=g;d[e]=g;e=e+1|0;f=(f+1|0)&65535;}f=97;while(f<=122){g=f<<24>>24;c[e]=g;d[e]=g;e=e+1|0;f=(f+1|0)&65535;}g=48;while(g<=57){f=g<<24>>24;c[e]=f;d[e]=f;e=e+1|0;g=(g+1|0)&65535;}c[e]=43;d[e]=45;e=e+1|0;c[e]=47;d[e]=95;FS(b,(-1));FS(C6,(-1));g=0;while(true){b=Dq.data;if(g>=b.length)break;Eb.data[b[g]]=g;C6.data[GH.data[g]]
=g;g=g+1|0;}},GK=F(0),GS=F(0);
function Ex(){let a=this;E.call(a);a.dy=null;a.dx=null;a.eg=null;a.d6=0;a.dK=0;a.dp=null;}
let Ji=(a,b,c,d,e)=>{a.dp=b;a.dK=b.cZ;a.dy=c;a.dx=d;a.d6=e;},F7=(a,b,c,d)=>{let e=new Ex();Ji(e,a,b,c,d);return e;},Fz=a=>{let b;if(a.dK>=a.dp.cZ)return;b=new Fl;L(b);J(b);};
function F0(){let a=this;E.call(a);a.e0=null;a.df=null;a.dg=null;}
function Fs(){E.call(this);this.eu=null;}
let Hu=(a,b)=>{let c,d,e,f,g,h,i;c=BS(b.cL.length);d=c.data;e=0;f=d.length;while(e<f){d[e]=CL(b,e)<<24>>24;e=e+1|0;}g=a.eu;Bi();h=(f/4|0)*3|0;i=f%4|0;if(!(i!=2&&i!=3))h=h+(i-1|0)|0;e=f-1|0;while(e>=0&&d[e]==61){h=h+(-1)|0;e=e+(-1)|0;}d=BS(h);Ii(c,d,g);return d;},Fl=F(O),GV=F(O);
HW([-1,"java",0,"util",0,"lang",-1,"org",3,"lwjgl"]);
C9([E,0,0,[],1,0,0,0,By,0,E,[],1537,0,0,0,Cl,0,E,[],1537,0,0,0,DL,0,E,[],1537,0,0,0,Z,0,E,[By,Cl,DL],17,0,()=>BW(),["bz",BJ(Bt),"b2",CF(Iq)],D_,0,E,[By],1025,0,0,0,B6,0,D_,[Cl],1,0,()=>B2(),["b2",CF(Hk),"bz",BJ(Jx)],Dr,0,E,[By,DL],0,0,0,0,DD,0,E,[],1537,0,0,0,EI,0,Dr,[DD],1,0,0,0,Bg,0,E,[],1,0,0,0,Bv,0,Bg,[],1,0,0,0,O,0,Bv,[],1,0,0,0,B3,0,E,[],1025,0,0,0,H7,0,B3,[],17,0,0,0,HV,0,B3,[],17,0,0,0,E8,0,E,[],1537,0,0,0,GJ,0,E,[E8],1537,0,0,0,Ey,0,E,[],1537,0,0,0,Fk,0,E,[GJ,Ey],17,0,0,0,Dx,0,E,[],1537,0,0,0,En,0,
E,[Dx],1,0,()=>M(),0,Jg,0,E,[],17,0,0,0,JN,0,E,[],17,0,0,0,J9,0,E,[],17,0,0,0,B9,0,E,[Dx],1,0,()=>Bo(),0,F9,0,E,[],1537,0,0,0,FD,0,E,[F9],1,0,0,0,DU,0,E,[Cl],1,0,()=>Db(),0,EW,0,E,[],1,0,0,0,HX,0,E,[],17,0,0,0,Ek,0,E,[],17,0,0,0,I1,0,E,[],17,0,0,0,Fg,0,E,[],1537,0,0,0,GF,0,E,[Fg],1,0,0,0,Bd,"IndexOutOfBoundsException",2,O,[],1,0,0,0,Cm,0,E,[],1537,0,0,0,GX,0,E,[Cm],1,0,0,["bu",CF(Ir)],GC,0,E,[],0,0,0,0,CI,"IllegalMonitorStateException",2,O,[],1,0,0,0,EV,0,E,[],1537,0,0,0,Js,0,E,[Cm,EV],1536,0,0,0,Jr,"ClassCastException",
2,O,[],1,0,0,0,Ff,"IllegalStateException",2,O,[],1,0,0,0,Gm,0,E,[Cm],1,0,0,["bu",CF(I2)],F3,0,E,[],1537,0,0,0,FO,0,E,[F3],0,0,0,["h",BJ(CT),"bI",BJ(Jw)],EX,0,E,[Cm],1,0,0,0,E9,0,E,[],1537,0,0,0,CN,0,E,[E9],1537,0,0,0]);
C9([B4,0,E,[CN],1025,0,0,0,EA,0,E,[CN],1537,0,0,0,Eh,0,E,[CN],1537,0,0,0,D9,0,E,[EA,Eh],1537,0,0,0,BX,0,E,[],1537,0,0,0,F5,0,B4,[D9,BX,By],1,0,0,0,IZ,0,E,[],17,0,0,0,CQ,"StringIndexOutOfBoundsException",2,Bd,[],1,0,0,0,GI,0,E,[],1,0,()=>Bh(),0,Bp,0,E,[],1537,0,0,0,FX,0,E,[Bp],1537,0,0,0,Da,0,E,[FX],1,0,0,0,CB,0,E,[],1,0,()=>BB(),0,C_,"NullPointerException",2,O,[],1,0,0,0,Gv,0,E,[],1537,0,0,0,Fi,0,E,[Gv],1537,0,0,0,Gg,0,E,[],1537,0,0,0,DJ,0,E,[Fi,Gg],1025,0,0,0,Dp,0,DJ,[],1,0,0,0,Dl,0,Dp,[DD],1,0,0,0,Cd,0,Dl,
[],1025,0,0,0,EZ,0,Cd,[],1,0,0,["B",BJ(Jt)],EQ,0,E,[],1537,0,0,0,D$,0,E,[EQ],1025,0,0,0,D7,0,D$,[BX,By],1,0,0,0,EP,0,E,[Eh],1537,0,0,0,Cg,0,B4,[EP],1025,0,0,0,Dz,0,Cg,[],1025,0,0,0,D6,0,Dz,[D9,BX],1,0,0,0,FR,0,E,[],1,0,()=>Ck(),0,FP,0,E,[],1,0,0,0,H1,0,E,[Cl],1025,0,0,0,T,0,E,[Bp],1537,0,0,0,C7,0,E,[T],1,0,0,0,Dt,0,E,[Bp],1025,0,0,0,Cs,0,Dt,[],1025,0,0,0,G9,0,Cs,[],1,0,0,0,B_,"IllegalArgumentException",2,O,[],1,0,0,0,Kc,0,E,[],17,0,0,0,FE,0,E,[],0,0,()=>Ch(),0,I$,0,E,[Bp],1,0,0,0,H8,0,E,[Bp],1025,0,0,0,Ej,0,
E,[Bp],1536,0,0,0,Dd,0,E,[Ej],1,0,0,0,Dc,0,E,[Ej],1,0,0,0,Es,0,E,[],1537,0,0,0,D8,0,E,[Es,BX],0,0,0,0,DO,0,E,[T],1,0,0,0,Ga,0,E,[],1,0,()=>V(),0,DN,0,E,[T],1,0,0,0]);
C9([JB,0,Cs,[],1,0,0,0,GU,0,E,[],1,0,0,0,Fa,0,E,[],1537,0,0,0,FG,0,E,[Fa],1,0,0,0,EL,0,E,[],1,0,0,0,El,"NoSuchElementException",1,O,[],1,0,0,0,GO,0,E,[],1,0,0,0,CC,0,D8,[],0,0,0,0,Ee,0,E,[T],0,0,0,0,Eg,0,E,[T],0,0,0,0,Ef,0,E,[T],0,0,0,0,Gc,"LWJGLException",4,Bv,[],1,0,0,0,DY,0,E,[T],0,0,0,0,D1,0,E,[T],0,0,0,0,D2,0,E,[T],0,0,0,0,DZ,0,E,[T],0,0,0,0,D0,0,E,[T],0,0,0,0,D4,0,E,[T],0,0,0,0,D5,0,E,[T],0,0,0,0,D3,0,E,[T],0,0,0,0,FV,0,E,[],1537,0,0,0,FL,0,Cg,[BX,By,FV],1,0,0,0,EU,0,Cd,[],1,0,0,["B",BJ(BL)],IC,0,E,[],
1,0,0,0,Gx,0,E,[],1,0,0,0,H5,0,E,[],17,0,0,0,CK,"ArrayStoreException",2,O,[],1,0,0,0,JK,0,E,[],17,0,0,0,DM,0,E,[],1,0,()=>Cu(),0,Dn,0,E,[],1,0,()=>BF(),0,GP,0,E,[Bp],1537,0,0,0,Di,0,E,[GP],1,0,0,0,F$,0,E,[],1,0,0,0,F4,0,E,[],17,0,()=>Bi(),0,GK,0,E,[],1537,0,0,0,GS,0,E,[GK],1537,0,0,0,Ex,0,E,[GS],0,0,0,0,F0,0,E,[],0,0,0,0,Fs,0,E,[],1,0,0,0,Fl,"ConcurrentModificationException",1,O,[],1,0,0,0,GV,"NegativeArraySizeException",2,O,[],1,0,0,0]);
let JJ=Bc(Iw),Je=Bc(FK),Ja=Bc(G1),JS=Bc(HM),F_=Bc(E2),EB=Bc(DA);
HH(["Can\'t enter monitor from another thread synchronously","0","<java_object>@","null",": ","\n","\tat ","Caused by: ","[L"," fps, ","main","object","function","string","number","undefined","Either src or dest is null","keyup","NONE","ESCAPE","1","2","3","4","5","6","7","8","9","MINUS","EQUALS","BACK","TAB","Q","W","E","R","T","Y","U","I","O","P","LBRACKET","RBRACKET","RETURN","LCONTROL","A","S","D","F","G","H","J","K","L","SEMICOLON","APOSTROPHE","GRAVE","LSHIFT","BACKSLASH","Z","X","C","V","B","N","M","COMMA",
"PERIOD","SLASH","RSHIFT","MULTIPLY","LMENU","SPACE","CAPITAL","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","NUMLOCK","SCROLL","NUMPAD7","NUMPAD8","NUMPAD9","SUBTRACT","NUMPAD4","NUMPAD5","NUMPAD6","ADD","NUMPAD1","NUMPAD2","NUMPAD3","NUMPAD0","DECIMAL","","F11","F12","F13","F14","F15","F16","F17","F18","KANA","F19","CONVERT","NOCONVERT","YEN","NUMPADEQUALS","CIRCUMFLEX","AT","COLON","UNDERLINE","KANJI","STOP","AX","UNLABELED","NUMPADENTER","RCONTROL","SECTION","NUMPADCOMMA","DIVIDE","SYSRQ","RMENU","FUNCTION",
"PAUSE","HOME","UP","PRIOR","LEFT","RIGHT","END","DOWN","NEXT","INSERT","DELETE","CLEAR","LMETA","RMETA","APPS","POWER","SLEEP","/terrain.png","/","BUTTON","mousedown"]);
Z.prototype.toString=function(){return BT(this);};
Z.prototype.valueOf=Z.prototype.toString;E.prototype.toString=function(){return BT(Jk(this));};
E.prototype.__teavm_class__=function(){return J3(this);};
let C=G3(IQ);
C.javaException=IM;
let Ki=Symbol('jsoClass');
(()=>{let c;c=Da.prototype;c.onAnimationFrame=R(JO);c=C7.prototype;c.handleEvent=R(JD);c=Dd.prototype;c.accept=R(Iu);c=Dc.prototype;c.accept=R(HS);c=DO.prototype;c.handleEvent=R(Ip);c=DN.prototype;c.handleEvent=R(Jp);c=Ee.prototype;c.handleEvent=R(I8);c=Eg.prototype;c.handleEvent=R(IS);c=Ef.prototype;c.handleEvent=R(I5);c=DY.prototype;c.handleEvent=R(Hl);c=D1.prototype;c.handleEvent=R(H4);c=D2.prototype;c.handleEvent=R(Jh);c=DZ.prototype;c.handleEvent=R(J2);c=D0.prototype;c.handleEvent=R(I6);c=D4.prototype;c.handleEvent
=R(Jb);c=D5.prototype;c.handleEvent=R(Ix);c=D3.prototype;c.handleEvent=R(HC);c=Di.prototype;c.onResult=R(G2);})();
B.main=C;}));
