"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let GF=2463534242,Jb=()=>{let x=GF;x^=x<<13;x^=x>>>17;x^=x<<5;GF=x;return x;},K=f=>function(){return f(this);},G=f=>function(p1){return f(this,p1);},W=f=>function(p1,p2){return f(this,p1,p2);},CR=f=>function(p1,p2,p3){return f(this,
p1,p2,p3);},Ct=f=>function(p1,p2,p3,p4){return f(this,p1,p2,p3,p4);},GS=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=Bh(BF(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=B$(args[i]);}Io(()=>{f.call(null,javaArgs);},callback);},Bo=target=>target.$clinit=()=>{},Kr=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls[Y]&&cls[Y].item){++arrayDegree;cls=cls[Y].item;}let clsName="";if(cls[Y].primitiveKind!==0){clsName=cls[Y].name;}else {clsName=cls[Y]?cls[Y].name||"a/"+cls.name:"@"+cls.name;}while
(arrayDegree-->0){clsName+="[]";}return clsName;},F=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=BF();}return function(){superclass.call(this);};},Y=Symbol("teavm_meta"),Ck=cls=>{if(cls[Y].classObject===null){cls[Y].classObject=Hm(cls);}return cls[Y].classObject;},BF=()=>E,BG=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},DZ=source=>{return Object.assign({name:null,binaryName:null,parent:null,superinterfaces:[],modifiers:0,
primitiveKind:0,itemType:null,arrayType:null,enclosingClass:null,declaringClass:null,simpleName:null,clinit:()=>{},constructor:null,enumConstants:()=>null,resolvedEnumConstants:null,reflection:null,classObject:null,assignableCache:null,valueToObject:o=>o,objectToValue:o=>o},source||{});},Cn=(name,binaryName,kind,config)=>{let cls=()=>{};let meta=DZ({name:name,binaryName:binaryName,modifiers:1|1<<4,primitiveKind:kind});cls[Y]=meta;if(typeof config==='function'){config(meta);}return cls;},Iz=Cn("boolean","Z",
1,meta=>{}),FL=Cn("char","C",4,meta=>{}),EL=Cn("int","I",5,meta=>{}),Hc=Cn("double","D",8,meta=>{}),IP=Cn("void","V",9),EI=(a,b)=>a===b?0:a<b? -1:1,Kn=(a,b)=>a===b?0:a>b?1: -1,I=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},DD=(a,b)=>(a>>>0)/(b>>>0)>>>0,Ku=(a,b)=>(a>>>0)%(b>>>0)>>>0,Df=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;},GG=BigInt(0),CT=(lo,hi)=>BigInt.asIntN(64,BigInt.asUintN(64,BigInt(lo))|BigInt.asUintN(64,
BigInt(hi)<<BigInt(32))),B2=val=>BigInt.asIntN(64,BigInt(val|0)),FN=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),Jx=val=>Number(val),G2=val=>Number(BigInt.asIntN(32,val))|0,Ho=(a,b)=>a!==b,Ew=(a,b)=>BigInt.asIntN(64,a+b),H0=(a,b)=>BigInt.asIntN(64,a*b),JW=(a,b)=>BigInt.asIntN(64,a/b),Hq=(a,b)=>BigInt.asIntN(64,a%b),D8=(a,b)=>BigInt.asIntN(64,a&b),H6=(a,b)=>BigInt.asIntN(64,a^b),Jn=(a,b)=>BigInt.asIntN(64,a<<BigInt(b&63)),Jo=(a,b)=>BigInt.asIntN(64,a>>BigInt(b&63)),Bh=(cls,sz)=>{let data
=new Array(sz);data.fill(null);return new (BY(cls))(data);},DN=(cls,data)=>new (BY(cls))(data),Cs=sz=>new Jq(new Uint16Array(sz)),Gp=sz=>new Jy(new Int32Array(sz)),Kw=sz=>new J7(new Int8Array(sz)),C8=sz=>new Hn(new Float64Array(sz)),BY=cls=>{let result=cls[Y].arrayType;if(result===null){function JavaArray(data){(BF()).call(this);this.data=data;}JavaArray.prototype=Object.create((BF()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str
="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.f2=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (BY(this.type))(dataCopy);};let name="["+cls[Y].binaryName;JavaArray[Y]=DZ({name:name,binaryName:name,parent:BF(),itemType:cls});result=JavaArray;cls[Y].arrayType=JavaArray;}return result;};
function KR(array){return array.data.length;}
let DL,Hs=strings=>{JF();DL=new Array(strings.length);for(let i=0;i<strings.length;++i){DL[i]=Ez(B$(strings[i]));}},D=index=>DL[index],Fi=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},B$=str=>str===null?null:FX(str),Cg=str=>str===null?null:str.cJ,JF=()=>Ci(),Ez;
{Ez=str=>str;}let Bs=ex=>{throw HI(ex);},CO=Symbol("javaException"),HI=ex=>{if(!ex.$jsException){E7(ex);}return ex.$jsException;},E7=ex=>{let javaCause=KC(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new BN("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[CO]=ex;ex.$jsException=err;J8(err,ex);},J8=(err,ex)=>{if(typeof G6==="function"&&err.stack){let stack=G6(err.stack);let javaStack
=Bh(Hl(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Jl(B$(element.className),B$(element.methodName),B$(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){HD(ex,javaStack);}}},BN;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");BN=function BN(message,cause){let self=Reflect.construct(Error,[void 0,cause],BN);Object.setPrototypeOf(self,BN.prototype);self[defaultMessage]=message;return self;}
;BN.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:BN},message:{get(){try {let javaException=this[CO];if(typeof javaException==='object'){let javaMessage=IJ(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {BN=Error;}let IQ=e=>e instanceof Error&&typeof e[CO]==='object'?e[CO]:null,IJ=t=>
KA(t),KC=t=>KG(t),Hl=()=>BF(),Jl=(className,methodName,fileName,lineNumber)=>{{return null;}},HD=(e,stack)=>{},Jr=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},IC=typeof $rt_putStdoutCustom==="function"?$rt_putStdoutCustom:typeof console==="object"?Jr(msg=>console.info(msg)):()=>{},Ej=null,HL=data=>{let i=0;let packages=new Array(data.length);for
(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}Ej=packages;},Hv=[],CI=data=>{let packages=Ej;let i=0;while(i<data.length){let cls=data[i++];Hv.push(cls);let m=DZ();cls[Y]=m;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.parent=superclass!==0?superclass
:null;m.superinterfaces=data[i++];if(m.parent){cls.prototype=Object.create(m.parent.prototype);}else {cls.prototype={};}cls.prototype.constructor=cls;m.modifiers=data[i++];m.primitiveKind=0;let innerClassInfo=data[i++];if(innerClassInfo!==0){let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit
=data[i++];m.clinit=clinit!==0?()=>{m.clinit=()=>{};clinit();}:()=>{};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}}},Io=(runner,callback)=>{let result;try {result=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function E(){this.$id$=0;}
let CB=a=>{return Ck(Ie(a));},Ie=a=>{return a.constructor;},Hd=(a,b)=>{return a!==b?0:1;},Jv=a=>{let b,c,d,e,f,g,h,i;b=a;if(!b.$id$)b.$id$=Jb();c=a.$id$;CH();if(!c)d=D(0);else{e=(((32-Fm(c)|0)+4|0)-1|0)/4|0;f=Cs(e);g=f.data;e=(e-1|0)*4|0;h=0;while(e>=0){i=h+1|0;g[h]=D0((c>>>e|0)&15,16);e=e-4|0;h=i;}d=G3(f);}b=Q();M(M(b,D(1)),d);return R(b);},BL=F(0),Cb=F(0),DH=F(0);
function Ba(){E.call(this);this.ed=0;}
let IO=null,Hw=null,Hi=null,Ci=()=>{Ci=Bo(Ba);Im();},HS=(a,b)=>{Ci();a.cJ=Fi(b.data,0,b.data.length);},G3=a=>{let b=new Ba();HS(b,a);return b;},Ii=(a,b)=>{a.cJ=b;},FX=a=>{let b=new Ba();Ii(b,a);return b;},Fo=(a,b)=>{let c;if(b>=0&&b<a.cJ.length)return a.cJ.charCodeAt(b);c=new DM;Bz(c);Bs(c);},BO=a=>{return a.cJ.length;},B_=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof Ba))return 0;c=b;return a.cJ!==c.cJ?0:1;},Fl=a=>{let b;a:{if(!a.ed){b=0;while(true){if(b>=a.cJ.length)break a;a.ed=(31*a.ed|0)+a.cJ.charCodeAt(b)
|0;b=b+1|0;}}}return a.ed;},C3=a=>{let b;b=a.cJ.toLowerCase();if(b!==a.cJ)a=FX(b);return a;},Im=()=>{let b;IO=Cs(0);b=new Ba;Ci();b.cJ="";Hw=b;Hi=new Fy;},DW=F(),EA=F(DW),Hu=null,CH=()=>{CH=Bo(EA);Hg();},Fm=b=>{let c,d;CH();if(!b)return 32;c=0;d=b>>>16|0;if(d)c=16;else d=b;b=d>>>8|0;if(!b)b=d;else c=c|8;d=b>>>4|0;if(!d)d=b;else c=c|4;b=d>>>2|0;if(!b)b=d;else c=c|2;if(b>>>1|0)c=c|1;return (32-c|0)-1|0;},Hg=()=>{Hu=Ck(EL);};
function Dp(){let a=this;E.call(a);a.cV=null;a.cZ=0;}
let CU=(a,b,c)=>{let d,e,f,g;d=a.cZ;e=d-b|0;d=(d+c|0)-b|0;Gx(a,d);f=e-1|0;while(f>=0){g=a.cV.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.cZ=a.cZ+(c-b|0)|0;},Dz=F(0),Eq=F(Dp),Ju=a=>{a.cV=Cs(16);},Q=()=>{let a=new Eq();Ju(a);return a;},M=(a,b)=>{let c,d,e,f,g,h;c=a.cZ;d=a;b=b===null?D(2):b;e=d;if(c>=0&&c<=e.cZ){a:{if(b===null)b=D(2);else if(b.cJ.length?0:1)break a;f=e.cZ+b.cJ.length|0;Gx(e,f);f=e.cZ-1|0;while(f>=c){e.cV.data[f+b.cJ.length|0]=e.cV.data[f];f=f+(-1)|0;}e.cZ=e.cZ+b.cJ.length|0;f=0;while(f<b.cJ.length){g
=e.cV.data;h=c+1|0;g[c]=Fo(b,f);f=f+1|0;c=h;}}return a;}b=new DM;Ga(b);Bs(b);},Bn=(a,b)=>{let c,d,e,f,g,h,i,j;c=a.cZ;d=1;if(b<0){d=0;b= -b|0;}a:{if(Df(b,10)<0){if(d)CU(a,c,c+1|0);else{CU(a,c,c+2|0);e=a.cV.data;f=c+1|0;e[c]=45;c=f;}a.cV.data[c]=D0(b,10);}else{g=1;h=1;f=DD((-1),10);b:{while(true){i=g*10|0;if(Df(i,b)>0){i=g;break b;}h=h+1|0;if(Df(i,f)>0)break;g=i;}}if(!d)h=h+1|0;CU(a,c,c+h|0);if(d)f=c;else{e=a.cV.data;f=c+1|0;e[c]=45;}while(true){if(!i)break a;e=a.cV.data;j=f+1|0;e[f]=D0(DD(b,i),10);b=Ku(b,i);i
=DD(i,10);f=j;}}}return a;},Cp=(a,b)=>{let c,d;c=a.cZ;d=a;CU(d,c,c+1|0);d.cV.data[c]=b;return a;},R=a=>{let b,c,d,e,f;b=new Ba;c=a.cV;d=c.data;e=a.cZ;Ci();f=d.length;if(e>=0&&e<=(f-0|0)){b.cJ=Fi(c.data,0,e);return b;}b=new Cd;Bz(b);Bs(b);},Gx=(a,b)=>{let c,d,e,f;c=a.cV.data.length;if(c<b){b=c>=1073741823?2147483647:CE(b,CE(c*2|0,5));d=a.cV.data;e=Cs(b);f=e.data;b=E8(b,d.length);c=0;while(c<b){f[c]=d[c];c=c+1|0;}a.cV=e;}};
function DU(){let a=this;E.call(a);a.fO=null;a.fY=null;a.fG=0;a.fP=0;}
let KL=a=>{return a;},Fb=a=>{E7(a);},KA=a=>{return a.fO;},KG=a=>{let b;b=a.fY;if(b===a)b=null;return b;},DQ=F(DU),Bb=F(DQ),Bz=a=>{Fb(a);a.fG=1;a.fP=1;},KK=()=>{let a=new Bb();Bz(a);return a;},DE=(a,b)=>{Fb(a);a.fG=1;a.fP=1;a.fO=b;},KS=a=>{let b=new Bb();DE(b,a);return b;},Cm=F(),H2=F(Cm),He=(a,b)=>{switch(a.primitiveKind){default:return Bh(a,b);}},HK=F(Cm),EQ=F(0),GB=F(0),Eg=F(0);
function E6(){E.call(this);this.e4=null;}
let Hm=b=>{let c;c=new E6;c.e4=b;return c;},Ha=a=>{let b;b=a.e4[Y].itemType;return b===null?null:Ck(b);};
function C_(){let a=this;E.call(a);a.eT=0;a.e6=null;a.eP=null;a.fH=null;a.dd=null;a.fn=null;a.eO=null;}
let B0=()=>{B0=Bo(C_);JT();},JN=a=>{let b,c,d,e,f,g;B0();b=window.document;c=b.createElement("canvas");a.dd=c;d=160;c.width=d;c=a.dd;d=120;c.height=d;a.dd.style.setProperty("width","640px");a.dd.style.setProperty("height","480px");a.dd.style.setProperty("image-rendering","pixelated");a.dd.style.setProperty("image-rendering","crisp-edges");d=b.body;c=a.dd;d.appendChild(c);c=a.dd.getContext("2d");a.fn=c;a.eO=c.createImageData(160.0,120.0);c=new Fn;c.cQ=B7();a.e6=c;c=new F3;C9(c,160,120);c.fV=0;d=new Et;C9(d,160,
91);d.dc=C8(14560);d.fi=C8(160);c.c6=d;d=DA();c.fJ=FK(64,64);e=0;while(e<4096){c.fJ.cL.data[e]=I(GM(d),Br(d,5)/4|0);e=e+1|0;}a.eP=c;c=new EO;c.d9=Kw(65536);f=window;d=new Dx;d.fr=c;f.addEventListener("keydown",By(Bu(d),"handleEvent"));f=window;b=new Dw;b.ft=c;f.addEventListener("keyup",By(Bu(b),"handleEvent"));b=window;g=new Du;g.fS=c;b.addEventListener("blur",By(Bu(g),"handleEvent"));a.fH=c;},Jh=()=>{let a=new C_();JN(a);return a;},G1=b=>{B0();BH();Cf(D(3),new FJ);Cf(D(4),new FI);Cf(D(5),new FH);Cf(D(6),new FG);Cf(D(7),
new FF);Cf(D(8),new FE);GC(DN(Ba,[D(3),D(4),D(5),D(6),D(7),D(8)]),0,new Fc);},GC=(b,c,d)=>{let e,f,g,h,i,j;B0();e=b.data;if(c>=e.length){d=new Fq;O();Es=d;BQ(D(9),new Fx);BQ(D(10),new Fw);BQ(D(11),new Fv);BQ(D(12),new Fu);BQ(D(13),new Ft);BQ(D(14),new Fs);BQ(D(15),new Fr);BQ(D(16),new Fz);return;}f=e[c];g=new Fh;g.fm=b;g.fl=c;g.fk=d;BH();h=window.document;i=h.createElement("img");d=Q();M(M(M(d,D(17)),f),D(18));d=Cg(R(d));i.src=d;j=new Dy;j.fC=i;j.fE=h;j.fD=f;j.fB=g;i.addEventListener("load",By(Bu(j),"handleEvent"));},JT
=()=>{return;},Js=F(),Ka=F(),By=(b,c)=>{if(b===null||b===undefined){return null;}let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},Ky=F();
function Bf(){let a=this;E.call(a);a.dr=null;a.d1=0;a.dZ=0;a.eg=null;a.ej=0;a.el=0;a.df=0;a.dw=0;a.dE=0;a.e1=0;a.e7=0;a.eR=0;a.d4=null;a.cO=null;a.di=null;a.cX=null;}
let De=null,D2=null,CG=null,BH=()=>{BH=Bo(Bf);JO();},Cc=a=>{BH();a.eg=CX();a.df=11783906;a.dw=10264731;a.dE=10264731;a.e1=0;a.e7=0;a.eR=0;a.d4=CA();a.di=D(19);},Cf=(b,c)=>{let d;BH();d=De;b=C3(b);Di(d,b,c);},FY=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m;a.cO=b;a.cX=b.cI;a.eg.cR=H(a.df);a.eg.cN=H(a.e1);a.d1=d;a.dZ=e;a.dr=Bh(N,I(d,e));g=0;while(g<e){h=0;while(h<d){i=f.data;j=h+I(g,d)|0;k=i[j]&16777215;l=255-(i[j]>>24&255)|0;m=a.z(h,g,k);m.dg=l;if(m.cN==(-1))m.cN=a.e1;if(m.cW==(-1))m.cW=a.e7;if(m.du==(-1))m.du=a.eR;if(m.cR
==(-1))m.cR=H(a.df);if(m.dt==(-1))m.dt=H(a.dw);if(m.eD==(-1))m.eD=H(a.dE);a.dr.data[j]=m;m.dM=a;m.eb=h;m.ea=g;h=h+1|0;}g=g+1|0;}g=0;while(g<e){h=0;while(h<d){i=f.data;j=h+I(g,d)|0;k=i[j]&16777215;a.A(h,g,a.dr.data[j],k);h=h+1|0;}g=g+1|0;}},V=(a,b)=>{BE(a.d4,b);b.cG=a;FS(b);},Ja=(a,b)=>{Ey(a.d4,b);(P(a,b.d8,b.dB)).F(b);},E$=(a,b,c,d,e)=>{let f,g,h,i,j;d.G(a,b,c);if(e==16776960){a.ej=b;a.el=c;}if(e==11162880){f=new Cy;C0();Ce(f);f.eJ=0.0;f.cC=b;f.cB=c;g=Bp(0.0,0.0,0.0,16,DB);f.fx=g;BE(f.dD,g);V(a,f);}if(e==16711680)V(a,
EH(b,c));if(e==16711681){g=new FU;h=b;i=c;BD(g,h,i,32,H(16776960));g.cC=h;g.cB=i;g.c3=5;g.cP=0.3;g.c$=1;V(a,g);}if(e==16711682){g=new DJ;h=b;i=c;BD(g,h,i,34,H(8562721));g.cC=h;g.cB=i;g.c3=6;g.cP=0.4;g.de=0.05;V(a,g);}if(e==16711683){g=new EP;h=b;i=c;BD(g,h,i,34,H(16776960));g.cC=h;g.cB=i;g.c3=10;g.cP=0.4;g.de=0.05;V(a,g);}if(e==16711684){g=new Da;h=b;i=c;BD(g,h,i,36,H(8711423));g.cC=h;g.cB=i;g.c3=4;g.cP=0.3;g.d2=2.0;g.de=g.de*1.5;g.c$=1;V(a,g);}if(e==16711685){g=new DK;h=b;i=c;BD(g,h,i,36,H(16776960));g.cC=
h;g.cB=i;g.c3=10;g.cP=0.3;g.d2=4.0;g.de=g.de*1.5;g.c$=1;V(a,g);}if(e==16711686){g=new Dt;h=b;i=c;BD(g,h,i,38,H(16777215));g.dz=0.0;g.cC=h;g.cB=i;g.c3=4;g.cP=0.3;g.c$=1;V(a,g);}j=EI(e,16711687);if(!j){g=new CV;h=b;i=c;BD(g,h,i,38,H(16776960));g.dG=0.0;g.ef=0;g.cC=h;g.cB=i;g.c3=10;g.c$=1;V(a,g);}if(!(e!=1712392&&j)){d.cW=7;d.du=7;}if(e==13027014)d.cR=H(10526880);if(e==13026967)d.cR=H(10526880);if(e==6633984){d.dt=H(11888128);d.cW=25;}if(e==9699227){d.cR=H(2797363);d.cN=8;}},Ee=(a,b,c,d)=>{let e,f,g,h,i,j;if(d
==9699227)return CX();if(d==37632){e=new Gz;Bg(e);e.ff=0;e.cW=1;e.cK=1;return e;}if(d==16777215)return CX();if(d==65535){e=new FT;CC(e);e.fd=0;e.cN=1;return e;}if(d==16777060){e=new Fp;Bg(e);e.fe=0;e.cN=1;e.cK=1;f=Bp(0.0,0.0,0.0,16,H(16776960));e.fK=f;Bt(e,f);return e;}if(d==255){e=new CM;Bg(e);e.d_=0;e.cK=1;return e;}if(d==16726530){e=new Gd;Bg(e);f=Bp(0.0,0.0,0.0,3,H(16776960));e.dI=f;BE(e.dK,f);return e;}if(d==5000268){e=new FR;Bg(e);e.ei=0;f=Bp(0.0,0.0,0.0,0,2105376);e.fv=f;Bt(e,f);e.cK=1;return e;}if(d
==16738047)return Ei(0);if(d==10354846)return Ei(1);if(d==12697933){e=new E3;Bg(e);e.eI=0;f=Bp(0.0,0.0,0.0,18,H(16777088));e.fA=f;Bt(e,f);e.cK=1;return e;}if(d==13027014)return JS();if(d==65447){e=new D7;CC(e);e.ew=0;e.cN=2;return e;}if(d==37760){e=new Gu;Bg(e);e.dX=0;e.cW=2;return e;}if(d==16711685)return Eb();if(d==4144992)return Eb();if(d==13026967){e=new EC;E4(e);e.cN=5;return e;}if(d==16759298){e=new Gf;Bg(e);e.eN=0;e.cK=1;f=Bp(0.0,0.0,0.0,20,H(14876644));e.fa=f;Bt(e,f);return e;}if(d!=7639847){if(d==1712392)return FO();if
(d==49831){e=new Fj;CC(e);e.eY=0;e.cN=11;return e;}if(d!=86)return FO();e=new Em;Bg(e);return e;}e=new Gj;Bg(e);e.cW=7;e.du=7;e.cK=1;d=0;while(d<6){g=Bm(BP)-0.5;h=(Bm(BP)-0.7)*0.3;i=Bm(BP)-0.5;j=Bp(g,h,i,38+Br(BP,2)|0,H(2105376));Bt(e,j);d=d+1|0;}return e;},P=(a,b,c)=>{let d;if(b>=0&&c>=0){d=a.d1;if(b<d&&c<a.dZ)return a.dr.data[b+I(c,d)|0];}return a.eg;},ET=(b,c)=>{let d,e,f;BH();if(Gm(CG,c)===null?0:1)return Dq(CG,c);d=D2;e=C3(c);d=Dq(d,e);if(d===null){b=new Bb;d=Q();M(M(d,D(20)),c);DE(b,R(d));Bs(b);}e=De;f
=C3(c);e=Dq(e,f);if(e===null){b=new Bb;d=Q();M(M(d,D(21)),c);DE(b,R(d));Bs(b);}e=e.R();e.S(b,c,d.fy,d.fL,d.fz);Di(CG,c,e);return e;},H_=(a,b,c,d,e)=>{let f,g,h,i,j,k,l;f=Bj((d+b)/2.0)|0;g=Bj((e+c)/2.0)|0;h=g-2|0;g=g+2|0;i=f-2|0;f=f+2|0;while(h<=g){j=i;while(j<=f){k=(P(a,j,h)).dj;l=0;k=k;while(l<k.cS){if(EN(Bw(k,l),b,c,d,e))return 1;l=l+1|0;}j=j+1|0;}h=h+1|0;}return 0;},Jm=(a,b,c,d,e)=>{let f,g,h,i,j,k,l,m,n;f=Bj((d+b)/2.0)|0;g=Bj((e+c)/2.0)|0;h=g-2|0;g=g+2|0;i=f-2|0;f=f+2|0;while(h<=g){j=i;while(j<=f){k=(P(a,
j,h)).dj;l=0;m=k;while(l<m.cS){n=Bw(m,l);if(!n.c$&&EN(n,b,c,d,e))return 1;l=l+1|0;}j=j+1|0;}h=h+1|0;}return 0;},Iw=a=>{let b,c,d,e;b=0;while(true){c=a.d4;if(b>=c.cS)break;c=Bw(c,b);c.W();FS(c);if(!c.d3)d=b;else{c=a.d4;d=b+(-1)|0;D4(c,b);}b=d+1|0;}d=0;while(d<a.dZ){e=0;while(true){b=a.d1;if(e>=b)break;a.dr.data[e+I(d,b)|0].W();e=e+1|0;}d=d+1|0;}},BR=(a,b,c)=>{let d,e,f,g;d=0;while(d<a.dZ){e=0;while(true){f=a.d1;if(e>=f)break;g=a.dr.data[e+I(d,f)|0];if(g.dg==b)g.Y(c);e=e+1|0;}d=d+1|0;}},Id=(a,b)=>{let c,d,e,f;c
=0;while(c<a.dZ){d=0;while(true){e=a.d1;if(d>=e)break;f=a.dr.data[d+I(c,e)|0];if(f.dg==b&&f instanceof C$){a.ej=d;a.el=c;}d=d+1|0;}c=c+1|0;}},Ca=(a,b)=>{let c;if(b==20){c=a.cO;S();BV(c,B9);}if(b==21){c=a.cO;S();BV(c,Cv);}},J0=a=>{let b,c,d;b=a.cO;c=a.cX;d=new E5;d.eG=30;d.e5=c;b.cQ=d;},Kc=a=>{let b,c,d;b=a.cO;c=a.cX;d=new Gw;d.eB=30;d.fg=c;b.cQ=d;},GJ=(a,b)=>{let c,d;c=a.cO;d=new E2;d.d$=30;d.eA=b;c.cQ=d;},Hh=(b,c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p,q,r,s;BH();g=b.naturalWidth;h=b.naturalHeight;f=c.createElement("canvas");c
=g;f.width=c;c=h;f.height=c;i=f.getContext("2d");i.drawImage(b,0.0,0.0);j=i.getImageData(0.0,0.0,g,h).data;k=I(g,h);l=Gp(k);m=l.data;n=0;while(n<k){o=n*4|0;p=j[o]&255;q=j[o+1|0]&255;r=j[o+2|0]&255;m[n]=(j[o+3|0]&255)<<24|p<<16|q<<8|r;n=n+1|0;}b=D2;c=C3(d);d=new Fa;d.fy=g;d.fL=h;d.fz=l;Di(b,c,d);if(e!==null){b=e;m=b.fm;s=b.fl;b=b.fk;B0();GC(m,s+1|0,b);}},JO=()=>{De=D5();D2=D5();CG=D5();},CW=F(0),Fc=F(),F6=F(0),Fy=F(),DO=F(),Ht=null,Jz=null,CL=()=>{CL=Bo(DO);Ia();},D0=(b,c)=>{CL();if(c>=2&&c<=36&&b>=0&&b<c)return b
<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},Ia=()=>{Ht=Ck(FL);Jz=Bh(DO,128);},BU=F(0),FJ=F(),JP=a=>{let b;b=new EY;Cc(b);b.di=D(22);return b;},FI=F(),KB=a=>{let b;b=new Go;Cc(b);b.dw=4210752;b.dE=4210752;b.df=4210752;b.di=D(23);return b;},FH=F(),Kz=a=>{let b;b=new F4;Cc(b);b.eR=(-1);b.dw=5276243;b.e7=24;b.df=10526880;b.di=D(24);return b;},FG=F(),Kg=a=>{let b;b=new Fe;Cc(b);b.dU=0;b.dw=9069718;b.dE=9069718;b.df=13610459;b.di=D(25);return b;},FF=F(),I$=a=>{let b;b=new GH;Cc(b);b.dw=12114912;b.dE=12114912;b.df
=7071999;b.di=D(26);return b;},FE=F(),JL=a=>{let b;b=new Gi;Cc(b);b.df=12994900;b.dw=9325137;b.dE=9325137;b.di=D(27);return b;};
function Fh(){let a=this;E.call(a);a.fm=null;a.fl=0;a.fk=null;}
let HQ=F();
function C2(){E.call(this);this.fF=null;}
let Hp=(a,b)=>{a.fF=b;},Cq=a=>{let b=new C2();Hp(b,a);return b;},FQ=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=B$(typeof b);d=!B_(c,D(28))&&!B_(c,D(29))?0:1;CD();e=Ec;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Cq(b);e.set(b,new WeakRef(h));return h;}if(B_(c,D(30))){i=C4;j=Ea;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Cq(b);k=h;i.set(b,new WeakRef(k));j.register(k,
b);return h;}if(B_(c,D(31))){l=CY;m=Ek;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Cq(b);k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(B_(c,D(32))){f=ES;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Cq(b);ES=new WeakRef(h);return h;}}return Cq(b);},T=b=>{if(b!==null&&!(b instanceof BF()))b=FQ(b);return b;},Bu=b=>{if(b===null)return null;return !(b instanceof C2)?b:b.fF;},Dh=b=>{if(b===null)return null;return b instanceof BF()
&&b instanceof C2?Bu(b):b;},EG=F(0),DT=F(),C5=F(0);
function Gg(){let a=this;DT.call(a);a.dn=0;a.c4=null;a.dL=0;a.fQ=0.0;a.e8=0;}
let GX=a=>{let b;b=FV(16);a.dn=0;a.c4=Bh(CN,b);a.fQ=0.75;Gh(a);},D5=()=>{let a=new Gg();GX(a);return a;},FV=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},Gh=a=>{a.e8=a.c4.data.length*a.fQ|0;},Dq=(a,b)=>{let c;c=Gm(a,b);if(c===null)return null;return c.en;},Gm=(a,b)=>{let c,d;if(b===null)c=GD(a);else{d=Fl(b);c=EU(a,b,d&(a.c4.data.length-1|0),d);}return c;},EU=(a,b,c,d)=>{let e,f;e=a.c4.data[c];while(e!==null){if(e.eS==d){f=e.fc;if
(b!==f&&!B_(b,f)?0:1)break;}e=e.d7;}return e;},GD=a=>{let b;b=a.c4.data[0];while(b!==null&&b.fc!==null){b=b.d7;}return b;},Di=(a,b,c)=>{let d,e,f;if(b===null){d=GD(a);if(d===null){a.dL=a.dL+1|0;d=F_(a,null,0,0);e=a.dn+1|0;a.dn=e;if(e>a.e8)Gq(a);}}else{e=Fl(b);f=e&(a.c4.data.length-1|0);d=EU(a,b,f,e);if(d===null){a.dL=a.dL+1|0;d=F_(a,b,f,e);e=a.dn+1|0;a.dn=e;if(e>a.e8)Gq(a);}}b=d.en;d.en=c;return b;},F_=(a,b,c,d)=>{let e,f,g;e=new CN;f=null;e.fc=b;e.en=f;e.eS=d;g=a.c4.data;e.d7=g[c];g[c]=e;return e;},Gq=a=>{let b,
c,d,e,f,g,h,i;b=a.c4.data.length;b=FV(!b?1:b<<1);c=Bh(CN,b);d=c.data;e=0;f=b-1|0;while(true){g=a.c4.data;if(e>=g.length)break;h=g[e];g[e]=null;while(h!==null){b=h.eS&f;i=h.d7;h.d7=d[b];d[b]=h;h=i;}e=e+1|0;}a.c4=c;Gh(a);},BT=F(0),B6=F(0);
function Dy(){let a=this;E.call(a);a.fC=null;a.fE=null;a.fD=null;a.fB=null;}
let Jw=(b,c)=>{b=b;Hh(b.fC,b.fE,b.fD,b.fB,c);},Cd=F(Bb),Ga=a=>{Bz(a);},KN=()=>{let a=new Cd();Ga(a);return a;},JD=F(Bb),CP=F(Bb),D_=F(0);
function DS(){let a=this;E.call(a);a.fc=null;a.en=null;}
function CN(){let a=this;DS.call(a);a.eS=0;a.d7=null;}
function Fa(){let a=this;E.call(a);a.fy=0;a.fL=0;a.fz=null;}
let Fq=F(),Gl=F(),FZ=null,GK=null,En=null,ED=null,Gy=null,CF=null,FB=null,Co=null,D1=0,Es=null,O=()=>{O=Bo(Gl);GW();},BJ=()=>{let b,c,d,e;O();b=D1-1|0;D1=b;if(!b&&Es!==null){B0();c=F9();DR=U(T(c),D(33));Cw=U(T(c),D(34));Bv=U(T(c),D(35));Ch=U(T(c),D(36));IK=U(T(c),D(37));E9=U(T(c),D(38));Ff=U(T(c),D(39));EV=U(T(c),D(40));Gv=U(T(c),D(41));EB=U(T(c),D(42));EE=U(T(c),D(43));FA=U(T(c),D(44));Ev=U(T(c),D(45));EZ=U(T(c),D(46));E_=U(T(c),D(47));Fk=U(T(c),D(48));D9=U(T(c),D(49));F5=U(T(c),D(50));Gr=U(T(c),D(51));EK=
U(T(c),D(52));Fg=U(T(c),D(53));d=Jh();if(!d.eT){d.eT=1;c=new Dv;c.ey=d;c.dC=0.0;e=performance.now()/1000.0;c.eQ=e;c.eV=0.016666666666666666;c.dS=0;c.eZ=e;requestAnimationFrame(By(Bu(c),"onAnimationFrame"));}}},BQ=(b,c)=>{let d,e,f;O();d=window.document;e=d.createElement("img");b=Cg(b);e.src=b;f=new Dg;f.fo=e;f.fq=d;f.fp=c;e.addEventListener("load",By(Bu(f),"handleEvent"));},H=b=>{let c,d,e;O();c=b>>16&255;d=b>>8&255;e=b&255;return ((c*85|0)/255|0)<<16|((d*85|0)/255|0)<<8|((e*85|0)/255|0);},Km=(b,c,d,e)=>{let f,
g,h,i,j,k,l,m,n,o,p;O();f=b.naturalWidth;g=b.naturalHeight;h=c.createElement("canvas");e=f;h.width=e;c=g;h.height=c;c=h.getContext("2d");c.drawImage(b,0.0,0.0);i=c.getImageData(0.0,0.0,f,g).data;j=FK(f,g);k=0;f=I(f,g);while(k<f){g=k*4|0;l=i[g]&255;m=i[g+1|0]&255;n=i[g+2|0]&255;o=(i[g+3|0]&255)<<24|l<<16|m<<8|n;p=(o&15)>>2;if(o==(-65281))p=(-1);j.cL.data[k]=p;k=k+1|0;}d.bo(j);},GW=()=>{D1=8;},BC=F(0),Fx=F(),H9=(a,b)=>{O();FZ=b;BJ();},Fw=F(),Ij=(a,b)=>{O();GK=b;BJ();},Fv=F(),Is=(a,b)=>{O();En=b;BJ();},Fu=F(),ID
=(a,b)=>{O();ED=b;BJ();},Ft=F(),IE=(a,b)=>{O();Gy=b;BJ();},Fs=F(),It=(a,b)=>{O();CF=b;BJ();},Fr=F(),Ik=(a,b)=>{O();FB=b;BJ();},Fz=F(),G4=(a,b)=>{O();Co=b;BJ();};
function Dg(){let a=this;E.call(a);a.fo=null;a.fq=null;a.fp=null;}
let IB=(b,c)=>{b=b;Km(b.fo,b.fq,b.fp,c);};
function B5(){let a=this;E.call(a);a.cH=0;a.cF=0;a.cL=null;}
let C9=(a,b,c)=>{a.cH=b;a.cF=c;a.cL=Gp(I(b,c));},FK=(a,b)=>{let c=new B5();C9(c,a,b);return c;},Kd=(a,b,c,d)=>{let e,f,g,h,i,j;e=0;while(e<b.cF){a:{f=e+d|0;if(f>=0&&f<a.cF){g=0;while(true){h=b.cH;if(g>=h)break a;i=g+c|0;if(i>=0){j=a.cH;if(i<j)a.cL.data[i+I(f,j)|0]=b.cL.data[g+I(e,h)|0];}g=g+1|0;}}}e=e+1|0;}},BI=(a,b,c,d,e,f,g,h,i)=>{let j,k,l,m,n,o;j=0;while(j<h){a:{k=j+d|0;if(k>=0&&k<a.cF){l=0;while(true){if(l>=g)break a;m=l+c|0;if(m>=0){n=a.cH;if(m<n){o=b.cL.data[(l+e|0)+I(j+f|0,b.cH)|0];if(o>=0)a.cL.data[m
+I(k,n)|0]=I(o,i);}}l=l+1|0;}}}j=j+1|0;}},F7=(a,b,c,d,e,f,g,h,i,j)=>{let k,l,m,n,o,p,q;k=0;l=I(i,c);i=I(h,c);while(k<l){a:{m=k+e|0;if(m>=0&&m<a.cF){n=0;while(true){if(n>=i)break a;o=n+d|0;if(o>=0){p=a.cH;if(o<p){q=b.cL.data[((n/c|0)+f|0)+I((k/c|0)+g|0,b.cH)|0];if(q>=0)a.cL.data[o+I(m,p)|0]=I(q,j);}}n=n+1|0;}}}k=k+1|0;}},L=(a,b,c,d,e)=>{let f,g,h,i,j,k;f=0;while(f<b.cJ.length){a:{g=Fo(b,f);h=CE(0,0);if(g<65536){g=g&65535;while(true){if(h>=D(54).cJ.length){h=(-1);break a;}if(D(54).cJ.charCodeAt(h)==g)break;h=
h+1|0;}}else{CL();i=(55296|(g-65536|0)>>10&1023)&65535;j=(56320|g&1023)&65535;while(true){if(h>=(D(54).cJ.length-1|0)){h=(-1);break a;}if(D(54).cJ.charCodeAt(h)==i&&D(54).cJ.charCodeAt((h+1|0))==j)break;h=h+1|0;}}}if(h>=0){i=h%42|0;k=h/42|0;O();BI(a,ED,c+(f*6|0)|0,d,i*6|0,k*8|0,5,8,e);}f=f+1|0;}},Cu=(a,b,c,d,e,f)=>{let g;while(c<e){g=b;while(g<d){a.cL.data[g+I(c,a.cH)|0]=f;g=g+1|0;}c=c+1|0;}},DM=F(Cd);
function GE(){E.call(this);this.fM=null;}
let DR=null,Cw=null,Bv=null,Ch=null,IK=null,E9=null,Ff=null,EV=null,Gv=null,EB=null,EE=null,FA=null,Ev=null,EZ=null,E_=null,Fk=null,D9=null,F5=null,Gr=null,EK=null,Fg=null,U=(b,c)=>{let d,e;d=new GE;e=new DP;e.fj=d;JQ(Dh(b),Cg(c),By(Bu(e),"onLoaded"));return d;},J=a=>{let b,c;b=F9();c=a.fM;IV(Dh(b),Dh(c));},F9=()=>{if(!window._audioCtx){window._audioCtx=new (window.AudioContext||window.webkitAudioContext)();}return window._audioCtx;},JQ=(b,c,d)=>{((((fetch(c)).then(function(res){return res.arrayBuffer();})).then(function(data)
{return b.decodeAudioData(data);})).then(function(buf){d(buf);})).catch(function(err){console.error('Failed to load sound:',c,err);});},IV=(b,c)=>{if(!c)return;if(b.state==='suspended'){b.resume();}var source=b.createBufferSource();source.buffer=c;source.connect(b.destination);source.start(0);};
function Fn(){let a=this;E.call(a);a.fu=0;a.c1=null;a.cI=null;a.ex=0;a.cQ=null;}
let Bx=(a,b,c)=>{let d,e;a.ex=30;Ja(a.c1,a.cI);b=ET(a,b);a.c1=b;Id(b,c);b=a.cI;d=a.c1;c=d.ej;b.cC=c;e=d.el;b.cB=e;(P(d,c,e)).fh=1;b=a.cI;b.cC=b.cC+Z(b.cM)*0.2;b=a.cI;b.cB=b.cB+Be(b.cM)*0.2;V(a.c1,a.cI);},Kt=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o;c=a.ex;if(c>0){a.ex=c-1|0;return;}b=b.data;a.fu=a.fu+1|0;c=!b[17]&&!b[18]&&!b[0]&&!b[16]?0:1;d=!b[37]&&!b[100]?0:1;e=!b[39]&&!b[102]?0:1;f=!b[87]&&!b[38]&&!b[104]?0:1;g=!b[83]&&!b[40]&&!b[98]?0:1;a:{b:{if(!b[65]){if(!c)break b;if(!d)break b;}h=1;break a;}h=0;}c:{d:{if
(!b[68]){if(!c)break d;if(!e)break d;}i=1;break c;}i=0;}e:{f:{if(!b[81]){if(c)break f;if(!d)break f;}j=1;break e;}j=0;}g:{h:{if(!b[69]){if(c)break h;if(!e)break h;}k=1;break g;}k=0;}l=b[32];m=0;while(m<8){c=49+m|0;if(b[c]){b[c]=0;n=a.cI;n.db=m;n.c5=0;}m=m+1|0;}if(b[27]){b[27]=0;if(a.cQ===null){o=new GI;o.eM=DN(Ba,[D(55),D(56)]);o.cY=1;a.cQ=o;}}if(l)b[32]=0;n=a.cQ;if(n===null){HB(a.cI,f,g,h,i,j,k);if(l)Jc(a.cI);Iw(a.c1);}else{b[104]=0;b[38]=0;b[87]=0;b[98]=0;b[40]=0;b[83]=0;b[65]=0;b[68]=0;n.bC(a,f,g,h,i,l);}},BV
=(a,b)=>{let c,d,e,f;c=a.cI;S();if(b===B9)c.dl=c.dl+20|0;if(b===Cv)c.dv=c.dv+1|0;d=0;a:{while(true){e=c.dh.data;f=e.length;if(d>=f){d=0;while(d<f){if(e[d]===B8){e[d]=b;c.db=d;c.c5=0;c=c.cG;if(c!==null)GJ(c,b);break a;}d=d+1|0;}break a;}if(e[d]===b)break;d=d+1|0;}c=c.cG;if(c!==null)GJ(c,b);}};
function F3(){let a=this;B5.call(a);a.fJ=null;a.c6=null;a.fV=0;}
let HX=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u;if(b.c1===null){d=a.cH;e=a.cF;Cu(a,0,0,d,e,0);}else{f=b.cI;g=f.c5<=0?0:1;a:{h=f.dh.data[f.db];if(b.ex>0){d=a.cH;e=a.cF;i=a;Cu(i,0,0,d,e,0);j=Bh(Ba,1).data;f=b.c1.di;k=Q();M(M(k,D(57)),f);j[0]=R(k);l=0;while(true){m=j.length;if(l>=m)break;f=j[l];d=(a.cH-(BO(j[l])*6|0)|0)/2|0;e=a.c6.cF;m=m*8|0;e=(e-m|0)/2|0;n=l*8|0;L(i,f,d,(e+n|0)+1|0,1118481);L(i,j[l],(a.cH-(BO(j[l])*6|0)|0)/2|0,((a.c6.cF-m|0)/2|0)+n|0,5592388);l=l+1|0;}}else{b:{JA(a.c6,b);KE(a.c6,b.c1);f
=b.c1;k=b.cI;i=P(f,k.cC+0.5|0,k.cB+0.5|0);if(i.dR!==null&&c){l=0;while(true){j=i.dR.data;if(l>=j.length)break b;f=a.c6;k=j[l];m=(a.cH-(BO(j[l])*6|0)|0)/2|0;d=(a.c6.cF-(i.dR.data.length*8|0)|0)/2|0;e=l*8|0;d=(d+e|0)+1|0;L(f,k,m,d,1118481);f=a.c6;j=i.dR.data;k=j[l];n=(a.cH-(BO(j[l])*6|0)|0)/2|0;m=((a.c6.cF-(i.dR.data.length*8|0)|0)/2|0)+e|0;L(f,k,n,m,5592388);l=l+1|0;}}}f=a.c6;k=a;Kd(k,f,0,0);f=b.cI;d=f.et*32.0|0;o=Z(f.ep*0.4)*1.0;p=b.cI.d6;e=o*p+p*2.0|0;if(g){d=0;e=d;}q=d+(a.cH/2|0)|0;m=e+((a.cF-29|0)-45|0)|
0;S();if(h!==B8){O();F7(k,CF,3,q,m,(16*h.es|0)+1|0,17+(!g?0:16)|0,15,15,H(h.eu));}f=b.cI;m=f.dp;if(!(m<=0&&!f.dk)){o=1.5-m/30.0;f=EX(B2(111));if(b.cI.dk)o=0.5;m=0;while(true){if(m>=a.cL.data.length)break a;l=a.cH;p=m%l|0;k=a.c6;p=(p-k.cH/2.0)/l*2.0;r=m/l|0;s=k.cF;r=(r-s/2.0)/s*2.0;if(Bm(f)+o<BB(p*p+r*r))a.cL.data[m]=I(Br(f,5)/4|0,5570560);m=m+1|0;}}}}O();f=Gy;l=a.cF-29|0;n=a.cH;q=H(7368816);t=a;BI(t,f,0,l,0,0,n,29,q);L(t,D(58),3,(a.cF-26|0)+0|0,65535);m=b.cI.dQ;f=Q();M(Bn(f,m),D(59));L(t,R(f),10,(a.cF-26|0)
+0|0,16777215);L(t,D(60),3,(a.cF-26|0)+8|0,16776960);m=b.cI.dx;f=Q();Bn(f,m);L(t,R(f),10,(a.cF-26|0)+8|0,16777215);L(t,D(61),3,(a.cF-26|0)+16|0,16711680);m=b.cI.c8;f=Q();Bn(f,m);L(t,R(f),10,(a.cF-26|0)+16|0,16777215);m=0;while(m<8){k=b.cI.dh.data[m];S();if(k!==B8){f=CF;l=30+(m*16|0)|0;BI(t,f,l,(a.cF-29|0)+2|0,k.es*16|0,0,16,16,H(k.eu));if(k===B9){d=b.cI.dl;f=Q();Bn(f,d);u=R(f);L(t,u,(l+17|0)-(BO(u)*6|0)|0,((a.cF-29|0)+1|0)+10|0,5592405);}if(k===Cv){d=b.cI.dv;f=Q();Bn(f,d);u=R(f);L(t,u,(l+17|0)-(BO(u)*6|0)|0,
((a.cF-29|0)+1|0)+10|0,5592405);}}m=m+1|0;}BI(t,CF,30+(b.cI.db*16|0)|0,(a.cF-29|0)+2|0,0,48,17,17,H(16777215));f=h.e_;L(t,f,26+((128-(BO(f)*4|0)|0)/2|0)|0,a.cF-9|0,16777215);}b=b.cQ;if(b!==null){m=0;while(true){j=a.cL.data;if(m>=j.length)break;j[m]=(j[m]&16579836)>>2;m=m+1|0;}b.bO(a);}if(!c){m=0;while(true){j=a.cL.data;if(m>=j.length)break;j[m]=(j[m]&16579836)>>2;m=m+1|0;}if(Ho(Hq(JW(GZ(),B2(450)),B2(2)),GG)){c=(a.cH-(BO(D(62))*6|0)|0)/2|0;m=(a.cF/3|0)+4|0;L(a,D(62),c,m,16777215);}}};
function EO(){E.call(this);this.d9=null;}
let Gk=F(0);
function DP(){E.call(this);this.fj=null;}
let JJ=(b,c)=>{c=c===null?null:c instanceof BF()?c:FQ(c);b.fj.fM=c;},Bc=F();
function El(){let a=this;Bc.call(a);a.eW=null;a.c0=0;a.eX=0;}
let J6=a=>{a.eW=DN(Ba,[D(63),D(64),D(65)]);a.c0=0;a.eX=1;},B7=()=>{let a=new El();J6(a);return a;},KH=(a,b)=>{let c,d,e,f,g;Cu(b,0,0,160,120,0);O();BI(b,Co,0,8,0,0,160,36,H(16777215));c=0;while(true){d=a.eW.data;if(c>=d.length)break;e=d[c];f=9474192;if(a.c0==c){g=Q();M(M(g,D(66)),e);e=R(g);f=16777088;}L(b,e,40,60+(c*10|0)|0,H(f));c=c+1|0;}L(b,D(67),5,111,H(3158064));},I7=(a,b,c,d,e,f,g)=>{let h,i,j,k;if(a.eX){a.eX=0;J(DR);}if(!(!c&&!d))J(Ch);if(c)a.c0=a.c0-1|0;if(d)a.c0=a.c0+1|0;if(a.c0<0)a.c0=0;c=a.c0;d=a.eW.data.length;if
(c>=d)a.c0=d-1|0;if(g){J(Bv);if(!a.c0){b.cQ=null;BH();h=CG;if(h.dn>0){h.dn=0;i=h.c4.data;j=null;c=0;d=i.length;if(c>d){b=new CP;Bz(b);Bs(b);}while(c<d){e=c+1|0;i[c]=j;c=e;}h.dL=h.dL+1|0;}b.c1=ET(b,D(3));h=new Bl;Ce(h);h.db=0;h.dp=0;h.c8=20;h.dQ=0;h.dx=0;h.dk=0;h.eK=0;h.dl=0;h.dv=0;i=Bh(Cl,8);k=i.data;h.dh=i;h.dA=0;h.cP=0.3;c=0;d=k.length;while(c<d){S();k[c]=B8;c=c+1|0;}b.cI=h;j=b.c1;h.cG=j;j.cX=h;h.cC=j.ej;h.cB=j.el;V(j,h);b.cI.cM=3.541592653589793;}c=a.c0;if(c==1){h=new EW;h.ek=30;b.cQ=h;}if(c==2){h=new Ep;h.eq
=30;b.cQ=h;}}};
function Et(){let a=this;B5.call(a);a.dc=null;a.fi=null;a.dV=0.0;a.d5=0.0;a.em=0.0;a.eo=0.0;a.ec=0.0;a.dJ=0.0;a.ez=0.0;a.ee=0.0;a.d0=0.0;}
let JA=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x;c=0;while(true){d=a.cH;if(c>=d)break;a.fi.data[c]=0.0;c=c+1|0;}e=0;while(e<I(d,a.cF)){a.dc.data[e]=10000.0;e=e+1|0;}f=b.cI;g=f.cM;a.d0=g;a.dV=f.cC-Z(g)*0.3;a.d5=b.cI.cB-Be(a.d0)*0.3;h=Z(b.cI.ep*0.4)*0.01;f=b.cI;a.em=(-0.2)+h*f.d6-f.dY;a.ez=a.cH/2.0;a.ee=a.cF/3.0;a.eo=Be(a.d0);a.ec=Z(a.d0);a.dJ=a.cF;f=b.c1;i=Bj(a.dV)|0;j=Bj(a.d5)|0;k=j-6|0;j=j+6|0;l=i-6|0;i=i+6|0;m=k;while(m<=j){n=l;while(n<=i){o=P(f,n,m);p=n+1|0;q=P(f,p,m);r=m+1|0;s=P(f,n,r);if(o instanceof Cr)
{t=1.0-o.cT*7.0/8.0;if(!q.cU){h=n+0.5;u=h-0.125;v=m;w=v+t;B1(a,u,v,u,w,o.cN,o.cR,t,0.0);g=h+0.125;B1(a,g,w,g,v,o.cN,o.cR,0.0,t);B1(a,u,w,g,w,o.cN,(o.cR&16711422)>>1,0.375,0.625);}else{u=n;v=u+t;h=m+0.5;w=h-0.125;B1(a,v,w,u,w,o.cN,(o.cR&16711422)>>1,0.0,t);g=h+0.125;B1(a,u,g,v,g,o.cN,(o.cR&16711422)>>1,t,0.0);B1(a,v,g,v,w,o.cN,o.cR,0.375,0.625);}}if(!o.cU){if(q.cU){h=p;CJ(a,h,m,h,r,q.cN,q.cR);}if(s.cU){g=p;h=r;CJ(a,g,h,n,h,s.cN,(s.cR&16711422)>>1);}}else{if(!q.cU){g=p;CJ(a,g,r,g,m,o.cN,o.cR);}if(!s.cU){g=n;h
=r;CJ(a,g,h,p,h,o.cN,(o.cR&16711422)>>1);}}n=p;}m=m+1|0;}while(k<=j){n=l;while(n<=i){o=P(f,n,k);r=0;while(true){b=o.dj;if(r>=b.cS)break;q=Bw(b,r);e=0;while(true){b=q.dD;if(e>=b.cS)break;x=Bw(b,e);FD(a,q.cC+x.da,0.0-x.dq,q.cB+x.c_,x.c2,x.c9);e=e+1|0;}r=r+1|0;}e=0;while(true){b=o.dK;if(e>=b.cS)break;x=Bw(b,e);FD(a,n+x.da,0.0-x.dq,k+x.c_,x.c2,x.c9);e=e+1|0;}n=n+1|0;}k=k+1|0;}IS(a,f);},IS=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r;c=0;while(c<a.cF){d=(c+0.5-a.ee)/a.dJ;e=1;f=a.em*8.0;g=(4.0-f)/d;if(d<0.0){e=0;g
=(4.0+f)/ -d;}h=0;while(true){i=a.cH;if(h>=i)break;if(!(a.dc.data[h+I(c,i)|0]<=g)){d=(a.ez-h)/a.dJ*g;f=a.eo;j=d*f;k=a.ec;j=j+g*k+(a.dV+0.5)*8.0;k=g*f-d*k+(a.d5+0.5)*8.0;i=j*2.0|0;l=k*2.0|0;m=P(b,i>>4,l>>4);n=m.dt;o=m.cW;if(!e){n=m.eD;o=m.du;}if(o<0)a.dc.data[h+I(c,a.cH)|0]=(-1.0);else{p=a.dc.data;q=h+I(c,a.cH)|0;p[q]=g;r=a.cL.data;O();r[q]=I(GK.cL.data[((i&15)+((o%8|0)*16|0)|0)+(((l&15)+((o/8|0)*16|0)|0)*128|0)|0],n);}}h=h+1|0;}c=c+1|0;}},FD=(a,b,c,d,e,f)=>{let g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,
bc,bd;g=(b-a.dV)*2.0;b=a.ec;h=g-b*0.2;i=(c-a.em)*2.0;c=(d-a.d5)*2.0;d=a.eo;j=c-d*0.2;k=h*d-j*b;l=j*d+h*b;if(l<0.1)return;b=a.ez;c=k/l;d=a.dJ;m=b-c*d;n=i/l*d+a.ee;b=a.cF/l;o=m-b;p=m+b;q=n-b;r=n+b;s=BS(o)|0;t=BS(p)|0;u=BS(q)|0;v=BS(r)|0;if(s<0)s=0;w=a.cH;if(t>w)t=w;if(u<0)u=0;x=a.cF;if(v<=x)x=v;d=l*4.0;l=r-q;b=p-o;v=(e%8|0)*16|0;while(u<x){y=(u-q)/l*16.0|0;z=s;while(z<t){ba=(z-o)/b*16.0|0;bb=a.dc.data;bc=z+I(u,w)|0;if(bb[bc]>d){O();bd=En.cL.data[(ba+v|0)+((y+((e/8|0)*16|0)|0)*128|0)|0];if(bd>=0){a.cL.data[bc]
=I(bd,f);bb[bc]=d;}}z=z+1|0;}u=u+1|0;}},CJ=(a,b,c,d,e,f,g)=>{B1(a,b,c,d,e,f,g,0.0,1.0);},B1=(a,b,c,d,e,f,g,h,i)=>{let j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ba,bb,bc,bd,be,bf,bg,bh,bi,bj,bk,bl,bm,bn,bo,bp,bq,br,bs,bt,bu,bv;b=b-0.5;j=a.dV;k=(b-j)*2.0;c=c-0.5;b=a.d5;l=(c-b)*2.0;c=a.eo;m=k*c;n=a.ec;o=m-l*n;p=a.em;q=((-0.5)-p)*2.0;r=(0.5-p)*2.0;s=l*c+k*n;t=(d-0.5-j)*2.0;u=(e-0.5-b)*2.0;v=t*c-u*n;w=u*c+t*n;b=h*16.0;c=i*16.0;x=EI(s,0.2);if(x<0&&w<0.2)return;if(x<0){d=0.2-s;e=w-s;y=d/e;s=s+e*y;o=o+(v-o)*y;b=b+(c-b)*y;}if
(w<0.2){d=0.2-s;e=w-s;y=d/e;w=s+e*y;v=o+(v-o)*y;c=b+(c-b)*y;}d=a.ez;e=o/s;h=a.dJ;n=d-e*h;z=d-v/w*h;if(n>=z)return;x=BS(n)|0;ba=BS(z)|0;if(x<0)x=0;bb=a.cH;if(ba<=bb)bb=ba;d=q/s;e=a.dJ;d=d*e;h=a.ee;p=d+h;bc=r/s*e+h;bd=q/w*e+h;be=r/w*e+h;bf=1.0/s;bg=1.0/w;bh=bg-bf;bi=b*bf;bj=c*bg-bi;bk=1.0/(z-n);c=bd-p;e=be-bc;bl=(f%8|0)*16|0;while(x<bb){a:{j=(x-n)*bk;m=bf+bh*j;bm=a.fi.data;if(!(bm[x]>m)){bm[x]=m;bn=(bi+bj*j)/m|0;bo=p+c*j-0.5;bp=bc+e*j;bq=BS(bo)|0;br=BS(bp)|0;if(bq<0)bq=0;ba=a.cF;if(br<=ba)ba=br;bs=1.0/(bp-bo);br
=bn+bl|0;d=1.0/m*4.0;while(true){if(bq>=ba)break a;bt=16.0*(bq-bo)*bs|0;bu=a.cL.data;bv=x+I(bq,a.cH)|0;O();bu[bv]=I(FZ.cL.data[br+((bt+((f/8|0)*16|0)|0)*128|0)|0],g);a.dc.data[bv]=d;bq=bq+1|0;}}}x=x+1|0;}},KE=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n;c=0;while(true){d=a.cH;if(c>=I(d,a.cF))break;e=a.dc.data[c];if(e<0.0){d=(Bj((c%d|0)-a.d0*512.0/6.283185307179586)|0)&511;f=c/a.cH|0;g=a.cL.data;O();g[c]=I(FB.cL.data[d+(f*512|0)|0],4473941);}else{h=c%d|0;i=(c/d|0)*14|0;j=h;k=d;l=(j-k/2.0)/k;m=a.cL.data;n=m[c];h=((300.0
-e*6.0*(l*l*2.0+1.0)|0)+(((h+i|0)&3)*4|0)|0)>>4<<4;if(h<0)h=0;if(h>255)h=255;m[c]=(I(n>>16&255,h)/255|0)<<16|(I(n>>8&255,h)/255|0)<<8|(I(n&255,h)/255|0);}c=c+1|0;}},F$=F(0),Br=(a,b)=>{let c,d,e;if(b<=0){c=new CP;Bz(c);Bs(c);}CH();d=((b&((-2147483648)>>>Fm(b)|0))<<1)-1|0;c=a;while(true){e=GM(c)&d;if(e<b)break;}return e;};
function Dk(){let a=this;E.call(a);a.fw=0.0;a.eL=0;a.e9=GG;}
let Hf=a=>{Er(a,FN(BM()*2.81474976710656E14-1.0));},DA=()=>{let a=new Dk();Hf(a);return a;},Er=(a,b)=>{a.e9=D8(H6(b,CT(3740067437, 5)),CT(4294967295, 65535));},EX=a=>{let b=new Dk();Er(b,a);return b;},GM=a=>{return Dj(a,32);},Dj=(a,b)=>{let c;c=D8(Ew(H0(a.e9,CT(3740067437, 5)),B2(11)),CT(4294967295, 65535));a.e9=c;return G2(Jo(c,48-b|0));},Bm=a=>{return Jx(Ew(Jn(B2(Dj(a,26)),27),B2(Dj(a,27))))*1.1102230246251565E-16;},Ef=a=>{let b,c,d,e,f;if(a.eL){a.eL=0;return a.fw;}b=new F2;b.fs=a;b=b;while(true){while(true)
{c=2.0*D$(b)-1.0;d=2.0*D$(b)-1.0;e=c*c+d*d;if(e>=1.0)continue;else break;}if(e===0.0)continue;else break;}e=BB((-2.0)*Iq(e)/e);f=C8(2).data;f[0]=c*e;f[1]=d*e;a.eL=1;a.fw=f[1];return f[0];};
function Dx(){E.call(this);this.fr=null;}
let Kx=(b,c)=>{let d,e;b=b;d=c.keyCode;if(d>0){e=b.fr.d9.data;if(d<e.length)e[d]=1;}a:{if(d!=32){if(d<37)break a;if(d>40)break a;}c.preventDefault();}};
function Dw(){E.call(this);this.ft=null;}
let Je=(b,c)=>{let d,e;b=b;d=c.keyCode;if(d>0){e=b.ft.d9.data;if(d<e.length)e[d]=0;}};
function Du(){E.call(this);this.fS=null;}
let HR=(b,c)=>{let d,e;b=b;d=0;while(true){e=b.fS.d9.data;if(d>=e.length)break;e[d]=0;d=d+1|0;}},KF=F(),FC=F(),Hj=null,Ec=null,C4=null,CY=null,ES=null,Ea=null,Ek=null,CD=()=>{CD=Bo(FC);I0();},I0=()=>{let b;Hj=new WeakMap();Ec=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();C4=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();CY=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(C4===null)b=null;else{b=new Dc;b=new FinalizationRegistry(By(Bu(b),"accept"));}Ea=b;if(CY===null)b=null;else{b=new Db;b=
new FinalizationRegistry(By(Bu(b),"accept"));}Ek=b;},Jf=F(),I6=F(),Z=b=>{return Math.sin(b);},Be=b=>{return Math.cos(b);},Iq=b=>{return Math.log(b);},BB=b=>{return Math.sqrt(b);},BS=b=>{return Math.ceil(b);},Bj=b=>{return Math.floor(b);},Ed=(b,c)=>{return Math.atan2(b,c);},BM=()=>{return J_();},J_=()=>{return Math.random();},E8=(b,c)=>{if(b<c)c=b;return c;},CE=(b,c)=>{if(b>c)c=b;return c;},Ip=b=>{return Math.abs(b);},F8=b=>{return Ip(b);},H7=F(),D3=F(0),Dc=F(),Iv=(b,c)=>{b;CD();C4.delete(c);},Db=F(),HF=(b,c)=>
{b;CD();CY.delete(c);},F0=F(0);
function Dv(){let a=this;E.call(a);a.dC=0.0;a.eQ=0.0;a.eV=0.0;a.dS=0;a.eZ=0.0;a.ey=null;}
let Hk=(b,c)=>{let d,e,f,g,h,i,j,k,l,m;c;b=b;d=performance.now()/1000.0;e=d-b.eQ;b.eQ=d;if(e<0.0)e=0.0;if(e>0.1)e=0.1;b.dC=b.dC+e;f=0;while(b.dC>b.eV){c=b.ey;Kt(c.e6,c.fH.d9);b.dC=b.dC-b.eV;f=1;}if(f){c=b.ey;HX(c.eP,c.e6,1);g=c.eO.data;f=0;while(f<19200){h=c.eP.cL.data[f];i=h>>16&255;j=h>>8&255;h=h&255;k=f*4|0;g[k]=i;g[k+1|0]=j;g[k+2|0]=h;g[k+3|0]=255;f=f+1|0;}c.fn.putImageData(c.eO,0.0,0.0);b.dS=b.dS+1|0;}if(d-b.eZ>=1.0){if(Dr===null){c=new EJ;l=null;m=null;c.f0=l;c.fW=Q();c.f1=Cs(32);c.fX=0;c.fZ=m;Dr=c;}g
=Dr;f=b.dS;c=Q();M(Bn(c,f),D(68));c=R(c);l=g;Gc(l,c);Gc(l,D(69));b.dS=0;b.eZ=d;}if(b.ey.eT)requestAnimationFrame(By(Bu(b),"onAnimationFrame"));},Ic=F(),II=F(),I9=F(),Dr=null,GZ=()=>{return FN((new Date()).getTime());},Gn=F(0),E0=F(0),Gb=F(0),DG=F();
function Do(){DG.call(this);this.f0=null;}
function Dn(){let a=this;Do.call(a);a.fX=0;a.fW=null;a.f1=null;a.fZ=null;}
let Ds=F(Dn),EJ=F(Ds),Gc=(a,b)=>{if(b===null)b=D(2);IC(Cg(b));},HT=F();
function Bi(){let a=this;E.call(a);a.dD=null;a.cC=0.0;a.cB=0.0;a.cM=0.0;a.cE=0.0;a.cD=0.0;a.c7=0.0;a.cP=0.0;a.cG=null;a.d8=0;a.dB=0;a.c$=0;a.d3=0;}
let Bd=null,Bq=()=>{Bq=Bo(Bi);J4();},Ce=a=>{Bq();a.dD=CA();a.cP=0.4;a.d8=(-1);a.dB=(-1);a.c$=0;a.d3=0;},KO=()=>{let a=new Bi();Ce(a);return a;},FS=a=>{let b,c,d;b=a.cC+0.5|0;c=a.cB+0.5|0;d=a.d8;if(!(b==d&&c==a.dB)){(P(a.cG,d,a.dB)).F(a);a.d8=b;a.dB=c;if(!a.d3)(P(a.cG,b,c)).I(a);}},KP=a=>{return a.d3;},BW=a=>{(P(a.cG,a.d8,a.dB)).F(a);a.d3=1;},Cz=a=>{let b,c,d,e,f,g;b=F8(a.cE*100.0)+1.0|0;c=b;a:{while(true){if(b<=0)break a;d=a.cE;e=a.cC;d=d*b/c;if(C6(a,e+d,a.cB))break;a.cE=0.0;b=b+(-1)|0;}a.cC=a.cC+d;}b=F8(a.cD
*100.0)+1.0|0;f=b;b:{while(true){if(b<=0)break b;e=a.cD;d=a.cC;g=a.cB;e=e*b/f;if(C6(a,d,g+e))break;a.cD=0.0;b=b+(-1)|0;}a.cB=a.cB+e;}},C6=(a,b,c)=>{let d,e,f,g,h,i,j,k,l,m,n,o,p,q;d=b+0.5;e=Bj(d-a.cP)|0;f=Bj(d+a.cP)|0;g=c+0.5;h=Bj(g-a.cP)|0;i=Bj(g+a.cP)|0;if((P(a.cG,e,h)).b7(a))return 0;if((P(a.cG,f,h)).b7(a))return 0;if((P(a.cG,e,i)).b7(a))return 0;if((P(a.cG,f,i)).b7(a))return 0;j=Bj(d)|0;k=Bj(g)|0;l=k-2|0;i=k+2|0;k=j-2|0;m=j+2|0;while(l<=i){n=k;while(n<=m){o=(P(a.cG,n,l)).dj;p=0;o=o;while(p<o.cS){q=Bw(o,
p);if(q!==a&&!q.b8(a,a.cC,a.cB,a.cP)&&q.b8(a,b,c,a.cP)){q.b9(a);a.b9(q);return 0;}p=p+1|0;}n=n+1|0;}l=l+1|0;}return 1;},HH=(a,b)=>{return;},DX=(a,b,c,d,e)=>{let f,g;if(b instanceof Bk&&b.dP===a)return 0;f=a.cC;g=a.cP;if(f+g<=c-e)return 0;if(f-g>=c+e)return 0;f=a.cB;if(f+g<=d-e)return 0;if(!(f-g>=d+e))return 1;return 0;},IG=(a,b,c)=>{let d,e;d=a.cC;e=a.cP;if(d+e<=b)return 0;if(d-e>=b)return 0;b=a.cB;if(b+e<=c)return 0;if(!(b-e>=c))return 1;return 0;},EN=(a,b,c,d,e)=>{let f,g;f=a.cC;g=a.cP;if(f+g<=b)return 0;if
(f-g>=d)return 0;b=a.cB;if(b+g<=c)return 0;if(!(b-g>=e))return 1;return 0;},GY=(a,b,c)=>{return 0;},GQ=a=>{return;},J4=()=>{Bd=DA();};
function Bl(){let a=this;Bi.call(a);a.d6=0.0;a.ep=0.0;a.et=0.0;a.db=0;a.c5=0;a.dY=0.0;a.eF=0.0;a.dp=0;a.c8=0;a.dQ=0;a.dx=0;a.dk=0;a.eK=0;a.dl=0;a.dv=0;a.fN=null;a.dh=null;a.dA=0;a.ev=0;}
let HB=(a,b,c,d,e,f,g)=>{let h,i,j,k,l,m,n,o,p,q,r;if(!a.dk)a.ev=a.ev+1|0;else{b=0;c=a.eK+1|0;a.eK=c;if(c<=120){g=b;f=b;e=b;d=b;c=b;}else{Kc(a.cG);g=b;f=b;e=b;d=b;c=b;}}h=a.c5;if(h>0)a.c5=h-1|0;h=a.dp;if(h>0)a.dp=h-1|0;i=P(a.cG,a.cC+0.5|0,a.cB+0.5|0);j=i.b_(a);if(i instanceof CM&&!(a.fN instanceof CM))J(EB);a.fN=i;if(a.dk)j=(-0.6);k=a.dY;if(j>k){a.dY=k+(j-k)*0.2;a.eF=0.0;}else{l=a.eF-0.01;a.eF=l;l=k+l;a.dY=l;if(l<j){a.dY=j;a.eF=0.0;}}m=0.03*i.ca(a);if(f)a.c7=a.c7+0.05;if(g)a.c7=a.c7-0.05;k=0.0;n=0.0;if(b)n=
(-1.0);if(c)n=n+1.0;if(d)k=(-1.0);if(e)k=k+1.0;o=k*k+n*n;l=!(o>0.0)?1.0:BB(o);a:{k=k/l;l=n/l;n=a.d6*0.6;a.d6=n;j=a.et*0.8;a.et=j;a.et=j+a.c7;j=k*k+l*l;a.d6=n+BB(j);a.ep=a.ep+BB(j)*i.ca(a);p=a.dA;a.dA=0;if(i instanceof Dm){q=CZ(a);S();if(q!==BZ){j=a.cE;o=j*j;m=a.cD;n=m*m;if(o>n){a.dA=1;a.cD=0.0;if(!(j>0.0))a.cE=(-0.08);else a.cE=0.08;l=a.cB;a.cB=l+((l+0.5|0)-l)*0.2;}else if(!(o<n)){a.cE=j-(k*Be(a.cM)+l*Z(a.cM))*0.1;a.cD=a.cD-(l*Be(a.cM)-k*Z(a.cM))*0.1;}else{a.dA=1;a.cE=0.0;if(!(m>0.0))a.cD=(-0.08);else a.cD=
0.08;l=a.cC;a.cC=l+((l+0.5|0)-l)*0.2;}if(p)break a;if(!a.dA)break a;J(D9);break a;}}a.cE=a.cE-(k*Be(a.cM)+l*Z(a.cM))*m;a.cD=a.cD-(l*Be(a.cM)-k*Z(a.cM))*m;}Cz(a);r=i.cd(a);a.cE=a.cE*r;a.cD=a.cD*r;l=a.cM;m=a.c7;a.cM=l+m;a.c7=m*0.4;},Jc=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v;if(a.dk)return;if(a.c5>0)return;b=a.dh.data[a.db];S();if(b===B9){if(a.dl>0){J(EZ);a.c5=10;V(a.cG,GN(a,a.cC,a.cB,a.cM,1.0,0,16777215));a.dl=a.dl-1|0;}return;}if(b===Cv){if(a.dv>0&&a.c8<20){J(Fg);a.c5=20;c=a.c8;Bq();c=c+(5+Br(Bd,6)
|0)|0;a.c8=c;if(c>20)a.c8=20;a.dv=a.dv-1|0;}return;}if(b===DV)a.c5=10;if(b===Cj)a.c5=10;if(b===Cx)a.c5=10;d=2.0*Z(a.cM);e=2.0*Be(a.cM);f=a.cC+0.5|0;g=a.cB+0.5|0;h=CA();i=g-3|0;j=g+3|0;c=f-3|0;k=f+3|0;while(i<=j){l=c;while(l<=k){m=(P(a.cG,l,i)).dj;n=0;m=m;while(n<m.cS){o=Bw(m,n);if(o!==a)BE(h,o);n=n+1|0;}l=l+1|0;}i=i+1|0;}n=0;m=h;while(n<100){p=a.cC;q=n;r=p+d*q/100.0;s=a.cB+e*q/100.0;j=0;while(j<m.cS){o=Bw(m,j);if(IG(o,r,s)&&o.cg(a,a.dh.data[a.db]))return;j=j+1|0;}t=r+0.5|0;u=s+0.5|0;if(!(t==(a.cC+0.5|0)&&u==
(a.cB+0.5|0))){v=P(a.cG,t,u);if(v.ch(a.cG,a.dh.data[a.db]))return;if(v.b7(a))return;}n=n+1|0;}},IN=(a,b,c,d,e)=>{return DX(a,b,c,d,e);},CZ=a=>{return a.dh.data[a.db];},E1=(a,b,c)=>{let d,e,f;if(a.dp<=0&&!a.dk){a.dp=40;c=a.c8-c|0;a.c8=c;if(c<=0){a.c8=0;J(Gv);a.dk=1;}J(E9);d=b.cC-a.cC;e=b.cB-a.cB;f=BB(d*d+e*e);a.cE=a.cE-d/f*0.1;a.cD=a.cD-e/f*0.1;d=a.c7;Bq();a.c7=d+(Bm(Bd)-0.5)*0.2;return;}},GU=(a,b)=>{if(b instanceof Bk){if(CB(b.dP)===CB(a))return;if(a.dp>0)return;BW(b);E1(a,b,1);}};
function GI(){let a=this;Bc.call(a);a.eM=null;a.cY=0;}
let JB=(a,b)=>{let c,d,e,f,g;O();BI(b,Co,0,8,0,0,160,36,H(16777215));c=0;while(true){d=a.eM.data;if(c>=d.length)break;e=d[c];f=9474192;if(a.cY==c){g=Q();M(M(g,D(66)),e);e=R(g);f=16777088;}L(b,e,40,60+(c*10|0)|0,H(f));c=c+1|0;}},KD=(a,b,c,d,e,f,g)=>{if(!(!c&&!d))J(Ch);if(c)a.cY=a.cY-1|0;if(d)a.cY=a.cY+1|0;if(a.cY<0)a.cY=0;c=a.cY;d=a.eM.data.length;if(c>=d)a.cY=d-1|0;if(g){J(Bv);if(!a.cY)b.cQ=B7();if(a.cY==1)b.cQ=null;}};
function N(){let a=this;E.call(a);a.cK=0;a.cU=0;a.dR=null;a.dK=null;a.dj=null;a.cN=0;a.cR=0;a.dt=0;a.eD=0;a.cW=0;a.du=0;a.dM=null;a.eb=0;a.ea=0;a.dg=0;}
let BP=null,G0=null,D6=()=>{D6=Bo(N);Iu();},Bg=a=>{D6();a.cK=0;a.cU=0;a.dK=CA();a.dj=CA();a.cN=(-1);a.cR=(-1);a.dt=(-1);a.eD=(-1);a.cW=(-1);a.du=(-1);},FO=()=>{let a=new N();Bg(a);return a;},Bt=(a,b)=>{BE(a.dK,b);},HM=(a,b,c)=>{return 0;},B4=a=>{let b,c,d;b=0;while(true){c=a.dK;if(b>=c.cS)break;c=Bw(c,b);c.W();if(!c.dy)d=b;else{c=a.dK;d=b+(-1)|0;D4(c,b);}b=d+1|0;}},Ge=(a,b)=>{Ey(a.dj,b);},B3=(a,b)=>{BE(a.dj,b);},HN=(a,b)=>{return a.cK;},Kb=(a,b,c,d)=>{return;},Ir=(a,b)=>{return 0.0;},IU=(a,b)=>{return 1.0;},Ix
=(a,b)=>{return 0.6;},IW=(a,b)=>{return;},Iu=()=>{BP=DA();G0=CX();};
function DY(){let a=this;E.call(a);a.fU=null;a.fT=0;}
function Cl(){let a=this;DY.call(a);a.es=0;a.eu=0;a.e_=null;a.fI=null;}
let B8=null,Cj=null,B9=null,CQ=null,Cx=null,BZ=null,DV=null,Cv=null,GT=null,S=()=>{S=Bo(Cl);HU();},JH=(a,b,c,d,e,f,g)=>{S();a.fU=b;a.fT=c;a.es=d;a.eu=e;a.e_=f;a.fI=g;},BK=(a,b,c,d,e,f)=>{let g=new Cl();JH(g,a,b,c,d,e,f);return g;},HU=()=>{let b,c,d;B8=BK(D(70),0,(-1),16761699,D(19),D(19));Cj=BK(D(71),1,0,16761699,D(72),D(73));B9=BK(D(74),2,1,15395562,D(75),D(76));CQ=BK(D(77),3,2,8174591,D(78),D(79));Cx=BK(D(80),4,3,13421772,D(81),D(82));BZ=BK(D(83),5,4,11432191,D(84),D(85));DV=BK(D(86),6,5,16728128,D(87),D(88));b
=BK(D(89),7,6,4915015,D(90),D(91));Cv=b;c=Bh(Cl,8);d=c.data;d[0]=B8;d[1]=Cj;d[2]=B9;d[3]=CQ;d[4]=Cx;d[5]=BZ;d[6]=DV;d[7]=b;GT=c;};
function EW(){Bc.call(this);this.ek=0;}
let JG=(a,b)=>{let c,d;Cu(b,0,0,160,120,0);L(b,D(64),40,8,H(16777215));c=Bh(Ba,7).data;c[0]=D(92);c[1]=D(93);c[2]=D(19);c[3]=D(94);c[4]=D(95);c[5]=D(19);c[6]=D(96);d=0;while(d<c.length){L(b,c[d],4,32+(d*8|0)|0,H(10526880));d=d+1|0;}if(!a.ek)L(b,D(97),40,b.cF-16|0,H(16777088));},Hy=(a,b,c,d,e,f,g)=>{c=a.ek;if(c>0)a.ek=c-1|0;else if(g){J(Bv);b.cQ=B7();}};
function Ep(){Bc.call(this);this.eq=0;}
let G$=(a,b)=>{let c,d;Cu(b,0,0,160,120,0);L(b,D(65),60,8,H(16777215));c=Bh(Ba,8).data;c[0]=D(98);c[1]=D(99);c[2]=D(100);c[3]=D(101);c[4]=D(19);c[5]=D(102);c[6]=D(103);c[7]=D(104);d=0;while(d<c.length){L(b,c[d],4,28+(d*8|0)|0,H(10526880));d=d+1|0;}if(!a.eq)L(b,D(97),40,b.cF-16|0,H(16777088));},HO=(a,b,c,d,e,f,g)=>{c=a.eq;if(c>0)a.eq=c-1|0;else if(g){J(Bv);b.cQ=B7();}},BA=F(N),CC=a=>{Bg(a);a.cU=1;a.cK=1;},CX=()=>{let a=new BA();CC(a);return a;};
function Cr(){let a=this;BA.call(a);a.dW=0;a.cT=0.0;}
let E4=a=>{CC(a);a.dW=0;a.cT=0.0;a.cN=4;a.cU=0;},JS=()=>{let a=new Cr();E4(a);return a;},Kk=(a,b,c)=>{let d;d=a.dW?0:1;a.dW=d;if(!d)J(Ch);else J(Bv);return 1;},Ks=a=>{let b,c,d,e,f;B4(a);b=a.dW;if(!b)a.cT=a.cT-0.2;else a.cT=a.cT+0.2;if(a.cT<0.0)a.cT=0.0;if(a.cT>1.0)a.cT=1.0;if(a.cT<0.875&&!b&&!a.cK){c=a.dM;d=a.eb;e=d-0.5;f=a.ea;if(H_(c,e,f-0.5,d+0.5,f+0.5)){a.cT=0.875;return;}}a.cK=!(a.cT<0.875)?0:1;},I2=(a,b)=>{let c;c=Kn(a.cT,0.875);if(c>=0&&b instanceof Bl)return a.cK;if(c>=0&&b instanceof Bk)return a.cK;if
(c>=0&&b instanceof DJ)return a.cK;return 1;};
function BX(){let a=this;E.call(a);a.da=0.0;a.dq=0.0;a.c_=0.0;a.c2=0;a.c9=0;a.dy=0;}
let C1=(a,b,c,d,e,f)=>{a.c9=2105376;a.dy=0;a.da=b;a.dq=c;a.c_=d;a.c2=e;a.c9=f;},Bp=(a,b,c,d,e)=>{let f=new BX();C1(f,a,b,c,d,e);return f;},JV=a=>{return;},ER=F(0),DC=F(0),C7=F(),Gs=F(0),EF=F(0);
function DF(){C7.call(this);this.eh=0;}
let FW=F(0);
function FM(){let a=this;DF.call(a);a.ds=null;a.cS=0;}
let HW=a=>{a.ds=Bh(E,10);},CA=()=>{let a=new FM();HW(a);return a;},Bw=(a,b)=>{Eu(a,b);return a.ds.data[b];},BE=(a,b)=>{let c,d,e,f,g,h;c=a.cS+1|0;d=a.ds.data.length;if(d<c){c=d>=1073741823?2147483647:CE(c,CE(d*2|0,5));e=a.ds;f=Ha(CB(e));if(f===null){b=new Eo;Bz(b);Bs(b);}if(f===Ck(IP)){b=new CP;Bz(b);Bs(b);}if(c<0){b=new GO;Bz(b);Bs(b);}g=e.data;e=He(f.e4,c);h=E8(c,g.length);d=0;while(d<h){e.data[d]=g[d];d=d+1|0;}a.ds=e;}e=a.ds.data;h=a.cS;a.cS=h+1|0;e[h]=b;a.eh=a.eh+1|0;return 1;},D4=(a,b)=>{let c,d,e,f;Eu(a,
b);c=a.ds.data;d=c[b];e=a.cS-1|0;a.cS=e;while(b<e){f=b+1|0;c[b]=c[f];b=f;}c[e]=null;a.eh=a.eh+1|0;return d;},Ey=(a,b)=>{let c,d,e,f;c=a;d=c.cS;e=0;a:{while(true){if(e>=d){e=(-1);break a;}f=Bw(c,e);if(b===f?1:b!==null?Hd(b,f):f!==null?0:1)break;e=e+1|0;}}if(e<0)return 0;D4(a,e);return 1;},Eu=(a,b)=>{let c;if(b>=0&&b<a.cS)return;c=new Cd;Bz(c);Bs(c);};
function CM(){N.call(this);this.d_=0;}
let J3=a=>{let b;B4(a);b=a.d_-1|0;a.d_=b;if(b<=0){a.cW=8+Br(BP,3)|0;a.dt=H(255);a.d_=16;}},Hz=(a,b)=>{let c;if(b instanceof Bl){c=CZ(b);S();if(c===CQ)return 0;}if(!(b instanceof Bk))return a.cK;return 0;},Ji=(a,b)=>{return (-0.5);},G_=(a,b)=>{return 0.4;},Dm=F(N),GR=a=>{Bg(a);a.cK=0;a.cW=16;},Eb=()=>{let a=new Dm();GR(a);return a;},HY=a=>{B4(a);a.dt=H(8421631);},In=(a,b)=>{let c;c=CZ(b);S();if(c!==BZ)return 1.4;return 0.05;},HJ=(a,b)=>{let c;c=CZ(b);S();if(c!==BZ)return 1.0;return 0.98;},G8=(a,b)=>{if(b instanceof Bl)return 0;if
(b instanceof Bk)return 0;if(b instanceof DK)return 0;if(!(b instanceof Da))return 1;return 0;};
function Bk(){Bi.call(this);this.dP=null;}
let Dd=(a,b,c,d,e,f,g,h)=>{let i;Ce(a);a.cP=0.01;a.dP=b;a.cE=Z(e)*0.2*f;f=Be(e)*0.2*f;a.cD=f;a.cC=c-f/2.0;a.cB=d+a.cE/2.0;b=a.dD;i=Bp(0.0,0.0,0.0,24+g|0,H(h));BE(b,i);a.c$=1;},GN=(a,b,c,d,e,f,g)=>{let h=new Bk();Dd(h,a,b,c,d,e,f,g);return h;},Kp=a=>{let b,c,d,e;b=a.cE;c=a.cD;d=a;Cz(d);e=a.cE;if(!(!(e===0.0&&a.cD===0.0)&&e===b&&a.cD===c))BW(d);},Jd=(a,b,c,d,e)=>{if(b instanceof Bk)return 0;if(b!==a.dP)return DX(a,b,c,d,e);return 0;},Hb=(a,b)=>{return;},Gi=F(Bf),Jg=(a,b,c,d,e,f)=>{FY(a,b,c,d,e,f);BR(a,6,1);BR(a,
7,1);},IH=(a,b)=>{if(b==1)Bx(a.cO,D(3),2);},I_=(a,b)=>{let c;Ca(a,b);if(b==1){c=a.cO;S();BV(c,Cj);}},H4=(a,b,c)=>{BR(a,b,c);if(b==5)BR(a,6,c?0:1);if(b==4)BR(a,7,c?0:1);},F4=F(Bf),JK=(a,b)=>{if(b==1)Bx(a.cO,D(3),1);if(b==2)Bx(a.cO,D(4),1);if(b==3)Bx(a.cO,D(6),1);if(b==5)Bx(a.cO,D(7),1);},Kv=(a,b)=>{let c;Ca(a,b);if(b==1){c=a.cO;S();BV(c,Cx);}},Go=F(Bf),I4=(a,b)=>{if(b==1)Bx(a.cO,D(5),2);},IA=(a,b)=>{let c;Ca(a,b);if(b==1){c=a.cO;S();BV(c,CQ);}};
function Fe(){Bf.call(this);this.dU=0;}
let KJ=(a,b)=>{if(b==1)Bx(a.cO,D(5),3);},IT=(a,b)=>{let c;Ca(a,b);if(b==1){c=a.cO;S();BV(c,BZ);}},HC=(a,b,c)=>{let d,e;d=a.dU;b=1<<b;e=d|b;a.dU=e;if(!c)a.dU=e^b;if(a.dU!=14)BR(a,1,0);else BR(a,1,1);},GH=F(Bf),Ib=(a,b)=>{if(b==1)Bx(a.cO,D(5),5);},G7=(a,b)=>{let c;Ca(a,b);if(b==1){c=a.cO;S();BV(c,BZ);}},EY=F(Bf),IZ=(a,b,c,d,e)=>{E$(a,b,c,d,e);},Ki=(a,b,c,d)=>{return Ee(a,b,c,d);},JZ=(a,b)=>{if(b==1)Bx(a.cO,D(5),1);if(b==2)Bx(a.cO,D(8),1);},J9=(a,b)=>{Ca(a,b);},HZ=F(),Eo=F(Bb),GO=F(Bb);
function Gw(){let a=this;Bc.call(a);a.eB=0;a.fg=null;}
let HA=(a,b)=>{let c,d,e,f;O();BI(b,Co,0,10,0,39,160,23,H(16777215));c=a.fg.ev/60|0;d=c/60|0;c=c%60|0;e=Q();Cp(Bn(e,d),58);e=R(e);if(c<10){f=Q();Cp(M(f,e),48);e=R(f);}f=Q();Bn(M(f,e),c);f=R(f);c=a.fg.dx;e=Q();M(Bn(M(e,D(105)),c),D(106));L(b,R(e),40,45,H(9474192));e=Q();M(M(e,D(107)),f);L(b,R(e),40,55,H(9474192));if(!a.eB)L(b,D(97),40,b.cF-40|0,H(16777088));},JC=(a,b,c,d,e,f,g)=>{c=a.eB;if(c>0)a.eB=c-1|0;else if(g){J(Bv);b.cQ=B7();}};
function Gz(){N.call(this);this.ff=0;}
let HE=(a,b)=>{B3(a,b);if(!a.ff&&b instanceof Cy){BW(b);a.ff=1;a.cK=0;b=new BX;C0();C1(b,0.0,0.0,0.0,10,DB);Bt(a,b);J(Gr);}},H5=(a,b)=>{if(!(b instanceof Cy))return a.cK;return 0;};
function FT(){BA.call(this);this.fd=0;}
let J5=(a,b,c)=>{let d,e;if(a.fd)return 0;a.fd=1;a.cK=0;a.cU=0;J(Fk);d=0;while(d<32){e=EM();e.c9=a.cR;Bt(a,e);d=d+1|0;}return 1;};
function Fp(){let a=this;N.call(a);a.fe=0;a.fK=null;}
let I3=(a,b,c)=>{if(a.fe)return 0;c=a.fK;c.c2=c.c2+1|0;a.fe=1;b.cs(a.dg);J(E_);return 1;};
function Gd(){N.call(this);this.dI=null;}
let I5=(a,b,c,d)=>{let e,f,g,h,i,j,k;e=EX(B2(I(c+(d*1000|0)|0,341871231)));f=0;g=c-1|0;h=d-1|0;i=c+1|0;j=d+1|0;a:{while(true){if(f>=1000)break a;k=Br(e,4);if(!k&&(P(b,g,d)).cU){b=a.dI;b.da=b.da-0.4;break a;}if(k==1&&(P(b,c,h)).cU){b=a.dI;b.c_=b.c_-0.4;break a;}if(k==2&&(P(b,i,d)).cU){b=a.dI;b.da=b.da+0.4;break a;}if(k==3&&(P(b,c,j)).cU)break;f=f+1|0;}b=a.dI;b.c_=b.c_+0.4;}},Jt=a=>{B4(a);if(!Br(BP,4))a.dI.c2=3+Br(BP,2)|0;};
function FR(){let a=this;N.call(a);a.fv=null;a.ei=0;}
let Ig=(a,b,c)=>{if(a.ei)return 0;S();if(c===Cx){J(F5);a.fv.c2=1;a.ei=1;}return 1;},G9=(a,b)=>{let c;c=a.ei;if(c&&b instanceof Bl)return 0;if(c&&b instanceof Bk)return 0;return a.cK;};
function C$(){N.call(this);this.fh=0;}
let GP=(a,b)=>{let c;Bg(a);if(!b){a.du=1;c=Bp(0.0,0.0,0.0,12,H(14388819));Bt(a,c);}else{a.cW=1;c=Bp(0.0,0.0,0.0,11,H(14388819));Bt(a,c);}},Ei=a=>{let b=new C$();GP(b,a);return b;},Kh=(a,b)=>{Ge(a,b);if(b instanceof Bl)a.fh=0;},JR=(a,b)=>{B3(a,b);if(!a.fh&&b instanceof Bl){a.dM.cu(a.dg);J(EK);}};
function E3(){let a=this;N.call(a);a.eI=0;a.fA=null;}
let Kf=(a,b)=>{B3(a,b);if(!a.eI&&b instanceof Bl){a.fA.dy=1;a.eI=1;a.cK=0;b=b;b.dx=b.dx+1|0;J(FA);}},Il=(a,b)=>{if(!(b instanceof Bl))return a.cK;return 0;};
function D7(){BA.call(this);this.ew=0;}
let Ko=(a,b,c)=>{let d;d=a.ew?0:1;a.ew=d;if(!d)a.cN=2;else a.cN=3;b.cq(a.dg,d);if(!a.ew)J(Ch);else J(Bv);return 1;};
function Gu(){N.call(this);this.dX=0;}
let Iy=a=>{let b,c,d,e,f;B4(a);b=a.dM;c=a.eb;d=c-0.2;e=a.ea;f=Jm(b,d,e-0.2,c+0.2,e+0.2);if(f!=a.dX){a.dX=f;if(!f)a.cW=2;else a.cW=3;a.dM.cq(a.dg,f);if(!a.dX)J(Ch);else J(Bv);}},H$=(a,b)=>{if(!a.dX)return 0.02;return (-0.02);},EC=F(Cr),IM=(a,b,c)=>{return 0;},I1=(a,b)=>{a.dW=b;};
function Gf(){let a=this;N.call(a);a.eN=0;a.fa=null;}
let Hx=(a,b)=>{let c,d;B3(a,b);if(!a.eN&&!(!(b instanceof Dt)&&!(b instanceof CV))){BW(b);a.eN=1;a.cK=0;a.fa.dy=1;c=0;while(c<8){d=EM();d.c9=a.fa.c9;Bt(a,d);c=c+1|0;}if(!(b instanceof CV))J(DR);else{V(a.dM,CK(a.eb,a.ea));J(Cw);}}},KI=(a,b)=>{return a.cK;},Gj=F(N),IL=(a,b)=>{if(b instanceof Bk)return 0;return a.cK;};
function Fj(){BA.call(this);this.eY=0;}
let IF=(a,b,c)=>{if(a.eY)return 0;if(b.cX.dQ<4)return 0;J(Bv);a.eY=1;b.cq(a.dg,1);return 1;},Em=F(N),GV=(a,b)=>{B3(a,b);if(b instanceof Bl)J0(b.cG);};
function Cy(){let a=this;Bi.call(a);a.fx=null;a.eJ=0.0;}
let DB=0,C0=()=>{C0=Bo(Cy);IY();},HV=a=>{let b,c,d;b=a.eJ;c=a.cE;c=c*c;d=a.cD;c=b+BB(c+d*d);a.eJ=c;a.fx.c2=8+((c*4.0|0)&1)|0;b=a.cE;c=a.cD;Cz(a);if(a.cE===0.0&&b!==0.0)a.cE= -b*0.3;if(a.cD===0.0&&c!==0.0)a.cD= -c*0.3;b=a.cE*0.98;a.cE=b;c=a.cD*0.98;a.cD=c;if(b*b+c*c<1.0E-4){a.cD=0.0;a.cE=0.0;}},Kq=(a,b,c)=>{S();if(c!==Cj)return 0;J(Ev);a.cE=a.cE+Z(b.cM)*0.1;a.cD=a.cD+Be(b.cM)*0.1;return 1;},IY=()=>{DB=H(11510419);};
function X(){let a=this;Bi.call(a);a.dH=null;a.e$=0.0;a.dN=0.0;a.eE=0;a.dO=0;a.dF=0;a.dm=0;a.c3=0;a.de=0.0;a.d2=0.0;}
let BD=(a,b,c,d,e)=>{let f;Ce(a);a.dF=0;a.dm=0;a.c3=3;a.de=0.1;a.d2=1.0;a.cC=b;a.cB=c;a.dO=e;a.eE=d;f=Bp(0.0,0.0,0.0,32,e);a.dH=f;BE(a.dD,f);a.cP=0.3;},KQ=(a,b,c,d)=>{let e=new X();BD(e,a,b,c,d);return e;},CS=a=>{let b,c,d,e;b=a.dF;if(b>0){b=b-1|0;a.dF=b;if(!b)a.dH.c9=a.dO;}c=a.dm+1|0;a.dm=c;a.dH.c2=a.eE+((c/10|0)%2|0)|0;a.cc();if(!(a.cE!==0.0&&a.cD!==0.0)){d=a.dN;Bq();a.dN=d+Ef(Bd)*Bm(Bd)*0.3;}d=a.dN;Bq();d=d+Ef(Bd)*Bm(Bd)*a.de;a.dN=d;e=a.e$+d;a.e$=e;a.dN=d*0.8;d=a.cE*0.8;a.cE=d;a.cD=a.cD*0.8;a.cE=d+Z(e)*0.004
*a.d2;a.cD=a.cD+Be(a.e$)*0.004*a.d2;},JI=(a,b,c)=>{if(a.dF>0)return 0;S();if(c!==Cj)return 0;a.cy(Z(b.cM),Be(b.cM));return 1;},Ex=(a,b,c)=>{let d,e,f,g,h;a.dH.c9=H(16711680);a.dF=15;d=BB(b*b+c*c);a.cE=a.cE+b/d*0.2;a.cD=a.cD+c/d*0.2;J(Ff);e=a.c3-1|0;a.c3=e;if(e<=0){e=a.cC+0.5|0;f=a.cB+0.5|0;g=P(a.cG,e,f);h=new Fd;C1(h,a.cC-e,0.0,a.cB-f,5,2236962);h.eU=20;Bt(g,h);a.cz();BW(a);J(EV);}},Jp=a=>{return;},JU=(a,b)=>{if(b instanceof Bk){if(CB(b.dP)===CB(a))return;if(a.dF>0)return;BW(b);a.cy(b.cE,b.cD);}if(b instanceof Bl)E1(b,
a,1);},GL=F(X),JM=(a,b,c)=>{BD(a,b,c,32,H(8545902));a.cC=b;a.cB=c;a.c3=2;a.cP=0.3;a.c$=1;},EH=(a,b)=>{let c=new GL();JM(c,a,b);return c;},FU=F(X),G5=a=>{J(Cw);V(a.cG,CK(a.cC,a.cB));},J1=a=>{let b,c,d;CS(a);Bq();if(!Br(Bd,20)){b=a.cC+(Bm(Bd)-0.5)*2.0;c=a.cB+(Bm(Bd)-0.5)*2.0;d=EH(b,c);d.cG=a.cG;d.cC=(-999.0);d.cB=(-999.0);if(C6(d,b,c))V(a.cG,d);}};
function DJ(){X.call(this);this.er=0;}
let JY=(a,b,c)=>{Ex(a,b,c);a.er=50;},JX=a=>{let b,c,d,e,f,g;CS(a);b=a.er;if(b>0)a.er=b-1|0;else{Bq();if(!Br(Bd,40)){a.er=40;c=a.cG;d=new Bk;e=a.cC;f=a.cB;g=c.cX;Dd(d,a,e,f,Ed(g.cC-e,g.cB-f),0.3,1,a.dO);V(c,d);}}};
function EP(){let a=this;X.call(a);a.eC=0;a.fb=0;}
let Ke=a=>{J(Cw);V(a.cG,CK(a.cC,a.cB));},HG=a=>{let b,c,d;CS(a);b=a.eC;if(b>0)a.eC=b-1|0;else{a.eC=5;c=0;while(c<4){d=1.5707963267948966*(c+((a.fb/10|0)%2|0)*0.5);V(a.cG,GN(a,a.cC,a.cB,d,0.4,1,a.dO));c=c+1|0;}b=a.fb+1|0;a.fb=b;if(!(b%10|0))a.eC=40;}},Da=F(X),DK=F(X),J$=a=>{J(Cw);V(a.cG,CK(a.cC,a.cB));};
function Dt(){X.call(this);this.dz=0.0;}
let H1=a=>{let b,c,d,e,f,g;b=a.dm+1|0;a.dm=b;a.dH.c2=a.eE+((b/10|0)%2|0)|0;c=a.cG.cX.cC+Z(a.dz)-a.cC;d=a.cG.cX.cB+Be(a.dz)-a.cB;e=c*c+d*d;if(e<16.0){if(e<1.0)a.dz=a.dz+0.04;else{a.dz=a.cG.cX.cM;f=a.cE;Bq();a.cE=f+(Bm(Bd)-0.5)*0.02;a.cD=a.cD+(Bm(Bd)-0.5)*0.02;}g=BB(e);c=c/g;g=d/g;a.cE=a.cE+c*0.004;a.cD=a.cD+g*0.004;}Gt(a);a.cE=a.cE*0.9;a.cD=a.cD*0.9;},If=(a,b,c)=>{return;},Gt=a=>{a.cC=a.cC+a.cE;a.cB=a.cB+a.cD;};
function CV(){let a=this;X.call(a);a.dG=0.0;a.ef=0;}
let IX=a=>{let b,c,d,e,f,g,h,i,j;b=a.dm+1|0;a.dm=b;a.dH.c2=a.eE+((b/10|0)%2|0)|0;c=a.cG.cX.cC+Z(a.dG)*2.0-a.cC;d=a.cG.cX.cB+Be(a.dG)*2.0-a.cB;e=c*c+d*d;if(!(e<1.0))a.dG=a.cG.cX.cM;else a.dG=a.dG+0.04;if(e<16.0){e=BB(e);f=c/e;d=d/e;a.cE=a.cE+f*0.006;a.cD=a.cD+d*0.006;g=a.ef;if(g>0)a.ef=g-1|0;else{Bq();if(!Br(Bd,10)){a.ef=10;h=a.cG;i=new Bk;c=a.cC;d=a.cB;j=h.cX;Dd(i,a,c,d,Ed(j.cC-c,j.cB-d),0.2,1,a.dO);V(h,i);}}}FP(a);a.cE=a.cE*0.9;a.cD=a.cD*0.9;},H8=(a,b,c)=>{return;},FP=a=>{a.cC=a.cC+a.cE;a.cB=a.cB+a.cD;};
function Eh(){let a=this;BX.call(a);a.e0=0.0;a.e2=0.0;a.e3=0.0;}
let JE=a=>{C1(a,BM()-0.5,BM()*0.8,BM()-0.5,2,5592405);a.e0=BM()-0.5;a.e2=BM();a.e3=BM()-0.5;},EM=()=>{let a=new Eh();JE(a);return a;},HP=a=>{let b,c,d,e,f;b=a.da;c=a.e0;a.da=b+c*0.03;d=a.dq;b=a.e2;e=d+b*0.03;a.dq=e;d=a.c_;f=a.e3;a.c_=d+f*0.03;a.e2=b-0.1;if(e<0.0){a.dq=0.0;a.e0=c*0.8;a.e3=f*0.8;if(BM()<0.04)a.dy=1;}};
function DI(){let a=this;Bi.call(a);a.fR=null;a.dT=0.0;a.eH=0.0;}
let F1=0,Dl=()=>{Dl=Bo(DI);Kj();},Kl=(a,b,c)=>{let d;Dl();Ce(a);a.cC=b;a.cB=c;a.dT=0.5;a.eH=0.025;d=Bp(0.0,0.0,0.0,19,F1);a.fR=d;BE(a.dD,d);},CK=(a,b)=>{let c=new DI();Kl(c,a,b);return c;},H3=a=>{let b,c,d;Cz(a);b=a.dT;c=a.eH;d=b+c;a.dT=d;if(d<0.0)a.dT=0.0;a.eH=c-0.005;a.fR.dq=a.dT;},Jj=(a,b)=>{if(b instanceof Bl){J(EE);b=b;b.dQ=b.dQ+1|0;BW(a);}},Kj=()=>{F1=H(65535);},GA=F(0);
function F2(){E.call(this);this.fs=null;}
let D$=a=>{return Bm(a.fs);};
function Fd(){BX.call(this);this.eU=0;}
let Ih=a=>{let b;b=a.eU;a.eU=b-1|0;if(b<=0)a.dy=1;},Hr=F();
function E5(){let a=this;Bc.call(a);a.eG=0;a.e5=null;}
let J2=(a,b)=>{let c,d,e,f;O();BI(b,Co,0,10,0,65,160,23,H(16777215));c=a.e5.ev/60|0;d=c/60|0;c=c%60|0;e=Q();Cp(Bn(e,d),58);e=R(e);if(c<10){f=Q();Cp(M(f,e),48);e=R(f);}f=Q();Bn(M(f,e),c);f=R(f);c=a.e5.dx;e=Q();M(Bn(M(e,D(105)),c),D(106));L(b,R(e),40,45,H(9474192));e=Q();M(M(e,D(107)),f);L(b,R(e),40,55,H(9474192));if(!a.eG)L(b,D(97),40,b.cF-40|0,H(16777088));},IR=(a,b,c,d,e,f,g)=>{c=a.eG;if(c>0)a.eG=c-1|0;else if(g){J(Bv);b.cQ=B7();}};
function E2(){let a=this;Bc.call(a);a.d$=0;a.eA=null;}
let I8=(a,b)=>{let c,d,e,f;c=a.eA.e_;d=Q();Cp(M(M(d,D(108)),c),33);d=R(d);O();c=CF;e=(b.cH/2|0)-24|0;f=a.eA;F7(b,c,3,e,2,f.es*16|0,0,16,16,H(f.eu));L(b,d,((b.cH-(d.cJ.length*6|0)|0)/2|0)+2|0,50,H(16777088));c=a.eA.fI;L(b,c,((b.cH-(c.cJ.length*6|0)|0)/2|0)+2|0,60,H(10526880));if(!a.d$)L(b,D(97),40,b.cF-40|0,H(16777088));},Jk=(a,b,c,d,e,f,g)=>{d=a.d$;if(d>0)a.d$=d-1|0;else if(g)b.cQ=null;};
HL([]);
CI([E,0,0,[],1,0,0,0,BL,0,E,[],1537,0,0,0,Cb,0,E,[],1537,0,0,0,DH,0,E,[],1537,0,0,0,Ba,0,E,[BL,Cb,DH],17,0,()=>Ci(),0,DW,0,E,[BL],1025,0,0,0,EA,0,DW,[Cb],1,0,()=>CH(),0,Dp,0,E,[BL,DH],0,0,0,0,Dz,0,E,[],1537,0,0,0,Eq,0,Dp,[Dz],1,0,0,0,DU,0,E,[],1,0,0,0,DQ,0,DU,[],1,0,0,0,Bb,0,DQ,[],1,0,0,0,Cm,0,E,[],1025,0,0,0,H2,0,Cm,[],17,0,0,0,HK,0,Cm,[],17,0,0,0,EQ,0,E,[],1537,0,0,0,GB,0,E,[EQ],1537,0,0,0,Eg,0,E,[],1537,0,0,0,E6,0,E,[GB,Eg],17,0,0,0,C_,0,E,[],1,0,()=>B0(),0,Js,0,E,[],17,0,0,0,Ka,0,E,[],17,0,0,0,Ky,0,E,[],
17,0,0,0,Bf,0,E,[],1025,0,()=>BH(),["S",function(b,c,d,e,f){FY(this,b,c,d,e,f);},"A",Ct(E$),"z",CR(Ee),"cq",W(BR)],CW,0,E,[],1537,0,0,0,Fc,0,E,[CW],1,0,0,0,F6,0,E,[],1537,0,0,0,Fy,0,E,[F6],1,0,0,0,DO,0,E,[Cb],1,0,()=>CL(),0,BU,0,E,[],1537,0,0,0,FJ,0,E,[BU],1,0,0,["R",K(JP)],FI,0,E,[BU],1,0,0,["R",K(KB)],FH,0,E,[BU],1,0,0,["R",K(Kz)],FG,0,E,[BU],1,0,0,["R",K(Kg)],FF,0,E,[BU],1,0,0,["R",K(I$)],FE,0,E,[BU],1,0,0,["R",K(JL)],Fh,0,E,[CW],1,0,0,0,HQ,0,E,[],17,0,0,0,C2,0,E,[],17,0,0,0,EG,0,E,[],1537,0,0,0,DT,0,E,[EG],
1025,0,0,0,C5,0,E,[],1537,0,0,0,Gg,0,DT,[C5,BL],1,0,0,0,BT,0,E,[],1537,0,0,0,B6,0,E,[BT],1537,0,0,0,Dy,0,E,[B6],1,0,0,0,Cd,0,Bb,[],1,0,0,0,JD,0,Bb,[],1,0,0,0,CP,0,Bb,[],1,0,0,0]);
CI([D_,0,E,[],1537,0,0,0,DS,0,E,[D_,C5],0,0,0,0,CN,0,DS,[],0,0,0,0,Fa,0,E,[],1,0,0,0,Fq,0,E,[CW],1,0,0,0,Gl,0,E,[],1,0,()=>O(),0,BC,0,E,[],1537,0,0,0,Fx,0,E,[BC],1,0,0,["bo",G(H9)],Fw,0,E,[BC],1,0,0,["bo",G(Ij)],Fv,0,E,[BC],1,0,0,["bo",G(Is)],Fu,0,E,[BC],1,0,0,["bo",G(ID)],Ft,0,E,[BC],1,0,0,["bo",G(IE)],Fs,0,E,[BC],1,0,0,["bo",G(It)],Fr,0,E,[BC],1,0,0,["bo",G(Ik)],Fz,0,E,[BC],1,0,0,["bo",G(G4)],Dg,0,E,[B6],1,0,0,0,B5,0,E,[],1,0,0,0,DM,0,Cd,[],1,0,0,0,GE,0,E,[],1,0,0,0,Fn,0,E,[],1,0,0,0,F3,0,B5,[],1,0,0,0,EO,
0,E,[],1,0,0,0,Gk,0,E,[BT],1537,0,0,0,DP,0,E,[Gk],0,0,0,0,Bc,0,E,[],1,0,0,0,El,0,Bc,[],1,0,0,["bO",G(KH),"bC",function(b,c,d,e,f,g){I7(this,b,c,d,e,f,g);}],Et,0,B5,[],1,0,0,0,F$,0,E,[],1537,0,0,0,Dk,0,E,[F$,BL],1,0,0,0,Dx,0,E,[B6],0,0,0,0,Dw,0,E,[B6],0,0,0,0,Du,0,E,[B6],0,0,0,0,KF,0,E,[],17,0,0,0,FC,0,E,[],0,0,()=>CD(),0,Jf,0,E,[BT],1,0,0,0,I6,0,E,[],17,0,0,0,H7,0,E,[BT],1025,0,0,0,D3,0,E,[BT],1536,0,0,0,Dc,0,E,[D3],1,0,0,0,Db,0,E,[D3],1,0,0,0,F0,0,E,[BT],1537,0,0,0,Dv,0,E,[F0],0,0,0,0,Ic,0,E,[],1,0,0,0,II,
0,E,[],1,0,0,0,I9,0,E,[],17,0,0,0,Gn,0,E,[],1537,0,0,0,E0,0,E,[Gn],1537,0,0,0,Gb,0,E,[],1537,0,0,0,DG,0,E,[E0,Gb],1025,0,0,0,Do,0,DG,[],1,0,0,0]);
CI([Dn,0,Do,[Dz],1,0,0,0,Ds,0,Dn,[],1025,0,0,0,EJ,0,Ds,[],1,0,0,0,HT,0,E,[Cb],1025,0,0,0,Bi,0,E,[],1,0,()=>Bq(),["cc",K(Cz),"b9",G(HH),"b8",Ct(DX),"cg",W(GY),"W",K(GQ)],Bl,0,Bi,[],1,0,0,["b8",Ct(IN),"b9",G(GU)],GI,0,Bc,[],1,0,0,["bO",G(JB),"bC",function(b,c,d,e,f,g){KD(this,b,c,d,e,f,g);}],N,0,E,[],1,0,()=>D6(),["ch",W(HM),"W",K(B4),"F",G(Ge),"I",G(B3),"b7",G(HN),"G",CR(Kb),"b_",G(Ir),"ca",G(IU),"cd",G(Ix),"Y",G(IW)],DY,0,E,[Cb,BL],1025,0,0,0,Cl,0,DY,[],65553,0,()=>S(),0,EW,0,Bc,[],1,0,0,["bO",G(JG),"bC",function(b,
c,d,e,f,g){Hy(this,b,c,d,e,f,g);}],Ep,0,Bc,[],1,0,0,["bO",G(G$),"bC",function(b,c,d,e,f,g){HO(this,b,c,d,e,f,g);}],BA,0,N,[],1,0,0,0,Cr,0,BA,[],1,0,0,["ch",W(Kk),"W",K(Ks),"b7",G(I2)],BX,0,E,[],1,0,0,["W",K(JV)],ER,0,E,[],1537,0,0,0,DC,0,E,[ER],1537,0,0,0,C7,0,E,[DC],1025,0,0,0,Gs,0,E,[DC],1537,0,0,0,EF,0,E,[Gs],1537,0,0,0,DF,0,C7,[EF],1025,0,0,0,FW,0,E,[],1537,0,0,0,FM,0,DF,[C5,BL,FW],1,0,0,0,CM,0,N,[],1,0,0,["W",K(J3),"b7",G(Hz),"b_",G(Ji),"ca",G(G_)],Dm,0,N,[],1,0,0,["W",K(HY),"ca",G(In),"cd",G(HJ),"b7",
G(G8)],Bk,0,Bi,[],1,0,0,["W",K(Kp),"b8",Ct(Jd),"b9",G(Hb)],Gi,0,Bf,[],1,0,0,["S",function(b,c,d,e,f){Jg(this,b,c,d,e,f);},"cu",G(IH),"cs",G(I_),"cq",W(H4)],F4,0,Bf,[],1,0,0,["cu",G(JK),"cs",G(Kv)],Go,0,Bf,[],1,0,0,["cu",G(I4),"cs",G(IA)],Fe,0,Bf,[],1,0,0,["cu",G(KJ),"cs",G(IT),"cq",W(HC)],GH,0,Bf,[],1,0,0,["cu",G(Ib),"cs",G(G7)],EY,0,Bf,[],1,0,0,["A",Ct(IZ),"z",CR(Ki),"cu",G(JZ),"cs",G(J9)],HZ,0,E,[],17,0,0,0,Eo,0,Bb,[],1,0,0,0,GO,0,Bb,[],1,0,0,0,Gw,0,Bc,[],1,0,0,["bO",G(HA),"bC",function(b,c,d,e,f,g){JC(this,
b,c,d,e,f,g);}],Gz,0,N,[],1,0,0,["I",G(HE),"b7",G(H5)],FT,0,BA,[],1,0,0,["ch",W(J5)],Fp,0,N,[],1,0,0,["ch",W(I3)],Gd,0,N,[],1,0,0,["G",CR(I5),"W",K(Jt)],FR,0,N,[],1,0,0,["ch",W(Ig),"b7",G(G9)],C$,0,N,[],1,0,0,["F",G(Kh),"I",G(JR)],E3,0,N,[],1,0,0,["I",G(Kf),"b7",G(Il)],D7,0,BA,[],1,0,0,["ch",W(Ko)],Gu,0,N,[],1,0,0,["W",K(Iy),"b_",G(H$)],EC,0,Cr,[],1,0,0,["ch",W(IM),"Y",G(I1)],Gf,0,N,[],1,0,0,["I",G(Hx),"b7",G(KI)],Gj,0,N,[],1,0,0,["b7",G(IL)],Fj,0,BA,[],1,0,0,["ch",W(IF)],Em,0,N,[],1,0,0,["I",G(GV)]]);
CI([Cy,0,Bi,[],1,0,()=>C0(),["W",K(HV),"cg",W(Kq)],X,0,Bi,[],1,0,0,["W",K(CS),"cg",W(JI),"cy",W(Ex),"cz",K(Jp),"b9",G(JU)],GL,0,X,[],1,0,0,0,FU,0,X,[],1,0,0,["cz",K(G5),"W",K(J1)],DJ,0,X,[],1,0,0,["cy",W(JY),"W",K(JX)],EP,0,X,[],1,0,0,["cz",K(Ke),"W",K(HG)],Da,0,X,[],1,0,0,0,DK,0,X,[],1,0,0,["cz",K(J$)],Dt,0,X,[],1,0,0,["W",K(H1),"cy",W(If),"cc",K(Gt)],CV,0,X,[],1,0,0,["W",K(IX),"cy",W(H8),"cc",K(FP)],Eh,0,BX,[],1,0,0,["W",K(HP)],DI,0,Bi,[],1,0,()=>Dl(),["W",K(H3),"b9",G(Jj)],GA,0,E,[],1537,0,0,0,F2,0,E,[GA],
1,0,0,0,Fd,0,BX,[],1,0,0,["W",K(Ih)],Hr,0,E,[],17,0,0,0,E5,0,Bc,[],1,0,0,["bO",G(J2),"bC",function(b,c,d,e,f,g){IR(this,b,c,d,e,f,g);}],E2,0,Bc,[],1,0,0,["bO",G(I8),"bC",function(b,c,d,e,f,g){Jk(this,b,c,d,e,f,g);}]]);
let J7=BY(Iz),Jq=BY(FL),Jy=BY(EL),Hn=BY(Hc);
Hs(["0","<java_object>@","null","start","crypt","overworld","temple","ice","dungeon","tex/walls.png","tex/floors.png","tex/sprites.png","tex/font.png","tex/gamepanel.png","tex/items.png","tex/sky.png","gui/logo.png","level/",".png","","Level asset data has not been preloaded for: ","No registered Factory found for level configuration: ","The Prison","The Crypt","The Island","The Temple","The Frost Cave","The Dungeons","object","function","string","number","undefined","snd/altar.wav","snd/bosskill.wav","snd/click.wav",
"snd/click2.wav","snd/hit.wav","snd/hurt.wav","snd/hurt2.wav","snd/kill.wav","snd/death.wav","snd/splash.wav","snd/key.wav","snd/pickup.wav","snd/roll.wav","snd/shoot.wav","snd/treasure.wav","snd/crumble.wav","snd/slide.wav","snd/cut.wav","snd/thud.wav","snd/ladder.wav","snd/potion.wav","ABCDEFGHIJKLMNOPQRSTUVWXYZ.,!?\"\'/\\<>()[]{}abcdefghijklmnopqrstuvwxyz_               0123456789+-=*:;Ã–Ã…Ã„Ã¥                      ","Abort game","Continue","Entering ","Ã¥","/4","Ã„","Ã…","Click to focus!","New game","Instructions",
"About","-> ","Copyright (C) 2011 Mojang"," fps","\n","none","powerGlove","Power Glove","Smaaaash!!","pistol","Pistol","Pew, pew, pew!","flippers","Flippers","Splish splash!","cutters","Cutters","Snip, snip!","skates","Skates","Sharp!","key","Key","How did you get this?","potion","Potion","Healthy!","Use W,A,S,D to move, and","the arrow keys to turn.","The 1-8 keys select","items from the inventory","Space uses items","-> Continue","Prelude of the Chambered","by Markus Persson.","Made Aug 2011 for the","21\'st Ludum Dare compo.",
"This game is freeware,","and was made from scratch","in just 48 hours.","Trinkets: ","/12","Time: ","You found the "]);
Ba.prototype.toString=function(){return Cg(this);};
Ba.prototype.valueOf=Ba.prototype.toString;E.prototype.toString=function(){return Cg(Jv(this));};
E.prototype.__teavm_class__=function(){return Kr(this);};
let C=GS(G1);
C.javaException=IQ;
let KM=Symbol('jsoClass');
(()=>{let c;c=Dy.prototype;c.handleEvent=BG(Jw);c=Dg.prototype;c.handleEvent=BG(IB);c=DP.prototype;c.onLoaded=BG(JJ);c=Dx.prototype;c.handleEvent=BG(Kx);c=Dw.prototype;c.handleEvent=BG(Je);c=Du.prototype;c.handleEvent=BG(HR);c=Dc.prototype;c.accept=BG(Iv);c=Db.prototype;c.accept=BG(HF);c=Dv.prototype;c.onAnimationFrame=BG(Hk);})();
B.main=C;}));
